### ISSUE TITLE
OLM collect-profiles job tries to access non existing volumes after upgrade from 4.8 to 4.9

### ISSUE THREAD

**Issue by daFritz84** [openshift/okd#1004]
**Describe the bug**
I noticed that the OLM collect-profiles job tries and fails to access some volumes. 
```
MountVolume.SetUp failed for volume "config-volume" : object "openshift-operator-lifecycle-manager"/"collect-profiles-config" not registered
MountVolume.SetUp failed for volume "kube-api-access-d4kzh" : [object "openshift-operator-lifecycle-manager"/"kube-root-ca.crt" not registered, object "openshift-operator-lifecycle-manager"/"openshift-service-ca.crt" not registered]
MountVolume.SetUp failed for volume "secret-volume" : object "openshift-operator-lifecycle-manager"/"pprof-cert" not registered
```
I noticed, that the same log messages can be found here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-upgrade-from-stable-4.8-e2e-aws-ovn-upgrade/1428509007814856704

**Version**
4.9.0-0.okd-2021-11-28-035710

**How reproducible**
Upgrade existing 4.8 okd cluster to 4.9

**Log bundle**
Could not pull "must-gather" image from quay.io. I still have to investigate why I ran into a back-off timeout here.

**Comment by vrutkovs** [comment]
Seems to be affecting OCP as well, please re-file this as a bugzilla ticket

**Comment by daFritz84** [comment]
OCP Bugzilla Link: https://bugzilla.redhat.com/show_bug.cgi?id=2029836
