### ISSUE TITLE
Upgrade from OKD4.8 to OKD4.9 fails due to "Cluster operator operator-lifecycle-manager should not be upgraded between minor versions" error

### ISSUE THREAD

**Issue by mesilat** [openshift/okd#1008]
**Describe the bug**
OKD cluster upgrade from version 4.8.0-0.okd-2021-11-14-052418 to version 4.9.0-0.okd-2021-11-28-035710 stuck at 19% with error message:

> Cluster operator operator-lifecycle-manager should not be upgraded between minor versions: ClusterServiceVersions blocking cluster upgrade: openshift-operators/gitlab-runner-operator.v1.1.0 is incompatible with OpenShift minor versions greater than 4.8

![Screenshot 2021-12-08 at 09 26 15](https://user-images.githubusercontent.com/69498272/145160841-56e93625-3415-42ad-9d13-09da6c7ed50e.png)

There is a possibly similar issue described at https://access.redhat.com/solutions/6267791 however the solution is confusing:

> This error message is incorrect. The status does not block upgrades for versions greater than 4.8.0.
> This is a know issue being tracked in Red Hat Bugzilla #1992677. Even if this message is being displayed, the cluster status should not be degraded and all should work without issues.
> If you would like to track the above mentioned RHBZ, feel free to open a Support Case with Red Hat Technical Support team.

But it does block cluster upgrade as shown in the screenshot above. Is there any advice how to fix the issue?

**Version**
4.8.0-0.okd-2021-11-14-052418

**How reproducible**
This one case, never tried to reproduce.

**Log bundle**
Can be downloaded here: http://dev.mesilat.com/must-gather.tar.gz

**Comment by vrutkovs** [comment]
Not an OKD issue:
>openshift-operators/gitlab-runner-operator.v1.1.0 is incompatible with OpenShift minor versions greater than 4.8
