### ISSUE TITLE
Correct the title text on the Download page 

### ISSUE THREAD

**Issue by bodunov** [openshift/okd#101]
Suggestion to replace "The Enterprise Open Source Kubernetes Distribution" by "The Community Open Source..." on OKD Download page https://www.okd.io/download.html

**Comment by vrutkovs** [comment]
Diane, iirc you're familiar with okd.io site source, right?

**Comment by dmueller2001** [comment]
@vrutkovs Correct, I am the editor for the okd.io site. Some thought (and negotiation with Red Hat marketing/legal) did go into phrasing of the description for the landing page for okd.io and the use of "Enterprise" was incorporated to differentiate from the raw k8s distro and give a subtle nod (perhaps too subtle?) to all the value add that being the open source distro of OpenShift implies.

**Comment by LorbusChris** [comment]
maybe it could be "Community Enterprise" (as in the "Cent" in CentOS)?
As it's not necessarily incorrect as-is, I'll close this issue here :)
