### ISSUE TITLE
Unable to mirror OKD 4.9 images for disconnected install.

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#1010]
OKD version 4.9.0-0.okd-2021-11-28-035710

```bash
oc adm -a pull_secret.json release mirror --from=quay.io/openshift/okd:4.9.0-0.okd-2021-11-28-035710 --to=nexus.clg.lab:5001/4.9.0-0.okd-2021-11-28-035710 --to-release-image=nexus.clg.lab:5001/4.9.0-0.okd-2021-11-28-035710:4.9.0-0.okd-2021-11-28-035710
```

Errors:

```bash
error: unable to push quay.io/openshift/okd-content: failed to upload blob sha256:9298e99c05c3fbe3d5678773a250984c8b9e104bd8f833a4f5538f4d1e5a948d: invalid reference format

.... lot's more like it...

error: unable to push quay.io/openshift/okd-content: failed to upload blob sha256:06038631a24a25348b51d1bfc7d0a0ee555552a8998f8328f9b657d02dd4c64c: invalid reference format

.... lot's more like it...
```

**Comment by cgruver** [comment]
This is an issue with Nexus, or with the MIME type that is in Quay...

Either way, one is not compatible with the other.

If you are using Sonatype Nexus, the uncheck `Validate that all content uploaded to this repository is of a MIME type appropriate for the repository format`  Under `Strict Content Type Validation` in the configuration of the hosted docker repository in Nexus.

**Comment by cgruver** [comment]
I validated that the mirror works with `4.8.0-0.okd-2021-11-14-052418`.

I am using Sonatype Nexus OSS version: 3.37.

With OKD 4.9 I get `invalid reference format` errors for every image.

**Comment by cgruver** [comment]
I've narrowed it down to the `oc` command in the 4.9 bundle.

I used the `oc` binary from 4.8.0-0.okd-2021-11-14-052418, and mirrored 4.9 successfully...

**Comment by cgruver** [comment]
This issue persists with `4.9.0-0.okd-2021-12-12-025847`

**Comment by cgruver** [comment]
I have tested this with both the Mac OS and Linux client tools.

Same failures.

The 4.8 version of the client tools works.

**Comment by vrutkovs** [comment]
This needs to be filed for `oc`, I don't think its OKD specific

**Comment by cgruver** [comment]
It's not OKD.  I'm going to move this over to `oc`.

This fails:
`oc adm -a pull_secret.json release mirror --from=quay.io/openshift/okd:4.9.0-0.okd-2021-11-28-035710 --to=nexus.clg.lab:5001/4.9.0-0.okd-2021-11-28-035710 --to-release-image=nexus.clg.lab:5001/4.9.0-0.okd-2021-11-28-035710:4.9.0-0.okd-2021-11-28-035710`

But this works:

`oc adm -a pull_secret.json release mirror --from=quay.io/openshift/okd:4.9.0-0.okd-2021-11-28-035710 --to=nexus.clg.lab:5001/okd --to-release-image=nexus.clg.lab:5001/okd:4.9.0-0.okd-2021-11-28-035710`

**Comment by cgruver** [comment]
https://github.com/openshift/oc/issues/997

**Comment by sandrobonazzola** [comment]
@cgruver / @vrutkovs I think you can close this one as it's now tracked in openshift/oc#997

**Comment by vrutkovs** [comment]
I'd rather track it here as well, as it might be frequent gotcha for new installations.

@cgruver please file a bugzilla ticket instead

**Comment by LorbusChris** [comment]
@cgruver is this still an issue? Is there a BZ for tracking?
