### ISSUE TITLE
UPI install requires manual intervention to complete install: Machine-Config Operator Degraded

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#1013]
Affects:  OKD-4.8 and OKD 4.9

The Machine Config Operator will remain in a degraded state, looking for a rendered-master machine config that does not exist.

Executing the following will force the generation of the missing rendered-master:

```bash
oc delete mc 99-master-okd-extensions 99-okd-master-disable-mitigations
```

**Comment by vrutkovs** [comment]
Looks similar to #963

**Comment by cgruver** [comment]
Yes, I believe it is.  We can mark this as a dup if you want to reopen #963.

I am booting from the FCOS that is extracted from the bundle:

`FCOS_VER=$(openshift-install coreos print-stream-json | jq -r '.architectures.x86_64.artifacts.qemu.release')`

**Comment by vrutkovs** [comment]
Lets move there, seems MCO is inconsistently applying kargs (also probably the issue in #1014 )

**Comment by cgruver** [comment]
Dup of #963
