### ISSUE TITLE
4.9.0-0.okd-2021-12-12-025847 is not upgradable from 4.9.0-0.okd-2021-11-28-035710 on the stable-4 channel?

### ISSUE THREAD

**Issue by titou10titou10** [openshift/okd#1016]
The [OKD release status page](https://amd64.origin.releases.ci.openshift.org/) lists v4.9.0-0.okd-2021-12-12-025847 and v4.9.0-0.okd-2021-11-28-035710 as the two last "stable" versions for OKD 

![image](https://user-images.githubusercontent.com/15241034/145722919-64001501-74a9-4fc7-aef1-669a3be44f48.png)

But 4.9.0-0.okd-2021-11-28-035710  can not be upgraded to the latest version 4.9.0-0.okd-2021-12-12-025847, due to failing tests it seems

![image](https://user-images.githubusercontent.com/15241034/145723232-d2b0e974-acc6-4777-a1ad-f96eda6d9e80.png)

Q:
- Is this a bug, ie this version should not have been released on the stable channel?
- if we are currently on v4.9.0-0.okd-2021-11-28-035710 are we stuck there or will a future version be released where the upgrade will be possible?

I was on the understanding that each version released on the "stable" channel was a linear upgrade from the previous one, at least for OKD. Is it a wrong assumption?

**Comment by vrutkovs** [comment]
Lets use Github Discussions for Q&A and track bugs with tech info in Issues

>But 4.9.0-0.okd-2021-11-28-035710 can not be upgraded to the latest version 4.9.0-0.okd-2021-12-12-025847, due to failing tests it seems

2021-11-28-035710 can be updated to 2021-12-12-025847, as one passing upgrade is sufficient.

>Is this a bug, ie this version should not have been released on the stable channel?

If there would be no upgrade path we'd remove it, yes. This has happened to few releases already

> if we are currently on v4.9.0-0.okd-2021-11-28-035710 are we stuck there or will a future version be released where the upgrade will be possible?

A new version would be released and upgrade is always possible. "Upgrade from previous stable version" is the only release criteria so far (conformance tests are required to pass for a nightly, which is then promoted to a stable version)

**Comment by titou10titou10** [comment]
> Lets use Github Discussions for Q&A and track bugs with tech info in Issues

OK

> A new version would be released and upgrade is always possible. "Upgrade from previous stable version" is the only release criteria so far (conformance tests are required to pass for a nightly, which is then promoted to a stable version)
OK. Since this morning the latest version suddenly "appeared" as a valid upgrade version from the`stable-4`channel

The missing tech info for completion (sorry for that..)

    oc version <- I will upgrade the client to latest before upgrading...
    Client Version: 4.9.0-0.okd-2021-11-28-035710
    Server Version: 4.9.0-0.okd-2021-11-28-035710
    Kubernetes Version: v1.22.1-1820+4dd1b5a1afc832-dirty

    oc get clusterversion
    NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
    version   4.9.0-0.okd-2021-11-28-035710   True        False         14d     Cluster version is 4.9.0-0.okd-2021-11-28-035710

    oc adm upgrade <- now with the latest version as a possible upgrade...
    Cluster version is 4.9.0-0.okd-2021-11-28-035710

    Upstream: https://amd64.origin.releases.ci.openshift.org/graph
    Channel: stable-4
    Updates:
    VERSION                       IMAGE
    4.9.0-0.okd-2021-12-12-025847 registry.ci.openshift.org/origin/release@sha256:4323eccc8c7cf782ff632a3c8ddf783b3f971af52e1b4bdcb93ab9127ed0be57

Anyway, it seems I can upgrade the cluster now, 
Thanks for the clarifications and sorry for the noise
