### ISSUE TITLE
4.9 install fails with latest coreOS 35 images on bare metal - Docs do not mention 34 is needed

### ISSUE THREAD

**Issue by markusdd** [openshift/okd#1020]
I have been pulling my hair out because after some successful trials I was not able to deploy our new bare metal okd4 cluster which is due to replace our 3.11 setup.

Now I came to find out the 4.9 installation routine simply does not work with latest coreos images, but the official docs just say to go to the coreOS download page and get the coreOS iso there.

The installation fails in an almost undebuggable way, as the boostrap node does come up, but the masters simply refuse to pull their config and start provisioning. (installation and ignition application is all fine)
As the masters cannot be logged into as they do not get the ssh key right away before pulling from the bootstrap node, this has cost me 2 days of thinking I am too stupid.

the command `openshift-install coreos print-stream-json` needs to be put into the documentation with the hint to look up the coreOS image links in there and use these for installation, which went like a breeze.

Also, I have not found a hint in the docs (but I might have overlooked it) if you prepare the install on one day and want to run it on the next, the installer cert might have expired and you also get very subtle errors which makes it all not work.

I think the one day expiration is definitely too short and it is not mentioned prominently anywhere.

So this is mostly a documentation bug report, but I do not know if it is expected that coreOS35 does not work with 4.9.

**Comment by dickyhome** [comment]
thank you we also got it from github but with that command make even more sure

**Comment by hunter86bg** [comment]
@markusdd ,
can you check if you observe the same coredump like in openshift/okd#1045

**Comment by markusdd** [comment]
I cannot really tell because I was never able to login into any of the nodes.

**Comment by hunter86bg** [comment]
When the first provisioning happen, use 'systemd.debug-shell' kernel parameter. Then switch to TTY8 (or somewhere there) and you will obtain root shell 
Sadly, there is another bug which breaks ssh-ing.

**Comment by markusdd** [comment]
ok. due to the COVID situation I have no physical access to the machines right now, so if SSH is broken there is not much I can do.

Also, could I even attempt to use 35 for a node in my cluster now?

I have since moved on and provisioned everything using the 34 image encoded in the installer, with that everything went fine.

**Comment by hunter86bg** [comment]
The ssh bug is fixed, but I'm not sure when it will be merged.
If you don't have IPMI or other remote management , you can't ssh.

Yesterday I was fighting whole day with 35 (latest image) and it never worked.

**Comment by markusdd** [comment]
I have IPMI access via HP ilo (obviously, otherwise I couldn't deploy the OS at all) but I am not really aware if I can switch TTYs in there. CoreOS haves very erratically in there anyway as the character encoding is completely off.
just entering the coreos install command with the ignition url is painful.

**Comment by vrutkovs** [comment]
Please stop offtopic discussion, @hunter86bg issue should be detailed in #1045, not in a documentation issue

**Comment by markusdd** [comment]
I mean we are trying to get you more info on the issue but ok, then I'm out I guess.

Be nice.

**Comment by hunter86bg** [comment]
@vrutkovs ,

Are you sure it's documentation issue ?
For me it's a doc issue ONLY if Fedora CoreOS 35 is not supported.

**Comment by markusdd** [comment]
exactly. it makes sense to document that ideally the image from the installer-build should be used, but generally I consider this to be a wider ranging bug.

**Comment by vrutkovs** [comment]
We _already_ know that documentation needs updating. In later releases we might have various issue when users don't use recommended FCOS, so documentation needs to be updated to use `openshift-installer` and warn that deviating from suggested initial FCOS may cause issue. So its fairly generic and limited to OKD 4.8+ documentation only. 

In #1045 we'd need to figure out why things are crashing with FCOS 35 now - and propose a particular solution (if possible) for latest OKD 4.9. Lets discuss it there so that a person picking this bug to fix would not be confused by F35 specific bug and such

**Comment by hunter86bg** [comment]
To be honest, this is my first time deploying OKD and I guess I missed that version limitation ...
I was left with the impression that every FCOS version is enough .

Let's keep both threads separated.

**Comment by dkoci** [comment]
I had the same problem with latest fcos version. How to know which is the right fcos version before installation? Is there any command or something? The command `openshift-install coreos print-stream-json` is not working for me.
Another question: where to get older fcos versions? There is only the latest version available in official fedora site.

**Comment by dkoci** [comment]
Sorry, the command `openshift-install coreos print-stream-json` is ok in OKD 4.9. I tried in OKD 4.7 before.

**Comment by vrutkovs** [comment]
See https://github.com/vrutkovs/installer/blob/release-4.7-okd/data/data/fcos-amd64.json for 4.7 version

**Comment by markusdd** [comment]
> I had the same problem (vmware upi install) with latest fcos version. How to know which is the right fcos version before installation? Is there any command or something? The command `openshift-install coreos print-stream-json` is not working for me. Another question: where to get older fcos versions? There is only the latest version available in official fedora site.

All older builds from stable are in the build browser:
https://builds.coreos.fedoraproject.org/browser?stream=stable&arch=x86_64

**Comment by hector-vido** [comment]
I don't find in anywhere, there is a way to update the documentation? I would gladly do that.
