### ISSUE TITLE
marketplace-operator with changed defaults and `registry.access.redhat.com` not working anymore

### ISSUE THREAD

**Issue by bo0ts** [openshift/okd#1033]
The marketplace-operator shipped with OKD uses a different registry for the generated `catalogsources` (e.g. `community-operators`). This is done through a `sed` step during the build process: `sed -i 's;registry.redhat.io;registry.access.redhat.com;' /defaults/03_community_operators.yaml` (see https://quay.io/repository/openshift/okd-content/manifest/sha256:937327f92a7c9e45551871812d52fb14c6e42d3cf074d44383970719faa949c0).

Unfortunately since today `registry.access.redhat.com` isn't working anymore. Is this a planned change or downtime?

**Comment by vrutkovs** [comment]
```
$ podman manifest inspect registry.access.redhat.com/redhat/community-operator-index:v4.9                                                                
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
```
Works fine here

**Comment by bo0ts** [comment]
Working again here as well. I suspect this was caused by the ongoing `quay.io` outage.
