### ISSUE TITLE
vSphere: Adding custom CA for external registry not possible after installation

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#104]
Hi,

I tried to add a custom CA for our company registry to OKD after a fresh installation. I followed the instructions on

https://docs.openshift.com/container-platform/4.3/builds/setting-up-trusted-ca.html 
or
https://docs.openshift.com/container-platform/4.3/registry/configuring-registry-operator.html#images-configuration-cas_configuring-registry-operator

After I created a simple pod which should pull an image from our external registry, I constantly got x509 errors.

Only the method of setting my custom CA in **install-config.yaml** to the field **additionalTrustBundle** worked for me:

https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html

I'm not sure if this is a bug.

Release image: 4.4.0-0.okd-2020-03-14-003840

Thanks and greetings,

Josef

**Comment by LorbusChris** [comment]
Is it a single cert or a bundle?
Possibly related: https://github.com/coreos/ignition/issues/931

**Comment by LorbusChris** [comment]
hm looking at this, the field _is_ called **additionalTrustBundle**.

**Comment by jomeier** [comment]
Its a single cert.

**Comment by jomeier** [comment]
Sorry: It's a root CA and an intermediate cert -> CA Bundle.

How do I have to add that in a running cluster?

**Comment by vrutkovs** [comment]
Does your pod mount a custom CA and uses it to access the registry?

I don't think its an issue (its certainly not an OKD issue).

**Comment by jomeier** [comment]
I create a pod which pulls its image from an external registry which uses our company cert bundle.

If I add the cert bundle in one of this methods here:

https://docs.openshift.com/container-platform/4.3/builds/setting-up-trusted-ca.html
or
https://docs.openshift.com/container-platform/4.3/registry/configuring-registry-operator.html#images-configuration-cas_configuring-registry-operator

no one of this methods works. 

The api server gets restarted and gets this cert bundle mounted. Pulling from the external registry doesnt work either without getting a x509 error.

**Comment by vrutkovs** [comment]
I'm pretty sure this has been resolved in GA build. Please reopen (or file new issue) if this still occurs
