### ISSUE TITLE
oVirt CSI operator failing on 4.9.0-0.okd-2021-12-12-025847

### ISSUE THREAD

**Issue by 0penshifty** [openshift/okd#1056]
**Describe the bug**
Upgraded cluster from v4.8.x to v4.9, and the oVirt CSI driver keeps failing due to liveness probes.

**Version**
oVirt IPI 4.9.0-0.okd-2021-12-12-025847

**How reproducible**
Cannot reproduce issue as I don't have the resources to spin up another cluster.

**Log bundle**
https://nextcloud.endofday.com/s/3KgjAnJdd7pdy4K

**Comment by vrutkovs** [comment]
Dupe of #1053?
