### ISSUE TITLE
Version OKD4 not found in update channel

### ISSUE THREAD

**Issue by ksamartsev** [openshift/okd#1059]
Hi!

I observe problem with OKD version 4.8.0-0.okd-2021-11-24-062209

In Cluster settings  i see error:

Version 4.8.0-0.okd-2021-11-24-062209 not found in channel stable-4. To request update recommendations, configure a channel that supports your version

[root@centos7-template ~]#  oc get clusterversion -o json|jq ".items[0].status.history"                                                               [
>  {
    "completionTime": "2021-11-27T00:48:37Z",
    "image": "registry.ci.openshift.org/origin/release@sha256:42971c167a72f9cea7fccae6a4dca6ead777930980848f447d0f8044d3b78049",
    "startedTime": "2021-11-25T09:03:03Z",
    "state": "Completed",
    "verified": true,
    "version": "4.8.0-0.okd-2021-11-24-062209"
  },
  {
    "completionTime": "2021-11-24T09:48:39Z",
    "image": "registry.ci.openshift.org/origin/release@sha256:1bd8465e745516310dcf45df838ef438bd1e541a054c1915b76e6199fb9658b8",
    "startedTime": "2021-11-24T09:07:34Z",
    "state": "Completed",
    "verified": false,
    "version": "4.8.0-0.okd-2021-11-24-014209"
  }
]

[root@centos7-template ~]# oc get clusterversion -o json|jq ".items[0].spec"

>{
  "channel": "stable-4",
  "clusterID": "dd53db71-c057-448d-85ec-564191ccd546",
  "desiredUpdate": {
    "image": "registry.ci.openshift.org/origin/release@sha256:42971c167a72f9cea7fccae6a4dca6ead777930980848f447d0f8044d3b78049",
    "version": "4.8.0-0.okd-2021-11-24-062209"
  },
  "upstream": "https://amd64.origin.releases.ci.openshift.org/graph"
}

Please,help me decide this case.

Thank you.

**Comment by vrutkovs** [comment]
See https://amd64.origin.releases.ci.openshift.org/#4-stable for a list of releases in `stable-4` channel

**Comment by tae9yu** [comment]
I faced same problem.

> Danger alert:Version 4.10.0-0.okd-2022-03-05-093244 not found in channel stable-4. To request update recommendations, configure a channel that supports your version.

The version 4.10.0-0.okd-2022-03-05-093244 was released on last weekend and I can't find it at https://amd64.origin.releases.ci.openshift.org/#4-stable or https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/#4.10.0-0.okd.
How can I updae to 4.10.0-0.okd-2022-03-07-131213?

**Comment by vrutkovs** [comment]
See [openshift/okd#getting-started](https://github.com/openshift/okd#getting-started)

>Please note that each nightly release is pruned after 72 hours
