### ISSUE TITLE
Certificates on OpenShift

### ISSUE THREAD

**Issue by Montana** [openshift/okd#1068]
I'm wondering if anyone could share the steps for updating the certificates on OpenShift + Kubernetes 4.6? I've checked using the below command and some are expired:

```bash
find /etc/kubernetes/ -type f -name "*.crt" -print|egrep -v 'ca.crt$'|xargs -L 1 -t  -i bash -c 'openssl x509  -noout -text -in {}|grep After'
```
I'm not able to find relevant steps to my UPN install. The following certificates are expired as well:

```bash
81789506 lrwxrwxrwx. 1 root root   59 Jan  9 00:32 kubelet-server-current.pem -> /var/lib/kubelet/pki/kubelet-server-2021-06-18-20-35-33.pem 81800208 lrwxrwxrwx. 1 root root   59 Jan  9 00:32 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2021-06-19-13-16-00.pem
```
Since the API server is offline, I'm not able to renew the certificates via `oc` commands. All OC commands return an error since the API server ( port 6443 ) is offline. This cluster is installed on VMware using the UPI method. I seen a really similar thread almost exactly, I was wondering if there's any remedy for this? 

Thank you so much! 
Cheers,
Montana Mendy

**Comment by rvanderp3** [comment]
For 4.6, the recovery 'should' be automatic and just require CSR approval.  I would start by ssh'ing to the control plane nodes and inspecting the kube-apiserver container logs with `crictl logs`.  afaik the kube-apiserver shouldnt be crashlooping.

**Comment by Montana** [comment]
Hey @rvanderp3, 

I started investigating and when I tested these additional lines for `api-server`, it fixed the problem for me:

```bash
--feature-gates=APIPriorityAndFairness=false
--runtime-config=flowcontrol.apiserver.k8s.io/v1beta1=false
```
I also removed the `/remove-sig cluster-lifecycle`.
