### ISSUE TITLE
Documentation: describe pull secret differences from OCP

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#107]
* "Fake" pull secret
* Optional pull secret in installer survey

**Comment by jxadro** [comment]
Hi, could you comment quicky what happens if we use the fake pull secret? Which are the limitations?

**Comment by vrutkovs** [comment]
* Telemetry and Insights operators would no longer send data to Red Hat servers
* Any content - like imagestreams and operators - from `registry.redhat.io` registry would be unavailable (`registry.access.redhat.com` would still be available though as it doesn't require a pull secret)

**Comment by kai-uwe-rommel** [comment]
In the OKD documentation, specifically in
https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere.html
it says:

"3. From the Pull Secret page on the Red Hat OpenShift Cluster Manager site, download your installation pull secret as a .txt file. This pull secret allows you to authenticate with the services that are provided by the included authorities, including Quay.io, which serves the container images for OKD components."

Is it really OK to use a pull secret from the OpenShift Cluster Manager site for an OKD installation? What instead (in case that the OKD docs have not been updated correctly in this spot)?

**Comment by bdlink** [comment]
Perhaps related to this, with 4.6 the samples operator does not fail, and does load samples, and templates, but get the alert

> The samples operator cannot find credentials for 'registry.redhat.io'. Many of the sample ImageStreams will fail to import unless the 'samplesRegistry' in the operator configuration is changed.

Documentation does not indicate alternative registry to use when not using a RedHat pull secret.  This information, along with a sample oc edit on how to configure would be useful.

**Comment by mburke5678** [comment]
@vrutkovs @jxadro Would adding a note like the following cover your concerns?

```
If you do not use the pull secret from the {cloud-redhat-com} site:

* Red Hat Operators are not available. 
* The Telemetry and Insights operators do not send data to Red Hat.
* Content from the [Red Hat Container Catalog](link:https://registry.redhat.io/) registry, such as image streams and Operators, are unavailable. 
```
https://github.com/openshift/openshift-docs/pull/29061
