### ISSUE TITLE
Cannot update to 4.9.0-0.okd-2021-12-12-025847

### ISSUE THREAD

**Issue by cronchiq** [openshift/okd#1071]
### Discussed in https://github.com/openshift/okd/discussions/1070

<div type='discussions-op-text'>

<sup>Originally posted by **cronchiq** January 14, 2022</sup>
Cannot upgrade OKD cluster from 4.8.0-0.okd-2021-11-14-052418 to 4.9.0-0.okd-2021-12-12-025847. Progress is stuck at 91%.

**ClusterID**: 008bfbb1-dbbf-4236-b1a2-dfbaf0b66f11
**ClusterVersion**: Updating to "4.9.0-0.okd-2021-12-12-025847" from "4.9.0-0.okd-2021-11-28-035710" for 41 hours: Unable to apply 4.9.0-0.okd-2021-12-12-025847: wait has exceeded 40 minutes for these operators: authentication
**ClusterOperators**:
        clusteroperator/authentication is degraded because CustomRouteControllerDegraded: Ingress.config.openshift.io "cluster" is invalid: [status.componentRoutes.currentHostnames: Invalid value: "oauth-openshift.apps.njzmp.okd.cz.o2": status.componentRoutes.currentHostnames in body must be of type hostname: "oauth-openshift.apps.njzmp.okd.cz.o2", status.componentRoutes.defaultHostname: Invalid value: "oauth-openshift.apps.njzmp.okd.cz.o2": status.componentRoutes.defaultHostname in body must be of type hostname: "oauth-openshift.apps.njzmp.okd.cz.o2"]

**must-gather**:  https://drive.google.com/file/d/1ApTbYcm3F6wTcDdCb03v8TDJU69Zzkwz/view?usp=sharing</div>

**Comment by vrutkovs** [comment]
No need to create a new issue until we find out in the discussion that its an OKD issue
