### ISSUE TITLE
Documentation: Drop section on adding RHEL compute nodes

### ISSUE THREAD

**Issue by sgreene570** [openshift/okd#108]
https://docs.okd.io/latest/machine_management/adding-rhel-compute.html

OKD latest does not support RHEL compute nodes. Maybe in the future, Fedora compute nodes could be supported, but I don't think that's on the roadmap at the moment. We should probably just remove this section of the docs.

**Comment by vrutkovs** [comment]
There is no "support" in OKD, but these playbooks could be used to add CentOS / Fedora nodes to the cluster.

I think the section should stay, but in OKD version "RHEL" needs to be replaced with "CentOS/Fedora".

However these require OpenShift repos to install kubelet / crio etc. and these are not available - so its probably easier to drop this section then mislead the users

**Comment by jxadro** [comment]
Hi, just to double check, with OKD, currently it is not possible to add CentOS nodes as compute nodes to an OKD cluster, is it? Or is it just a documentation issue?

Which repos would be needed to add to CentOS so the ansible script could work?

**Comment by vrutkovs** [comment]
Its possible, but not trivial. We don't publish kubelet and crio repos - these should be provided by CentOS PaaS team. Once you have them you'd use openshift-ansible master / release-4.4 branch playbooks

**Comment by sgreene570** [comment]
similarly https://docs.okd.io/latest/updating/updating-cluster-rhel-compute.html would also be affected
