### ISSUE TITLE
Status of the OKD documentation (https://docs.okd.io/latest/)

### ISSUE THREAD

**Issue by jxadro** [openshift/okd#109]
Hi

Is the URL https://docs.okd.io/latest/ the "official" documentation for OKD.

Is there any date planned to be 100% OKD flavour?

I think currently it is the OCP documentation changing OCP with OKD but everywhere it points to RHCOS instead of FedoraCOS and there is no specific information for OKD like for example what happens with the pull secret required for the installation.

Thank you.

**Comment by vrutkovs** [comment]
>Is the URL docs.okd.io/latest the "official" documentation for OKD.

Yes

>Is there any date planned to be 100% OKD flavour?

It is 100% OKD flavor, the rest is bugs we need to fix - see https://github.com/openshift/okd/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Akind%2Fdocumentation and "OKD" issues in https://github.com/openshift/openshift-docs repo
