### ISSUE TITLE
OKD 4.7 - Kernel Panic Error When Creating Bootstrap Node.

### ISSUE THREAD

**Issue by indacofilippo** [openshift/okd#1095]
hi,
I have a problem with installing a lab okd 4.7.
I'm following the guide https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee by @cragr (Craig Robinson), but when I get to the "Starting the bootstrap node" I get a "kernel panic" error after entering the parameters indicated in the guide.
I am trying to install OKD 4.7 with Fedora CoreOS 34.20210529.3.0, but I have also tried using Fedora CoreOS 35.20220116.3.0and got the same error.
Do you have any suggestions? Did it happen to you?
Thanks in advance for your help.

![OKD-BOOTSTRAP-01](https://user-images.githubusercontent.com/7949159/152691880-16613ca2-37c5-4898-b0a2-3767fcb20aa5.png)

![OKD-BOOTSTRAP-02](https://user-images.githubusercontent.com/7949159/152691877-023266bb-dd63-4e0e-a967-ae296785c921.png)

![OKD-BOOTSTRAP-03](https://user-images.githubusercontent.com/7949159/152691881-b0204e1d-81c8-4772-a17d-cdf5c5b646cc.png)

**Comment by vrutkovs** [comment]
"Cannot open root device "(null)" and "please append a correct root" with no disks available, not an OKD issue

**Comment by indacofilippo** [comment]
do you think it could be an error on the ESXi side?

**Comment by indacofilippo** [comment]
This problem has been solved. I recreated the VM by lowering the hardware compatibility to version 6.5 and using Fedora CoreOS 34.20210529.3.0
