### ISSUE TITLE
OKD support for GCP provider

### ISSUE THREAD

**Issue by DanyC97** [openshift/okd#11]
We would like to keep this master issue to link new issues which are related to GCP deployment so we can keep track as well as letting community know if a specific provider deployment is supported or has known issues etc

**Comment by vrutkovs** [comment]
Depends on https://github.com/coreos/fedora-coreos-tracker/issues/147 mostly

**Comment by bdurrow** [comment]
coreos/fedora-coreos-tracker#147  is now completed and closed; fcos images are now available in GCP, documentation here: https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-gcp/

**Comment by vrutkovs** [comment]
GCP support is available in Beta 4 at least, closing
