### ISSUE TITLE
Master polling the oVirt API too frequently

### ISSUE THREAD

**Issue by abaxo** [openshift/okd#110]
Hi,

I have raised a bugzilla for the oVirt project for this too, but I noticed that the OKD service seems to poll the ovirt hosted-engine api very frequently (looks to be generating a new session every 5 seconds). This is having a knock-on effect of exposing a bug in oVirt which causes the hosted-engine to stop responding to API requests as it is unable to do GC fast enough, even on a high powered system.

The BZ is https://bugzilla.redhat.com/show_bug.cgi?id=1815271

- Is it possible to reduce/tune the frequency of the API queries?
- Is it possible to re-use the same authentication session instead of generating a new one for each request?

**Comment by vrutkovs** [comment]
OKD uses the same ovirt api controller as OCP, so perhaps we don't need a tracking bug in OKD. I don't mind keeping it open for tracking purposes though

**Comment by abaxo** [comment]
So I *may* have some additional information for this. I had forgotten that I had configured the session timeout within oVirt to be 1440 minutes instead of 30minutes. I've reduced this back to 30minutes and I haven't seen this issue reoccur. 

My view is that:
a) this is a bug with oVirt, not with OKD.
b) it would be a "nice to have" to be able to configure the frequency of polling as right now oVirt users will be forced to have sessions no longer than the default 30minutes which could frustrate some workflows.

What do you think? Should we keep this ticket as a feature request, or should that be a seperate ticket somewhere else?

**Comment by abaxo** [comment]
As an afterthought it might be worth also having a feature request to re-use an existing session token rather than hammering the API with new login requests.
