### ISSUE TITLE
stable-4 4.9.0-0.okd-2022-01-29-035536 cluster does not offer upgrade to 4.9.0-0.okd-2022-02-12-140851

### ISSUE THREAD

**Issue by bdurrow** [openshift/okd#1113]
**Describe the bug**
After upgrading from 4.9.0-0.okd-2021-12-12-025847 to 4.9.0-0.okd-2022-01-29-035536 I expected to see an available upgrade to the most recent version available in the stable-4 channel (4.9.0-0.okd-2022-02-12-140851) but no upgrades are available.

**Version**
4.9.0-0.okd-2022-01-29-035536 GCP IPI

**How reproducible**
Unknown

**Log bundle**
If a log bundle is the only way to proceed then please close the issue.  I will not provide one.

```
# oc version
Client Version: 4.9.8
Server Version: 4.9.0-0.okd-2022-01-29-035536
Kubernetes Version: v1.22.1-1829+2cb60681522d23-dirty
# oc adm upgrade
Cluster version is 4.9.0-0.okd-2022-01-29-035536

Upstream: https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/graph
Channel: stable-4
No updates available. You may force an upgrade to a specific release image, but doing so may not be supported and may result in downtime or data loss.
# 
```

**Comment by vrutkovs** [comment]
This has happened before - https://github.com/openshift/okd/discussions/982#discussioncomment-1685551 :(

**Comment by bdurrow** [comment]
@vrutkovs, the linked comment mentions that the release was deleted.  Is that what happened here or were you referring to https://github.com/openshift/okd/discussions/1108#discussioncomment-2200157?

**Comment by vrutkovs** [comment]
Right, we don't need a bundle for this - the problem is with https://amd64.origin.releases.ci.openshift.org not persisting upgrade job results.

>were you referring to https://github.com/openshift/okd/discussions/1108#discussioncomment-2200157?

Right, sorry, wrong link

**Comment by vrutkovs** [comment]
RC stores all uprgade edges in the graph and due to amount of nightlies the secret has grown too large. It was pruned so now edges should be persisted. Running upgrade tests for latest 4.8 stable + two previous 4.9 stables now

**Comment by vrutkovs** [comment]
All edges should be in place now, please verify.

I'll leave this open in case this happens again soon.
/lifecycle stale

**Comment by bdurrow** [comment]
It looks like it works as expected:

Reachable from 4.9.0-0.okd-2022-01-29-035536:
```
# oc adm upgrade
Cluster version is 4.9.0-0.okd-2022-01-29-035536

Upstream: https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/graph
Channel: stable-4
Updates:

VERSION                       IMAGE
4.9.0-0.okd-2022-02-12-140851 registry.ci.openshift.org/origin/release@sha256:72e4a15592c5e20c1a663ac6d633b218e14e232c5ee0200c7c9f5f1b8a15caf6
```

As expected, *NOT* reachable from 4.9.0-0.okd-2021-12-12-025847:
```
# oc adm upgrade
Cluster version is 4.9.0-0.okd-2021-12-12-025847

Upstream: https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/graph
Channel: stable-4
Updates:

VERSION                       IMAGE
4.9.0-0.okd-2022-01-14-230113 registry.ci.openshift.org/origin/release@sha256:6360b9c14765767a0a4265990a9e95bedfa460a282c6b9d5ca8fb5b50a46d54d
4.9.0-0.okd-2022-01-29-035536 registry.ci.openshift.org/origin/release@sha256:ce42e3e42c19b2d97f51221a65e1f97191b6f51f6e8552ba339dace501e29d1a
```

**Comment by vrutkovs** [comment]
Excellent, thank you!
