### ISSUE TITLE
Unable to run buildah pod on OKD

### ISSUE THREAD

**Issue by darren-oxford** [openshift/okd#1127]
First thing to mention is this issue applies to OKD, not OpenShift, hence why reporting here and not upstream with OpenShift.

Trying to use a buildah pod as part of a Tekton pipeline results in the following error...
`Error: error writing "0 0 4294967295\n" to /proc/33/uid_map: write /proc/33/uid_map: operation not permitted`

Buildah needs to map multiple uids, the pipelines service account has cap_setgid, and cap_setuid capabilities.
Confirmed by presance of openshift.io/scc: anyuid in Pod manifest metadta.

User namespaces are enabled on FCOS

```
cat /proc/sys/user/max_user_namespaces
257127
```

This apears to be due to to the fact that FCOS kernel is > 5.12.

user_namespaces man page says...

If updating /proc/[pid]/uid_map to create a mapping that maps
UID 0 in the parent namespace, then one of the following must
be true:

*  if writing process is in the parent user namespace, then it
    must have the CAP_SETFCAP capability in that user
    namespace; or

*  if the writing process is in the child user namespace, then
   the process that created the user namespace must have had
   the CAP_SETFCAP capability when the namespace was created.

This rule has been in place since Linux 5.12.  It eliminates
 an earlier security bug whereby a UID 0 process that lacks the
 CAP_SETFCAP capability, which is needed to create a binary
 with namespaced file capabilities (as described in
 capabilities(7)), could nevertheless create such a binary, by
 the following steps

However, I tried adding SETFCAP capability to the pipelines scc, still no luck.

Any suggestions?

**Comment by vrutkovs** [comment]
@adambkaplan @mrunalp could you help us with buildah and kernel 5.12+ issue in builds?

**Comment by darren-oxford** [comment]
It turns out that I was on the right path but hadn't added the securityContext in the buildah clustertask supplied by the Tekton Operator, that my pipeline was using.

So in conclusion...

**The cause:**

FCOS using Kernel > 5.12 means that the behaviour is different between OKD & OpenShift. (This will become an issue for OpenShift further down the line when RHCOS reaches kernel > 5.12, so is a useful thing to be aware of.) The buildah container now requires CAP_SETFCAP capability.

**The Soloution**
- Add CAP_SETFCAP to the allowed capabilities in the pipelines SCC.
- Add CAP_SETFCAP to securityContext:capabilities:add: to buildah build step. 

This issue will affect any pods that try to perform uid mapping, so I don't know if perhaps CAP_SETFCAP should be added as default to the anyuid SCC?

**Comment by vrutkovs** [comment]
Oh, so its a problem with Tekton builds, not Builds and Buildconfigs, right?

**Comment by darren-oxford** [comment]
Yes this is a Tekton build that wasn't running. The buildah ClusterTask does not run privileged, it runs as a service account called pipelines that is attached to a scc called pipelines-scc. So it is using a custom SCC.

The reason for the suggestion of adding CAP_SETFCAP to anyuid SCC is that if you run a buildah pod on OpenSHift it can run using the anyuid SCC as kernel < 5.12 does not need CAP_SETFCAP. So adding CAP_SETFCAP to the anyuid SCC would mean that all containers that run on OpenShift using anyuid SCC would also run on OKD.

It may not be worthwhile, just people are going to trip up on it and not many are going to realise that the changes user_namespace behaviour due to the different kernels in the OS running on the nodes is the cause. I'll close this issue anyway as I found a solution, thanks for taking the time to look at it.
