### ISSUE TITLE
Back-off pulling image "registry.ci.openshift.org/origin/4.9-2022-02-17-165123@sha256:829abbb76b94c505fc22336f45f66d53d96d76c79a4c302290c87a6bf139396f"

### ISSUE THREAD

**Issue by nnachefski** [openshift/okd#1134]
I installed a cluster with the version 4.9-2022-02-17-165123 but now i'm getting a ton of these in the event logs for critical pods:

Back-off pulling image "registry.ci.openshift.org/origin/4.9-2022-02-17-165123@sha256:829abbb76b94c505fc22336f45f66d53d96d76c79a4c302290c87a6bf139396f"

Looking at the okd releases page, i dont even see this release in there anymore.  

How can i get this cluster stable again?  Can i go back to the latest 4.9 stable that is still on the releases page (4.9.0-0.okd-2022-02-12-140851)?  Or would going backwards like that tragically break this cluster?

Would i just update the 'desired' image and version in ClusterVersion to the older release that still exists?

```
                "desired": {
                    "image": "registry.ci.openshift.org/origin/release@sha256:564d16aff06cb12d827cce6d0f08bdaa1a619316edfd6700b8ed989ebf6b3916",
                    "version": "4.9.0-0.okd-2022-02-17-165123"
                },
                "history": [
                    {
                        "completionTime": "2022-02-19T13:00:59Z",
                        "image": "registry.ci.openshift.org/origin/release@sha256:564d16aff06cb12d827cce6d0f08bdaa1a619316edfd6700b8ed989ebf6b3916",
                        "startedTime": "2022-02-19T12:33:23Z",
                        "state": "Completed",
                        "verified": false,
                        "version": "4.9.0-0.okd-2022-02-17-165123"
                    }
                ],
```

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd#getting-started
>Please note that each nightly release is pruned after 72 hours

**Comment by nnachefski** [comment]
In case anyone else runs into this (deployed a connected cluster on a nightly build and then the upstream image gets purged after 72 hours) you can run this command to shift the install to a GA release instead of the nightly (it performs an 'upgrade' to the GA release)

`oc adm upgrade --allow-explicit-upgrade --to-image registry.ci.openshift.org/origin/release@sha256:72e4a15592c5e20c1a663ac6d633b218e14e232c5ee0200c7c9f5f1b8a15caf6`
