### ISSUE TITLE
VGAuth Service for open-vm-tools failing with libxmlsec1.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by msheldyakov** [openshift/okd#114]
systemd[1]: Started VGAuth Service for open-vm-tools.
VGAuthService[793]: /usr/bin/VGAuthService: error while loading shared libraries: libxmlsec1.so.1: cannot open shared object file: No such file or directory
systemd[1]: vgauthd.service: Main process exited, code=exited, status=127/n/a
systemd[1]: vgauthd.service: Failed with result 'exit-code'.

/usr/bin/VGAuthService: error while loading shared libraries: libxmlsec1.so.1: cannot open shared object file: No such file or directory
[test-bootstrap-300 core]# ldd /usr/bin/VGAuthService
	linux-vdso.so.1 (0x00007fffb29a8000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f0a432f0000)
	libxmlsec1.so.1 => not found
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f0a43187000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f0a430f1000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f0a42e11000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0a42def000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0a42c24000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0a42bb0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0a42ba9000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0a42b8f000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f0a42b66000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0a42a20000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0a43444000)

openshift-install version:
unreleased-master-2459-gfc790034704d5e279eabacd833d3e90c76815978-dirty
built from commit fc790034704d5e279eabacd833d3e90c76815978
release image registry.svc.ci.openshift.org/origin/release@sha256:418767cc3dd242a34d315aac07e51cd830bfaeda7ee11cd6dc5429c78e17665d

fcos version 31.20200223.3.0 (stable):
cat /etc/fedora-release
Fedora release 31 (Thirty One)

**Comment by vrutkovs** [comment]
Seems we're not mixing `xmlsec1` RPM in machine-os-content. Not sure if that affects volume mounting or network status, so probably not a beta blocker
