### ISSUE TITLE
Error translating config: No translator exists for variant openshift with version 4.10.0

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#1142]
If I follow the instructions on https://docs.okd.io/latest/installing/install_config/installing-customizing.html#installation-special-config-chrony_installing-customizing and download the latest butane binary from https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/ (Mon Jan 31 12:41:48 2022) I receive "Error translating config: No translator exists for variant openshift with version 4.10.0" when I'm trying to create the yaml configuration for latest OKD version 4.10.0-0.okd-2022-03-07-131213:

```
cat 99-worker-chrony.bu
variant: openshift
version: 4.10.0
metadata:
  name: 99-worker-chrony 
  labels:
    machineconfiguration.openshift.io/role: worker 
storage:
  files:
  - path: /etc/chrony.conf
    mode: 0644 
    overwrite: true
    contents:
      inline: |
        pool *** iburst trust
        pool *** iburst
        pool *** iburst
        driftfile /var/lib/chrony/drift
        makestep 1.0 3
        rtcsync
        logdir /var/log/chrony

./butane 99-worker-chrony.bu -o 99-worker-chrony.yaml
Error translating config: No translator exists for variant openshift with version 4.10.0

```

**Comment by vrutkovs** [comment]
That sounds like `butane` issue (https://github.com/coreos/butane), not OKD?

**Comment by myg0v** [comment]
I can not evaluate if its a mistake in the documentation or an issue with butane. I opened also an issue here: https://github.com/coreos/butane/issues/330
