### ISSUE TITLE
Documentation: Update oc CLI installation instructions

### ISSUE THREAD

**Issue by sgreene570** [openshift/okd#115]
https://docs.okd.io/latest/cli_reference/openshift_cli/getting-started-cli.html

Not sure what the "official" way to install the oc and installer binaries is, but this section of the docs mentions having an active OKD subscription and using subscription manager to installer the oc rpm, which isn't correct.

**Comment by vrutkovs** [comment]
Correct, we don't make RPMs. Instead OKD should have a section to download `oc` from mirror.openshift.com
