### ISSUE TITLE
OVN-kubernetes failinng to bind port on pods

### ISSUE THREAD

**Issue by uselessidbr** [openshift/okd#1172]
**Describe the bug**

Majority of pods at all nodes in our cluster are unable to create containers, they get stuck with status ContainerCreating. 

The "multus-admission-controller" and "network-metrics-daemon" pods won't even start, which i think is the cause. 

**Version**

Client Version: 4.7.0-0.okd-2021-06-04-191031
Server Version: 4.9.0-0.okd-2021-11-28-035710
Kubernetes Version: v1.22.1-1820+4dd1b5a1afc832-dirty
**How reproducible**

100% of time when creating a new pod that is using multus
**Log bundle**

Here is an example of a pod:

(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_revision-pruner-112-master-2_openshift-kube-scheduler_f51f1602-3d29-4986-8552-42cdc4e7c869_0(a4b87b62e89cd9e50f1593002430cf50bbc2455d8d4409ba9c4fcb9bba2f7492): error adding pod openshift-kube-scheduler_revision-pruner-112-master-2 to CNI network "multus-cni-network": [openshift-kube-scheduler/revision-pruner-112-master-2:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[openshift-kube-scheduler/revision-pruner-112-master-2 a4b87b62e89cd9e50f1593002430cf50bbc2455d8d4409ba9c4fcb9bba2f7492] [openshift-kube-scheduler/revision-pruner-112-master-2 a4b87b62e89cd9e50f1593002430cf50bbc2455d8d4409ba9c4fcb9bba2f7492] failed to configure pod interface: timed out waiting for OVS port binding (ovn-installed) for 0a:58:0a:82:03:01 [10.129.4.8/23] '

Also we are facing these errors on ovnkube-node pods (ovnkube-node containter):

[openshift-multus/network-metrics-daemon-kx7sn ebbde0d354872f5e3e0d91bda0392ad5eea371f4db34302c2d3f575ef8808ade]
W0323 00:14:17.261510 2051160 helper_linux.go:426] Failed to delete OVS port ebbde0d354872f5: failed to run 'ovs-vsctl --timeout=30 del-port br-int ebbde0d354872f5': exit status 1
  "ovs-vsctl: no port named ebbde0d354872f5\n"
  ""
I0323 00:14:17.275738 2051160 cni.go:190] [openshift-multus/network-metrics-daemon-kx7sn ebbde0d354872f5e3e0d91bda0392ad5eea371f4db34302c2d3f575ef8808ade] DEL finished CNI request [openshift-multus/network-metrics-daemon-kx7sn ebbde0d354872f5e3e0d91bda0392ad5eea371f4db34302c2d3f575ef8808ade], result "", err <nil>
I0323 00:14:17.291878 2051160 cni.go:169] [openshift-network-diagnostics/network-check-target-r6mm9 901cbeb1a4ad046a78f1a2fb5e9b3dc8c3ed40f36c67f4b8149fc7c119dcba91] ADD starting CNI request [openshift-network-diagnostics/network-check-target-r6mm9 901cbeb1a4ad046a78f1a2fb5e9b3dc8c3ed40f36c67f4b8149fc7c119dcba91]
I0323 00:14:17.328823 2051160 helper_linux.go:258] ConfigureOVS: namespace: openshift-network-diagnostics, podName: network-check-target-r6mm9
I0323 00:14:17.905093 2051160 cni.go:169] [openshift-multus/network-metrics-daemon-kx7sn fa41b218418a02a55355ece63c26ad3041d1665a62bb2a493abdc38410b838d1] ADD starting CNI request [openshift-multus/network-metrics-daemon-kx7sn fa41b218418a02a55355ece63c26ad3041d1665a62bb2a493abdc38410b838d1]
I0323 00:14:17.933108 2051160 helper_linux.go:258] ConfigureOVS: namespace: openshift-multus, podName: network-metrics-daemon-kx7sn

On ovnkube-master (ovnkube-master container):

I0323 00:06:52.596823       1 node_tracker.go:162] Processing possible switch / router updates for node okd4-2ptts-master-2
I0323 00:06:57.456453       1 reflector.go:530] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.Endpoints total 24 items received
2022-03-23T00:07:07.693Z|00872|ovn_dbctl|INFO|Running command run -- set load_balancer b9ca48e8-fe59-4a07-a2f4-cc0d9322b49a external_ids:k8s.ovn.org/kind=Service external_ids:k8s.ovn.org/owner=openshift-multus/multus-admission-controller name=Service_openshift-multus/multus-admission-controller_TCP_cluster options:event=false options:reject=true options:skip_snat=false protocol=tcp selection_fields=[] "vips={\"172.30.201.172:443\"=\"\",\"172.30.201.172:8443\"=\"\"}"
I0323 00:07:07.686566       1 services_controller.go:233] Processing sync for service openshift-multus/multus-admission-controller
I0323 00:07:07.686610       1 kube.go:297] Getting endpoints for slice openshift-multus/multus-admission-controller-qv27t
I0323 00:07:07.686617       1 kube.go:340] LB Endpoints for openshift-multus/multus-admission-controller are: [] / [] on port: 0
I0323 00:07:07.686628       1 kube.go:297] Getting endpoints for slice openshift-multus/multus-admission-controller-qv27t
I0323 00:07:07.686633       1 kube.go:340] LB Endpoints for openshift-multus/multus-admission-controller are: [] / [] on port: 0
I0323 00:07:07.686667       1 services_controller.go:293] Service openshift-multus/multus-admission-controller has 2 cluster-wide and 0 per-node configs, making 1 and 0 load balancers
I0323 00:07:07.695721       1 services_controller.go:237] Finished syncing service multus-admission-controller on namespace openshift-multus : 9.15699ms

**Comment by uselessidbr** [comment]
I also noted this error:

`Warning  FailedCreatePodSandBox  121m                    kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_multus-admission-controller-97bp4_openshift-multus_710c4678-568b-4518-b389-80bc0e2d475c_0(4719ce09a4c2c6d9353cd74a8c4429a2d1b5b298cdd787aa98ed7554ecb1eb59): error adding pod openshift-multus_multus-admission-controller-97bp4 to CNI network "multus-cni-network": Multus: [openshift-multus/multus-admission-controller-97bp4]: have you checked that your default network is ready? still waiting for readinessindicatorfile @ /var/run/multus/cni/net.d/10-ovn-kubernetes.conf. pollimmediate error: timed out waiting for the condition`

**Comment by uselessidbr** [comment]
The error in the last comment only happens once.

The /var/log/openvswitch/ovsdb-server.log is showing those erros constantly:
2022-03-23T08:06:40.701Z|12863|reconnect|WARN|unix#45050: connection dropped (Connection reset by peer)
2022-03-23T08:06:40.701Z|12864|reconnect|WARN|unix#45051: connection dropped (Connection reset by peer)
2022-03-23T08:06:40.918Z|12865|reconnect|WARN|unix#45064: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.148Z|12866|reconnect|WARN|unix#45078: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.365Z|12867|reconnect|WARN|unix#45093: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.366Z|12868|reconnect|WARN|unix#45095: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.366Z|12869|reconnect|WARN|unix#45092: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.366Z|12870|reconnect|WARN|unix#45094: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.584Z|12871|reconnect|WARN|unix#45104: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.585Z|12872|reconnect|WARN|unix#45106: connection dropped (Connection reset by peer)
2022-03-23T08:06:41.707Z|12873|reconnect|WARN|unix#45119: connection dropped (Broken pipe)

**Comment by tonymalynn9** [comment]
hey @uselessidbr I've run into this issue before this solution from RH helped. https://access.redhat.com/solutions/6449381

**Comment by JaimeMagiera** [comment]
@uselessidbr Did the above solution work for you?

**Comment by uselessidbr** [comment]
> @uselessidbr Did the above solution work for you?

Had to destroy and rebuild the cluster as it was production environment and so didnt have the chance to test this workaround.

**Comment by vrutkovs** [comment]
Closing as it doesn't have must-gather provided
