### ISSUE TITLE
Cannot DNS-resolve the internal cluster registry

### ISSUE THREAD

**Issue by mihaigalos** [openshift/okd#1184]
Cannot DNS-resolve the internal cluster registry.

**Description**

I can see [this](https://github.com/openshift/okd-machine-os/pull/156) change got merged since we have the service run on the nodes in our cluster.
Seems the `fix-resolv-conf-search.service` does not always correctly remove the `search .` from `/etc/resolv.conf` (symlink to `/run/systemd/resolve/resolv.conf`):
```bash
sh-5.1# cat /run/systemd/resolve/resolv.conf 
# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.100.126.13
search .
```
Sometimes the `search .` is removed correctly, sometimes no.
We suspect something is overwriting the file and readding the `search .` after the fixer service ran.

**Version**
4.10.0-0.okd-2022-03-07-131213
FCOS 35
Fresh installation.

**How to reproduce**
```bash
$ curl image-registry.openshift-image-registry.svc.cluster.local:5000

curl: (6) Could not resolve host: image-registry.openshift-image-registry.svc.cluster.local
```

**Comment by mihaigalos** [comment]
It's a new install:

> Fresh installation.

**Comment by fortinj66** [comment]
Yup...  See my edit <sigh/>

I'd try a nightly and see if it still happens

**Comment by mihaigalos** [comment]
Hi @fortinj66,
Nightly is not an option for us at the moment.

Can you maybe share a reference or explanation of the other fix which fixes this?
We would love to know what it is, since we invested effort in debugging this. :sweat_smile:

**Comment by fortinj66** [comment]
This is the one...  It changes the timing for the service:  https://github.com/openshift/okd-machine-os/pull/324

**Comment by kai-uwe-rommel** [comment]
See here: https://bugzilla.redhat.com/show_bug.cgi?id=2063414

**Comment by mihaigalos** [comment]
Thank you all. I've manually applied the patch as a script for the moment, until we upgrade to a higher version.
