### ISSUE TITLE
Documentation: Update OKD telemetry info

### ISSUE THREAD

**Issue by sgreene570** [openshift/okd#119]
https://docs.okd.io/latest/support/remote_health_monitoring/about-remote-health-monitoring.html

Red Hat telemtry only kicks in for clusters with valid pull secrets. Thus OKD clusters can "opt out" of this feature.

**Comment by vrutkovs** [comment]
This is already covered though - https://docs.okd.io/latest/support/remote_health_monitoring/opting-out-of-remote-health-reporting.html
