### ISSUE TITLE
OKD support for BareMetal provider

### ISSUE THREAD

**Issue by DanyC97** [openshift/okd#12]
We would like to keep this master issue to link new issues which are related to BareMetal deployment so we can keep track as well as letting community know if a specific provider deployment is supported or has known issues etc

**Comment by vrutkovs** [comment]
Baremetal UPI is supported, there's been a few reports that it works. CI has not been configured yet though.

IPI needs to have upstream metal3.io images using RDO promoted to `origin` (instead of internally built images) - and CI setup

**Comment by vrutkovs** [comment]
Closing this - baremetal UPI is supported, not entirely sure about IPI, but lets file a new bug for that
