### ISSUE TITLE
"cronjobs.v1.batch" mutated to "cronjobs.v1beta1.batch" then "APIRemovedInNextEUSReleaseInUse" alert is generated

### ISSUE THREAD

**Issue by titou10titou10** [openshift/okd#1202]
**Describe the bug**

  With OKD 4.10.0-0.okd-2022-04-23-131357, when a`Cronjob`is created, the version is "magically"  mutated(?) to the now soon to be removed older/beta version, triggering a`"APIRemovedInNextEUSReleaseInUse"`alert

Creating a Cronjob with:

    kind: CronJob
    apiVersion: batch/v1
    {...}

is immediately changed to:

    kind: CronJob
    apiVersion: batch/v1beta1
    {...}

and triggers the following alert:

    APIRemovedInNextEUSReleaseInUse

    Deprecated API that will be removed in the next EUS version is being used. 
    Removing the workload that is using the batch.v1beta1/cronjobs API might be necessary for a successful upgrade to the next EUS cluster version. 
    Refer to `oc get apirequestcounts cronjobs.v1beta1.batch -o yaml` to identify the workload.

**Version**

    oc version
    Client Version: 4.10.0-0.okd-2022-04-23-131357
    Server Version: 4.10.0-0.okd-2022-04-23-131357
    Kubernetes Version: v1.23.5-rc.0.2062+9ce5071670476d-dirty

**How reproducible**
   
    Always

**Comment by titou10titou10** [comment]
this is probable du to [bug 2065840](https://bugzilla.redhat.com/show_bug.cgi?id=2065840)

**Comment by vrutkovs** [comment]
4.10 cherry-pick - https://bugzilla.redhat.com/show_bug.cgi?id=2106385

Lets follow this in bugzilla, as its not OKD-specific?
