### ISSUE TITLE
[4.10] Alertmanager is not properly formatting `externalURL` field in alert payloads

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/okd#1203]
Alertmanager payloads now have an invalid URL string for the `externalURL` value. They now look like this:

```
[...]
externalURL: "https:///console-openshift-console.basedomain.tld/monitoring",
[...]
``` 
Note the three slashes after `https:`. I'm not sure what is causing this. Attempting to manually edit the YAML for the Alertmanager StatefulSet does not work, as something (not CMO as far as I can tell, because it still happens when I manually scale CMO to 0) seems to immediately put it back. Attempting to manually set an `externalUrl` via `cluster-monitoring-config` doesn't work either.

**Version**

4.10.0-0.okd-2022-04-23-131357

**How reproducible**

100% of the time for me so far. But my sample size is 1 so that's not very representative.

**Comment by vrutkovs** [comment]
We don't have a customized monitoring operator in OKD, so its probably affecting OCP as well. Lets file a bugzilla for this problem, no need to have a separate OKD issue for this
