### ISSUE TITLE
GCP install is stuck on bootstrap - LB marks bootstrap as not healthy

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#121]
After recent installer rebase api-int LB is no longer marking bootstrap as healthy once MCS is started. As a result, masters can't fetch Ignition from MCS.

This doesn't happen in OCP 4.4

**Comment by abaxo** [comment]
Possibly related to #120  ?

**Comment by vrutkovs** [comment]
Should be fixed since 4.4.0-0.okd-2020-04-09-120408
