### ISSUE TITLE
[OpenStack] installer is stuck on "Image import started."

### ISSUE THREAD

**Issue by VivianMeally** [openshift/okd#122]
Installer failing on uploading Fcos image to Glance.

OpenStack Version: Train

OKD Version: release:4.4.0-0.okd-2020-03-28-092308

Log:
```
DEBUG Generating Terraform Variables...
INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200310.3.0/x86_64/fedora-coreos-31.20200310.3.0-openstack.x86_64.qcow2.xz?sha256=dc045796f1ed272a1a77fc9fd59b667a4c646fb1e4129b1f8f31578a58e3bf8b'
INFO The file was found in cache: /root/.cache/openshift-installer/image_cache/c3c5779901a590f83626725a3aa0fed5. Reusing...
DEBUG Creating a Glance image for RHCOS...
DEBUG Image dev3-fj2kp-rhcos was created.
DEBUG Checking if the image import mechanism is supported
DEBUG Glance Direct image import plugin was found
DEBUG Using Image Import API to upload RHCOS to the image "dev3-fj2kp-rhcos" with ID "143848fe-785f-4be6-bab8-4e7f02e74ec8"
DEBUG The data was uploaded.
DEBUG Begin image import for the image "dev3-fj2kp-rhcos" with ID "143848fe-785f-4be6-bab8-4e7f02e74ec8"
DEBUG Image import started.

```

**Comment by vrutkovs** [comment]
@mandre any ideas how to debug image upload to Glance?

**Comment by mandre** [comment]
Could you let us know what the status of the image is with `openstack image show dev3-fj2kp-rhcos`.

From what I can tell from the logs, the image was uploaded correctly to your cloud and it is being imported into glance using the direct import plugin. It means that glance will chose the correct image format depending on your backend. It may be that this operation is particularly slow on your cloud?

If the image status is `importing`, the image import is still in progress. It will move to `active` once finished and the installer will go on with the deployment.

Do you know what backend you are using for glance?

You can see it in glance configuration file (if you're administering your openstack cloud):
https://docs.openstack.org/glance/latest/configuration/configuring.html#configuring-glance-storage-backends

If you have access to the glance logs, you might also find some information about what is going on.

**Comment by VivianMeally** [comment]
> > Do you know what backend you are using for glance?

ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)

> > If the image status is importing, the image import is still in progress. It will move to active once finished and the installer will go on with the deployment.

Waited more than 1h, it was still in "importing" status
 
At the weekend I have tested this version, import worked fine.
https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-03-25-102431
```
openstack image show dev3-fj2kp-rhcos
+------------------+------------------------------------------------------------------------------+
| Field            | Value                                                                        |
+------------------+------------------------------------------------------------------------------+
| checksum         | None                                                                         |
| container_format | bare                                                                         |
| created_at       | 2020-03-30T20:09:52Z                                                         |
| disk_format      | qcow2                                                                        |
| file             | /v2/images/143848fe-785f-4be6-bab8-4e7f02e74ec8/file                         |
| id               | 143848fe-785f-4be6-bab8-4e7f02e74ec8                                         |
| min_disk         | 0                                                                            |
| min_ram          | 0                                                                            |
| name             | dev3-fj2kp-rhcos                                                             |
| owner            | 0d4d02f870474b16a7132cc8a6bb439e                                             |
| properties       | locations='[]', os_hash_algo='None', os_hash_value='None', os_hidden='False' |
| protected        | False                                                                        |
| schema           | /v2/schemas/image                                                            |
| size             | None                                                                         |
| status           | importing                                                                    |
| tags             | openshiftClusterID=dev3-fj2kp                                                |
| updated_at       | 2020-03-30T20:10:14Z                                                         |
| virtual_size     | None                                                                         |
| visibility       | shared                                                                       |
+------------------+------------------------------------------------------------------------------+

```

**Comment by mandre** [comment]
It seems like the image wasn't staged properly. I checked our code and found we didn't check for failures correctly. This should be fixed with https://github.com/openshift/installer/pull/3385

Now that doesn't explain why your image wasn't stage -- but at least with the above patch the installer should let you know then the image failed to upload.

Perhaps glance logs tell you the reason why it failed to stage the image?

**Comment by LorbusChris** [comment]
Unfortunately the Ignition binary in FCOS does not yet understand HTTPHeaders in Ignition config, so provisioning is likely broken due to this for OpenShift right now. The next release of Ignition will support this (it has already merged into master).

**Comment by mandre** [comment]
I got access to another cloud where the glance direct import was enabled, and I got the same result where the installer also blocks on image import. The image was still in `uploading` status, meaning it has finished uploading but hasn't started the image import (I know... poor naming) after leaving it running overnight. I also tried using the glance image-create-via-import command, same result. Which leads me to think, it's a misconfiguration of glance but also that glance direct import might be broken for A LOT of people.

As a consequence we decided to switch back to the usual image upload in the installer until we're able to detect if the cloud *really* supports glance direct image import: https://github.com/openshift/installer/pull/3394

**Comment by vrutkovs** [comment]
`fcos` cherrypick for this PR - https://github.com/openshift/installer/pull/3397

**Comment by LorbusChris** [comment]
Ignition v2.3.0 with stable spec 3.1 was released last Thursday and will likely make its way into the next Fedora CoreOS release images.

We also need to update the import here: https://github.com/openshift/installer/blob/fcos/pkg/tfvars/openstack/bootstrap_ignition.go#L14
