### ISSUE TITLE
4.10.0-0.okd-2022-05-07-021833 and csi.vsphere.vmware.com snapshots stay in pending state

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#1223]
Did a fresh install 4.10.0-0.okd-2022-05-07-021833 (3 masters, 4 workers) in VSphere 6.7 cluster. Started to play around with csi.vsphere.vmware.com driver PVC's. Everything works fine when I create the PVC, a volumn is created in the fcd folder of my vsphere datastore. But running into a problem when I try to take a snapshot. The snapshot is stuck in a pending state with an event "Waiting for a snapshot default/test-csi-pvc-snapshot to be created by the CSI driver." Please note: I did not do any additional configuration after installing the okd cluster. Do I need to do any if so can someone point me to the config docs if I do.

![image](https://user-images.githubusercontent.com/23619505/167983640-2cb6675e-0127-4a73-8946-5ef52ecf70bb.png)

![image](https://user-images.githubusercontent.com/23619505/167983650-57f8ec5a-5bee-4137-910a-a85654aca8b1.png)

![image](https://user-images.githubusercontent.com/23619505/167983683-a31b9ed5-ea4a-49d7-baff-2c4e4d43e27d.png)

![image](https://user-images.githubusercontent.com/23619505/167983691-9e15b76d-8248-43d7-a46d-cf348f43e792.png)

![image](https://user-images.githubusercontent.com/23619505/167983753-b2efbe95-753e-44bd-a24f-ca7e33f5125c.png)

**Comment by vrutkovs** [comment]
Not OKD specific, no log bundle.

OKD team is a group of volunteers and its really hard to focus on resolving OKD specific issues when any problem is immediately filed as an OKD issue. Please use Discussions and provide must-gathers so that we could have them triaged
