### ISSUE TITLE
OKD Web interface 

### ISSUE THREAD

**Issue by tucsolo** [openshift/okd#1229]
Hello everyone,

we are experiencing a bug related to the web interface (console) of our OKD:

- We go in Developer mode
- Go to +Add button
- Browse catalog of all services
- Pick any "Template" ("Helm Charts" and "Devfiles" seems to not be afffected)
- Change variables (e.g.: the name)

If we resize/maximize/unmaximize the browser window, variables fallback to default value, forgetting all values. It happens on my browsers on Debian:

- Firefox 91.9.0esr
- Chromium 101.0.4951.64 

as well as on my workmates' Windows + different browsers.

OpenShift (OKD) version: 4.10.0-0.okd-2022-05-07-021833
Update channel: stable-4.10
IPI

**Comment by vrutkovs** [comment]
OKD uses OCP console, so its not an OKD specific bug.

Please file a new issue at https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform&component=Management%20Console
