### ISSUE TITLE
OKD cluster trial expire

### ISSUE THREAD

**Issue by bnk120** [openshift/okd#1237]
**Version**
4.10.9

In my Cluster dashboard on https://console.redhat.com/openshift I see information about expiration 60 days trial subscription:
"Your 60-day evaluation has expired. Edit subscription settings to continue using this cluster, or archive this cluster if it no longer exits". 
I thought openshift okd is free for everyone and now i cannot start my own cluster in my laptop after trial expired. 
Is it possible to renew my cluster or edit that subscription somehow so that I can work again in the same cluster?
I cannot figure out any option to change subscription. I've only seen option to 'archive cluster' or 'transfer cluster ownership'.
![Zrzut ekranu 2022-05-27 215916](https://user-images.githubusercontent.com/12136214/170782059-a1331b2b-950d-419b-b1e6-2ab5e03e26f5.png)

**Comment by JaimeMagiera** [comment]
Admittedly, it's a bit confusing. OKD doesn't currently have a separate relationship with the Red Hat console .So, all OKD clusters will show up as expired after that 60 days. It's something we can look into changing. Sorry for the confusion.

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd#getting-started:
>You will also be prompted for a pull-secret that will be made available to all of of your machines - for OKD4 you should either paste the pull-secret you use for your registry, or paste {"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}} to bypass the required value check (see https://github.com/openshift/okd/issues/182).

If you're using pull secret generated at console.redhat.com you're abiding the ToS which has evaluation period. OKD itself doesn't need a special pull-secret, so it won't expire
