### ISSUE TITLE
Upgrade from 4.9.0-0.okd-2022-02-12-140851 to 4.10.0-0.okd-2022-05-28-062148 results in worker nodes constantly rebooting

### ISSUE THREAD

**Issue by DavidHaltinner** [openshift/okd#1246]
**Describe the bug**

Upon running the upgrade from 2/12 to 5/28, the worker nodes end up in reboot loops (after all operators and masters upgraded).The majority of the reboots appear to be unclean.
The master/control plane nodes do not do this however.

This is a UPI bare metal install, as VMs on Nutanix AHV. 
A similar cluster in Azure does not show this issue.

**Version**

UPI, updating from 4.9.0-0.okd-2022-02-12-140851 to 4.10.0-0.okd-2022-05-28-062148

**How reproducible**

Begin a cluster upgrade as normal, and wait until the worker node upgrades begin.

**Log bundle**

must-gather is here: https://drive.google.com/file/d/1DWpm5CFJY3lBR1lac2Po9Iv8W-drrkw2/view?usp=sharing 
just the domain name has been obfuscated.

**Comment by vrutkovs** [comment]
>Kubelet stopped posting node status.

is all I see in the logs, it appears the nodes just don't boot? Check console output

**Comment by DavidHaltinner** [comment]
The nodes do boot fully. 
They will often be in a Ready state in openshift for a few minutes, before rebooting again. I have seen it up to about 10 minutes, and they will start running workloads, and then drop off.
I have been loging into the machine and am reviewing journalctl when it will reboot without warning.

**Comment by DavidHaltinner** [comment]
Sorry for the delay on this, finally got back to it.

I have been able to reproduce this same issue on an Azure UPI upgrade as well now (same path from 2/12).

Turns out the kernel is panic'ing when a pod using persistent storage gets scheduled, it panics on the mount command. I have examples attached with it panic'ing when mounting NFS, but I believe I had one with it also mounting CIFS (used for Azure FIles).

Right now, the only mitigation I have is to pause the worker MCP, and 'rpm-ostree rollback' the worker nodes, leaving the upgrade in a state of limbo.

Attached is console logs on the panic.
[console-2.log](https://github.com/openshift/okd/files/8838490/console-2.log)
[console-1.log](https://github.com/openshift/okd/files/8838491/console-1.log)


[Here](https://drive.google.com/file/d/146zjxew2ETSSuUsKqiwDet63WAVQ7YcR/view?usp=sharing) is also a must gather from the Azure cluster.

**Comment by vrutkovs** [comment]
Right, kernel crashes on mounting NFS4.1

This needs to be [reported to Fedora](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=kernel) so that once the update with the fix lands in Fedora updates it would be picked up by OKD.

Leaving this open as a tracking bug

**Comment by titou10titou10** [comment]
I don't know if it helps but most of our dynamic Persistent Volumes are on NFS. We are not using NFS for the nodes file systems themselves...)

It  works without any problem, no kernel panic ...

Versions: 

-  OKD v 4.10.0-0.okd-2022-05-28-062148 (Upgraded from version to versions since a few years)
-  Fedora CoreOS 35
-  kernel 5.17.9-200.fc35.x86_64
- UPI install on bare (Proxmox VMs - qemu-)
- NFS is accessed via the "official" K8S NFS provisionner: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
- NFS server: Truenas Core v12.0-U8.1:  https://www.truenas.com/truenas-core/

**Comment by DavidHaltinner** [comment]
> Maybe it is related to the persistent dynamic provisionner you are using? Which one is it ? a CSI NFS provisionner? a "proprietary" Azure CSI driver?

The NFS side is actually two separate Nutanix clusters running "Nutanix Files" with shares being served over NFS.
These are not dynamic provisioned (in fact these are legacy file shares we are migrating over to Azure Files slowly, and they have been around for years, and created manually in Nutanix). So the PV/PVCs were all created manually to point to existing shares.

I have been able to replicate this with 3 OKD clusters against two separate Nutanix clusters (with separate Files instances as well).
Both serve via NFS v4, is your TrueNAS serving via NFS v3 or v4? It could be related to the NFS version and the backend kernel driver for that version.

I can try and spin up a standalone box to act as an NFS server and try a few versions there to see what happens.

**Comment by DavidHaltinner** [comment]
Quicker than I thought, I have v3 and v4 enabled on one of the Nutanix Files instances.

So added the mountOption for nfsv3 to a PV to try out.

Sure enough, NFS v3 works, NFS v4 panics.

**Comment by titou10titou10** [comment]
@DavidHaltinner , from one of the worker nodes:

    nfsstat -m

    /var/lib/kubelet/pods/f1fff356-{...}/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root from xxx.xxx.xxx.xxx:/lv_k8s/oc4
     Flags: rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=xxx.xxx.xxx.xxx,local_lock=none,addr=xxx.xxx.xxx.xxx

    /var/lib/kubelet/pods/d6fb4db4-{...}/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root from truenas.xxxxx.xxxxx:/mnt/POOL-ZFS01/DS-OKD
     Flags: rw,relatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=xxx.xxx.xxx.xxx,local_lock=none,addr=xxx.xxx.xxx.xxx

First mount is from local proxmox NFS server in v4.2 and second line is a mount t othe truenas with NFS v4.1

**Comment by DavidHaltinner** [comment]
In doing some more trial and error with different versions and different things as NFS servers, I think I see at a high-level why this might be happening.

So my normal "Nutanix Files" NFS servers support NFS v4, but only 4.0 apparently ("mount.nfs: Protocol not supported" when I try to mount as 4.1 or 4.2 manually. The Nutanix itself doesnt tell me about the minor versions supported, might have to RTFM to check on that part, but thats besides the point for the moment).

The older OKD 4.9 clusters are mounting these shares as NFS 4.0, as it seems it should.

But 4.10 (or the FCOS underneath?) is forcing them to NFS 4.1 based on the panic. And since that protocol isnt supported on the NFS server side, instead of just failing to mount, the kernel panics.

If I add the NFS version to he PV, it works:
  mountOptions:
    - nfsvers=4.0

So it seems that whoever is controlling which NFS version to mount (I'm not sure if that decision is handled at the FCOS or OKD layer?), is choosing one that isnt supported, and then causing a panic.

So two issues it seems:

1. The kernel shouldnt panic when an unsupported NFS version is attempted to be moutned.
2. OKD is choosing to mount as a NFS version that isnt supported.

@vrutkovs you might know where that NFS version decision occurs?

**Comment by DavidHaltinner** [comment]
This appears to be fixed in 4.10.0-0.okd-2022-07-09-073606. I have upgraded 2 clusters and can no longer replicate the issue on them. I will do the remaining clusters next weekend, and should I see it again, I can reopen the issue.
I will close this issues as it does not appear that anyone else has reported the issue.
