### ISSUE TITLE
[Azure] OpenShift console operator not present in some installations

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#125]
Hi,

the day before yesterday I had twice the problem, that during an installation of OKD 4.4 (Beta Version!) I came in a situation that there was no openshift-console-operator or openshift-console present, not even the namespace existed.

The assumption was, that it has something to do with the CVO (may be).

Could this also be related to this PR here: https://github.com/openshift/machine-config-operator/pull/1603 ?

I recreated (deleted and created) the cluster again yesterday and everything worked as expected. 

I only saw this effect on Azure up to now but this could only be bad luck.

Thanks and greetings,

Josef

**Comment by vrutkovs** [comment]
console operator is always included in the payload and is required for cluster install to complete.

We're gonna need CVO logs (check pods in `openshift-cluster-version` namespace) and preferably must-gather archive

**Comment by jomeier** [comment]
I never saw this again. Maybe ist was a problem with the Beta1 release that occurred in parallel at that time.
