### ISSUE TITLE
Use FCOS with latest Ignition for openstack to support http headers

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#127]
This unblocks Swift-less install of post-rebase OKD on Openstack.

HTTP headers support has been merged in ignition master, so we need:

* [x] Build Ignition RPM
* [x] Prepare a new FCOS bootimage with a newer Ignition
* [x] Update installer URL to use this image for Openstack only
* [x] Revert these hacks once updated Ignition lands in stable FCOS and update images in installer
* [x] Fix Ignition spec2 declarations for master
* [x] Fix local DNS prepender https://github.com/openshift/installer/pull/3782

See https://kubernetes.slack.com/archives/C6AD6JM17/p1585678330035500

**Comment by MPV** [comment]
@vrutkovs It looks like https://github.com/coreos/ignition/issues/957 has been completed:

>Ignition 2.3.0 is now released, with a stabilized spec 3.1.0.

Am I right in assuming that the next step is to prepare a new FCOS bootimage with Ignition 2.3.0?

**Comment by vrutkovs** [comment]
Correct, we're waiting for updated Ignition RPM to land in stable FCOS release

**Comment by gerr1t** [comment]
Hi @vrutkovs . I am currently running into the problem you are describing, which I reported here: https://github.com/openshift/installer/issues/3745.

Is there any workaround for deploying OKD4 on OpenStack right now? Is there any working version?

**Comment by vrutkovs** [comment]
https://origin-release.svc.ci.openshift.org/releasestream/4.5.0-0.okd/release/4.5.0-0.okd-2020-06-21-084504 should have all necessary fixes
