### ISSUE TITLE
OOM-killer kill pod when he doesn't exceed limit

### ISSUE THREAD

**Issue by stillya** [openshift/okd#1275]
#### Version OKD: 3.11

OOM kill my pod when rss was low, but vm-total is high(higher than limit). Here's memory stat of pod, limit was 5GB:
``` bash 
> cat memory.stat
cache 0
rss 401408
rss_huge 0
mapped_file 0
swap 0
pgpgin 481
pgpgout 383
pgfault 1897
pgmajfault 0
inactive_anon 0
active_anon 372736
inactive_file 0
active_file 0
unevictable 0
hierarchical_memory_limit 4999999488
hierarchical_memsw_limit 4999999488
total_cache 0
total_rss 401408
total_rss_huge 0
total_mapped_file 0
total_swap 0
total_pgpgin 481
total_pgpgout 383
total_pgfault 1897
total_pgmajfault 0
total_inactive_anon 0
total_active_anon 372736
total_inactive_file 0
total_active_file 0
total_unevictable 0
> cat memory.usage_in_bytes
438272
```
I tried to turn off overcommited, but I need overcommited because my pod allocating more memory than limits, but not using. 
It feels like OOM looks on vm-total, not RSS, but it's **not** right.
P.S. _Pod is just small script on Python Dask._

**Comment by vrutkovs** [comment]
Please use https://bugzilla.redhat.com/enter_bug.cgi?product=Okd for OKD 3.11 bugs
