### ISSUE TITLE
openshift-install not creating the worker vm on vSphere using IPI

### ISSUE THREAD

**Issue by Murf** [openshift/okd#1287]
Describe the bug
I am trying to deploy a new cluster into my vSphere infrastructure using IPI
Bootstrap process completes but the workers are never created

Version
./openshift-install-4.10 4.10.0-0.okd-2022-07-09-073606
built from commit d63a12ba0ec33d492093a8fc0e268a01a075f5da
release image quay.io/openshift/okd@sha256:5a748561c829c23c7413b0fe0ec8f97b4eabf5cfd1934b9e93a8a5df3f59738d
release architecture amd64

IPI installation on vSphere

I have try 20 times bootstrap completes but the workers are never created
I have tried with 2 master/2 worker and 3 of each as well

this is my install-config.yml

apiVersion: v1
baseDomain: mylab.bogusdomain.net
proxy:
  httpProxy: http://proxy.gtm.mylab.bogusdomain.net:3128
  httpsProxy: http://proxy.gtm.mylab.bogusdomain.net:3128
  noProxy: mylab.bogusdomain.net,172.17.134.0/24,localhost,127.0.0.1,10.0.0.0/16,172.30.0.0/16,10.128.0.0/14
compute: 
- architecture: amd64
  hyperthreading: Enabled 
  name: worker
  replicas: 3
  platform:
    vsphere: 
      cpus: 8
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 150
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    vsphere: 
      cpus: 8
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 150
metadata:
  creationTimestamp: null
  name: snp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 172.17.134.130
    cluster: MYCLUSTER
    datacenter: MYDC
    defaultDatastore: mynfsdatastore01
    diskType: thin
    ingressVIP: 172.17.134.131
    network: my_pg
    password: apassword
    username: administrator@vsphere.local
    vCenter: ost-mod-vce-n01-mgmt.mylab.bogusdomain.net
publish: External
pullSecret: redacted
sshKey: redacted

I have no Forbidden entries in the must-gather logs indicating that all required destination url domains are whitelisted in the proxy correctly.

Is there any way I can try and find the pod/container that is supposed to bring up the worker VMs so i can check it's logs?

**Comment by jcpowermac** [comment]
@Murf a must gather would help troubleshoot this.

**Comment by Murf** [comment]
> @Murf a must gather would help troubleshoot this.

how do I send you a PM please? Or should i post them publicly?

**Comment by Murf** [comment]
The master nodes are tainted for some reason
Taints:             node-role.kubernetes.io/master:NoSchedule

**Comment by Murf** [comment]
> @Murf a must gather would help troubleshoot this.

https://drive.google.com/file/d/1ZiYQMy126Dgui5V7kjX0WVV0FZ6fp6rB/view?usp=sharing

**Comment by Murf** [comment]
> > @Murf a must gather would help troubleshoot this.
> 
> @jcpowermac https://drive.google.com/file/d/1ZiYQMy126Dgui5V7kjX0WVV0FZ6fp6rB/view?usp=sharing

@jcpowermac you should have permission now sorry

**Comment by jcpowermac** [comment]
@Murf the logs are full of messages that multiple components are unable to connect to vCenter.

Just one example:
```                                                                                    
namespaces/openshift-kube-controller-manager/pods/kube-controller-manager-snp-vlpsj-master-2/kube-controller-manager/kube-controller-manager/logs/current.log:2
211:2022-07-14T01:51:10.516234347Z E0714 01:51:10.516212       1 nodemanager.go:451] Cannot connect to vCenter with err: Post "https://ost-mod-vce-n01-mgmt.pla
tform.corp.company.com:443/sdk": dial tcp 10.145.244.130:443: i/o timeout  
```

**Comment by Murf** [comment]
> namespaces/openshift-kube-controller-manager/pods/kube-controller-manager-snp-vlpsj-master-2/kube-controller-manager/kube-controller-manager/logs/current.log:2
> 211:2022-07-14T01:51:10.516234347Z E0714 01:51:10.516212       1 nodemanager.go:451] Cannot connect to vCenter with err: Post "https://ost-mod-vce-n01-mgmt.pla
> tform.corp.company.com:443/sdk": dial tcp 10.145.244.130:443: i/o timeout

Thanks so much for this, I was focused on proxy and whitelisting, didn't even think of the Firewall rules after I initially set them all up.

**Comment by Murf** [comment]
Master nodes did not have network access to the vSphere API.
