### ISSUE TITLE
[4.11] Red Hat catalogs are enabled by default

### ISSUE THREAD

**Issue by zlojkota** [openshift/okd#1299]
![image_2022-08-03_14-42-43](https://user-images.githubusercontent.com/10040062/182616566-e0d34e58-0888-42dd-85ef-40051c9a9708.png)
[must-gather.local.7201955160566774722.zip](https://github.com/openshift/okd-machine-os/files/9251650/must-gather.local.7201955160566774722.zip)
cluster: 3 master|1worker load|1worker infrastructure
OpenShift version: 4.11.0-0.okd-2022-07-29-154152
Two operators error: **Error: ImagePullBackOff**

**Comment by vrutkovs** [comment]
https://github.com/operator-framework/operator-marketplace/pull/468 pre-creates OperatorHub on runlevel 3 with `create-only`. Later on we mix in our version at runlevel 50, but since the manifest is `create-only` CVO won't apply changes.

Seems we need a custom manifest for OKD payload

**Comment by vrutkovs** [comment]
This resulted in OLM bug, so lets track it in bugzilla - https://bugzilla.redhat.com/show_bug.cgi?id=2115225
