### ISSUE TITLE
OKD 4.3. Clarification about the pull secret options.

### ISSUE THREAD

**Issue by jxadro** [openshift/okd#130]
Hi.

I think this is not a duplicated of https://github.com/openshift/okd/issues/107.

Is it allowed to use a pull secret obtained in the redhat site in an OKD installation?

What are the consequences/restrictions?

In the doc there are some steps where if I'm not wrong you need a valid secret, for example to install logging.

https://docs.okd.io/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-eo-cli_cluster-logging-deploying

To install the logging feature it is documented to use an operator in the redhat-operators "repository".
´´´
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "elasticsearch-operator"
  namespace: "openshift-operators-redhat" 
spec:
...
  source: "redhat-operators" 
...
´´´

But to access to this operator repository and the images of the operator I think you must have configured a valid pull secret.

I couldn't find any documentation, neither in OKD or in OCP / RedHat side about if I'm allowed to use the redhat pull secret outside an OCP installation.

Thank you.

**Comment by vrutkovs** [comment]
Isn't that (shortly) answered in https://github.com/openshift/okd/issues/107#issuecomment-601381700?

>Is it allowed to use a pull secret obtained in the redhat site in an OKD installation?

Yes, sure, its not necessary to install OKD parts, but gives you access to images on redhat.io - and enables telemetry.
