### ISSUE TITLE
[4.11] Cannot shutdown masters

### ISSUE THREAD

**Issue by smuda** [openshift/okd#1315]
**Describe the bug**

Issuing "sudo shutdown now" (or pushing the power button) does not power off the master machine, but rather reboots. Worker does shutdown nicely though.

After issuing the "sudo shutdown now" command, as expected I cannot ssh to the node anymore ("System is going down. Unprivileged users are not permitted to log in anymore. For technical details, see pam_nologin(8).") Once the worker node has shutdown (and a period of "ssh: connect to host master1.okd4.example.com port 22: Connection refused" and then "System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)."), I can again ssh to the masters.

**Version**

User-provided metal installation according to https://github.com/AyoyAB/okd-with-ansible with three intel NUCs gen 10 as masters and one intel NUC gen 7 as worker.

Tried OKD-versions:
- 4.11.0-0.okd-2022-08-20-022919 (with FCOS 35.20220327.3.0): Does not shutdown
- 4.11.0-0.okd-2022-07-29-154152 (with FCOS 35.20220327.3.0): Does not shutdown
- 4.10.0-0.okd-2022-07-09-073606 (with FCOS 35.20220327.3.0): Shutdown correctly
- 4.10.0-0.okd-2022-06-24-212905 (with FCOS 35.20220327.3.0): Shutdown correctly
- 4.10.0-0.okd-2022-06-10-131327 (with FCOS 35.20220327.3.0): Shutdown correctly
- 4.10.0-0.okd-2022-05-28-062148 (with FCOS 35.20220327.3.0): Shutdown correctly

**How reproducible**

Every time.

**Log bundle**

[Log bundle](https://allberg-filedrop.s3.eu-north-1.amazonaws.com/must-gather.local.5510601452524825351.zip)

**Comment by vrutkovs** [comment]
This looks like a kernel issue, so its a FCOS/Fedora bug on particular hardware, not OKD-specific issue. Please refile this at https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

**Comment by smuda** [comment]
Hmm... I honestly thought that the FCOS was the same between masters and workers. Why should FCOS behave differently between masters and workers?

**Comment by vrutkovs** [comment]
It is the same, with different files layered though. Lets find out more debug info about this in FCOS tracker and if its OKD-specific files are to blame we'll reopen
