### ISSUE TITLE
Allowing deprecated api versions on OKD 4.4

### ISSUE THREAD

**Issue by parthakom2** [openshift/okd#133]
When deploying apps with deprecated api versions like v1beta1, we get this error
```
unable to recognize "STDIN": no matches for kind "Deployment" in version "extensions/v1beta1"
```

Is there a way to allow deprecated api versions on OKD 4.4?

**Comment by vrutkovs** [comment]
OKD 4.4 is based on k8s 1.17, support for `extensions/v1beta` has been [removed](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).
