### ISSUE TITLE
OKD cluster on GCP unstable. Install is unpredictable

### ISSUE THREAD

**Issue by rprav007** [openshift/okd#135]
Hello All,

This is weird but I am going to try and explain this the best way possible.

The openshift install on GCP is unpredictable, succeeds only 2 out of 10 times, running the same steps. During the times the install failed, the installer got stuck in different stages of the install, either creating resources or API server not coming up or bootstrapping. Unable to pin point one specific area where the installer was stuck each time. There was no underlying reason that could be identified for each failure as the steps and configurations were the same

After the install, during the 2 times when it was successful, the cluster was up for 5 mins and then its no longer reachable

After 5 mins I get Unable to connect to the server (API server is down)

I understand the installer is in Dev Preview, posting this to see if others have had similar problems.

Thanks

**Comment by vrutkovs** [comment]
Do you have bootstrap log bundles from unsuccessful attempts? Which base Fedora CoreOS image did you use?

**Comment by vrutkovs** [comment]
Probably related - https://github.com/openshift/installer/pull/3432 and https://github.com/openshift/machine-config-operator/pull/1633

**Comment by LorbusChris** [comment]
yup, those should fix this ^

**Comment by vrutkovs** [comment]
Is it still an issue? Recent nightlies (and beta3) should be more stable in this regard, thanks to pull retries in firstboot service and gcp-routes script refactoring

**Comment by LorbusChris** [comment]
I think these were the only known issues.
I'll close this for now
