### ISSUE TITLE
404: Not Found console registry template , broken url

### ISSUE THREAD

**Issue by bessalahAmar** [openshift/okd#137]
Description of problem:
can't access the template for the registry console provided in the okd 3.11 documentation(https://docs.okd.io/3.11/install_config/registry/deploy_registry_existing_clusters.html#registry-console) i'm getting 404 response

Steps to Reproduce:
1. curl https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_hosted_templates/files/v1.5/origin/registry-console.yaml

Actual results:
404: Not Found

Expected results:
get the template of the registry console

**Comment by vrutkovs** [comment]
Documentation bug, correct way to install registry console is to use openshift-ansible and set `openshift_hosted_manage_registry_console: true`

Please file an issue for that in https://github.com/openshift/openshift-docs
