### ISSUE TITLE
After successful deployment, etcd still trying to connect to removed bootstrap node.

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#139]
Release:  4.4.0-0.okd-2020-04-10-182115

I noticed the following in the logs of `etcd-operator`

```
W0411 21:17:24.716221       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://10.11.11.99:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.11.11.99:2379: operation was canceled". Reconnecting...
```
10.11.11.99 was the bootstrap node.

**Comment by cgruver** [comment]
Ran a clean install just to verify.

In this case, the installation is still completing (98%), but the bootstrap has already been removed and shutdown.

```
W0412 11:27:56.309090       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://10.11.11.49:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.11.11.49:2379: operation was canceled". Reconnecting...
```

`10.11.11.49` was the bootstrap node.

**Comment by cgruver** [comment]
This bootstrap node is still listed in the ENV for etcd pods.

<img width="1382" alt="Screen Shot 2020-04-12 at 8 22 45 AM" src="https://user-images.githubusercontent.com/39659182/79068715-f83e6a00-7c96-11ea-8408-97ce8b6c9ff7.png">

There are two config maps, `etcd-pod` & `etcd-pod-2` which appear to be the source of the ENV vars that still include the bootstrap node IP address.

**Comment by cgruver** [comment]
Also seeing the following alert:

<img width="1002" alt="Screen Shot 2020-04-12 at 8 48 58 AM" src="https://user-images.githubusercontent.com/39659182/79069216-908a1e00-7c9a-11ea-9fd3-eb25949da9b8.png">

The master nodes have 20GB RAM and 8 vCPUs.  No resource alerts firing on Nodes.

**Comment by vrutkovs** [comment]
That's UPI install, right?

@hexfusion @alaypatel07 do we have a guide how to reconfigure the operator to remove bootstrap etcd instance?

**Comment by cgruver** [comment]
@vrutkovs Correct.  UPI Bare Metal install.

**Comment by PiotrKlimczak** [comment]
Same problem with 4.4.0-0.okd-2020-04-16-074048-beta3.

**Comment by Koma-Andrea** [comment]
Also there!

**Comment by hexfusion** [comment]
/assign

cc @ironcladlou @retroflexer

**Comment by hexfusion** [comment]
> @hexfusion @alaypatel07 do we have a guide how to reconfigure the operator to remove bootstrap etcd instance?

The operator has a controller to handle this. Transient failure is possible but we should eventually scale down the bootstrap etcd instance from the etcd cluster. If that never happens that would be a bug.

**Comment by Koma-Andrea** [comment]
> > @hexfusion @alaypatel07 do we have a guide how to reconfigure the operator to remove bootstrap etcd instance?
> 
> The operator has a controller to handle this. Transient failure is possible but we should eventually scale down the bootstrap etcd instance from the etcd cluster. If that never happens that would be a bug.

It doesn't scale down after 24hr here.

**Comment by hexfusion** [comment]
can you post you `install-config` so I can understand the network topology? Also, full operator logs or must-gather if apiserver is up.

**Comment by Koma-Andrea** [comment]
> can you post you `install-config` so I can understand the network topology? Also, full operator logs or must-gather if apiserver is up.

I'm building with my [https://github.com/Koma-Andrea/openshift4_vmware_infra_provisioner](Pseudi IPI) it's a 3 master + 3 worker.
The installation is done like baremetal passing via kernel parameters  ip netmask hostname and gateway.
The DNS records are  triple checked and I've a duplicate PTR for the ip of the master records and etcd records (i cannot change them RN).
I'll provide logs as soon I reinstall (it's a lab I'm working on a new feature for this Pseudo IPI)

**Comment by deanpeterson** [comment]
This is happening on my 4.4.3 and 4.4.6 Openshift bare metal install as well.

**Comment by deanpeterson** [comment]
> > @hexfusion @alaypatel07 do we have a guide how to reconfigure the operator to remove bootstrap etcd instance?
> 
> The operator has a controller to handle this. Transient failure is possible but we should eventually scale down the bootstrap etcd instance from the etcd cluster. If that never happens that would be a bug.

It's not that the bootstrap etcd instance is still up, it's that the etcd-operator is still trying to connect to the bootstrap instance after it is gone. The etcd-pod.yaml file still retains references to the the bootstrap ip.

**Comment by ironcladlou** [comment]
Tracking this here: https://bugzilla.redhat.com/show_bug.cgi?id=1832923

**Comment by vrutkovs** [comment]
Lets use bugzilla for tracking
