### ISSUE TITLE
[oVirt]: Cluster passes install-complete, but machines do not get node link

### ISSUE THREAD

**Issue by abaxo** [openshift/okd#140]
Hiya,

So on build `4.4.0-0.okd-2020-04-10-182115` (maybe earlier too) it appears that something has regressed, as any machines (masters + workers) that have been provisioned as part of the install get a Machine definition and are enrolled into the cluster as a node successfully, but do not have a link between the record causing the machine set to believe that it has provisioned (but not provisioned as node state) N number of nodes, but 0 are ready and available. This in turn causes the alert `MachineWithoutValidNode` to fire. 

This is true both of newly introduced workers via machineset scaleup, and of the originally provisioned masters + workers.

Cheers
Craig

**Comment by abaxo** [comment]
I've just noticed that also it seems that metrics and logs are not available for all worker nodes, but are available for pods running on the masters. 

Possibly something certificate related?

**Comment by abaxo** [comment]
Metrics and logs were a red herring, though I have a few builds now where the cert approver doesnt seem to fire for new worker nodes.

**Comment by abaxo** [comment]
So i've just run a clean install against beta 4 and the behaviour persists. I'm having a bit of a poke around and from what I can see, the nodelink controller is expecting the machine to be reporting an InternalIP which it uses to resolve the node.

The machines that are created in the cluster (including newly provisioned machines) don't report an InternalIP address but report InternalDNS. There is also no ProviderID set either btw, I expected to see the UUID from oVirt in that field, but I don't know if that is a changed behaviour or what is expected.
```
status:
  addresses:
    - address: bee-zm2cm-worker-0-8qh8q
      type: InternalDNS
```

Log from the nodelink-controller container:
```
I0425 17:13:31.169139       1 nodelink_controller.go:291] Watched machine event, finding node to reconcile.Request
I0425 17:13:31.169159       1 nodelink_controller.go:334] Finding node from machine "bee-zm2cm-worker-0-8qh8q"
I0425 17:13:31.169167       1 nodelink_controller.go:351] Finding node from machine "bee-zm2cm-worker-0-8qh8q" by providerID
W0425 17:13:31.169174       1 nodelink_controller.go:353] Machine "bee-zm2cm-worker-0-8qh8q" has no providerID
I0425 17:13:31.169180       1 nodelink_controller.go:375] Finding node from machine "bee-zm2cm-worker-0-8qh8q" by IP
W0425 17:13:31.169187       1 nodelink_controller.go:386] not found internal IP for machine "bee-zm2cm-worker-0-8qh8q"
I0425 17:13:31.169193       1 nodelink_controller.go:328] No-op: Node for machine "bee-zm2cm-worker-0-8qh8q" not found
```

This is where my knowledge of the internals fails me, but I would guess that either the way that machines are being reported has changed and now machines don't get IP's reported (maybe this is relying on the appropriate guest tools to be running - in this case ovirt agent to be there if it gets the info from the cloud provider?) 

By the look of it this https://github.com/openshift/machine-api-operator/blob/master/pkg/controller/nodelink/nodelink_controller.go#L333-L406 is where the magic for figuring out which machine goes with which node happens. Could it be worth adding a function here to resolve by InternalDNS if ProviderID + InternalIP fails?

**Comment by abaxo** [comment]
Found this comment in the ovirt provider code: https://github.com/openshift/cluster-api-provider-ovirt/blob/master/pkg/cloud/ovirt/machine/actuator.go#L291-L292 looks like ovirt does need to rely on InternalDNS resolution for machines until the guest agent is there.

**Comment by abaxo** [comment]
Had a bit of a play and got the oVirt agent running to see if simply having the IP available via oVirt would help and sadly it doesn't seem that is the case. Machines still don't get a ProviderID (according to the machine-api log) or InternalIP according to the status field in the pod yaml.

```
[craig@LAPTOP-VH63CB0H darkh]$ oc get machines -o wide --all-namespaces
NAMESPACE               NAME                       PHASE         TYPE   REGION   ZONE   AGE     NODE   PROVIDERID   STATE
openshift-machine-api   bee-2lfzn-master-0         Provisioned                          3h33m
openshift-machine-api   bee-2lfzn-master-1         Provisioned                          3h33m
openshift-machine-api   bee-2lfzn-master-2         Provisioned                          3h33m
openshift-machine-api   bee-2lfzn-worker-0-7jptq   Provisioned                          6m29s
openshift-machine-api   bee-2lfzn-worker-0-ctvn9   Provisioned                          3h27m
openshift-machine-api   bee-2lfzn-worker-0-m26cv   Provisioned                          3h27m
openshift-machine-api   bee-2lfzn-worker-0-qtdpv   Provisioned                          3h27m
[craig@LAPTOP-VH63CB0H darkh]$ oc get nodes -o wide
NAME                       STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION           CONTAINER-RUNTIME
bee-2lfzn-master-0         Ready    master   3h31m   v1.17.1   10.50.103.84   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
bee-2lfzn-master-1         Ready    master   3h31m   v1.17.1   10.50.103.83   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
bee-2lfzn-master-2         Ready    master   3h32m   v1.17.1   10.50.103.85   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
bee-2lfzn-worker-0-7jptq   Ready    worker   3m5s    v1.17.1   10.50.103.89   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
bee-2lfzn-worker-0-ctvn9   Ready    worker   3h15m   v1.17.1   10.50.103.88   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
bee-2lfzn-worker-0-m26cv   Ready    worker   3h21m   v1.17.1   10.50.103.86   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
bee-2lfzn-worker-0-qtdpv   Ready    worker   3h17m   v1.17.1   10.50.103.87   <none>        Fedora CoreOS 31.20200420.20.0   5.5.17-200.fc31.x86_64   cri-o://1.17.1
```

**Comment by abaxo** [comment]
So more of a fiddle later, if I place the UUID in to the machine spec as per https://github.com/openshift/machine-api-operator/blob/release-4.4/install/0000_30_machine-api-operator_02_machine.crd.yaml#L37 then the other bits of the puzzle.. i.e the CSR approver that wasn't approving CSR's suddenly come back to life:

```
[craig@LAPTOP-VH63CB0H darkh]$ oc get machines -o wide --all-namespaces
NAMESPACE               NAME                       PHASE         TYPE   REGION   ZONE   AGE     NODE                       PROVIDERID                             STATE
openshift-machine-api   bee-2lfzn-master-0         Provisioned                          3h59m
openshift-machine-api   bee-2lfzn-master-1         Provisioned                          3h59m
openshift-machine-api   bee-2lfzn-master-2         Provisioned                          3h59m
openshift-machine-api   bee-2lfzn-worker-0-7jptq   Provisioned                          33m
openshift-machine-api   bee-2lfzn-worker-0-ctvn9   Running                              3h54m   bee-2lfzn-worker-0-ctvn9   c7c2be9a-5f5b-45fe-bde1-94e181b29623
openshift-machine-api   bee-2lfzn-worker-0-m26cv   Provisioned                          3h54m
openshift-machine-api   bee-2lfzn-worker-0-qtdpv   Provisioned                          3h54m
```

So.... I guess the million dollar question now is where was `.spec.providerID` previously being created from? I think it came from cluster-api-provider-ovirt repo.... but.. I can't make heads or tails of this crazy go language to figure it out. My gut feeling (no evidence) is something with @rgolangh 's latest change is pushing back the whole provider yaml definition, modifying the  provider Spec (because doing excellent things with cpu/ram/disk customisation) placing that copy back into the API but leaves out the providerID. I am probably completely wrong.

**Comment by abaxo** [comment]
Just checking in, this is still true in the latest beta.

**Comment by vrutkovs** [comment]
Please attach must-gather to get all nodes/machine information

**Comment by vrutkovs** [comment]
Closing as insufficient info has been provided. Please reopen if that is still an issue and attach must-gather
