### ISSUE TITLE
Issue with Safari Browser and OKD4.4 web console

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#142]
So, here's an odd one...

Safari version: Version 13.1 (15609.1.20.111.8)
OKD Version: 4.4.0-0.okd-2020-04-10-182115

Safari displays the following when connecting to the web console:

<img width="1321" alt="Screen Shot 2020-04-12 at 7 09 00 AM" src="https://user-images.githubusercontent.com/39659182/79067567-35522e80-7c8e-11ea-8a42-05860ead3224.png">

Randomly, connection will work.  As long as I stay logged in, the console works as expected.  Upon logging out the image above is displayed again.

Chrome works as expected.

Please, no commentary on Safari...  ;-)   I know...  But, it's the built in Browser.

**Comment by cgruver** [comment]
Captured some logs with the Safari Web Inspector:

```
https://oauth-openshift.apps.okd4.my.domain.org/oauth/authorize?client_id=console&redirect_uri=https%3A%2F%2Fconsole-openshift-console.apps.okd4.my.domain.org%2Fauth%2Fcallback&response_type=code&scope=user%3Afull&state=d34f446f
Failed to load resource: the server responded with a status of 503 ()

Failed to load resource: the server responded with a status of 403 (Forbidden)
```

Randomly, it will work.

**Comment by vrutkovs** [comment]
Looks like an auth server issue, so that would affect OCP too - could you file a bugzilla for that (with must-gather data)?

**Comment by cgruver** [comment]
Yes.  I'll open a bugzilla this weekend when I get back to my lab.

**Comment by cgruver** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1825489

The must-gather is 300MB compressed.  Is there a way to extract useful info from it?  Bugzilla did not want an attachment that big, for obvious reasons...

**Comment by cgruver** [comment]
This issue no longer appears in a new cluster built from 4.4.0-0.okd-2020-05-07-024321
