### ISSUE TITLE
OKD v4.4 on bare metal: nodes vm with Fedora CoreOS or RH CoreOS?

### ISSUE THREAD

**Issue by titou10titou10** [openshift/okd#144]
This is about the documentation on how to install OKD 4.4 on bare metal: https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html

In this doc, installing OKD 4.4 on bare metal requires the nodes vm to use FCOS:
https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal

FCOS is referenced everywhere on this doc

However, the steps to install the vm for the nodes tell us to download RH CoreOS iso images (`rhcos-<version>-installer.<architecture>.iso`): https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#creating-machines-bare-metal

So is the documentation right or wrong? is the installation procedure described there is correct? Do we have to install RH Core OS?

##### Version
okd v4.4 on bare metaL

**Comment by cgruver** [comment]
@titou10titou10 The current docs were copied from OCP 4.3 and are slowly being brought up to spec for Upstream OKD.

This might help you get going: https://github.com/cgruver/okd4-upi-lab-setup

It is very specific to my home lab setup, but will point you to the FCOS images and give some guide on a bare metal UPI install.

**Comment by titou10titou10** [comment]
@cgwalters thanks. I'll monitor the page
@cgruver thanks for the info. After reading your tutorial, I understand that the FCOS image is  downloade from https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable
I need to download the **ISO** and **RAW** images, currently 
- `fedora-coreos-31.20200323.3.2-live.x86_64.iso`
- `fedora-coreos-31.20200323.3.2-metal.x86_64.raw.xz`

in place of `rhcos-<version>-installer.<architecture>.iso` and  `rhcos-<version>-metal.<architecture>.raw.gz`

Now it is not clear if the kernel params are the same for FCOS (I'm not installing the vm with PXE but manually with proxmox ..) :

    coreos.inst=yes
    coreos.inst.install_dev=sda 
    coreos.inst.image_url=<bare_metal_image_URL> 
    coreos.inst.ignition_url=http://example.com/config.ign 
    ip=<dhcp or static IP address> 

@cgruver I've seen them in your`fcos-okd4.ipxe`file so I guess they are the same

Also is ther a place with the schema of the` install-config-upi.yaml `file and the possible keys and their meaning? can't find one anywhere

**Comment by cgruver** [comment]
This may help you with the install-config.yaml: https://github.com/openshift/installer/blob/master/docs/user/customization.md

**Comment by titou10titou10** [comment]
@cgruver this is what I was looking for. thanks
IMHO there should be a link to this page in every OKD installation page that gives examples of the `install-config.yaml` install file

**Comment by LorbusChris** [comment]
Let's track this over in https://github.com/openshift/okd/issues/147 :)
