### ISSUE TITLE
need openshift-install for Windows

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#145]
Hi, I'm currently writing scripts to fully automate deployment of OpenShift (and OKD) 4 into corporate vSphere environments. Our customers usually run their DHCP and DNS on Windows servers so I decided to use PowerShell for vSphere (PowerCLI) and DHCP/DNS server configuration. To avoid platform switching in the process of a cluster deployment it would be of great help if not only the "oc" client but also "openshift-install" were available for Windows. To me it looks like this should not be too difficult as it does not seem to perform any *nix specific black magic but would just need to be compiled for Windows. Or is there a specific reason why not? Since it is written in Go, it should compile for Windows? I can perhaps try myself but I do not have experience with Go...
BTW, I would only need support for creating the configs for on-premise vSphere installations, no public cloud or OpenStack support.

**Comment by vrutkovs** [comment]
See https://github.com/openshift/installer/issues/1586

**Comment by LorbusChris** [comment]
This is an RFE for installer, please refer to the issue linked above
