### ISSUE TITLE
[vSphere] extreme high, rising memory consumption of etcd-quorum-guards in machine-config-operator

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#146]
Hi,

I just saw coincidently that after an upgrade vom beta1 to beta2 three etcd-quorum-guard pods in the namespace openshift-machine-config-operator all have a memory consumption of over 2GByte. 

And it's rising:

Monitoring values:
https://ibb.co/K2ghSNq

must-gather:
https://drive.google.com/open?id=1yfqIOqpv6wz4wdSAJ22my-yM6h9SV3pN

Greetings,

Josef

Edit: The problem also exists in Beta 1.

**Comment by jomeier** [comment]
@vrutkovs
This PR seems to fix this problem:

https://github.com/openshift/machine-config-operator/pull/705/files

The changed readiness probe script does not contain this environment variable. Maybe that's the problem.

**Comment by jomeier** [comment]
https://github.com/elastic/cloud-on-k8s/pull/1716
https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1044666

**Comment by jomeier** [comment]
If that's the problem, it was introduced here:

https://github.com/openshift/machine-config-operator/commit/7ae0bd65eef333fa2562ee01595a0ea9af248dba#diff-e5d177c08966d149b95ea388efe556aa

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/1653 would fix that in OKD

**Comment by vrutkovs** [comment]
Fixed in https://origin-release.svc.ci.openshift.org/releasetag/4.4.0-0.okd-2020-04-16-002702
