### ISSUE TITLE
[okd] docs contain incorrect references to rhcos

### ISSUE THREAD

**Issue by dmueller2001** [openshift/okd#147]
https://docs.okd.io/latest/architecture/architecture-rhcos.html

should be 

https://docs.okd.io/latest/architecture/architecture-fcos.html

**Comment by omenos** [comment]
Vadim made the following note during the meeting in regards to this:

> updating URL in openshift-docs would be a bit more complex - these are generated from markdown files - and that means we'd have to come up with some generic name and get it approved by Legal - and that's not a fast process

**Comment by LorbusChris** [comment]
There are more references to `rhcos` here: https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html

This was reported by @titou10titou10 over in https://github.com/openshift/okd/issues/144

**Comment by vrutkovs** [comment]
All of the issues above have been resolved
