### ISSUE TITLE
[vSphere] installer creates MachineSet (in UPI mode)

### ISSUE THREAD

**Issue by slauger** [openshift/okd#149]
The installer currently creates a MachineSet for each master node, even if we're managing the infrastructure by our own (via IPI). This results in a cluster alert for each master node.

![image](https://user-images.githubusercontent.com/8333300/79386560-9b7ad200-7f6a-11ea-81ff-017a2f0506f9.png)

Current workaround: delete the MachineSet/Machines manually.

Expected behavior: the installer should not create a MachineSet when using UPI (for vSphere and all other cloud providers as well).

Tested with OKD beta 2. Reproducible with my nightly OKD installation pipeline.

**Comment by slauger** [comment]
Workaround for new clusters (after running `openshift-install create manifests --dir=config`):
```
rm -f config/openshift/99_openshift-cluster-api_master-machines-*.yaml config/openshift/99_openshift-cluster-api_worker-machineset-*.yaml
```

**Comment by kai-uwe-rommel** [comment]
I see the same problem. Both in OKD 4.4 and in OCP 4.4 deployments on vSphere.
I did not see this with OCP 4.3.

**Comment by vrutkovs** [comment]
[OKD 4.5 nightlies](https://origin-release.svc.ci.openshift.org/#4.5.0-0.okd) should have machine-api enabled for vSphere, so both in IPI and UPI mode these alerts should no longer pop up. Could you give those a try?

**Comment by kai-uwe-rommel** [comment]
Unfortunately, not at this time, due to time constraints.
It is currently not a problem for me (easy to delete those objects).
I have customer deployments the next two weeks ... busy preparing for that.
I assume the next beta or 4.5 will be out afterwards and then I can test this again.

**Comment by vrutkovs** [comment]
This should be resolved in Beta 6, please reopen if it still occurs on latest beta/nightly

**Comment by kai-uwe-rommel** [comment]
I get these alerts on a fresh 4.5 beta6 installation:
![grafik](https://user-images.githubusercontent.com/26381804/86281604-1c4a8100-bbde-11ea-920d-d15f4d19f001.png)
This was a UPI installation. I see these objects:
```

>oc get machineset -A                                       
NAMESPACE               NAME                    DESIRED   CURRENT   READY   AVAILABLE   AGE 
openshift-machine-api   kur-test-2pjrl-worker   0         0                             48m 
                                                                                            
C:\Work\ARS\openshift-deployment>oc get machine -A                                          
NAMESPACE               NAME                      PHASE          TYPE   REGION   ZONE   AGE 
openshift-machine-api   kur-test-2pjrl-master-0   Provisioning                          48m 
openshift-machine-api   kur-test-2pjrl-master-1   Provisioning                          48m 
openshift-machine-api   kur-test-2pjrl-master-2   Provisioning                          48m 


```

**Comment by vrutkovs** [comment]
Hmm, its safe to silence these errors, I'll check if installer needs a fix

**Comment by kai-uwe-rommel** [comment]
There is another problem now, probably related:

The (auto) provisioning of volumes for the automatically predefined storage class "thin" now fails. This has worked in 4.4 beta5 before. The error message I see is:

![grafik](https://user-images.githubusercontent.com/26381804/86287083-e0b4b480-bbe7-11ea-99a1-5f3f5e629cb0.png)

The folder path is not correct. The /Test is the vSphere datacenter and /Test/vm is the base VM folder, right? And the subfolder where the cluster VMs are is named "kur-test" (same like the cluster name). No idea why the vSphere storage provisioner now tries to append this "-2pjrl" suffix. But it is the same like in the machineset above.

**Comment by kai-uwe-rommel** [comment]
And how to fix that? I have edited /etc/kubernetes/cloud.conf on all three master nodes and restarted kubelet. But nothing happens (the pvc's remain pending).

**Comment by vrutkovs** [comment]
Storage issues are not related, this is installer mistakenly creating machine objects

**Comment by slauger** [comment]
My inital issue is resolved. The main problem was that there were a machineconfig CR, but no support for the machine-api. I did not expect that we get machine api support for OKD that fast. :)

I still have the alerts with beta 6, but that only happens because i do not create the VMs with the expected naming schema (and labels?) for the machine api. My customer has a strict policy/naming schema of VMs in vSphere. I should be able to solve this by fixing the references in the machineset CR. I already solved this for OpenShift UPI on Openstack.

> And how to fix that? I have edited /etc/kubernetes/cloud.conf on all three master nodes and restarted kubelet.

Editing files directly on the nodes should never be necessary! The `2pjrl` suffix is your infraID.

```
-bash$ oc get machineset c04-hb6bf-worker -n openshift-machine-api -o yaml 
....
          workspace:
            datacenter: datacenter1
            datastore: datastore1
            folder: /folder1/vm/c04-hb6bf
            server: vcenter.foo.bar.com
```

See also [here](https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md#infra-id) and [here](https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md#remove-machines-and-machinesets) (needs to be adopted for vSphere).

**Comment by kai-uwe-rommel** [comment]
Ok, I'll move this to anew issue.
I got the infraID and when I rename the VM folder, the storage class starts working.
But then this is a documentation issue.

**Comment by vrutkovs** [comment]
>The main problem was that there were a machineconfig CR, but no support for the machine-api. I did not expect that we get machine api support for OKD that fast. :)

I suppose these were Machine/MachineSet CRs (MachineConfig CRs are handled by MCO), right? Were these created manually or created by installer?

**Comment by slauger** [comment]
This is the result of a fresh installation of Beta 6 on vSphere with UPI:

```
root@jumphost01vt:~# oc get machineset -A
NAMESPACE               NAME               DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   c04-r444k-worker   0         0                             134m

root@jumphost01vt:~# oc get machine -A
NAMESPACE               NAME                 PHASE          TYPE   REGION   ZONE   AGE
openshift-machine-api   c04-r444k-master-0   Provisioning                          135m
openshift-machine-api   c04-r444k-master-1   Provisioning                          135m
openshift-machine-api   c04-r444k-master-2   Provisioning                          135m
```

If i remember correctly this is the exact same behaviour as on Openstack UPI, isn't it? In my eyes this issue is solved.

**Comment by vrutkovs** [comment]
Ah, so the OCP solution is [remove these manifests](https://github.com/openshift/installer/pull/3619/files) when running a UPI install. I'm not sure if its a good solution, but we'll have to stick to it in order not to diverge from master branch code too much

**Comment by slauger** [comment]
> Ah, so the OCP solution is remove these manifests when running a UPI install.

I think because we're still on OCP 4.4? 

My prefered way is to update the machineset spec (which is described in the same documentation), because i really wan't the benefits from the (e.g. the monitoring) - even when using UPI.

You could also create the machines in the expected schema for the MCO. Then it just works. The MCO searches for a specific naming schema (in a specific folder with the InfraID etc.).
