### ISSUE TITLE
OKD support for Libvirt provider

### ISSUE THREAD

**Issue by DanyC97** [openshift/okd#15]
We would like to keep this master issue to link new issues which are related to Libvirt deployment so we can keep track as well as letting community know if a specific provider deployment is supported or has known issues etc

**Comment by sferich888** [comment]
[This](https://github.com/openshift/installer/issues/2717#issuecomment-560486759) to be a reason to provide, libvirt as a provider, to the openshift-installer for OKD.

**Comment by sferich888** [comment]
https://github.com/openshift/installer/pull/2678 should unblock or resolve this, when its complete.

**Comment by vrutkovs** [comment]
Libvirt is fixed since https://github.com/openshift/installer/pull/3587

It requires installer to be built using `TAGS="libvirt" hack/build.sh`
