### ISSUE TITLE
I am not able to get the okd 4.4 cluster up and running after complete shutdown

### ISSUE THREAD

**Issue by claudio-walser** [openshift/okd#154]
Hello
As the title states, I am having a hard time to get my testing cluster up and running again after I shutdown all nodes. I tried to debug a bit for the last few days but was not able to identify the issue i ran into.

It is probably kind of an issue with cni, but thats only a vague assumption I developed from looking through the logs.

Kubelet logs on master nodes say:
`hyperkube[1439115]: E0419 06:35:25.152699 1439115 kubelet.go:2191] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network`

crictl info also says:
`{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": false,
        "reason": "NetworkPluginNotReady",
        "message": "Network plugin returns error: Missing CNI default network"
      }
    ]
  }
}`

podman ps -a also says
`ERRO[0000] error loading cached network config: network "podman" not found in CNI cache`

And for some reason my cluster seem to not be able to pull images from the openshift registry anymore, also from kubelet logs:
`Apr 19 06:36:52 master-1 hyperkube[1441529]: I0419 06:36:52.559123 1441529 event.go:281] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-etcd", Name:"etcd-master-1", UID:"a42e4e38ca0e2ad87045372d04509389", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedCreatePodSandBox' Failed to create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-master-1_openshift-etcd_a42e4e38ca0e2ad87045372d04509389_0": Error initializing source docker://registry.svc.ci.openshift.org/origin/4.4-2020-03-13-053843@sha256:2f68508143d397e98e2aa53967d28357263a10d0832d611bee1656b3a32ecbc2: Error reading manifest sha256:2f68508143d397e98e2aa53967d28357263a10d0832d611bee1656b3a32ecbc2 in registry.svc.ci.openshift.org/origin/4.4-2020-03-13-053843: manifest unknown: manifest unknown`

Any help would be appreciated :-)

**Comment by cgruver** [comment]
The issue may be as simple as a nightly build that no longer exists in the registry.  If you did not install from a local mirror, then version `4.4-2020-03-13-053843` is likely no longer in `registry.svc.ci.openshift.org`.

Did you build this cluster back in March?

https://docs.okd.io/latest/installing/install_config/installing-restricted-networks-preparations.html

**Comment by claudio-walser** [comment]
Yes, i did install it at the 14 of march. Any chance you know where i can change the image versions?
Do i have to replace all manually in /etc/kubernetes?

**Comment by cgruver** [comment]
Unfortunately, I think you are looking at a reinstall.  Unless someone else here knows some magic.

I’d recommend creating a local mirror if you build from a nightly release.  The beta releases will stick around longer, but not indefinitely.  So, periodic upgrades are necessary to stay current.

The only way to pin a version and decouple yourself from the dynamic nature of these early releases is a local mirror.  The link above shows you a quick way with containerized Quay.  I’ve got instructions for using Nexus in a tutorial I’ve been writing.

**Comment by claudio-walser** [comment]
I see, thank you for your help.
Since the cluster is gone, i might try some manual changes and eventually reinstall it anyway.
