### ISSUE TITLE
[oVirt] Installer not finding all networks if some have DNS configuration

### ISSUE THREAD

**Issue by thmarth** [openshift/okd#161]
**Describe the bug**
While stepping through the "install-config" part for oVirt, it won't list all networks on the oVirt cluster if one or more oVirt logical networks have the "DNS Configuration" set.
From my testing I was able to lengthen/shorten the list by setting the "DNS Configuration" option on different networks.
It seems to be using the order of networks as returned from '/ovirt-engine/api/networks' and it will include the network having the "DNS Configuration" set, but none of the networks _after_ that one.

This also impacts actual installation, I attempted to edit the install-config file, but it would not accept the (lower) network name there either, so it would appear the internal list is also stopped from fully populating when encountering this network

**Version**
4.4.0-0.okd-2020-04-21-163702-beta4
Platform: oVirt

**How reproducible**
Every time the openshift-install guide hit's a network with "DNS Configuration" it will stop listing further networks.

**Comment by vrutkovs** [comment]
@rgolangh please have a look?

**Comment by vrutkovs** [comment]
Is this still occurring in beta5?

**Comment by rgolangh** [comment]
This is an ovirt go sdk bug which was solved the the OCP part is tracked here https://bugzilla.redhat.com/show_bug.cgi?id=1838559

**Comment by rgolangh** [comment]
solved in master

**Comment by vrutkovs** [comment]
Should be fixed since https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.5.0-0.okd/release/4.5.0-0.okd-2020-07-01-152058, could you verify?
