### ISSUE TITLE
OKD 4.4 Single Node Cluster: etcd-quorum-guard should not attempt to deploy 3 replicas

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#162]
Link to issue opened in MCO project: https://github.com/openshift/machine-config-operator/issues/1695

When deploying a single node cluster with OKD 4.4, it is possible to set useUnsupportedUnsafeNonHANonProductionUnstableEtcd so that the bootstrap process will complete with only one Master node. However, the etch-quorum-guard deployment is still set to three replicas, two of which cannot start, (for obvious reasons). The deployment can be scaled down, but the operator immediately restores the replicas value to 3.

This prevents the cluster from running in a healthy state, and prevents upgrades.

**Comment by vrutkovs** [comment]
This should now work "out-of-the-box" in beta5.

When installer notices `master: 1` in install config it would inject etcd and ingress settings. MCO would now own etcd-quorum-guard deployment and scale it down to 1 replica when etcd has useUnsupportedUnsafeNonHANonProductionUnstableEtcd setting.
