### ISSUE TITLE
[oVirt] Installation issue: failed to get ovirt Terraform variables: no locks available

### ISSUE THREAD

**Issue by viniciusferrao** [openshift/okd#164]
**Describe the bug**

Installation cannot proceed with terraform errors, just after answering the questions about oVirt/RHV deployment

**Version**

okd:4.4.0-0.okd-2020-04-21-163702-beta4
Target RHV pool:
OS Version: RHEL - 7.8 - 2.el7ev
OS Description: Red Hat Virtualization Host 4.3.9 (el7.8)
Client running:
Red Hat Enterprise Linux release 8.2 (Ootpa)

**How reproducible**

100%

**Log bundle**

I can't even generate the logs with oc adm command, so here's what I've done:

$ oc adm release extract --tools quay.io/openshift/okd:4.4.0-0.okd-2020-04-21-163702-beta4

$ ls *.gz | xargs -n1 tar -xzf <= this was needed to extract the files since oc adm didn't extract it, perhaps here is the issue.

$ openshift-install create cluster
? SSH Public Key /home/ferrao@DOMAIN.COM/.ssh/id_ed25519.pub
? Platform ovirt
? Enter oVirt's api endpoint URL https://rhv.DOMAIN.COMovirt-engine/api
? Is the installed oVirt certificate trusted? No
? Enter ovirt-engine username admin@internal
? Enter password ************
? Select the oVirt cluster IvyBridge
? Select the oVirt storage domain vm
? Select the oVirt network ovirtmgmt
? Enter the internal API Virtual IP 10.7.0.111
? Enter the internal DNS Virtual IP 10.7.0.113
? Enter the ingress IP  10.7.0.112
? Base Domain lab.DOMAIN.COM
? Cluster Name okd
? The container registry pull secret for this cluster, as a single line of JSON (e.g. {"auths": {...}}).

You can get this secret from https://cloud.redhat.com/openshift/install/pull-secret
? Pull Secret ************************************************************************************************************************************************************************************************************************************************************************INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200323.3.2/x86_64/fedora-coreos-31.20200323.3.2-openstack.x86_64.qcow2.xz?sha256=ba557b0d1f72d90cb7e3dbce0e244c90b218e910fe2c979760957e30482dc285' *********************FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get ovirt Terraform variables: no locks available

EDIT:
Ran it with --log-level=debug, here is the output:
https://pastebin.com/a6SaW45R

**Comment by vrutkovs** [comment]
@rgolangh any recommended debug steps for this?

**Comment by viniciusferrao** [comment]
This isn't happening anymore on beta6.
