### ISSUE TITLE
[ovirt] OKD 4.4 install on RHV 4.3 Not Progressing Beyond API v1.17.1 up

### ISSUE THREAD

**Issue by jasonbrooks** [openshift/okd#168]
**Describe the bug**

I'm trying to install an OKD 4.4 cluster on RHV using the directions at https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html -- I keep getting stuck, I'm not certain how. I get past API v1.17.1 up, and I'm stuck at Waiting up to 40m0s for bootstrapping to complete.

**Version**

4.4.0-0.okd-2020-04-21-163702-beta4

IPI ovirt (rhv 4.3)

**How reproducible**

I've tried multiple reinstalls

**Log bundle**

[bootstrap.zip](https://github.com/openshift/okd/files/4583179/bootstrap.zip)
[master0.zip](https://github.com/openshift/okd/files/4583180/master0.zip)
[master1.zip](https://github.com/openshift/okd/files/4583181/master1.zip)
[master2.zip](https://github.com/openshift/okd/files/4583182/master2.zip)
[bundle.zip](https://github.com/openshift/okd/files/4583184/bundle.zip)

**Comment by vrutkovs** [comment]
```
reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://api-int.okd.osas.lab.eng.rdu2.redhat.com:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup api-int.okd.osas.lab.eng.rdu2.redhat.com on 10.11.5.19:53: no such host
```
in kubelet's log. Seems the machine gets a wrong DNS address

**Comment by jasonbrooks** [comment]
Yes, my lab dhcp hands out three nameservers, and I believe I've had an issue w/ this before. When I add the int dns to the top of the list, the fourth nameserver is pushed off the stack. Maybe a similar sort of thing was happening w/ my int dns nameserver. I've manually updated my resolv.conf, the bootstrapping is proceeding. I'll update here if it completes.

**Comment by vrutkovs** [comment]
The way to solve this would be adding a new MachineConfig, which instructs NetworkManager to use correct DNS servers. See https://github.com/openshift/installer/blob/master/docs/user/customization.md#control-plane-with-no-taints as an example

**Comment by viniciusferrao** [comment]
Allow me to hijack this, I've a similar issue, but how can I get this logs? My SSH keys aren't accepted for the VMs and I don't know the root/password combination to login on the console.

**Comment by vrutkovs** [comment]
>My SSH keys aren't accepted for the VMs

Different bug, that means Ignition hasn't been applied to the machines

**Comment by jasonbrooks** [comment]
I managed to get my cluster up. One of the bigger issues is the lack of documentation about setting a dns record for api-int: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html#installing-rhv-preparing-the-network-environment_installing-rhv-default

I couldn't tell where to file a bug for the docs -- point me in the right direction and I will file one.

I hit a couple of other things that I'll file issues for. I'm planning on reinstalling my test cluster once the next OKD 4.4 release comes out.

I'm going to close this issue.

**Comment by vrutkovs** [comment]
>I couldn't tell where to file a bug for the docs -- point me in the right direction and I will file one.

https://github.com/openshift/openshift-docs

**Comment by jasonbrooks** [comment]
hidden in plain sight :)
