### ISSUE TITLE
Events->Streaming Events shows: Jan 1, 1970 1:00 am

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#17]
Hi,

I got some Events that show epoch 0 times (Jan 1, 1970 1:00 am).

version: 4.3.0-0.okd-2019-11-26-150235

My OKD 4 runs on Proxmox and on vSphere.

Greetings,

Josef

**Comment by barjahanshaik** [comment]
@jomeier Awesome that you got it on Proxmox. Even I am looking for the same. The current okd read me says AWS supported. Any specific using 4.3.0-0.okd-2019-11-26-150235
for bare metal?

**Comment by jomeier** [comment]
@barjahanshaik 
It‘s important to understand that you can install OpenShift 4/OKD 4 everywhere if you create the ignition files with the installer and start the VMs manually with them.

The platform type in the install-config.yaml must be „none“ in this case.

**Comment by vrutkovs** [comment]
"some events" meaning not all? Is there a pattern? Do you have an example of correct date events and the wrong ones?

**Comment by jomeier** [comment]
@vrutkovs:
Some of the Jan 1, 1970 events show 404 errors if I click on them, some others show details page.

https://imgur.com/a/CJNt8l9

I can't find a pattern. But it seems as if new events are affected.

**Comment by jomeier** [comment]
@vrutkovs:
In my Proxmox insallation with: 4.3.0-0.okd-2019-11-26-150235  I dont see this effect anymore.

On my vSphere Installation with 4.3.0-0.okd-2019-10-15-xxxxx I see it. 

I don't understand, why my cluster with the older version (2019-10-15) doesn't update automatically at least to 2019-11-26 but maybe someone has removed that version from the update channel.

I will continue to observe if the newer version shows this wrong dates again.

**Comment by vrutkovs** [comment]
There is no automatic upgrade (yet), so you have to click "Update cluster" yourself.

Please close this if its no longer reproducible in the latest version

**Comment by jomeier** [comment]
In the last hours I saw this wrong timestamps again in version 4.3.0-0.okd-2019-11-26-150235.

I'm asking myself what you mean with "click Update cluster". Is this already possible with OKD 4? Were can I click for the update?

I was wondering for days why one of my clusters updated itself automatically to version 2019-11-26 and the other cluster stays at 2019-10-15. Even if I call this:

```
curl --silent --header 'Accept: application/json' 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.3&arch=amd64'
```

or instead of stable-4.3 -> fast-4.3 I get back an empty graph JSON.

Where did my preview-1 cluster get its update to 2019-11-26 from :-) ?

**Comment by devstashuser** [comment]
@jomeier Can you please help me know how you created the rhcos vm in proxmox? Is it through cloud-init? I am trying to use it through cloud-init but no luck. Is this the process you approached to spin rhcos vms manually? Thanks in advance

**Comment by jomeier** [comment]
> @jomeier Can you please help me know how you created the rhcos vm in proxmox? Is it through cloud-init? I am trying to use it through cloud-init but no luck. Is this the process you approached to spin rhcos vms manually? Thanks in advance

https://github.com/openshift/okd/issues/27

**Comment by devstashuser** [comment]
@jomeier You are awesome. I will try it Thanks a lot.

**Comment by vrutkovs** [comment]
Is this reproducible if a 4.4 release from origin-release.svc.ci.openshift.org is used?

**Comment by jomeier** [comment]
@vrutkovs:
I installed OKD 4.4  from 4.4.0-0.okd-2020-01-21-152938 on vSphere. Beside the fact that the installation ran absolutely smoothely, this problem seems to be gone.

I'll investigate it further and close this ticket if it doesn't come back.

**Comment by vrutkovs** [comment]
Perfect. Lets close it and open a new ticket if that still occurs.

I think for console its safe to open them at https://github.com/openshift/console (don't forget to specify the payload)

**Comment by jomeier** [comment]
Seems to be fixed.
