### ISSUE TITLE
[oVirt] Installation fails while waiting bootstrap to complete

### ISSUE THREAD

**Issue by viniciusferrao** [openshift/okd#171]
**Describe the bug**

When deploy a new cluster installation fails during the bootstrapping completion phase. And after them the logs gathering fails too:

INFO Waiting up to 40m0s for bootstrapping to complete... 
E0507 18:14:20.957458    4798 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get https://api.okd.cc.iq.ufrj.br:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=3883&timeoutSeconds=355&watch=true: dial tcp 10.7.0.111:6443: connect: connection refused
E0507 18:14:21.960494    4798 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get https://api.okd.cc.iq.ufrj.br:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=3883&timeoutSeconds=505&watch=true: dial tcp 10.7.0.111:6443: connect: connection refused

**Version**

okd:4.4.0-0.okd-2020-04-21-163702-beta4
Target RHV pool:
OS Version: RHEL - 7.8 - 2.el7ev
OS Description: Red Hat Virtualization Host 4.3.9 (el7.8)
Client running `openshift-install` is Fedora 32.

**How reproducible**

100%

**Log bundle**

DEBUG OpenShift Installer 4.4.0-0.okd-2020-04-21-163702-beta4 
DEBUG Built from commit 05427285086348912f5183c0ac39094c75e0c1db 
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd.cc.iq.ufrj.br:6443... 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: i/o timeout 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: no route to host 
DEBUG Still waiting for the Kubernetes API: Get https://api.okd.cc.iq.ufrj.br:6443/version?timeout=32s: dial tcp 10.7.0.111:6443: connect: connection refused 
INFO API v1.17.1 up                               
INFO Waiting up to 40m0s for bootstrapping to complete... 
E0507 18:14:20.957458    4798 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get https://api.okd.cc.iq.ufrj.br:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=3883&timeoutSeconds=355&watch=true: dial tcp 10.7.0.111:6443: connect: connection refused
E0507 18:14:21.960494    4798 reflector.go:307] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: Get https://api.okd.cc.iq.ufrj.br:6443/api/v1/namespaces/kube-system/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dbootstrap&resourceVersion=3883&timeoutSeconds=505&watch=true: dial tcp 10.7.0.111:6443: connect: connection refused
DEBUG Fetching Install Config...                   
DEBUG Loading Install Config...                    
DEBUG   Loading SSH Key...                         
DEBUG   Using SSH Key loaded from state file       
DEBUG   Loading Base Domain...                     
DEBUG     Loading Platform...                      
DEBUG     Using Platform loaded from state file    
DEBUG   Using Base Domain loaded from state file   
DEBUG   Loading Cluster Name...                    
DEBUG     Loading Base Domain...                   
DEBUG     Loading Platform...                      
DEBUG   Using Cluster Name loaded from state file  
DEBUG   Loading Pull Secret...                     
DEBUG   Using Pull Secret loaded from state file   
DEBUG   Loading Platform...                        
DEBUG Using Install Config loaded from state file  
DEBUG Reusing previously-fetched Install Config    
INFO Pulling debug logs from the bootstrap machine 
DEBUG Added /home/ferrao/.ssh/id_ed25519 to installer's internal agent 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the private key is added to your authentication agent (ssh-agent) or specified with the --key parameter: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
FATAL Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition

**Comment by vrutkovs** [comment]
>ERROR Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the private key is added to your authentication agent (ssh-agent) or specified with the --key parameter: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Did the master machines boot? Did Ignition got applied and you see a login prompt in the console?

**Comment by viniciusferrao** [comment]
Hi @vrutkovs I got 5 machines in total, 3 masters, 1 bootstrap and one powered off tmpvm. They are booted and I can see the login prompt, but I don't know the user and password. There's a lot of SELinux messages on the screen.

I'm not sure about Ignition, because I don't know how to check for this. :(

![image](https://user-images.githubusercontent.com/2031761/81421602-137e8700-9128-11ea-8772-f4265390c58f.png)

**Comment by vrutkovs** [comment]
>They are booted and I can see the login prompt, but I don't know the user and password

Username is `core` and password is not set. You should be able to ssh on this machine. Public part of the ssh key has been specified in `install-config.yaml`.

Does ssh'in using `core` work on all machines?

**Comment by viniciusferrao** [comment]
@vrutkovs I was able to login successfully with my SSH key in all machines:

master0:
```
[ferrao@blackthorn ~]$ ssh 10.7.0.248 -l core
Enter passphrase for key '/home/ferrao@DOMAIN.COM/.ssh/id_ed25519': 
Fedora CoreOS 31.20200420.20.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

[core@okd-pgs79-master-0 ~]$ 
```

master1:
```
[ferrao@blackthorn ~]$ ssh 10.7.0.246 -l core
Enter passphrase for key '/home/ferrao@DOMAIN.COM/.ssh/id_ed25519': 
Fedora CoreOS 31.20200420.20.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

[core@okd-pgs79-master-1 ~]$
```

master2:
```
[ferrao@blackthorn ~]$ ssh 10.7.0.250 -l core
Enter passphrase for key '/home/ferrao@DOMAIN.COM/.ssh/id_ed25519': 
Fedora CoreOS 31.20200420.20.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

[core@okd-pgs79-master-2 ~]$
```

bootstrap:
```
[ferrao@blackthorn ~]$ ssh 10.7.0.243 -l core
Enter passphrase for key '/home/ferrao@DOMAIN.COM/.ssh/id_ed25519': 
This is the bootstrap node; it will be destroyed when the master is fully up.

The primary services are release-image.service followed by bootkube.service. To watch their status, run e.g.

  journalctl -b -f -u release-image.service -u bootkube.service
Fedora CoreOS 31.20200420.20.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/
```

I've noted that all the services fetches IP addresses from the DHCP service. I wasn't aware that we need DHCP running on the network. Should the DHCP have dynamic DNS entries? Just wondering.

Anyway, what should I try now?

**Comment by vrutkovs** [comment]
You'd need to run `/usr/local/bin/installer-gather.sh <random id> <space-separated list of master IPs>`, fetch the bundle from `/home/core`, upload to gdrive / any other public space or simply attach here

**Comment by viniciusferrao** [comment]
Hi @vrutkovs, there you go.I think I understood wrong what is the random ID or something is really messed up:

```
[core@localhost ~]$ /usr/local/bin/installer-gather.sh pgs79 10.7.0.248 10.7.0.246 10.7.0.250
Gathering bootstrap systemd summary ...
Gathering bootstrap failed systemd unit status ...
Gathering bootstrap journals ...
Gathering bootstrap containers ...
Gathering rendered assets...
Gathering cluster resources ...
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Waiting for logs ...
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Unable to connect to the server: dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host
Gather remote logs
Collecting info from pgs79
lost connection
ssh: Could not resolve hostname pgs79: Name or service not known
Collecting info from 10.7.0.248
Warning: Permanently added '10.7.0.248' (ECDSA) to the list of known hosts.
Gathering master systemd summary ...
Gathering master failed systemd unit status ...
Gathering master journals ...
Gathering master containers ...
Waiting for logs ...
Collecting info from 10.7.0.246
Warning: Permanently added '10.7.0.246' (ECDSA) to the list of known hosts.
Gathering master systemd summary ...
Gathering master failed systemd unit status ...
Gathering master journals ...
Gathering master containers ...
Waiting for logs ...
Collecting info from 10.7.0.250
Warning: Permanently added '10.7.0.250' (ECDSA) to the list of known hosts.
Gathering master systemd summary ...
Gathering master failed systemd unit status ...
Gathering master journals ...
Gathering master containers ...
Waiting for logs ...
Log bundle written to /var/home/core/log-bundle-.tar.gz
```

Anyway, the logs are here: https://www.if.ufrj.br/~ferrao/okd/log-bundle-.tar.gz

Thanks.

**Comment by vrutkovs** [comment]
>dial tcp: lookup api-int.okd.cc.iq.ufrj.br on 146.164.29.3:53: no such host

I think the docs are wrong - `api-int` needs to be declared, see https://github.com/openshift/okd/issues/172.

There's also some issue with certificates, bootkube log:
>[#2506] failed to fetch discovery: Get https://localhost:6443/api?timeout=32s: x509: certificate has expired or is not yet valid

Make sure you generate a new cluster config every time an installation is attempted

**Comment by viniciusferrao** [comment]
Hello, I've added the additional DNS entries:
```
api.okd                 IN      A       10.7.0.111
api-int.okd             IN      A       10.7.0.111
ns.okd                  IN      A       10.7.0.112
*.apps.okd              IN      A       10.7.0.113
```

It's deploying, but already hit another issue, although it does not cancel the installation:

```INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200323.3.2/x86_64/fedora-coreos-31.20200323.3.2-openstack.x86_64.qcow2.xz?sha256=ba557b0d1f72d90cb7e3dbce0e244c90b218e910fe2c979760957e30482dc285' 
INFO The file was found in cache: /home/ferrao/.cache/openshift-installer/image_cache/f36041c9aff5c3fc1164dd67425526a1. Reusing... 
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd.cc.iq.ufrj.br:6443... 
INFO API v1.17.1 up                               
INFO Waiting up to 40m0s for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
ERROR                                              
ERROR Warning: Resource targeting is in effect     
ERROR                                              
ERROR You are creating a plan with the -target option, which means that the result 
ERROR of this plan may not represent all of the changes requested by the current 
ERROR configuration.                               
ERROR                                                      
ERROR The -target option is not for routine use, and is provided only for 
ERROR exceptional situations such as recovering from errors or mistakes, or when 
ERROR Terraform specifically suggests to use it as part of an error message. 
ERROR                                              
ERROR                                              
ERROR Warning: Applied changes may be incomplete   
ERROR                                              
ERROR The plan was created with the -target option in effect, so some changes 
ERROR requested in the configuration may have been ignored and the output values may 
ERROR not be fully updated. Run the following command to verify that no other 
ERROR changes are pending:                         
ERROR     terraform plan                           
ERROR                                               
ERROR Note that the -target option is not suitable for routine use, and is provided 
ERROR only for exceptional situations such as recovering from errors or mistakes, or 
ERROR when Terraform specifically suggests to use it as part of an error message. 
ERROR                                              
INFO Waiting up to 30m0s for the cluster at https://api.okd.cc.iq.ufrj.br:6443 to initialize... 
```

I will edit this reply when the process is complete (or aborted).

**Comment by vrutkovs** [comment]
>How many leases do I need?

I think its 3 masters + 1 bootstrap + 3 VIP addresses + n workers, so 7 minimum.

>Increasing the DHCP pool does not solves the issue

Looks like the workers didn't join - what's the output `oc get nodes` and `oc machines -A` list worker nodes?

**Comment by viniciusferrao** [comment]
Hello @vrutkovs tried to run the command on the deploy machine and on master0. The results are equal:

```[core@okd-jqgzm-master-0 ~]$ oc get nodes
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
[core@okd-jqgzm-master-0 ~]$ oc machines -A
Error: unknown command "machines" for "oc"
Run 'oc --help' for usage1```

I came across this: https://bugzilla.redhat.com/show_bug.cgi?id=1811221

But I don't know if it's the same issue or not. Appears to be, but I'm not sure.

**Comment by UnlawfulMonad** [comment]
I'm running into a very similar issue. I'm able to contact the masters and get a list of pods using the `auth/kubeconfig` that the installer creates however some pods end up stalled with this error:
```
Warning  FailedCreatePodSandBox  2m53s (x24 over 14m)  kubelet, okd-tfx2x-master-1  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_installer-3-okd-tfx2x-master-1_openshift-etcd_94e47600-d199-4d6a-8b3d-f0756ed0b771_0(64a9def53cebf83c5d690267a22771d691a5e142df8c1bc3a3e53259046586b3): Multus: [openshift-etcd/installer-3-okd-tfx2x-master-1]: error adding container to network "ovn-kubernetes": delegateAdd: error invoking DelegateAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[openshift-etcd/installer-3-okd-tfx2x-master-1] failed to configure pod interface: timed out dumping br-int flow entries for sandbox: timed out waiting for the condition
```

The pods in question are these in the `openshift-etcd` namespace (but there are some in a bunch of places.
```
openshift-etcd                                          etcd-okd-tfx2x-master-0                                           3/3     Running             0          21m                          
openshift-etcd                                          installer-2-okd-tfx2x-master-0                                    0/1     Completed           0          21m                          
openshift-etcd                                          installer-3-okd-tfx2x-master-1                                    0/1     ContainerCreating   0          20m                          
openshift-etcd                                          revision-pruner-2-okd-tfx2x-master-0                              0/1     ContainerCreating   0          20m
```

@viniciusferrao Are you able to connect to using that kubeconfig file (`export KUBECONFIG=INSTALL_DIR/auth/kubeconfig`) and do you see pods stuck in `ContainerCreating`?

**Comment by viniciusferrao** [comment]
@UnlawfulMonad can you help me? I'm extremely noob with Kubernetes. Which command I should run with `kubectl`?

I'm just trying to move from VMs to Containers, missed the train a long time ago.

**Comment by viniciusferrao** [comment]
@vrutkovs I tried installing Red Hat's OpenShift release and it worked without any issue. There's any log that I can collect to help identify what is broken within OKD to be fixed?

**Comment by vrutkovs** [comment]
>There's any log that I can collect to help identify what is broken within OKD to be fixed?

Yes, [must-gather archive](https://docs.okd.io/latest/support/gathering-cluster-data.html)

**Comment by viniciusferrao** [comment]
@vrutkovs although this ticket was closed I never had an opportunity to check what happened. Anyway, with the new beta6 release I was unable to replicate this issue. So beta6 "solved" the issue.

**Comment by douglasawh** [comment]
I seem to be running into this issue on the latest version, but none of the workers get created so maybe it is a little different. I don't have any insight into what addresses DHCP is adding to the machines, so I don't have a way to ssh to them. I can open the machines in console, but I have no way to login. Using 'core' with no password does not work from the command line. 

We did add these to DNS, but those IP addresses don't get used, or the network doesn't get started or something. 
api.okd                 IN      A       192.168.40.228
*.apps.okd              IN      A       192.168.40.299

The bootstrap server is sitting at 63% CPU. It is trying to do something, I just don't know what.

We use a .local in our FQDN. I know this is something you can't do with Rancher. Is that also an issue with okd?
