### ISSUE TITLE
openshift-install destroy cluster with broken output

### ISSUE THREAD

**Issue by viniciusferrao** [openshift/okd#173]
**Describe the bug**

`openshift-install destroy cluster` will return bad messages with clearly broken output.

[ferrao@localhost okd]$ openshift-install destroy cluster
INFO searching VMs by tag=okd-pgs79               
INFO Found %!s(int=3) VMs                         
INFO Stopping VM okd-pgs79-master-2 : errors: %s%!(EXTRA <nil>) 
INFO Stopping VM okd-pgs79-master-1 : errors: %s%!(EXTRA <nil>) 
INFO Stopping VM okd-pgs79-master-0 : errors: %s%!(EXTRA <nil>) 
INFO Removing VM okd-pgs79-master-2 : errors: %s%!(EXTRA <nil>) 
INFO Removing VM okd-pgs79-master-1 : errors: %s%!(EXTRA <nil>) 
INFO Removing VM okd-pgs79-master-0 : errors: %s%!(EXTRA <nil>) 
ERROR Removing VMs - error: %!s(<nil>)             
INFO Removing tag okd-pgs79 : errors: %s%!(EXTRA <nil>) 
ERROR Removing Tag - error: %!s(<nil>)             
ERROR Removing Template - error: %!s(<nil>)   

**Version**

openshift-install-linux-4.4.0-0.okd-2020-04-21-163702-beta4.tar.gz

**How reproducible**

100%

**Log bundle**

No log bundle.

**Comment by vrutkovs** [comment]
Is it still happening on Beta5?

**Comment by viniciusferrao** [comment]
Hi @vrothberg I tried beta5 yesterday and yes, still happening.

```
[ferrao@fedora-test okd]$ openshift-install destroy cluster
INFO searching VMs by tag=okd-dzb6t               
INFO Found %!s(int=3) VMs                         
INFO Stopping VM okd-dzb6t-master-1 : errors: %s%!(EXTRA <nil>) 
INFO Stopping VM okd-dzb6t-master-0 : errors: %s%!(EXTRA <nil>) 
INFO Stopping VM okd-dzb6t-master-2 : errors: %s%!(EXTRA <nil>) 
INFO Removing VM okd-dzb6t-master-1 : errors: %s%!(EXTRA <nil>) 
INFO Removing VM okd-dzb6t-master-0 : errors: %s%!(EXTRA <nil>) 
INFO Removing VM okd-dzb6t-master-2 : errors: %s%!(EXTRA <nil>) 
ERROR Removing VMs - error: %!s(<nil>)             
INFO Removing tag okd-dzb6t : errors: %s%!(EXTRA <nil>) 
ERROR Removing Tag - error: %!s(<nil>)             
ERROR Removing Template - error: %!s(<nil>)   
```

**Comment by vrutkovs** [comment]
Oh, interesting. We'll fix that in Beta6

@rgolangh do you know if that is fixed in installer master already?

**Comment by rgolangh** [comment]
fixed both on master and 4.4

**Comment by vrutkovs** [comment]
Excellent, thanks. That would be a part of installer rebase during Beta 6 then

**Comment by vrutkovs** [comment]
Latest [4.5 nightlies](https://origin-release.svc.ci.openshift.org/#4.5.0-0.okd) are based on release-4.5 installer and should have a fix for that. Could you give it a try?

**Comment by vrutkovs** [comment]
This should be resolved in Beta 6, please reopen if it still occurs on latest beta/nightly

**Comment by viniciusferrao** [comment]
@vrutkovs I can confirm it's working now:

> [ferrao@fedora-test okd]$ openshift-install destroy cluster
> INFO Stopping VM okd-phhh9-master-2               
> INFO Stopping VM okd-phhh9-master-1               
> INFO Stopping VM okd-phhh9-master-0               
> INFO VM okd-phhh9-master-2 powered off            
> INFO VM okd-phhh9-master-1 powered off            
> INFO Removing VM okd-phhh9-master-1               
> INFO Removing VM okd-phhh9-master-2               
> INFO VM okd-phhh9-master-0 powered off            
> INFO Removing VM okd-phhh9-master-0               
> INFO Removing tag okd-phhh9                       
> INFO Time elapsed: 17s
