### ISSUE TITLE
[vSphere, UPI] I can read the ignition files from outside of the cluster without providing credentials

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#176]
Hi,

in my UPI vSphere setup I am able to get the ignition files for masters and workers with:

```
curl -k https://chmuokd4master0.rsint.net:22623/config/master
curl -k https://chmuokd4master0.rsint.net:22623/config/worker
```

from my local PC which is NOT part of the cluster. In my opinion this shouldn't work without providing credentials.

Version: Beta4

The solution for that seems to be to install a firewall around the cluster. But this seems to be kind of a workaround.

I rshed into several pods on my cluster and tried this curl to check, if any user that can enter the terminal of a pod can curl the ignition files and maybe can read cloud provider secrets provided there. In this case I got a 'connection refused' message. A user seems not to be able to get the ignition file. But I feel uncomfortable if this works in all situations.

The ignition files shouldn't be available without protection of the REST API of the machine config daemon at all in my opinion.

Greetings,

Josef

**Comment by vrutkovs** [comment]
Related: https://github.com/openshift/machine-config-operator/pull/784

**Comment by vrutkovs** [comment]
This resulted in https://github.com/openshift/enhancements/pull/443
