### ISSUE TITLE
Cancelled Beta Versions are still available for updates

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#177]
Hi,

today we mirrored the OKD 4.4 images locally. I expected to get the Beta4 images from end of April because on https://origin-release.svc.ci.openshift.org/ Beta4 is listed as the latest stable version but we got images from 2020-05-13 (Beta5 ?).

Beta5 was cancelled yesterday. This images shouldn't be marked as latest images for OKD 4.4.

Something seems to got mixed up in the download servers.

Greetings,

Josef

**Comment by vrutkovs** [comment]
I'm not seeing that: 
```
$ oc adm upgrade
Cluster version is 4.4.0-0.okd-2020-04-21-163702-beta4

No updates available. You may force an upgrade to a specific release image, but doing so may not be supported and result in downtime or data loss.
```

> we got images from 2020-05-13 (Beta5 ?)

I had to remove beta5 (OVNKubernetes regression broke beta4 -> beta5 updates), so please remove the release image on your mirror?

**Comment by jomeier** [comment]
My colleague did this a few hours ago today:

```
oc adm release mirror --from "registry.svc.ci.openshift.org/origin/release:4.4" --to docker.rsint.net/rs_ruscloud-dit/okd4 --to-release-image docker.rsint.net/rs_ruscloud-dit/okd-release:4.4
```

And in our internal registry we see this:

https://imgur.com/a/aWEYpw2

So for some reason the oc adm mirror command got Beta5 images from somewhere.

**Comment by jomeier** [comment]
This happened to me also for the first time you tried to release a Beta5 a week ago: I installed OKD 4 on Azure and Azure showed me not Beta4 but some image with a May date in its name.

**Comment by vrutkovs** [comment]
These look like usual nightlies to me. I removed release image for beta5, so you can't install it and certainly can't update to beta5.

Once OVNKubernetes is fixed in openshift's fork and update tests would pass we'll release a new beta5 (based on whatever nightly is available)

**Comment by jomeier** [comment]
I saw this effect here:
https://kubernetes.slack.com/archives/C6BRQSH2S/p1588790830093300

But don't you think that these nightlies should not get fetched with the command we used above? We adressed release:4.4 and no nightly at all. You deleted Beta5 yesterday and we mirrored latest 4.4 today. So I would assume that Beta4 is the latest 4.4 "release" build we should get and not a nightly. This shouldn't happen. 

Do you agree or did me use the mirror command in a wrong way?

**Comment by jomeier** [comment]
It seems to me that release:4.4 still points to the nightly you tried to release as Beta5 and not anymore to the Beta4 release as it should.

**Comment by vrutkovs** [comment]
Correct, `release:4.4` is the latest nightly (as expected). There is no imagestream for latest beta (we could create one eventually)

**Comment by jomeier** [comment]
Hm ... If we want to have the latest beta version: what is the right way to get this without addressing a Beta version individually ?

**Comment by jomeier** [comment]
So you mean that this is expected behaviour and won't be changed? I would close this issue in that case.

**Comment by vrutkovs** [comment]
Right, `release:4.4` -> latest nightly. I think we need a new issue for an imagestream of latest beta (that would require some infra work)

**Comment by jomeier** [comment]
If it does not delay the GA of OKD 4 ;-)

Maybe it helps to document the command to mirror a Beta:

```
./oc adm release mirror --from "quay.io/openshift/okd:4.4.0-0.okd-2020-04-21-163702-beta4" --to docker.rsint.net/rs_ruscloud-dit/okd4 --to-release-image docker.rsint.net/rs_ruscloud-dit/okd-release:4.4
```
