### ISSUE TITLE
Enhancement: Add imagestreams for beta releases or nightlies

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#178]
Hi,

currently release:4.4 does not point to beta versions but to nightly builds.

In my opinion 'release' is closer to a 'beta' version than to a 'nightly' build.

It would make sense to have an additional image stream for beta versions (or vice versa for nightlies) so we can write: 

beta:latest  or
nightly:latest or
release:latest points to the latest beta

But this should not delay the GA of OKD 4.

Greetings,

Josef

**Comment by vrutkovs** [comment]
Each nightly has its own imagestream. Latest nightly will be installed when `release:4.4` is used.

We should add a new imagestream to track betas (and eventually released) versions. I'm thinking `release:beta` and `release:ga` would be good candidates for that.

@smarterclayton any opinion on that?

**Comment by vrutkovs** [comment]
No longer relevant after OKD GA:
* nightlies are provided via `release:4.5`, `release:4.6` imagestream
* nightlies are tagged into stable using Cincinnati protocol
