### ISSUE TITLE
openshift-install doesn't support AWS GovCloud

### ISSUE THREAD

**Issue by flickerfly** [openshift/okd#179]
**Describe the bug**

openshift-install doesn't support AWS GovCloud

**Version**

openshift-install-linux-4.4.0-0.okd-2020-04-21-163702-beta4.tar.gz AWS 

**How reproducible**

 openshift-install create install-config
Choose AWS 
try to choose us-gov-east-1 region (it isn't there)

**Comment by vrutkovs** [comment]
I don't think there is FCOS uploaded to gov cloud, so IPI probably won't work.

Could you check that https://docs.okd.io/latest/installing/installing_aws/installing-aws-user-infra.html method (UPI) works?

**Comment by flickerfly** [comment]
Yeah, have to export / import that too
________________________________

**Comment by flickerfly** [comment]
We've managed to get this basically working in GovCloud with the UPI method and some tweaks like mentioned.

**Comment by vrutkovs** [comment]
Nice! I don't think FCOS can be officially uploaded to AWS Marketplace for govcloud, thus IPI method is not possible.
