### ISSUE TITLE
Will there be any migration path for 3.x users?

### ISSUE THREAD

**Issue by shinebayar-g** [openshift/okd#18]
Will there be any migration path for 3.x users?

**Comment by gratchie** [comment]
Not sure if this will be changing at some point, but the current recommendation is to do a lift-and-shift and then use tools like Velero and Restic to migrated namespaces/projects.

**Comment by vrutkovs** [comment]
See https://docs.openshift.com/container-platform/4.2/migration/migrating-3-4/about-migration.html
