### ISSUE TITLE
Upload public key used to sign releases / updates to verified location

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#181]
Currently OKD release payloads are signed with Red Hat key and releases uploaded to Github are using mine / Clayton's key.

The public parts for these should be uploaded to some verified locations:

* [x] okd.io
* [ ] origin-release.svc.ci.openshift.org

**Comment by flickerfly** [comment]
Just in case a workflow is of interest, I'm running this procedure in a container build. I manually pull the keys and commit to git so they are available to the pipeline to build this. I'm exploring encapsulating a UPI install. 

```
COPY vadim.pub .
COPY hashicorp.pub .
RUN gpg --import hashicorp.pub \
  && gpg --import vadim.pub \
  && gpg --list-keys --fingerprint |grep pub -A 1|egrep -Ev "pub|--"|tr -d ' '  | awk 'BEGIN { FS = "\n" } ; { print $1":6:" } ' | gpg --import-ownertrust

RUN echo "Verifying OKD checksum" && gpg --verify sha256sum.txt.asc sha256sum.txt
RUN echo "Verifying Hashicorp checksum" && gpg --verify terraform_${terraform_version}_SHA256SUMS.sig terraform_${terraform_version}_SHA256SUMS
```

**Comment by vrutkovs** [comment]
Updated README and uploaded the signing key to https://okd.io/keys.html
