### ISSUE TITLE
[bare metal] OKD 4.4 console fails to start with connection refused

### ISSUE THREAD

**Issue by fenggolang** [openshift/okd#183]
![image](https://user-images.githubusercontent.com/16982786/82333786-bf25b200-9a19-11ea-92ef-2132bc57926a.png)

![image](https://user-images.githubusercontent.com/16982786/82333823-ca78dd80-9a19-11ea-98c7-7e2cb09e0d1e.png)

![image](https://user-images.githubusercontent.com/16982786/82333874-dbc1ea00-9a19-11ea-967d-cd0c98e27f3f.png)
![image](https://user-images.githubusercontent.com/16982786/82333936-e9776f80-9a19-11ea-91f9-379946cd3e1e.png)

console specific logs：
[root@cloud-com-1 rhcos-4.4]#  oc describe pod console-687456646-5648h -n openshift-console
Name:                 console-687456646-5648h
Namespace:            openshift-console
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 master1/192.168.122.202
Start Time:           Tue, 19 May 2020 12:34:35 +0000
Labels:               app=console
                      component=ui
                      pod-template-hash=687456646
Annotations:          console.openshift.io/console-config-version: 132198
                      console.openshift.io/default-ingress-cert-config-version: 131913
                      console.openshift.io/image:
                        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:52465443a0c0f8e1d9dd8f2e3c7ec0e5d32dc438f181adf467ab883a6b283c26
                      console.openshift.io/oauth-secret-version: 164352
                      console.openshift.io/proxy-config-version: 733
                      console.openshift.io/service-ca-config-version: 132714
                      console.openshift.io/trusted-ca-config-version: 132202
                      k8s.v1.cni.cncf.io/networks-status:
                        [{
                            "name": "openshift-sdn",
                            "interface": "eth0",
                            "ips": [
                                "10.130.0.139"
                            ],
                            "dns": {},
                            "default-route": [
                                "10.130.0.1"
                            ]
                        }]
                      openshift.io/scc: restricted
                      operator.openshift.io/pull-spec:
                        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:52465443a0c0f8e1d9dd8f2e3c7ec0e5d32dc438f181adf467ab883a6b283c26
Status:               Running
IP:                   10.130.0.139
IPs:
  IP:           10.130.0.139
Controlled By:  ReplicaSet/console-687456646
Containers:
  console:
    Container ID:  cri-o://fe3c06ea88b82853f21fb20ef0a4d1334e254dda16412789aeee38801b422243
    Image:         quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:52465443a0c0f8e1d9dd8f2e3c7ec0e5d32dc438f181adf467ab883a6b283c26
    Image ID:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:52465443a0c0f8e1d9dd8f2e3c7ec0e5d32dc438f181adf467ab883a6b283c26
    Port:          443/TCP
    Host Port:     0/TCP
    Command:
      /opt/bridge/bin/bridge
      --public-dir=/opt/bridge/static
      --config=/var/console-config/console-config.yaml
      --service-ca-file=/var/service-ca/service-ca.crt
    State:       Running
      Started:   Tue, 19 May 2020 13:42:07 +0000
    Last State:  Terminated
      Reason:    Error
      Message:   T13:35:27Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd4-cluster.okd4.com/oauth/token failed: Head https://oauth-openshift.apps.okd4-cluster.okd4.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020-05-19T13:35:42Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd4-cluster.okd4.com/oauth/token failed: Head https://oauth-openshift.apps.okd4-cluster.okd4.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020-05-19T13:35:57Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd4-cluster.okd4.com/oauth/token failed: Head https://oauth-openshift.apps.okd4-cluster.okd4.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020-05-19T13:36:12Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd4-cluster.okd4.com/oauth/token failed: Head https://oauth-openshift.apps.okd4-cluster.okd4.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020-05-19T13:36:27Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd4-cluster.okd4.com/oauth/token failed: Head https://oauth-openshift.apps.okd4-cluster.okd4.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020-05-19T13:36:42Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd4-cluster.okd4.com/oauth/token failed: Head https://oauth-openshift.apps.okd4-cluster.okd4.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

      Exit Code:    2
      Started:      Tue, 19 May 2020 13:33:36 +0000
      Finished:     Tue, 19 May 2020 13:36:56 +0000
    Ready:          False
    Restart Count:  14
    Requests:
      cpu:        10m
      memory:     100Mi
    Liveness:     http-get https://:8443/health delay=150s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get https://:8443/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/pki/ca-trust/extracted/pem from trusted-ca-bundle (ro)
      /var/console-config from console-config (ro)
      /var/default-ingress-cert from default-ingress-cert (ro)
      /var/oauth-config from console-oauth-config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from console-token-2dwlb (ro)
      /var/service-ca from service-ca (ro)
      /var/serving-cert from console-serving-cert (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  console-serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  console-serving-cert
    Optional:    false
  console-oauth-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  console-oauth-config
    Optional:    false
  console-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      console-config
    Optional:  false
  service-ca:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      service-ca
    Optional:  false
  default-ingress-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      default-ingress-cert
    Optional:  false
  trusted-ca-bundle:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      trusted-ca-bundle
    Optional:  false
  console-token-2dwlb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  console-token-2dwlb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-reachable:NoExecute for 120s
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 120s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  <unknown>            default-scheduler  Successfully assigned openshift-console/console-687456646-5648h to master1
  Normal   Pulled     71m                  kubelet, master1   Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:52465443a0c0f8e1d9dd8f2e3c7ec0e5d32dc438f181adf467ab883a6b283c26" already present on machine
  Normal   Created    71m                  kubelet, master1   Created container console
  Normal   Started    71m                  kubelet, master1   Started container console
  Warning  Unhealthy  68m (x3 over 68m)    kubelet, master1   Liveness probe failed: Get https://10.130.0.139:8443/health: dial tcp 10.130.0.139:8443: connect: connection refused
  Normal   Killing    68m                  kubelet, master1   Container console failed liveness probe, will be restarted
  Warning  Unhealthy  11m (x267 over 71m)  kubelet, master1   Readiness probe failed: Get https://10.130.0.139:8443/health: dial tcp 10.130.0.139:8443: connect: connection refused
  Warning  BackOff    6m7s (x88 over 44m)  kubelet, master1   Back-off restarting failed container
[root@cloud-com-1 rhcos-4.4]#

**Comment by vrutkovs** [comment]
Please add the link to [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html)

**Comment by fenggolang** [comment]
[root@cloud-com-1 rhcos-4.4]#  oc adm must-gather
[must-gather      ] OUT imagestreams.image.openshift.io "must-gather" not found
[must-gather      ] OUT 
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/origin-must-gather:latest
[must-gather      ] OUT namespace/openshift-must-gather-z7nrt created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-zwknz created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-zwknz deleted
[must-gather      ] OUT namespace/openshift-must-gather-z7nrt deleted
Error from server (Forbidden): pods "must-gather-" is forbidden: error looking up service account openshift-must-gather-z7nrt/default: serviceaccount "default" not found
[root@cloud-com-1 rhcos-4.4]#

**Comment by fenggolang** [comment]
My error is very similar to https://github.com/openshift/okd/issues/159, but mine is bare metal, not aws upi

**Comment by vrutkovs** [comment]
No must-gather provided
