### ISSUE TITLE
[docs] OKD docs should use Ignition v3 examples instead of v2

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#184]
Hi,

here: 

https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere.html

I found a bug. 

The example for 'append_bootstrap.ign' contains 'append' (Ignition v2) instead of 'merge' (Ignition v3).

If we use 'append' Fedora Core OS won't configure itself.

Greetings,

Josef

**Comment by vrutkovs** [comment]
Renamed it to be a bit more generic:

* `append` vs `merge`
* `overwrite`
* `networkd`

**Comment by Bengrunt** [comment]
The same issue exists for the Openstack (UPI) installation documentation: https://docs.okd.io/latest/installing/installing_openstack/installing-openstack-user.html#installation-osp-converting-ignition-resources_installing-openstack-user

This is a bit unsettling when following the installation instructions, especially when not really familiar with ignition.

**Comment by vrutkovs** [comment]
This would be effectively fixed when OCP 4.6 documentation is out, as it uses Ignition 3

**Comment by jomeier** [comment]
The initial problem in the docs is fixed for vSphere.

**Comment by vrutkovs** [comment]
OCP 4.6 switched to Ignition 3, so OKD docs now contain config examples with Ignition 3
