### ISSUE TITLE
[vSphere] Problem with pause image in offline installation from local mirror Docker repository

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#187]
Hi,

today we tried out to create a cluster with a private registry. 

We expected that the installation of OKD 4 Beta 4 can be performed completely offline by pulling images only from our local mirror docker repository.

1. We mirrored the images with 'oc adm mirror ...' to our Artifactory repo (as described in contributing.md).
2. We created installation manifests, started the bootstrap VM. Internet access was deactivated (we are behind a proxy and no proxy vars were set anywhere).
3. The bootstrap VM started pulling images from the private registry. 
3.1 It pulled ~4 images and rebooted automatically.
3.2 Then after pulling approx. 13 images in total there was no more progress.
4. We compared everything with an older Beta 4 cluster that was created with internet access enabled (proxy vars set) and that pulled images from the internet without pull secrets. We saw that the list of images on this older, working cluster looks like this:
```
quay.io/openshift/okd           <none>   0eb9872f5f2f   5 weeks ago    303 MB
quay.io/openshift/okd-content   <none>   39fa98d4ce77   7 weeks ago    921 MB
quay.io/openshift/okd-content   <none>   e675022f0bfd   7 weeks ago    435 MB
quay.io/openshift/okd-content   <none>   4d1b68550c96   7 weeks ago    638 MB
quay.io/openshift/okd-content   <none>   a4cc9bdeb3da   8 weeks ago    304 MB
quay.io/openshift/okd-content   <none>   8a23e572a72b   8 weeks ago    291 MB
quay.io/openshift/okd-content   <none>   7ac1a7467d5e   2 months ago   289 MB
quay.io/openshift/okd-content   <none>   17fbb4685894   2 months ago   312 MB
quay.io/openshift/okd-content   <none>   852d52c83d96   2 months ago   290 MB
quay.io/openshift/okd-content   <none>   efe30bfdf339   2 months ago   288 MB
quay.io/openshift/okd-content   <none>   def0beca4fd4   2 months ago   294 MB
quay.io/openshift/okd-content   <none>   d8a6f3297327   3 months ago   275 MB
quay.io/openshift/okd-content   <none>   8dfb11025aa5   3 months ago   287 MB
quay.io/openshift/okd-content   <none>   c9fd92a1a557   3 months ago   268 MB
quay.io/openshift/okd-content   <none>   e6adc2b9095f   3 months ago   267 MB
k8s.gcr.io/pause                3.1      da86e6ba6ca1   2 years ago    749 kB 
```
5. We saw that the image *k8s.gcr.io/pause* was not mirrored to Artifactory.
6. @cgwalters told me that there was a bug with the pause image in OCP and that it has been fixed.
7. I compared some files that should fix that and I saw that in */etc/crio/crio.conf* this lines indicates that the pause image should be:
```
pause_image = "quay.io/openshift/okd-content@sha256:6e848b9eb42cd4a009b3f02518b3699cbc12d5f84fa2737084c7b73df4f5f5af"
```
But I don't see any image with this sha. Not even in the working cluster that pulled every image from the internet. The list of images in a working bootstrap VM looks like this:

```
[root@chmu2b0 bin]# podman images --no-trunc
REPOSITORY                      TAG      IMAGE ID                                                                  CREATED        SIZE
quay.io/openshift/okd           <none>   sha256:0eb9872f5f2fa138a25aa20f4f530ccb3f4c181178e8b2bfe7ff05cdfb7a1e4c   5 weeks ago    303 MB
quay.io/openshift/okd-content   <none>   sha256:39fa98d4ce7720dc50ff35b8a7eecdd38a208d0f17447ef72eb45ab9b7991eb1   7 weeks ago    921 MB
quay.io/openshift/okd-content   <none>   sha256:e675022f0bfdb864d279fc9e0d1d795340ab228c4b77a70d82adaa81e971f221   7 weeks ago    435 MB
quay.io/openshift/okd-content   <none>   sha256:4d1b68550c962f3a51e73a8108762c61025acd4b950414820ff717b16aee1976   7 weeks ago    638 MB
quay.io/openshift/okd-content   <none>   sha256:a4cc9bdeb3da45c1d1f824432381a2f34db1bf53949c344f2ae3f3fa3b37d989   8 weeks ago    304 MB
quay.io/openshift/okd-content   <none>   sha256:8a23e572a72b73a7b60d010fc470c128e2739805b99a825f632de886edd306aa   8 weeks ago    291 MB
quay.io/openshift/okd-content   <none>   sha256:7ac1a7467d5eabee2ad5b3fc16f2fab41bae687af791a9e58f461f33d7c67f57   2 months ago   289 MB
quay.io/openshift/okd-content   <none>   sha256:17fbb4685894bebb2a4d70fa1ca4c484d18c08c07e63e4a55c58766c359d55ef   2 months ago   312 MB
quay.io/openshift/okd-content   <none>   sha256:852d52c83d96d1d567af2ee2e0ea8c534aa157cd844ad9593f42969038f936c1   2 months ago   290 MB
quay.io/openshift/okd-content   <none>   sha256:efe30bfdf339031cb587932a8ab1380a04a2d7dffdccac34847877c784136503   2 months ago   288 MB
quay.io/openshift/okd-content   <none>   sha256:def0beca4fd42f1a7d9c26211176588dd79b090871ace66687076cbe525445ae   2 months ago   294 MB
quay.io/openshift/okd-content   <none>   sha256:d8a6f32973275841e2e94c79dcb10efbc0c843383a25dff8f06ce7cad07827b5   3 months ago   275 MB
quay.io/openshift/okd-content   <none>   sha256:8dfb11025aa570351592b9c009861b6679e180221a9121b6516ad757fdf00ca2   3 months ago   287 MB
quay.io/openshift/okd-content   <none>   sha256:c9fd92a1a5573792cb53a7f5b414041c5723959033703e0eebf107d99a71d6eb   3 months ago   268 MB
quay.io/openshift/okd-content   <none>   sha256:e6adc2b9095f6e2c0f8b7d6b0b651e54563b342d04f9963eaf21e933729e4d35   3 months ago   267 MB
k8s.gcr.io/pause                3.1      sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e   2 years ago    749 kB
```

Is it possible that the pause image referenced in the *crio.conf* file is missing from the release payload in OKD 4 and that an old pause image is used instead which must be pulled from the internet?

Greetings,

Josef

**Comment by jomeier** [comment]
Only the bootstrap VM shows this pause image. Neither the master VMs nor the worker VMs download it.

I assume that it seems to be a race condition with the crio systemd service maybe starting before the /etc/crio/crio.conf got the pause_image field set. Because if this field is not set, crio seems to try to pull the pause image from the internet, causing a problem in an offline environment.

**Comment by vrutkovs** [comment]
This is odd. During boot we do the following:

1. Start fresh FCOS image (no crio there)
2. Pivot it to machine-os-content. This adds a new deployment with crio and reboots the machine
3. On next boot bootkube.service is started, find out the pivot is done and configures crio

Apparently on step 3 between start and crio-configure cri-o service starts and attempts to pull gcr.io image. However I wonder why -  kubelet is not started at this point so nothing commands crio to start containers. Does it pre-pull `pause_image`?

Josef, could you attach journalctl for initial and pivoted boots?

**Comment by jomeier** [comment]
Here it is.
[journal.log](https://github.com/openshift/okd/files/4669228/journal.log)

**Comment by vrutkovs** [comment]
That's weird, so its your kubelet requesting it:
```
May 22 16:08:40 chmu2b0 hyperkube[975]: I0522 16:08:40.007773     975 flags.go:33] FLAG: --pod-infra-container-image="k8s.gcr.io/pause:3.1"
...
May 22 16:09:02 chmu2b0 crio[924]: time="2020-05-22 16:09:02.193980947Z" level=warning msg="imageStatus: can't find k8s.gcr.io/pause:3.1" id=4380e9ad-e1a5-4b56-bf85-0f8aff8f2564
```
That's Beta4 right? Could you give it a try with a newer stable image?

**Comment by jomeier** [comment]
Yes it's OKD 4 Beta 4.

I will try a newer FCOS image on monday.

**Comment by jomeier** [comment]
Also with FCOS version 20200505.3.0 I have this problem:

```
[root@chmu2b0 bin]# journalctl --no-pager | grep pause
May 25 09:01:31 chmu2b0 systemd[1]: user@1000.service: Killing process 1458 (podman pause) with signal SIGKILL.
May 25 09:01:43 chmu2b0 hyperkube[976]: I0525 09:01:43.554350     976 flags.go:33] FLAG: --pod-infra-container-image="k8s.gcr.io/pause:3.1"
May 25 09:02:05 chmu2b0 crio[921]: time="2020-05-25 09:02:05.892460066Z" level=warning msg="imageStatus: can't find k8s.gcr.io/pause:3.1" id=375da15f-f38c-4fcd-88b5-ce3b6045834b
```

The machine-config-daemon binary also contains a hard coded "k8s.gcr.io" string.

**Comment by jomeier** [comment]
This PR should fix it:

https://github.com/openshift/installer/pull/3652/commits/4e3580533da7541df6b4c4e97dd4ea4b87904feb

**Comment by jomeier** [comment]
PR was merged. I will close this issue.
