### ISSUE TITLE
RouterCertsDegraded after replacing default ingress certificate 

### ISSUE THREAD

**Issue by ignisanulum** [openshift/okd#188]
**Describe the bug**
Replacing the default ingress certificate with one signed by our internal CA according to https://docs.okd.io/latest/authentication/certificates/replacing-default-ingress-certificate.html degrades the authentification cluster operator. All other operatores are fine.
![image](https://user-images.githubusercontent.com/11412870/82707620-bb459a00-9c7c-11ea-8fb8-b616a56a9ca1.png)
As a consequence, the Webconsole displays a generic error and reloads every few seconds.

The following messages were displayed in the webconsole under Cluster Operator Detailes (before refreshing the page) `RouterCertsDegraded: secret/v4-0-config-system-router-certs.spec.data[apps.test-okd.test.el.eee.intern] -n openshift-authentication: not found`
`RouteHealthDegraded: failed to GET route: x509: certificate is valid for oauth-openshift.openshift-authentication.svc, oauth-openshift.openshift-authentication.svc.cluster.local, not oauth-openshift.apps.test-okd.test.el.eee.intern`

**Version**
OKD version release: 4.4.0-0.okd-2020-04-21-163702
UPI on Vmware, provisioned with terrafrom

**How reproducible**
100% reproducible, with no other changes made to the cluster, following these steps https://docs.okd.io/latest/authentication/certificates/replacing-default-ingress-certificate.html 

**Log bundle**
 `oc adm must-gather` archive:  https://drive.google.com/file/d/1AvWZlOfsa_Ac6iuM8WgdnMgDv-lV_gr4/view?usp=sharing

**Comment by vrutkovs** [comment]
`eeeroot-ca` configmap doesn't look good:

```
    ca-bundle.crt: "-----BEGIN CERTIFICATE-----\r\nMIIFXTCCA0WgAwIBAgIQEifNm7wmP41GvrbX29vQrDANBgkqhkiG9w0BAQUFADBB\r\nMRYwFAYKCZImiZPyLGQBGRYGaW50ZXJuMRMwEQYKCZImiZPyLGQBGRYDZWVlMRIw\r\n
```
instead of 
```
 ca-bundle.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDMDCCAhigAwIBAgIIPXuZXlbLKRQwDQYJKoZIhvcNAQELBQAwNjESMBAGA1UE
      CxMJb3BlbnNoaWZ0MSAwHgYDVQQDExdhZG1pbi1rdWJlY29uZmlnLXNpZ25lcjAe
      Fw0yMDA1MjIxNDE3MTlaFw0zMDA1MjAxNDE3MTlaMDYxEjAQBgNVBAsTCW9wZW5z
```
in other CAs. Perhaps its some Windows encoding?

Ingress certificate looks good though

**Comment by ignisanulum** [comment]
Thanks a lot, this was indeed one of the problems!
The other one being a single unnecessary blank space in front of the certificate name in the ingress config. Sorry about the fuss.
