### ISSUE TITLE
Unable to apply 4.4.0-0.okd-2020-05-23-055148-beta5: the image may not be safe to use

### ISSUE THREAD

**Issue by sapkra** [openshift/okd#192]
**Describe the bug**
I've tried to update from beta 4 to beta 5 using the web console but it is failing with the following message:

![image](https://user-images.githubusercontent.com/8087568/82840914-8f245600-9ed4-11ea-9c0d-70cfae7416e2.png)
![image](https://user-images.githubusercontent.com/8087568/82841019-ede9cf80-9ed4-11ea-91b3-d213f508c405.png)

**Version**
4.4.0-0.okd-2020-04-21-163702-beta4

**Comment by vrutkovs** [comment]
Dupe of #138

**Comment by sapkra** [comment]
So the beta's are also not signed? I thought that the issue is just for nightlies.

**Comment by cgruver** [comment]
Correct.  I've updated the issue name to avoid confusion.

**Comment by vrutkovs** [comment]
Betas are promoted nightlies

**Comment by chriskuipers** [comment]
For anyone running into this error from triggering the upgrade from the OKD web interface, I posted a workaround in #138
