### ISSUE TITLE
[Namespace stuck in terminating after Kubevirt operator cleanup] :  Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by kcns008** [openshift/okd#193]
status:
  phase: Terminating
  conditions:
    - type: NamespaceDeletionDiscoveryFailure
      status: 'True'
      lastTransitionTime: '2020-05-25T14:37:15Z'
      reason: DiscoveryFailed
      message: >-
        Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the
        server is currently unable to handle the request

After installing Kubevirt Operator and then cleanup:
All deleted Namespace going to Terminating State and stuck at 
" Discovery failed for some groups, 1 failing: unable to retrieve the
        complete list of server APIs: upload.cdi.kubevirt.io/v1alpha1: the
        server is currently unable to handle the request
"

**Version**
4.4.0-0.okd-2020-04-21-163702-beta4

**How reproducible**
- create OKD 4.4 cluster and install Kubevirt with:
$ curl https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/master/deploy/deploy.sh | bash

Then remove Kubevirt Operator by removing CRD and namespace

**Comment by vrutkovs** [comment]
No must-gather provided
