### ISSUE TITLE
[docs] Rename RHV to include/switch to oVirt

### ISSUE THREAD

**Issue by omenos** [openshift/okd#198]
Documentation for OKD refers to supporting RHV while installer uses oVirt terminology. Might be better to refer to it as oVirt/RHV | RHV/oVirt or other for those who may not be aware of the oVirt <=> RHV relationship.

https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html
https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-customizations.html
https://docs.okd.io/latest/installing/installing_rhv/uninstalling-cluster-rhv.html
https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-creating-custom-vm.html
https://docs.okd.io/latest/installing/install_config/installation-types.html
\+ the sidebar category heading

**Comment by LorbusChris** [comment]
This should really be moved to the https://github.com/openshift/openshift-docs repo
/remove-lifecycle rotten
/lifecycle frozen

**Comment by mburke5678** [comment]
Note: The `installing-rhv-creating-custom-vm.adoc` file is removed.
https://github.com/openshift/openshift-docs/pull/21746

**Comment by mburke5678** [comment]
@omenos 
>  Documentation for OKD refers to supporting RHV 

Where do we list support for RHV?

@vrutkovs The docs should refer to oVirt, correct?

**Comment by mburke5678** [comment]
Any needed changes tracked in https://github.com/openshift/openshift-docs/pull/29056

Reverting `{rh-virtualization}` variable that was changed to `RHV` in https://github.com/openshift/openshift-docs/pull/28717/files#diff-d53ae3c90b8c03f6ca277c25ffe37db6ef5deb6320cd74131021c546508b14b3

**Comment by omenos** [comment]
@mburke5678 

The following locations use RHV (or rhv) instead of oVirt (code samples mostly using `rhv-env.<uri>`):

Page Title: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html
Code sample: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html#installing-rhv-verifying-rhv-environment_installing-rhv-default
Code Sample: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html#installation-launching-installer_installing-rhv-default

Code Sample: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-verifying-rhv-environment_installing-rhv-customizations
Second Notice (relates to OCP, though, should be excluded from OKD docs?) + Code Sample: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-customizations.html#installation-initializing_installing-rhv-customizations

Code Sample: https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-user-infra.html#installing-rhv-verifying-rhv-environment_installing-rhv-user-infra

Chart Headers: https://docs.okd.io/latest/installing/install_config/installation-types.html

**Comment by mburke5678** [comment]
@vrutkovs @omenos I made the changes as suggested in https://github.com/openshift/openshift-docs/pull/29056. Many of the links share a common file, so only needed to update in a few places. 

Does this make sense for a fake oVirt URL:`
https://ovirtlab.example.com/ovirt-engine/api`

Vadim, you can preview the changes if you want: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-customizations.html#installation-initializing_installing-rhv-customizations (internal only, sorry!)

**Comment by mburke5678** [comment]
Page Title: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-default.html
Code sample: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-default.html#installing-rhv-verifying-rhv-environment_installing-rhv-default
Code Sample: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-default.html#installation-launching-installer_installing-rhv-default

Code Sample: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-verifying-rhv-environment_installing-rhv-customizations
Second Notice (relates to OCP, though, should be excluded from OKD docs?) + Code Sample: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-customizations.html#installation-initializing_installing-rhv-customizations

Code Sample: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/installing_rhv/installing-rhv-user-infra.html#installing-rhv-verifying-rhv-environment_installing-rhv-user-infra

Chart Headers: http://file.rdu.redhat.com/~mburke/okd-issue-198/installing/install_config/installation-types.html

**Comment by vrutkovs** [comment]
Looks great, thanks!
