### ISSUE TITLE
The OKD documentation still refers to v3

### ISSUE THREAD

**Issue by jaywryan** [openshift/okd#2]
This is something I don't believe that we have talked about, or I have missed.  The README points to the OKD Latest which is still v3. https://docs.okd.io/latest/welcome/index.html Is there work being done to get the docs in order?

**Comment by vrutkovs** [comment]
This has been resolved recently, https://docs.okd.io/latest/welcome/index.html is now a copy of OCP 4.3 documentation (with a few changes)
