### ISSUE TITLE
"Status: Host is powered off" in Compute -> Nodes

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#20]
Hi,

4.3.0-0.okd-2019-11-15-182656 on vSphere.

In Menu 'Compute -> Nodes' in column 'Status': alle Nodes have status "Host is powered off" but obviously they aren't.

Greetings,

Josef

**Comment by vrutkovs** [comment]
Fixed in https://github.com/openshift/console/pull/3283

**Comment by jomeier** [comment]
Thx.
