### ISSUE TITLE
OKD install Azure

### ISSUE THREAD

**Issue by pkyc** [openshift/okd#203]
Encounter error during the create cluster,  using OKD 4.0 (okd:4.4.0-0.okd-2020-04-21-163702-beta4)

ERROR                                              
ERROR Warning: "resource_group_name": [DEPRECATED] This field has been deprecated and is no longer used - will be removed in 2.0 of the Azure Provider 
ERROR                                              
ERROR   on ../../tmp/openshift-install-570842XXX/main.tf line 163, in resource "azurerm_storage_container" "vhd": 
ERROR  163: resource "azurerm_storage_container" "vhd" { 
ERROR                                              
ERROR (and 3 more similar warnings elsewhere)      
ERROR                                              
ERROR                                              
ERROR Error: Error reading queue properties for AzureRM Storage Account "cluster6gws4": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:30231cbb-5003-006b-52d0-3784fa000000\nTime:2020-06-01T04:54:05.6870679Z" 
ERROR                                              
ERROR   on ../../tmp/openshift-install-570842XXX/main.tf line 133, in resource "azurerm_storage_account" "cluster": 
ERROR  133: resource "azurerm_storage_account" "cluster" { 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform 

My service account should have sufficient permission.  No cue what is going wrong.

**Comment by vrutkovs** [comment]
Is it the same error in Beta 5?

**Comment by pkyc** [comment]
> Is it the same error in Beta 5?

Ah...sorry for my overlook.  It is not happen in beta5.
