### ISSUE TITLE
strange messages during OKD deployment

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#204]
**Describe the bug**
I have automated OKD deployment including UPI provisioning on vSphere with scripts. In these scripts I also finally deploy OKD with the regular openshift-install commands.
During deployment of OKD I always get strange warnings/errors during waitfor bootstrap and waitfor install-complete, like here:

```
06/01/2020 22:28:51 monitor cluster bootstrap
level=info msg="Waiting up to 20m0s for the Kubernetes API at https://api.okd-demo.ars.de:6443..."
level=info msg="API v1.17.1 up"
level=info msg="Waiting up to 40m0s for bootstrapping to complete..."
W0601 20:45:55.114126    4039 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ConfigMap ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
E0601 20:45:59.124000    4039 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ConfigMap: Get https://api.okd-demo.ars.de:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dbootstrap&limit=500&resourceVersion=0: EOF
level=info msg="It is now safe to remove the bootstrap resources"
06/01/2020 22:49:45 removing bootstrap node from HAProxy configuration
waiting for 10 minutes
certificatesigningrequest.certificates.k8s.io/csr-2nv7m approved
certificatesigningrequest.certificates.k8s.io/csr-scj68 approved
certificatesigningrequest.certificates.k8s.io/csr-z5fns approved
waiting for 1 minute
certificatesigningrequest.certificates.k8s.io/csr-fbcwh approved
certificatesigningrequest.certificates.k8s.io/csr-qk58k approved
certificatesigningrequest.certificates.k8s.io/csr-szpc9 approved
06/01/2020 23:00:51 monitor completion of cluster installation
level=info msg="Waiting up to 30m0s for the cluster at https://api.okd-demo.ars.de:6443 to initialize..."
W0601 21:05:47.137576    9394 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ClusterVersion ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
level=info msg="Waiting up to 10m0s for the openshift-console route to be created..."
level=info msg="Install complete!"
level=info msg="To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/opt/install/auth/kubeconfig'"
level=info msg="Access the OpenShift web-console here: https://console-openshift-console.apps.okd-demo.ars.de"
level=info msg="Login to the console with user: kubeadmin, password: xxxxxx"
power off bootstrap node
stage 06 06/01/2020 23:12:28 - completed successfully
```
I mean these W0601 and E0601 message lines.
I do not get these messages if I use my script to deploy OpenShift instead. After deploying OKD, it seems to work normally. Do I need to worry about these messages?

**Version**
OKD 4.4 beta5

**How reproducible**
100%

**Log bundle**
n/a

**Comment by vrutkovs** [comment]
These are expected:

>E0601 20:45:59.124000    4039 reflector.go:153] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to list *v1.ConfigMap: Get https://api.okd-demo.ars.de:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dbootstrap&limit=500&resourceVersion=0: EOF
>level=info msg="It is now safe to remove the bootstrap resources"

This happens when etcd-operator shuts down etcd member on bootstrap node, so a new leader is elected and all connections are reset

> W0601 21:05:47.137576    9394 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ClusterVersion ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received

That is harmless, probably one of the api-servers has accepted a connection and got updated to a new revision.

Do we want to keep this open for more warnings during the process?

**Comment by kai-uwe-rommel** [comment]
I ran my deployment process already a couple of times and always only see these messages.
So, no reason to keep this open.
I just wondered because I do not see these messages when doing the same with OpenShift (currently at 4.4.5).
My deployment scripts work for both OpenShift and OKD 4.
