### ISSUE TITLE
how to choose PRODUCT_REPO and OCP_RELEASE

### ISSUE THREAD

**Issue by majorinche** [openshift/okd#207]
export OCP_RELEASE=<release_version> 
export LOCAL_REGISTRY='<local_registry_host_name>:<local_registry_host_port>' 
export LOCAL_REPOSITORY='<repository_name>' 
export PRODUCT_REPO='openshift-release-dev' 
export LOCAL_SECRET_JSON='<path_to_pull_secret>' 
export RELEASE_NAME="ocp-release" 

it seems okd images located here: https://quay.io/repository/openshift/okd-content
but how to set the PRODUCT_REPO and OCP_RELEASE?
the tag here is like: 4.4.0-0.okd-2020-05-23-055148-beta5-multus-whereabouts-ipam-cni
not like: 4.4.0-x86_64

**Comment by vrutkovs** [comment]
```
export PRODUCT_REPO='okd'
export OCP_RELEASE="<name of the image you're deploying>"
```
