### ISSUE TITLE
Console->About states OpenShift, should be OKD

### ISSUE THREAD

**Issue by evertmulder** [openshift/okd#210]
**Describe the bug**
The about text `OpenShift is Red Hat's container application platform` should be updated to OKD's mission statment.

![image](https://user-images.githubusercontent.com/61044/83980305-e8e54100-a914-11ea-99aa-656bb5c0eeb8.png)

**Version**
4.4 beta5

**How reproducible**
Open `about` in the web console

**Comment by vrutkovs** [comment]
Lets re-file that as a console bug in bugzilla.

It seems that console supports setting custom product name (this whole section would be hidden though), but I'm not sure if its worth changing this line to OCP or OKD
