### ISSUE TITLE
etcd cannot bootup in bootstrap

### ISSUE THREAD

**Issue by majorinche** [openshift/okd#211]
[root@localhost ~]# podman ps
CONTAINER ID  IMAGE                                                                                                  COMMAND               CREATED            STATUS                PORTS  NAMES
1dd1f210f54e  quay.io/openshift/okd-content@sha256:5b25b115fc463152998c0b55f07d7aa3d4a15f5167f77b9dd976ff243f478278  --dial-timeout=10...  2 seconds ago      Up 2 seconds ago             _**etcdctl**_
03a95b272343  quay.io/openshift/okd-content@sha256:8755e700accb5b6d92fd7d2c7b7a6252ed62f843f06fc31812b415a0ac47e0e1  serve --cacrt=/op...  About an hour ago  Up About an hour ago         etcd-signer

only two process, the etcdctl already keep rebooting

okd version: 4.4.0-0.okd-2020-05-23-055148-beta5
FCOS version: 31.20200521.20.0

try to debug, like checking journalctl -xb, see these errors
approve-csr.sh[788]: Unable to connect to the server: x509: certificate has expired or is not yet valid

but not sure if it is a problem related to etcd

**Comment by vrutkovs** [comment]
No log bundle provided, please reopen if its still an issue - see https://docs.okd.io/latest/installing/installing-troubleshooting.html about necessary log files
