### ISSUE TITLE
Configure samples operator to use registry.redhat.io to get updates

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#212]
Have okd 4.4 beta-5 running in vsphere 6.7 cluster.

Had a problem with the sample operator accessing registry.redhat.io to get updates.
I changed the sample operator state from Managed to Unmanged that got rid of my errors, but I would like it to pull updates from registry.redhat.io.

How can I configure sample operator to pull from registry.redhat.io?

Any help would be greatly appreciated.

**Comment by vrutkovs** [comment]
>Had a problem with the sample operator accessing registry.redhat.io to get updates.

Which problem? Did you use pull secret from openshift.com/try?

**Comment by johnlongo** [comment]
No I used:
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 

What can I do to fix this without having to reinstall?

**Comment by vrutkovs** [comment]
You need a pull secret from https://openshift.com/try to pull images from registry.redhat.io

Pull secret can be updated - see [this section in the docs](https://docs.okd.io/latest/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets)

**Comment by johnlongo** [comment]
That worked great, thank you
