### ISSUE TITLE
unable to get REST mapping in bootstrap node

### ISSUE THREAD

**Issue by majorinche** [openshift/okd#213]
in bootstrap node, check the bootkube logs
journalctl -b -f -u release-image.service -u bootkube.service
and find this error
Jun 11 14:26:35 localhost bootkube.sh[316989]: [#1941] failed to create some manifests:
Jun 11 14:26:35 localhost bootkube.sh[316989]: "99_openshift-machineconfig_99-master-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-master-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"

this error just keep repeating

**Comment by vrutkovs** [comment]
Dupe #81. This is expected - CVO is waiting for machine-config-operator to start.
Please reopen with attached must-gather
