### ISSUE TITLE
how to download the FCOS

### ISSUE THREAD

**Issue by majorinche** [openshift/okd#214]
@vrutkovs hi, i notice here: https://github.com/openshift/okd/releases, about the machine-os version

Component Versions:
  kubernetes 1.17.1         
  machine-os 31.20200521.20 Fedora CoreOS

this version: 31.20200521.20 Fedora CoreOS, how can i download this version
i search on https://getfedora.org/coreos?stream=stable, did not find it.

**Comment by vrutkovs** [comment]
This is FCOS version from `testing-devel` stream. You should not be downloading it - start with the image suggested by installer (i.e. any image from `stable` stream) and after the pivot your machines would be updated automatically
