### ISSUE TITLE
Nightlies are shown as available updates for stable stream

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#217]
Nightly builds of 4.5.0-0.okd have additional upgrades test - upgrades from beta5. This adds the nightly to available updates on beta5.

We should either:
* configure channels in release controller or
* disable this test

so that "stable" beta5 users would be notified only when beta6 is available.

Seems its a release-controller bug - when `stable-x` channel is used it simply picks all releases starting with `x` instead of filtering by `/name` annotation

**Comment by bretm** [comment]
I accidentally consumed one of the nightlies; what's the recommended path to get back onto the betas?  Or am I facing a reinstall?

**Comment by cgruver** [comment]
Ouch...

You can probably continue to consume nightlies as upgrades until GA.  As long as the GA release is on the upgrade path, you should be fine.

**Comment by vrutkovs** [comment]
`oc adm update --to-image` can update to any release, regardless of tested path in the worst case

**Comment by bretm** [comment]
Seem to have successfully upgraded from 4.5.0-0.okd-2020-06-17-231259 to 4.5.0-0.okd-2020-06-29-110348-beta6 via:

oc adm upgrade --force --allow-explicit-upgrade --to-image='quay.io/openshift/okd:4.5.0-0.okd-2020-06-29-110348-beta6'
