### ISSUE TITLE
Zincati generates a lot of errors on FCOS

### ISSUE THREAD

**Issue by evertmulder** [openshift/okd#219]
**Describe the bug**
On OKD FCOS nodes zincati generates a lot of errors.

```
journalctl -u zincati -f
...
systemd[1]: zincati.service: Scheduled restart job, restart counter is at 786.
systemd[1]: Stopped Zincati Update Agent.
systemd[1]: Started Zincati Update Agent.
zincati[200836]: [INFO ] starting update agent (zincati 0.0.11)
zincati[200836]: Error: Error("missing field `coreos-assembler.basearch`", line: 10, column: 7)
zincati[200836]: failed to introspect OS base architecture
zincati[200836]: failed to build default identity
zincati[200836]: failed to validate agent identity configuration
zincati[200836]: failed to assemble configuration settings
systemd[1]: zincati.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: zincati.service: Failed with result 'exit-code'.
...
<repeat every 10 sec>
```   

I do not know if the zincati service is used for OKD for OS updates or if this message indicate the OS is not receiving updates... Is there some documentation around this? 

**Version**
Seen on:
4.4-beta5
4.5.0-0.okd-2020-06-16-144107

**How reproducible**
login to a node:
```
journalctl -u zincati -f
```

**Comment by vrutkovs** [comment]
`machine-os-content` needs to have a few more labels so that Zincati could parse these

**Comment by vrutkovs** [comment]
Zincati analyzes rpm-ostree commit, which we build using `coreos-assembler dev-overlay`. Unfortunately the latter can't set commit metadata.

The error is annoying, but harmless, so I'll move this out of Beta 6 milestone

**Comment by vrutkovs** [comment]
See also https://github.com/coreos/fedora-coreos-tracker/issues/392

**Comment by vrutkovs** [comment]
Fixed by https://github.com/openshift/machine-config-operator/pull/1890

**Comment by vrutkovs** [comment]
This is still happening on latest nighties

**Comment by vrutkovs** [comment]
Fixed in https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasetag/4.5.0-0.okd-2020-08-12-165745: `localhost systemd[1]: Condition check resulted in Zincati Update Agent being skipped.`
