### ISSUE TITLE
Timeout waiting fot cluster operator, install failed on AWS. OCP 4.2 works on same account.

### ISSUE THREAD

**Issue by jagusztinl** [openshift/okd#22]
Please find the log bundle here:
https://drive.google.com/open?id=1EuEWy1KhoM1uLk0iemBMqGohw7blcEV1

Please notify me after the download.

**Comment by vrutkovs** [comment]
```
kubelet.service: Failed at step EXEC spawning /usr/bin/hyperkube: No such file or directory
```

**Comment by vrutkovs** [comment]
Right, MCD binary didn't get extracted properly. This would be resolved by https://github.com/openshift/machine-config-operator/pull/1301

**Comment by vrutkovs** [comment]
Is this reproducible if a 4.4 release from origin-release.svc.ci.openshift.org is used?

**Comment by jagusztinl** [comment]
No, OKD 4.4 works perfectly!

**Comment by vrutkovs** [comment]
Great, lets close it then

**Comment by PiotrKlimczak** [comment]
I have exactly same problem now. Affects all available versions of OKD, including 4.3. and 4.4.
No customisations, just doing "openshift-install create cluster".

**Comment by vrutkovs** [comment]
>I have exactly same problem now

Please file a new issue and attach `oc adm must-gather` output

**Comment by PiotrKlimczak** [comment]
@vrutkovs, thanks for your answer. Where do you want me to call this from?
I can't run it from my local machine, as API fails to bootstrap.
From local I am getting:
```
The connection to the server xxx.xxx.xxx:6443 was refused - did you specify the right host or port?
```
I can't do that from bootstraps machine as there is nothing listening on such port too.
Also I can't ssh to masters from bootstrap machine as I am getting connection refused on port 22.
I completely run out of ideas, also whole FCOS is new concept for me as previously I was using DIY approach for all openshift 3.X deployments. I tried to go through FCOS docs but I am not familiar with terraform still so docs are pretty meaningless for me.
I don't want to start new thread as of yet, but rather try to solve it myself or gather more data so it can be investigated properly by you guys.
