### ISSUE TITLE
Producing valid ignitions seems to be broken for baremetal on OKD branch

### ISSUE THREAD

**Issue by ashaver** [openshift/okd#221]
Description of problem:
Producing valid ignitions seems to be broken for baremetal.

Version-Release number of selected component (if applicable):
quay.io/openshift/okd:4.4.0-0.okd-2020-05-23-055148-beta5
How reproducible:
Every time.

Steps to Reproduce:
1) Generate install-config.yaml from https://www.redhat.com/sysadmin/kubernetes-cluster-laptop
2) Get a recent OKD installer
   `oc adm release extract --tools quay.io/openshift/okd:4.4.0-0.okd-2020-05-23-055148-beta5`
3) Unpack the installer
4) Generate the ignitions
   `./openshift-install create ignition-configs`
5) Get a config validator from https://github.com/coreos/ignition/releases
   `wget https://github.com/coreos/ignition/releases/download/v2.3.0/ignition-validate-x86_64-linux`
   `chmod +x ignition-validate-x86_64-linux`
6) check validation on newly made bootstrap (and see that it complains they are made incorrectly)
    `./ignition-validate-x86_64-linux bootstrap.ign`
Actual results:
Ignition files cannot be parsed. This results in being unable to build a bootstrap node (and thus install any portion of the cluster).

Expected results:
Ignition files are valid and can be read by FCOS/RHCOS/CoreOS

**Comment by vrutkovs** [comment]
Can't reproduce - created ignitions for AWS and `./ignition-validate-x86_64-linux` won't throw an error for bootstrap/master/worker ignitions.

Also, we're using `2.2.1` in Beta5 (`2.3.0` in 4.5 nightlies), so it could be a `ignition-validate 2.3.0` bug

**Comment by ashaver** [comment]
Thank you so much for looking at it. I believe the issue is a baremetal issue, so the install-config would need to have a platform listing bare metal. Would you be so kind to try again with an install-config.yaml for baremetal (which has none listed for the platform).

An example config that I use to test generation is below:

<Start install-config.yaml>
apiVersion: v1
baseDomain: okd4.lab
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 1
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 1
metadata:
  name: lab-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":{"green:5000":{"auth":"ZG9ja2VyOmRvY2tlcg==","email":"docker@example.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2MLzAGXK5ThSxHUlLkZ55STdlzgL5sX5ZWfWJUX1fr4b22ZUjdbOLGnUqeBsSCtbxSufsAnk/KtHRxE4KjBhJYyLZSPdYiNrl2MsGIBwubXUM9DsBucLhe6ToOImc0sU4w1mwlrqFW7cMto+o8m+LPW16tfWbWDih3aCJaq4i/lNevecs6jmURfwL3shXQLcKjGew4gPs18zMUuiQDVGsQag4Bw3DBmvAuBESOhI/PD1aS0+xPslJQmxNEub2acuBRulq/OoTIDlB0TOEYxxXjOroIdrI+5NHIAXbXMLZrQidrVx7ieib1X812j5KX9YhZsA6kp8lT5S88J/bJNIt root@bastion' 
<End install-config.yaml>

**Comment by ashaver** [comment]
I tried using one of the nightlies (4.4.0-0.okd-2020-06-17-221719) and it did in-fact work. Is the right thing to do to close the bug (because it's fixed in the nightlies)?

Also, would it be worthwhile to make a unit test for changes to the installer to run through some basic cases and do validation afterwards (or would that be a useless test)?

**Comment by vrutkovs** [comment]
Pretty odd, but I still can't reproduce it?

```
$ oc adm release extract --command=openshift-install --command-os=linux --to=/tmp/ quay.io/openshift/okd:4.4.0-0.okd-2020-05-23-055148-beta5 
$ mkdir /tmp/cluster
$ vi /tmp/cluster/install-config.yaml
$ ./openshift-install create ignition-configs --dir=/tmp/cluster
INFO Consuming Install Config from target directory 
$ wget https://github.com/coreos/ignition/releases/download/v2.3.0/ignition-validate-x86_64-linux
$ chmod a+x ignition-validate-x86_64-linux
$ ./ignition-validate-x86_64-linux /tmp/cluster/bootstrap.ign
```

>Is the right thing to do to close the bug (because it's fixed in the nightlies)?

There hasn't been any changes to installer since Beta5.

`fcos` branch of installer is now building 4.5 nightlies, one of these would be promoted to beta - could you give one of these a try?

>would it be worthwhile to make a unit test for changes to the installer to run through some basic cases and do validation afterwards

That might be useful, yes, although

* ultimately this is tested when bootstrap node starts. If its invalid CI would make screenshots of a machine failing to boot
* we're using Ignition API to generate bootstrap, most dire ones are already fixed.

Lets keep this open so that we could investigate, but I haven't seen any "my bootstrap won't boot due to invalid Ignition" for a while.

**Comment by ashaver** [comment]
I went back and was unable to verify the bug on beta4, beta5, and nightly 2020-06-19-045550.

I will close the ticket. Thank you again for your help and time.

I think the user error on my part must have stemmed from grabbing an openshift installer (oc adm release extract --tools quay.io/openshift-release-dev/ocp-release:4.4.8-x86_64) instead of an OKD installer.

```
# Make directory test to hold the entire experiment (so it can be easily deleted later)

# Beta 5 Works
export OKD_VERSION=4.4.0-0.okd-2020-05-23-055148-beta5
export REPO=quay.io/openshift/okd

# Beta 4 Works
#export OKD_VERSION=4.4.0-0.okd-2020-04-21-163702-beta4
#export REPO=quay.io/openshift/okd

# Nightly Works
#export OKD_VERSION=4.4.0-0.okd-2020-06-19-045550
#export REPO=registry.svc.ci.openshift.org/origin/release

export STARTDIR=$PWD
mkdir $STARTDIR/test
mkdir $STARTDIR/test/installer
mkdir $STARTDIR/test/cluster-dir

# download extract and verify beta5 openshift-installer
cd $STARTDIR/test/installer
oc adm release -a ~/pull-secret.json extract --tools $REPO:$OKD_VERSION
tar -xzvf openshift-install-linux-$OKD_VERSION.tar.gz
./openshift-install version

# change to the location for the cluster to be built. Construct the ignition to reflect bare-metal, then build ignitions
cd $STARTDIR/test/cluster-dir

cat << EOF > install-config.yaml
apiVersion: v1
baseDomain: okd4.lab
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 1
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 1
metadata:
  name: lab-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":{"green:5000":{"auth":"ZG9ja2VyOmRvY2tlcg==","email":"docker@example.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2MLzAGXK5ThSxHUlLkZ55STdlzgL5sX5ZWfWJUX1fr4b22ZUjdbOLGnUqeBsSCtbxSufsAnk/KtHRxE4KjBhJYyLZSPdYiNrl2MsGIBwubXUM9DsBucLhe6ToOImc0sU4w1mwlrqFW7cMto+o8m+LPW16tfWbWDih3aCJaq4i/lNevecs6jmURfwL3shXQLcKjGew4gPs18zMUuiQDVGsQag4Bw3DBmvAuBESOhI/PD1aS0+xPslJQmxNEub2acuBRulq/OoTIDlB0TOEYxxXjOroIdrI+5NHIAXbXMLZrQidrVx7ieib1X812j5KX9YhZsA6kp8lT5S88J/bJNIt root@bastion'
EOF

$STARTDIR/test/installer/openshift-install create manifests
$STARTDIR/test/installer/openshift-install create ignition-configs

# Verify configs
wget https://github.com/coreos/ignition/releases/download/v2.3.0/ignition-validate-x86_64-linux
chmod +x ignition-validate-x86_64-linux 
./ignition-validate-x86_64-linux bootstrap.ign

# Cleanup
cd $STARTDIR
rm -rf $STARTDIR/test
```

**Comment by vrutkovs** [comment]
Oh, an OCP installer would have caused that, right. I wonder why ignition-validate won't go into the details what was wrong there.
