### ISSUE TITLE
4.5.0-0.okd-2020-06-18-025306 bootstrap never completes

### ISSUE THREAD

**Issue by disposab1e** [openshift/okd#222]
**Describe the bug**
Bootstrap coming up but master never join. bootstrap phase never completes.

**Version**
UPI / KVM 0.12.0
4.5.0-0.okd-2020-06-18-025306
32.20200615.2.0

**How reproducible**
100%

**Log bundle**
[journal.txt](https://www.dropbox.com/s/jfu9e0d828j4x5t/journal.txt?dl=0)

**Comment by vrutkovs** [comment]
No log bundle provided

**Comment by disposab1e** [comment]
This is all I have and was requested by Josef...

**Comment by cgruver** [comment]
@disposab1e 

I will be building a cluster this weekend with a 4.5 nightly build and FCOS 32.  Since our setups are similar, I'll let you know if I have any issues.  There might be a nuance that is tripping you.

**Comment by disposab1e** [comment]
wasted time for @vrutkovs so better closed

**Comment by jomeier** [comment]
@disposab1e 
No offense, but he asked you for logfiles a few times and you didn't give them to him. Apparently, you guys talked at cross purposes or had a bad day :-)

Calm down and help each other, please.

**Comment by Knutm2** [comment]
[admin@okd4-services ~]$ export KUBECONFIG=install_dir/auth/kubeconfig
[admin@okd4-services ~]$ oc adm must-gather
[must-gather      ] OUT the server could not find the requested resource (get imagestreams.image.openshift.io must-gather)
[must-gather      ] OUT
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/origin-must-gather:latest
[must-gather      ] OUT namespace/openshift-must-gather-82dtp created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-t2tlg created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/origin-must-gather:latest created
[must-gather-67ttf] OUT gather did not start: timed out waiting for the condition
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-t2tlg deleted
[must-gather      ] OUT namespace/openshift-must-gather-82dtp deleted
error: gather did not start for pod must-gather-67ttf: timed out waiting for the condition
[admin@okd4-services ~]$

**Comment by Knutm2** [comment]
[admin@okd4-services ~]$ oc get machineconfig
NAME                            GENERATEDBYCONTROLLER   IGNITIONVERSION   AGE
99-master-disable-mitigations                           3.1.0             69m
99-master-ssh                                           3.1.0             69m
99-worker-disable-mitigations                           3.1.0             69m
99-worker-ssh                                           3.1.0             69m
[admin@okd4-services ~]$ oc get machineconfigpools
NAME     CONFIG   UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master                                                                                                                            57m
worker                                                                                                                            57m
[admin@okd4-services ~]$
