### ISSUE TITLE
where is the vSphere config stored?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#224]
**Describe the bug**
This is actually a documentation bug ... I think.

When I install OKD on vSphere with UPI, I provide vSphere configuration (vcenter, credentials, datastore etc.) in install-config.yaml.

How can I change this information after the cluster has been deployed? Sometimes the vSphere account credentials will change or I need to target a different datastore so I must be able to change this information.

Where is it stored? I have checked for a configmap or secret but was unable to find it.

I did find the vCenter credentials in two secrets:
```
kube-system                                             vsphere-creds                                                        Opaque                   
openshift-machine-api                                   vsphere-cloud-credentials                                            Opaque                   
```

But where is the rest of the data? Such as the datastore name?

This is not mentioned anywhere in the documentation.

**Version**
4.4 beta5

**How reproducible**
Always

**Log bundle**
n/a

**Comment by kai-uwe-rommel** [comment]
I did now find the data in /etc/kubernetes/cloud.conf on all (!) master nodes.
So it looks like I need to change it that way, on all three master nodes ...
In any case, it needs to be documented in the OKD documentation!

**Comment by vrutkovs** [comment]
>How can I change this information after the cluster has been deployed?

That's not supported

**Comment by nate-duke** [comment]
@vrutkovs Could you clarify which part of this is not supported?
- vSphere Cluster settings (Datastore, Cluster, Datacenter, Folder, Resource Pool (not supported yet but in 4.6 OCP at least)
- vSphere Credentials
- Anything Related to vSphere IPI?

**Comment by kai-uwe-rommel** [comment]
Also, that is important. If such a cluster (be it OCP or OKD) is part of a professional IT environment (e.g. vSphere), it may need to adapt to changes from time to time. Such as a change in credentials, vSphere cluster/datacenter location/name. Or even moving the kubevols to a different vSphere datastore!

**Comment by vrutkovs** [comment]
> Could you clarify which part of this is not supported?

Updating vSphere credentials post-install is not currently supported. Once the support for this appears a new [enhancement](https://github.com/openshift/enhancements) would be created

**Comment by turchinc** [comment]
wow first day running okd on vsphere and stumbled onto this one. ouch.
