### ISSUE TITLE
Bootstrap VM doesn't come up in OpenShift 4.2 vSphere Installation

### ISSUE THREAD

**Issue by 5254565852** [openshift/okd#230]
Hi guys
I want to install okd 4.2 on vsphere 6.7 with [OpenShift 4.2 vSphere Install Quickstart](https://www.openshift.com/blog/openshift-4-2-vsphere-install-quickstart) documentation. But bootstrap VM doesn't come up. 
What is the reason?
Is there full and step by step installation document?
Thank you for your help

**Comment by vrutkovs** [comment]
There is no OKD 4.2, which release payload and installer are you using?

**Comment by 5254565852** [comment]
> There is no OKD 4.2, which release payload and installer are you using?

Thank you for reply.
I used [OpenShift 4.2 vSphere Install Quickstart](https://www.openshift.com/blog/openshift-4-2-vsphere-install-quickstart) and [openshift client and installation files](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/)

**Comment by vrutkovs** [comment]
That is OCP 4.2, not okd 4.2. See https://docs.openshift.com/container-platform/4.2/support/getting-support.html
