### ISSUE TITLE
Running 4.4.0-0.okd-2020-05-23-055148-beta5 with channel stable-4.4

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#236]
Running 4.4.0-0.okd-2020-05-23-055148-beta5 with channel stable-4.4.
I see that beta6 was released yesterday and not seeing an option to upgrade in the admin console.
Will I be able to upgrade to beta6 via the admin console?

**Comment by vrutkovs** [comment]
Why the channel is `stable-4.4`, installer should have set it to `stable-4`.

Use `oc patch clusterversion/version --patch '{"spec":{"channel":"stable-4"}}' --type=merge` to update it

**Comment by johnlongo** [comment]
That Worked Thank You

<img width="913" alt="2020-06-30_16-34-31" src="https://user-images.githubusercontent.com/23619505/86174478-b97abc00-baef-11ea-95a0-3e5f799428d5.png">
