### ISSUE TITLE
Update Status  shows Version not found

### ISSUE THREAD

**Issue by preinking** [openshift/okd#241]
**Describe the bug**
  Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2020-06-29-110348-beta6 not found in the "stable-4.5 

**Version**
4.5.0-0.okd-2020-06-29-110348-beta6
UPI install method on libvirt (KVM)

**How reproducible**
100% reproducible by doing a fresh install using the resources below and once the cluster comes up that selected channel is stable-4.5 but the version used to bring the cluster up is not available in that channel ?

okd_client: "https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-06-29-110348-beta6/openshift-client-linux-4.5.0-0.okd-2020-06-29-110348-beta6.tar.gz"
okd_installer: "https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-06-29-110348-beta6/openshift-install-linux-4.5.0-0.okd-2020-06-29-110348-beta6.tar.gz"

**Comment by vrutkovs** [comment]
This is resolved in latest nightlies - https://github.com/openshift/installer/pull/3832

Corrent channel should be `stable-4`, workaround: `oc patch clusterversion/version --patch '{"spec":{"channel":"stable-4"}}'`

**Comment by preinking** [comment]
After running `oc patch clusterversion/version --type=merge --patch '{"spec":{"channel":"stable-4"}}'` I'm getting the next result:Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2020-06-29-110348-beta6 not found in the "stable-4" channel`

**Comment by vrutkovs** [comment]
That's odd. Would you mind attaching `oc get clusterversion/version -o yaml`?

**Comment by preinking** [comment]
```
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  creationTimestamp: "2020-07-03T06:37:52Z"
  generation: 2
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:clusterID: {}
        f:upstream: {}
    manager: cluster-bootstrap
    operation: Update
    time: "2020-07-03T06:37:52Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:channel: {}
    manager: Mozilla
    operation: Update
    time: "2020-07-03T07:48:25Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:availableUpdates: {}
        f:conditions: {}
        f:desired:
          .: {}
          f:force: {}
          f:image: {}
          f:version: {}
        f:history: {}
        f:observedGeneration: {}
        f:versionHash: {}
    manager: cluster-version-operator
    operation: Update
    time: "2020-07-03T07:49:24Z"
  name: version
  resourceVersion: "42235"
  selfLink: /apis/config.openshift.io/v1/clusterversions/version
  uid: 390300ac-050e-4012-8af4-ad6d0e913fb5
spec:
  channel: stable-4
  clusterID: c8c5b756-16a5-4763-8801-e507d5142929
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
status:
  availableUpdates: null
  conditions:
  - lastTransitionTime: "2020-07-03T07:07:09Z"
    message: Done applying 4.5.0-0.okd-2020-06-29-110348-beta6
    status: "True"
    type: Available
  - lastTransitionTime: "2020-07-03T07:04:54Z"
    status: "False"
    type: Failing
  - lastTransitionTime: "2020-07-03T07:07:09Z"
    message: Cluster version is 4.5.0-0.okd-2020-06-29-110348-beta6
    status: "False"
    type: Progressing
  - lastTransitionTime: "2020-07-03T06:37:58Z"
    message: 'Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2020-06-29-110348-beta6
      not found in the "stable-4" channel'
    reason: VersionNotFound
    status: "False"
    type: RetrievedUpdates
  desired:
    force: false
    image: quay.io/openshift/okd@sha256:4195c00b498bff923889ae3a6f855d4b05ed05a4c5d2e7e0563f52b18b224e17
    version: 4.5.0-0.okd-2020-06-29-110348-beta6
  history:
  - completionTime: "2020-07-03T07:07:09Z"
    image: quay.io/openshift/okd@sha256:4195c00b498bff923889ae3a6f855d4b05ed05a4c5d2e7e0563f52b18b224e17
    startedTime: "2020-07-03T06:37:58Z"
    state: Completed
    verified: false
    version: 4.5.0-0.okd-2020-06-29-110348-beta6
  observedGeneration: 2
  versionHash: S47p_HLorz0=
```

**Comment by vrutkovs** [comment]
oh right, it has an incorrect "upstream" set too :facepalm: 

`oc patch clusterversion/version --type=merge --patch '{"spec":{"upstream":"https://origin-release.svc.ci.openshift.org/graph"}}'` would patch that

**Comment by andreasottosson** [comment]
If I do `oc patch clusterversion/version --type=merge --patch '{"spec":{"channel":"stable-4"}}'` and `oc patch clusterversion/version --type=merge --patch '{"spec":{"upstream":"https://origin-release.svc.ci.openshift.org/graph"}}'` it shows nightlies for 4.6.0 as updates. Reverting to stable-4.5 gives a green checkbox that the cluster is up to date on beta6. Perhaps that is expected.

**Comment by vrutkovs** [comment]
That's expected. It appears release-controller is misconfigured and won't filter updates by channels as expected, we'll look into that

**Comment by vrutkovs** [comment]
Invalid channel filtering is tracked in https://github.com/openshift/okd/issues/217
Upstream URL fixed in https://github.com/openshift/installer/pull/3839
