### ISSUE TITLE
Clair scanner reports multiple high priority vulnaribilities

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#242]
4.5-beta6 images have multiple vulnerabilities according to quay.

Most of these should be fixed in OCP build, lets focus on OKD-specific bits first 

<img width="1388" alt="screen_shot_2020-07-03_at_13 44 55" src="https://user-images.githubusercontent.com/114501/86468945-b8889b00-bd38-11ea-88a1-923828581679.png">

**Comment by andreasottosson** [comment]
FYI: RC shows even more vulnerable images. 63 in total vs 45 on beta6.

**Comment by philipp1992** [comment]
i was told the OKD and OCP images are the same, so this problem should be fixed once RedHat releases new images right?

**Comment by slauger** [comment]
The CSO (Container Security Operator) still reports a lot of CVEs on 4.5.0-0.okd-2020-10-15-235428. OCP 4.5.15 on the other hand is fine.

For example check the cluster-node-tuning-operator (`quay.io/openshift/okd-content@sha256:6b4bf0926816c18a607b5c57933c2d3a4af7d2a497a096b67c9fe892d2333be4`)

https://quay.io/repository/openshift/okd-content/manifest/sha256:6b4bf0926816c18a607b5c57933c2d3a4af7d2a497a096b67c9fe892d2333be4?tab=vulnerabilities

**Comment by jomeier** [comment]
Any news why that happens?

**Comment by jomeier** [comment]
The images mostly seem to be built of this image here: 

registry.svc.ci.openshift.org/openshift/origin-v4.0:base

In former discussions I understood from @vrutkovs that the plan is to use UBI base images because they are built regularly. This should also fix the CVE problem.

**Comment by jomeier** [comment]
Here is the discussion about what happened and how it will be resolved for OKD 4.6 (++):

https://kubernetes.slack.com/archives/C6BRQSH2S/p1604218274392100

**Comment by slauger** [comment]
It seems that the CVEs are still present in 4.6.0-0.okd-2020-12-12-135354. Did i miss something?

e.g. openshift-cluster-node-tuning-operator:

https://quay.io/repository/openshift/okd-content/manifest/sha256:5a66e66d72720bd6434ba69d1da6793dd7ac13ebb41e8abac29ae464358a200c?tab=vulnerabilities

**Comment by jomeier** [comment]
@slauger
