### ISSUE TITLE
docker daemon gets started on nodes

### ISSUE THREAD

**Issue by dustymabe** [openshift/okd#243]
In FCOS we include the moby-engine package to provide the docker CLI/daemon for users who want that. In OKD I don't think we want the service to start at all as we run containers with `cri-o` (or in some very few cases `podman`). Right now the docker service is socket activated and I think something within kubernetes/openshift is hitting that socket and starting the daemon.

```
Jul 03 19:51:29 node0 hyperkube[1016]: I0703 19:51:29.209861    1016 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/kubelet-ca.crt
Jul 03 19:51:29 node0 systemd[1]: Starting Docker Application Container Engine...
```

Should we [mask the service](https://github.com/coreos/fedora-coreos-tracker/issues/229#issuecomment-595834796) for now? It would save us the 150+ MiB hit:

```
$ systemctl status docker | grep Memory
     Memory: 182.2M
```

#### Versions 

- installer: `openshift-install-linux-4.5.0-0.okd-2020-06-29-110348-beta6`
- starting FCOS: `32.20200629.2.0`

**Comment by vrutkovs** [comment]
Right, we should disable it with a MachineConfig

**Comment by LorbusChris** [comment]
IMO docker should be disabled by preset in FCOS (in all of Fedora even!).

**Comment by LorbusChris** [comment]
Thank you for reporting this @dustymabe!

**Comment by vrutkovs** [comment]
Fixed since https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasetag/4.5.0-0.okd-2020-07-06-212947

**Comment by Fodoj** [comment]
Any reason to have Docker installed at all? I know it comes by default with FCOS, but why would OKD need it installed by default.

**Comment by LorbusChris** [comment]
@Fodoj OKD uses FCOS' rpm-ostree composes and we don't currently plan on doing an OKD-specific compose.
