### ISSUE TITLE
vSphere UPI: Update icon on status "Provisioned as node" for new machines not going away

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#245]
Hi,

today I managed to get automatic worker creation on vSphere UPI working. Even with automatic creation of their hostnames because we don't get them from our DHCP server.

The Machines are reported as "Provisioned as node" and have a refresh/update icon left of them:

![machineset](https://user-images.githubusercontent.com/12024238/86530576-1db7ca00-beba-11ea-9d9a-194a04ff2456.PNG)

What does that mean? Is OKD doing something or has it successfully finished creating this machines?

If the latter than the icon should be different in my opinion.

Verision: 4.5.0-0.okd-2020-07-02-103539

Greetings,

Josef

**Comment by vrutkovs** [comment]
"Provisioned as node" is the final state - machine has been created, booted and registered itself as node. 
Agree, checkmark on UI would fit better than a refresh-like icon - mind filing a bugzilla for console about that?

**Comment by jomeier** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1854131

**Comment by vrutkovs** [comment]
Thanks! Lets track this in the bugzilla

**Comment by jomeier** [comment]
https://github.com/openshift/console/pull/5901

Nice !

**Comment by kai-uwe-rommel** [comment]
@jomeier Could you please describe what you needed to do to get automatic worker creation on vSphere UPI? Thanks!

**Comment by jomeier** [comment]
Hi Kai Uwe,

we filled out the ProviderSpec for vSphere. You can use the MachineSet resources that are contained in OKD after the installation as an example. I remember that one field was missing there that is important.

You also must use a FCOS image that supports Ignition 2.3.0 (Spec 3.0.0) as a template for your workers.

I can post a sample tomorrow.

The most important thing was to get RBAC working on vSphere, because that’s a ... challenge  😁
