### ISSUE TITLE
vSphere UPI: Indicate in UI if node gets degraded because of config mismatch

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#246]
Hi,

I played around with some systemd services on my worker nodes (sshed in the nodes and manipulated things). 

The machine-config-daemon reported afterwards, that the node has been marked as degraded because of config mismatch.

That's good.

What's not so good: I don't see anything about this degradation in the web ui. I would expect that this degraded state is not only shown in logs but also in the UI. I don't have a chance to fix things, if I don't get a warning or error message.

If was looking for this in UI->nodes.

Maybe that's indicated somewhere else?

Greetings,

Josef

**Comment by vrutkovs** [comment]
Machine/Nodes don't have a degraded status per se - MCO can degrade on a particular node and not proceed further.

I believe linking a node to a MCO state would require an ehnancement - @LorbusChris WDYT?

**Comment by jomeier** [comment]
The command:

```
oc get mcp 
```

comes to the resue here. Also in the UI you can easily see that something has degraded in the MCP.

That's what I need.

I'll close this ticket. Thx!
