### ISSUE TITLE
AWS: crio.conf missing on bootstrap node

### ISSUE THREAD

**Issue by UnlawfulMonad** [openshift/okd#25]
During installation on AWS with default settings `bootkube.sh` fails with an error before restarting:

```
Dec 16 23:01:59 ip-10-0-8-136 bootkube.sh[4611]: sed: can't read /etc/crio/crio.conf: No such file or directory
```

I got past it by creating `/etc/crio/` and `/etc/crio.conf` (with the default contents on a fedora install).

I'm not sure what subproject this issue should go under.

**Comment by vrutkovs** [comment]
Is this reproducible if a 4.4 release from origin-release.svc.ci.openshift.org is used?

**Comment by UnlawfulMonad** [comment]
With [this][1] build I didn't run into this issue anymore.

[1]:  https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-21-152938
