### ISSUE TITLE
I found the error when I configured keycloak with user federation spi

### ISSUE THREAD

**Issue by Warren-Xia** [openshift/okd#252]
I configured keycloak with user federation spi, and I configured openid in openshift.
Then I login keycloak success, but page redirect to openshift, I found the following error:

E0708 23:33:48.152502       1 errorpage.go:26] AuthenticationError: User.user.openshift.io "AI6830admin" is invalid: identities[0]: Invalid value: "openid:f:2a973708-0869-4808-995b-eaa444e6307e:54335": 
must be in the format `<providerName>:<providerUserName>`

My openid config is:
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  creationTimestamp: '2020-05-22T05:56:33Z'
  generation: 15
  name: cluster
  resourceVersion: '44473020'
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: fd3ef448-9bf0-11ea-bc7c-005056ae64a9
spec:
  identityProviders:
    - mappingMethod: add
      name: openid
      openID:
        ca:
          name: openid-ca-bnq79
        claims:
          email:
            - email
          id:
            - preferred_username
          name:
            - name
          preferredUsername:
            - preferred_username
          sub:
            - preferred_username
        clientID: openshift
        clientSecret:
          name: openid-client-secret-kpb8x
        extraScopes: []
        issuer: >-
          https://keycloak-keycloak.apps.app.test.se-unicloud.com/auth/realms/SE-UNICLOUD
      type: OpenID

**Comment by vrutkovs** [comment]
Closing as insufficient info has been provided. Please reopen if that is still an issue and attach must-gather
