### ISSUE TITLE
Console messages from zincati on bootstrap node before masters are started

### ISSUE THREAD

**Issue by gmarcy** [openshift/okd#254]
During testing of the 4.5.0 release candidate I noticed zincati messages on the console of the bootstrap node.
I also noticed them appearing later on the master and worker nodes.  Since I was using the latest stable fcos
release that probably wasn't going to be a problem, but it indicates that the service could potentially perform
upgrades in the middle of an initial cluster install which could lead to failures in different scenarios.

4.5.0-0.okd-2020-07-12-134038 Release candidate

libvirt dhcp helpernode install following:

 https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/quickstart.md

This was my first install of this release, but had to disable vincati in earlier beta testing when I wasn't running
on the latest stable release.

No logs, just observed on the virt-viewer console as I was monitoring the install.

**Comment by vrutkovs** [comment]
Zincati is expected to run, but it needs to be disable via config.
Pretty sure we're disabling zincati on masters/workers correctly - we're shipping "no autoupdate" config and ensure pivot happens before `zincati.service`.
I'll check if there's a chance zincati can start before bootstrap.

Workaround: use the latest stable FCOS image on fresh installs

**Comment by vrutkovs** [comment]
This has been resolved in recent OKD 4.5 stable releases - correct configuration is laid on masters/workers which disables Zincati
