### ISSUE TITLE
OKD v4.4 on bare metal installation stuck in the fcos setup 

### ISSUE THREAD

**Issue by milan-dikkumburage** [openshift/okd#257]
we are trying install okd 4.4 cluster on Digital Ocean.
Following the https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html documentation 

But we stuck into the step of bootstrap of fcos step. It seems that we setup the https server to download the raw image and verify the connectivity. The connection works fine. But after we provide the kernel edit steps mentioned in the docs and we noticed it was not downloading the fcos raw image. any idea on this ? 

Note:- we are using latest fcos version .

**Comment by milan-dikkumburage** [comment]
• received below connection refused ERROR
[root@linux home]# openshift-install --dir=installation_directory/ wait-for bootstrap-complete --log-level=info
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd4.mydomain:6443...
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get https://api.okd4.mydomain:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 138.197.159.183:6443: connect: connection refused

**Comment by kasunsjc** [comment]
We are trying this on digital ocean VMs. If anyone has prior experience add your feedback

**Comment by vrutkovs** [comment]
See https://docs.okd.io/latest/installing/installing-troubleshooting.html

**Comment by milan-dikkumburage** [comment]
Hi @vrutkovs Thanks . I followed the troubleshooting guidance .I noticed below error messages .Any idea on this ? 

![image](https://user-images.githubusercontent.com/35827824/87537879-fbdbf580-c6b8-11ea-945c-6448928c9bf9.png)

output:- 

[core@okd ~]$ ./openshift-install gather bootstrap --dir=installation_directory/ --bootstrap xxx.xxx.xxx.xx  --master xxx.xxx.xxx.xxx
INFO Pulling debug logs from the bootstrap machine 
FATAL failed to run remote command: Process exited with status 127 


![image](https://user-images.githubusercontent.com/35827824/87538036-38a7ec80-c6b9-11ea-92df-5820b92d24c5.png)

output:-

No result showing 

core@bootstrap ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Wed 2020-07-15 05:43:23 UTC. --

![image](https://user-images.githubusercontent.com/35827824/87538132-5aa16f00-c6b9-11ea-8d88-65fb2aa65123.png)

output:-

![image](https://user-images.githubusercontent.com/35827824/87538200-79076a80-c6b9-11ea-84a1-ca489e859e12.png)


![image](https://user-images.githubusercontent.com/35827824/87538303-a2c09180-c6b9-11ea-9a52-1fac74b7d930.png)

output:- 

![image](https://user-images.githubusercontent.com/35827824/87538392-c257ba00-c6b9-11ea-817b-d687f063eac3.png)

**Comment by milan-dikkumburage** [comment]
Please find the attach .openshift_install_state.json file . 
[openshift_install_state.zip](https://github.com/openshift/okd/files/4932573/openshift_install_state.zip)

**Comment by milan-dikkumburage** [comment]
log bundle doesn't seem to be generated .we are getting below error while executing this command

[core@okd ~]$ ./openshift-install gather bootstrap --dir=installation_directory/ --bootstrap xxx.xxx.xxx.xxx --master xxx.xxx.xxx.xxx
INFO Pulling debug logs from the bootstrap machine 
FATAL failed to run remote command: Process exited with status 127

**Comment by vrutkovs** [comment]
Interesting, try https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-manually-gathering-logs-with-SSH_installing-troubleshooting?

My bad, I mistakenly requested `.openshift_install.json` while we needed `.openshift_install.log` - https://docs.okd.io/latest/installing/installing-troubleshooting.html#installing-getting-debug-information_installing-troubleshooting

**Comment by milan-dikkumburage** [comment]
Hi @vrutkovs . find the attach .openshift_install.log 
[openshift_install.log](https://github.com/openshift/okd/files/4932736/openshift_install.log)

**Comment by milan-dikkumburage** [comment]
I tried https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-manually-gathering-logs-with-SSH_installing-troubleshooting this .But not logs result displaying . 

[core@bootstrap ~]$  journalctl -b -f -u bootkube.service
-- Logs begin at Wed 2020-07-15 05:43:23 UTC. --

**Comment by vrutkovs** [comment]
You're using `OpenShift Installer 4.4.0-0.okd-2020-04-21-163702-beta4`, which is 3 month old. There's been multiple fixes releases since that

Please remove the install directory (including `.openshift_install*` files), get the installer from [GA build](https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.5.0-0.okd-2020-07-14-153706-ga) and start from scratch.

**Comment by milan-dikkumburage** [comment]
Thanks @vrutkovs  . I'll check it

**Comment by milan-dikkumburage** [comment]
Hi @vrothberg  I tried with GA build but still getting below terraform error. I have attached .openshift_install.log file .

![image](https://user-images.githubusercontent.com/35827824/87774341-083f8a00-c842-11ea-8854-0377a8abad30.png)
[openshift_install.log](https://github.com/openshift/okd/files/4937021/openshift_install.log)

**Comment by vrothberg** [comment]
I think @vrutkovs can help :)

**Comment by vrutkovs** [comment]
Could you also attach your `install-config.yaml`?

**Comment by milan-dikkumburage** [comment]
find the attach install-config.yaml file . 
[install-config.zip](https://github.com/openshift/okd/files/4937281/install-config.zip)

**Comment by vrutkovs** [comment]
Right. You shouldn't be using `openshift-install create cluster`, use `create ignition-configs`.

See https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-generate-k8s-manifest-ignition_installing-bare-metal

**Comment by milan-dikkumburage** [comment]
I followed create ignition-configs way . 
![image](https://user-images.githubusercontent.com/35827824/87779296-36c16300-c84a-11ea-9982-aa6a6b34edcb.png)

**Comment by rajith77** [comment]
> Right. You shouldn't be using `openshift-install create cluster`, use `create ignition-configs`.
> 
> See https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-generate-k8s-manifest-ignition_installing-bare-metal

Looks like even after following that step, they are hititng the same error.

**Comment by milan-dikkumburage** [comment]
Issues are resolved .Followed the @dustymabe okd installation steps and installed the okd cluster.   https://dustymabe.com/2020/08/13/openshift-okd-on-fedora-coreos-on-digitalocean-part-1-deployment/  . Thanks @dustymabe for the support given. and thanks @vrutkovs for checking the issue.
