### ISSUE TITLE
FCOS network interface is changing from ens192 to etho after the reboot

### ISSUE THREAD

**Issue by sredd128** [openshift/okd#261]
**Describe the bug**
FCOS network interface is changing from ens192 to eth0 after the reboot

when we booted the bootstrap machine, it started well and and we are able to login to bootstrap machine with our SSH key Auth. 

after this step 
 journalctl -b -f -u release-image.service -u bootkube.service
-- Logs begin at Wed 2020-07-15 21:47:26 UTC. --
Jul 15 21:47:33 localhost systemd[1]: Starting Download the OpenShift Release Image...
Jul 15 21:47:33 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1128]: Pulling quay.io/openshift/okd@sha256:4195c00b498bff923889ae3a6f855d4b05ed05a4c5d2e7e0563f52b18b224e17...
Jul 15 21:48:30 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1145]: 590306fa912c13261b435f96703438e0604fbeebce19014c1cb49d12d3c56ef5
Jul 15 21:49:12 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1664]: Failed to enable unit: Unit file gcp-routes.service does not exist.
Jul 15 21:49:12 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1666]: I0715 21:49:12.277301    1666 rpm-ostree.go:368] Running captured: rpm-ostree status --json
Jul 15 21:49:14 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1666]: I0715 21:49:14.238327    1666 rpm-ostree.go:161] Current origin is not custom
Jul 15 21:49:14 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1666]: I0715 21:49:14.238742    1666 run.go:16] Running: podman pull -q quay.io/openshift/okd-content@sha256:9847a6d9adee79c36fb0b1c02f086e1f5fff8bd4d8b84bb669d6afd3bdd4eea2

machine rebooted it self and then after we are not able to login to machine any more.  ( error from console is attached ) 

**Version**
openshift-install version 
openshift-install 4.5.0-0.okd-2020-07-12-134038-rc
built from commit 290e3b1de6096ecef2133fb071ff3a71c9c78594
release image quay.io/openshift/okd@sha256:9045ca92e8600577d64f8a77a1272a381ba74f35d4ebca1d7749d5552129610a

**How reproducible**
100% 

**Log bundle**
![Screen Shot 2020-07-16 at 3 32 15 AM](https://user-images.githubusercontent.com/61799588/87605789-180e7f80-c717-11ea-9130-3accc4b9ce05.png)

**Comment by vrutkovs** [comment]
>Jul 15 21:47:33 bootstrap.origindev.gbt.gbtad.com release-image-download.sh[1128]: Pulling quay.io/openshift/okd@sha256:4195c00b498bff923889ae3a6f855d4b05ed05a4c5d2e7e0563f52b18b224e17...

This image points to beta6. Please attach the log bundle

**Comment by sredd128** [comment]
We had same issue with both beta6 and rc

**Comment by sredd128** [comment]
we are unable to login to server. to generate a log-bundle

**Comment by vrutkovs** [comment]
See https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-manually-gathering-logs-with-SSH_installing-troubleshooting

**Comment by sredd128** [comment]
Issue is fixed. thanks
