### ISSUE TITLE
Cluster Deployment on OpenStack fails with "configmap kube-cloud-config not found"

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#269]
**Describe the bug**
When attempting to bootstrap an OKD 4.5(GA) cluster on OpenStack Ussuri, everything seems to be working fine, all of the nodes come up, COs start to become available but machine-config fails to come up due to the following error:
```
ERROR Cluster operator machine-config Degraded is True with RenderConfigFailed: Unable to apply 4.5.0-0.okd-2020-07-14-153706-ga: openshift-config-managed/kube-cloud-config configmap is required on platform OpenStack but not found: configmap "kube-cloud-config" not found 
```

**Version**
4.5.0-0.okd-2020-07-14-153706
OpenStack IPI (Ussuri running on RDO / CentOS 8)

**How reproducible**
100% reproducible, every time I try to run this install, I get the same MCO problem. 

**Log bundle**
https://drive.google.com/file/d/1biNjnTT8z0EaHha00VZB5Icl_njl_SBp/view?usp=sharing

**Comment by vrutkovs** [comment]
Seems to be requiring faster disks:

Bootkube log:
>"openshift-config-secret-pull-secret.yaml": failed to get secrets.v1./pull-secret -n openshift-config: etcdserver: request timed out

etcd member:
>2020-07-17 20:07:52.273304 W | wal: sync duration of 2.462785043s, expected less than 1s
2020-07-17 20:07:52.273483 W | etcdserver: read-only range request "key:\"/kubernetes.io/health\" " with result "range_response_count:0 size:5" took too long (3.562499584s) to execute
2020-07-17 20:07:52.273589 W | etcdserver: read-only range request "key:\"/kubernetes.io/deployments/openshift-cluster-version/cluster-version-operator\" " with result "range_response_count:1 size:4313" took too long (3.886438299s) to execute

**Comment by jdhirst1** [comment]
Hmm, that doesn't surprise me haha; I'll add another SSD to the ceph backend and try again. 

Do you think rbd will be fine for running OKD masters?

**Comment by vrutkovs** [comment]
As long as it has sufficient IO for etcd would do. In short, it needs 10ms tops to write to disk (including network roundtrip), otherwise it would attempt to elect a faster leader and things will go south

See [this post](https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd) on how to verify its fast enough.

**Comment by jdhirst1** [comment]
Ah, it turns out it likely wouldn't be fast enough, so I setup a second cinder storage backend using SSD on LVM and have configured openshift-installer to use it. 

This can be closed, thanks for the help!
