### ISSUE TITLE
MCO Degraded on OpenStack

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#272]
**Describe the bug**
When deploying OKD 4.5 GA on OpenStack, MCO becomes degraded due to the following message:
```
    Message:               Unable to apply 4.5.0-0.okd-2020-07-14-153706-ga: openshift-config-managed/kube-cloud-config configmap is required on platform OpenStack but not found: configmap "kube-cloud-config" not found
```

**Version**
4.5.0-0.okd-2020-07-14-153706

**How reproducible**
100%, I have tried 3-master and single master clusters to ensure there is no performance bottleneck issues on the system. The instances have a dedicated SSD to avoid issues with etcd thrashing the disk.

**Log bundle**
https://drive.google.com/file/d/1esb-wcvV5DzWV4A5C6jmWUn7mf24kvL7/view?usp=sharing

**Comment by vrutkovs** [comment]
121 "operation ... took too long" warnings from etcd, `authentication-operator-6d49d97966-wqwr6` crashloops due to etcd timeouts most likely

**Comment by bshephar** [comment]
Hey @jdhirst1. Are you able to provide some insights about the ephemeral disks the OKD VM's are using? ie, are they using Ceph? And are the disks SAS or SSD?

You can create another VM and test the IO is sufficient for etcd with a command like this:
```
mkdir testmyio
fio --rw=write --ioengine=sync --fdatasync=1 --directory=testmyio --size=22m --bs=2300 --name=testmyio
```

There is some information here about how to read the results and what outcome you're looking for:
https://prog.world/is-storage-speed-suitable-for-etcd-ask-fio/

**Comment by jdhirst1** [comment]
@bshephar I have a dedicated SSD assigned for my OKD cluster on this OpenStack node, it is simply an LVM cinder backend which is only used for the OKD cluster. I spun up a CentOS 8 instance and ran the i/o test, which produced these results:

```
[centos@iotest ~]$ fio --rw=write --ioengine=sync --fdatasync=1 --directory=testmyio --size=22m --bs=2300 --name=testmyio
testmyio: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
fio-3.7
Starting 1 process
Jobs: 1 (f=1): [W(1)][100.0%][r=0KiB/s,w=2192KiB/s][r=0,w=975 IOPS][eta 00m:00s]
testmyio: (groupid=0, jobs=1): err= 0: pid=14432: Wed Jul 22 06:56:19 2020
  write: IOPS=934, BW=2099KiB/s (2149kB/s)(21.0MiB/10732msec)
    clat (nsec): min=1793, max=2952.6k, avg=141065.40, stdev=126936.67
     lat (usec): min=2, max=2952, avg=141.42, stdev=126.93
    clat percentiles (usec):
     |  1.00th=[    3],  5.00th=[    4], 10.00th=[    4], 20.00th=[    5],
     | 30.00th=[    6], 40.00th=[    7], 50.00th=[  223], 60.00th=[  231],
     | 70.00th=[  237], 80.00th=[  245], 90.00th=[  260], 95.00th=[  285],
     | 99.00th=[  343], 99.50th=[  359], 99.90th=[  553], 99.95th=[  660],
     | 99.99th=[ 1467]
   bw (  KiB/s): min= 1972, max= 2205, per=100.00%, avg=2100.43, stdev=73.69, samples=21
   iops        : min=  878, max=  982, avg=935.33, stdev=32.84, samples=21
  lat (usec)   : 2=0.21%, 4=11.88%, 10=31.22%, 20=0.51%, 50=0.03%
  lat (usec)   : 250=41.29%, 500=14.73%, 750=0.10%, 1000=0.01%
  lat (msec)   : 2=0.02%, 4=0.01%
  fsync/fdatasync/sync_file_range:
    sync (usec): min=832, max=8620, avg=925.73, stdev=181.89
    sync percentiles (usec):
     |  1.00th=[  848],  5.00th=[  857], 10.00th=[  865], 20.00th=[  881],
     | 30.00th=[  889], 40.00th=[  898], 50.00th=[  906], 60.00th=[  914],
     | 70.00th=[  930], 80.00th=[  963], 90.00th=[  996], 95.00th=[ 1012],
     | 99.00th=[ 1106], 99.50th=[ 1385], 99.90th=[ 3425], 99.95th=[ 5669],
     | 99.99th=[ 7963]
  cpu          : usr=0.63%, sys=2.36%, ctx=41351, majf=0, minf=13
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,10029,0,0 short=10029,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=2099KiB/s (2149kB/s), 2099KiB/s-2099KiB/s (2149kB/s-2149kB/s), io=21.0MiB (23.1MB), run=10732-10732msec

Disk stats (read/write):
  vda: ios=5593/19919, merge=0/0, ticks=1310/9060, in_queue=110, util=98.45%
```
From what I read on that page, the disk performance looks adequate. Is it possible to increase the etcd timeout value to avoid this? This is not a production environment.

Another question is, can I specify which volume type the bootstrap node uses? If so, I can relieve pressure on the SSD which runs the master node(s). Bootstrap seems to run fine on ceph so that can be offloaded in theory but I can't find where I would specify that in my install-config.yaml.

**Comment by jdhirst1** [comment]
Also, another idea; is it possible to attach a block volume to the node specifically for the purpose of etcd? The rest of the master node could be causing disk thrashing and dropping that disk latency past the 10ms mark; however if the system had a dedicated volume specifically for etcd, this would solve the issue.

**Comment by bshephar** [comment]
Hey again. Yeah, that disk speed seems like it should be fine. 

At the moment, there is nothing in the install-config.yaml file to specify the volume types. The IPI is fairly prescriptive in that regard. You could definitely do something custom using a UPI deployment though which would allow you to be more specific about how you deploy it.

Just to clarify about the storage. Normally, when you deploy these VM's, the ephemeral disks wont be stored on Cinder volumes. They would normally be located at /var/lib/nova/instances on the Compute nodes they are running on. (You can verify this using virsh dumpxml instance-NUMBER on the compute node and see where the disk is located). If you have configured it to store all ephemeral disks as Cinder volumes. Then the LVM backed Cinder volumes will be presented as iscsi targets from the Controllers (which ever one is running the cinder-volume service). In that case, it could be possible that network latency or MTU could be a potential bottleneck and cause the issue. Generally, we would use MTU 9000 and have a dedicated network assigned for Storage to avoid that kind of issue.

And regarding tuning etcd, unfortunately, I'm not the right person to answer questions about tuning and changing timeout values. But hopefully someone else can chime in here and offer some suggestions regarding that if it's possible.

**Comment by vrutkovs** [comment]
>Also, another idea; is it possible to attach a block volume to the node specifically for the purpose of etcd?

I don't think we support additional disks in machine API yet :(

>In that case, it could be possible that network latency or MTU could be a potential bottleneck and cause the issue

This seems to be reproducible in a single master, so its unlikely to be network.

**Comment by jdhirst1** [comment]
Thanks guys for all the help!

As for the reasoning for using cinder volumes; it is simply because I have the ephemeral storage on the hosts configured to use ceph, so it was an easy option to configure OpenStack to use volumes and specify the volumeType. I may switch the dedicated SSD to map to /var/lib/nova/instances instead and see how that affects things. 

I was eventually able to get it to work only when all nodes are connected to local block devices (over iscsi) rather than on different hosts. This was fine for a single-node cluster, however I haven't tested it on a multi-node cluster. 

I will try with a 3-node cluster and let you know what happens :slightly_smiling_face:
