### ISSUE TITLE
4.5 bare-metal bootstrap node unable to start machine-config-controller container 

### ISSUE THREAD

**Issue by rmharwood** [openshift/okd#273]
**Describe the bug**
Attempting to install a new OKD 4.5 GA cluster and not getting beyond configuring the bootstrap node. Install gets part way but seemingly gets stuck trying to start the machine-config-controller container.
In particular:
`skipping: failed to "StartContainer" for "machine-config-controller" with CrashLoopBackOff: "back-off 5m0s restarting failed container=machine-config-controller pod=bootstrap-machine-config-operator...
`

**Version**
 4.5.0-0.okd-2020-07-14-153706-ga
IPI install on self-provisioned VMware VMs (*not* the vSphere install method)

**How reproducible**
Reproducible on all (current) FCOS bare-metal images : v 32.20200629.3.0 (stable), v 32.20200715.2.2 (testing), v 32.20200715.1.1 (next)

**Log bundle**
https://drive.google.com/drive/folders/1uCHBTT0dFnUC2NCZOfMILqlZnC59eKnK

**Comment by vrutkovs** [comment]
Installer from beta4 used

**Comment by rmharwood** [comment]
Closing this. Indeed, the wrong installer got used. Thanks!
