### ISSUE TITLE
OKD 4.5.0 IPI installation fails on Vmware vSphere

### ISSUE THREAD

**Issue by mcharan** [openshift/okd#280]
**Describe the bug**
We tried `openshift-install create cluster --log-level=info` over two different VMWare 6.70u3 clusters, and the installation fails during initial resources creation with the following error:

```
INFO Creating infrastructure resources...
ERROR

ERROR Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: cannot change the value of "thin_provisioned" - (old: true new: false)
ERROR
ERROR   on ../../../../../tmp/openshift-install-888008500/bootstrap/main.tf line 1, in resource "vsphere_virtual_machine" "vm":
ERROR    1: resource "vsphere_virtual_machine" "vm" {
```

The same error occurs for every resource - bootstrap and master nodes.
Already tried it with a specific role created as described in the "Required vCenter account privileges" doc, as well with the global Administrator role, and got the same error.

**Version**
4.5.0-0.okd-2020-07-14-153706
IPI Install on vSphere

**How reproducible**
100% of the installation attempts

**Log bundle**
openshift_install.log: https://drive.google.com/file/d/1LvgcOyPKCbV3QUl4iDi7oAV2CY3Aw7i9/view?usp=sharing

**Comment by mcharan** [comment]
Look like the same issue as #284, apparently more a Terraform problem than OKD. Look like the same issue as #284, apparently more a Terraform problem than OKD.

**Comment by vrutkovs** [comment]
I'll close this one in favor of #284 as it has more info
