### ISSUE TITLE
OKD 4.5:  scaled machineset down, scaled machineset up:  machine does not have valid node reference

### ISSUE THREAD

**Issue by brianotte** [openshift/okd#281]
**Describe the bug**
Scaling up machineset does not work in AWS, as server is provisioned in AWS, but not created as node.

oc get machines foo-worker-us-west-2a-vp27j
NAME                                 PHASE         TYPE         REGION      ZONE         AGE
foo-worker-us-west-2a-vp27j   Provisioned   i3.4xlarge   us-west-2   us-west-2a   6h3m

oc get machineset foo-worker-us-west-2a
NAME                           DESIRED   CURRENT   READY   AVAILABLE   AGE
foo-worker-us-west-2a   1         1                             20d

Error received:
machine foo-worker-us-west-2a-vp27j does not have valid node reference

Rational for scaling down / scaling up
Modified machineset adding this and wanted to test and have nodes reflect new label:

    spec:
      metadata:
        labels:
          key: value

1) scaled machineset down
2) scaled machineset up
3) server was provisioned in AWS
4) MachineWithoutValidNode:  machine NAME_HERE does not have valid node reference

**Version**
oc version
Client Version: 4.5.0-0.okd-2020-07-14-153706-ga
Server Version: 4.5.0-0.okd-2020-07-14-153706-ga
Kubernetes Version: v1.18.3

**How reproducible**
100%:  I have reverted and tried with original machineset and now with the changes.

**Log bundle**
It is 2.8GB -- but I can provide any / all information as requested.

**Comment by brianotte** [comment]
In AWS for the console of the provisioned system I am seeing the following:

[   19.002005] ignition[602]: GET result: OK
[   19.007708] systemd[1]: ignition-fetch.service: Main process exited, code=exited, status=1/FAILURE
[   19.019026] ignition[602]: failed to fetch config: unsupported config version
status ignition-fetch.service' for details.
[   19.025982] systemd[1]: ignition-fetch.service: Failed with result 'exit-code'.
 [0;1;38;5;185mDEPEND [0m] Dependency failed for  [0;1;39mIgnition Complete [0m.
[[   19.036578] ignition[602]: failed to acquire config: unsupported config version

**Comment by vrutkovs** [comment]
>[ 19.019026] ignition[602]: failed to fetch config: unsupported config version

Which AMI is this machineset using?

**Comment by brianotte** [comment]
NOTE:  When this issue was opened (2020/07/28) I was running 4.5.0-0.okd-2020-07-14-153706-ga.  I scaled down the machineset and upgraded cluster to 4.5.0-0.okd-2020-07-29-070316 to attempt to remediate.

However, that did not help.

To answer your question -- here is the answer

      providerSpec:
        value:
          ami:
            id: ami-03cbca3622d708c92

**Comment by vrutkovs** [comment]
Oh, hmm, that would mean nothing, as OKD clones the initial image, not using it as it.

Could you try replacing this with AMI from [official site](https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable) and attempting the scaling again?

**Comment by brianotte** [comment]
oc scale --replicas=0 machineset CLUSTER_NAME-worker-us-west-2a -n openshift-machine-api

Modifying to us-west-2 ami-0f2c8d6558d08dd83 as the follows

      providerSpec:
        value:
          ami:
            id: ami-0f2c8d6558d08dd83

As extracted from this command's output:
oc get machineset CLUSTER_NAME-worker-us-west-2a -o yaml

oc scale --replicas=1 machineset CLUSTER_NAME-worker-us-west-2a -n openshift-machine-api

Will report results as soon as known....

**Comment by brianotte** [comment]
oc get node --selector=node-role.kubernetes.io/worker=
NAME                                          STATUS   ROLES    AGE   VERSION
ip-FOO.us-west-2.compute.internal   Ready    worker   92s   v1.18.3

o.k. that worked  -- I can scale a node.

Is this something that I need to change for all machine-sets I have as none scale?
Is this a bug somewhere or why did the AMI's not automatically get changed?
Did I miss something?

Please let me know.

Thank you.

**Comment by vrutkovs** [comment]
>Is this something that I need to change for all machinesets I have as none scale?

Yes.

> Is this a bug somewhere or why did the AMI's not automatically get changed?

AMIs don't need to change, the OS would autoupdate itself from an older image.
The question is why AMI in machineset has been incorrect - could you collect more info about `ami-03cbca3622d708c92`?

**Comment by brianotte** [comment]
I have 4 machineset defined and all 4 had referenced ami-03cbca3622d708c92.  This was as created from a vanilla openshift-install.

**Comment by brianotte** [comment]
How could have I determined that the AMI was not available or the incorrect version?  I could find no indication what was wrong.  Is there a oc events or oc logs that I could have referenced to determine this issue?

**Comment by vrutkovs** [comment]
> This was as created from a vanilla openshift-install.

That's very odd. Are master machines running from this AMI? Was it a clean GA or you did upgrade to GA later?

**Comment by brianotte** [comment]
This was upgraded from previous version. Here are the completed cluster upgrade versions:

4.5.0-0.okd-2020-07-29-070316
4.5.0-0.okd-2020-07-14-153706-ga
4.5.0-0.okd-2020-06-29-110348-beta6
4.4.0-0.okd-2020-05-23-055148-beta5

Information captured from:  oc get clusterversion -o json|jq ".items[0].status.history"

**Comment by brianotte** [comment]
I checked all 3 masters and they all have the following ami:  ami-03cbca3622d708c92

Information captured from:  oc get machine CLUSTER_NAME-master-[012] -o yaml | grep -i ami

I am not sure the mechanism / procedure to change the master machine AMI as there is no machineset in openshift-machine-api project for master.

Is there a similar procedure to change the master AMI to ami-0f2c8d6558d08dd83 as was done for the worker nodes?
Is that recommended?
Is there any additional information I can provide to determine what occurred?

**Comment by vrutkovs** [comment]
Ooh, that explains it. `beta5` image is using Ignition 3.0 and won't accept Ignition 3.1, served by machine-config-server on GA.

Masters are not controlled by MachineSets, so these can't be scaled just yet - its not necessary to replace amiID there.

Seems this would affect only pre-beta5 updated clusters - and the workaround would be specifying amiID in the worker MachineSet once.

**Comment by brianotte** [comment]
o.k.  Thank you for the explanation and the quick responses.  

SYNOPSIS:  The 2 clusters I have -- the worker machinesets have been modified with the new AMI and scaled down and scaled backup referencing the AMI specified.  All is well

Thank you again.

**Comment by vrutkovs** [comment]
This issue (bootimages get outdated after multiple updates) would be addressed in https://github.com/openshift/enhancements/pull/201
