### ISSUE TITLE
How to change the update URL?

### ISSUE THREAD

**Issue by rtsisyk** [openshift/okd#282]
**Describe the bug**

I'm running OKD 4.5 with restricted network connection. `oc adm upgrade` tries to pull https://origin-release.svc.ci.openshift.org/graph page for the new versions. Is it possible to run local version of service? I expacted that OKD will check for the new versions directly in the registry (which I mirrored according to instruction).

**Version**

4.5.0-0.okd-2020-07-14-153706-ga

**How reproducible**

Disable the Internet connection on nodes:

```
oc adm upgrade

Error while reconciling 4.5.0-0.okd-2020-07-14-153706-ga: an unknown error has occurred: MultipleErrors

warning: Cannot display available updates:
  Reason: RemoteFailed
  Message: Unable to retrieve available updates: Get https://origin-release.svc.ci.openshift.org/graph?arch=amd64&channel=stable-4&id=56ef9a42-8840-460e-a41f-5b69752cf202&version=4.5.0-0.okd-2020-07-14-153706-ga: dial tcp 35.196.103.194:443: connect: connection timed out
```

**Comment by rtsisyk** [comment]
A related question. Is it possible to override image for openshift-cluster-version/cluster-version-operator?

```
Back-off pulling image "registry.svc.ci.openshift.org/origin/release@sha256:a2d5ef5e3884b125761a5fae1f7e89748eb6880d8ef5c7da4d11a1f661251532"
```

I already mapped registries in my containers/registries.conf:

```
          [[registry]]
            prefix = ""
            location = "quay.io/openshift/okd"
            mirror-by-digest-only = true
            [[registry.mirror]]
              location = "my-local-docker/openshift/okd"
              # insecure = true

          [[registry]]
            prefix = ""
            location = "quay.io/openshift/okd-content"
            mirror-by-digest-only = true
            [[registry.mirror]]
              location = "my-local-docker/openshift/okd"
              # insecure = true
```

**Comment by vrutkovs** [comment]
>oc adm upgrade tries to pull origin-release.svc.ci.openshift.org/graph page for the new versions. Is it possible to run local version of service?

Yes, however its not trivial to setup. See [Cincinnati](https://github.com/openshift/cincinnati/blob/master/docs/user/running-cincinnati.md) for tips how to get started (we don't have a full-blown guide just yet, sorry)

>I expacted that OKD will check for the new versions directly in the registry (which I mirrored according to instruction).

There are two part for upgrade here:
* an external service which serves the upgrade graph - release-controller. All it does is serve a JSON with "nodes" and "edges" on `/graph?arch=<server arch>&channel=<channel name>&id=<cluster id>&version=<current cluster version>`. It could as well be a static JSON hosted locally.
* CVO in cluster would parse that json, present upgrade options to user and start upgrade when version is selected.

So locally the options are:
* proxy to origin-release
* `oc adm update --allow-explicit-upgrade --to-image=` to override the graph settings
* hosting a static JSON file and updating CVO's `upstream`
* hosting full Cincinnati, which would automatically scan available release images and build a graph based on secondary metadata

**Comment by vrutkovs** [comment]
>Is it possible to override image for openshift-cluster-version/cluster-version-operator?

No, any image override means you'd create a new release payload.
Not sure why mirroring be setup for `quay.io` for a cluster using images from `registry.svc.ci.openshift.org`

**Comment by vrutkovs** [comment]
Closing as that's not an issue but rather a question
