### ISSUE TITLE
No "Kube Descheduler Operator" in OperatorHub for OKD despite its reference in the doc?

### ISSUE THREAD

**Issue by titou10titou10** [openshift/okd#283]
It seems that there is no **"Kube Descheduler Operator"** as stated in the official latest OKD doc: https://docs.okd.io/latest/nodes/scheduling/nodes-descheduler.html

This operator exists in OCP v4.4.x+ but not in the latest version of OKD

Who's wrong? the documentation or the OperatorHub connected to OKD?    
Is there an official "Descheduler" available with OKD? If not the doc should be fixed. If yes then it is not "visible" in the latest version of OKD

OKD  version:  **4.5.0-0.okd-2020-07-29-070316**

**Comment by vrutkovs** [comment]
Desheduler is being installed from OperatorHub. There is no community descheduler release available yet, so you might want to add Red Hat operators - see "[How do I enable Red Hat operators?](https://github.com/openshift/okd/blob/master/FAQ.md#how-can-i-enable-the-non-community-red-hat-operators)" section of FAQ

**Comment by titou10titou10** [comment]
thanks @vrutkovs ! it works
You closed this ticket: fine.
But IMHO the doc should indicate that the "Kube Descheduler Operator" is not visible after a fresh install of OKD because the RH CatalogSource is not active by default -> https://docs.okd.io/latest/nodes/scheduling/nodes-descheduler.html
If you just follow the doc, this is obciously not obvious... and I would not have solve the problem without that ticket
Adding a few line in the doc with the link you provided above would help a lot IMHO

**Comment by vrutkovs** [comment]
OKD can't control the contents of operator hub. By default we'll always use Community source only (so that OKD could be installed without additional pull secrets).

I think the best way to solve this is to have Descheduler published in community operators - I suggest to start with a ticket at https://github.com/operator-framework/community-operators

**Comment by vrutkovs** [comment]
We can convert this into "remove Descheduler from OKD docs", but that wouldn't be a good long-term solution

**Comment by titou10titou10** [comment]
I understand the point but the fact is that if you just follow the current doc for OKD, it just does now work without the extra step you gave on here. Stating in the doc that this extra step is necessary because there is currently no "official" community descheduler is valid too IMHO
Anyway, your choice and thanks again for your help. Have a good day
