### ISSUE TITLE
RFE: vSphere thin provisioning

### ISSUE THREAD

**Issue by bdobsonca** [openshift/okd#284]
**Describe the bug**

Trying to launch an OKD 4 cluster via an RHEL8 deployment box and receiving terraform errors to ESXi 6.5U3 in regard to the thin provision of the disk.

**Version**

openshift-install-linux-4.5.0-0.okd-2020-07-14-153706-ga

**How reproducible**

I am able to reproduce this 100% of the time using the administrator@vsphere.local user.

`ERROR Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: cannot change the value of "thin_provisioned" - (old: true new: false) 
ERROR                                              
ERROR   on ../tmp/openshift-install-252287718/master/main.tf line 1, in resource "vsphere_virtual_machine" "vm": 
ERROR    1: resource "vsphere_virtual_machine" "vm" { `

**Comment by vrutkovs** [comment]
Currently installer doesn't support thin provisioning.

This is tracked in https://issues.redhat.com/browse/RFE-1048

**Comment by bdobsonca** [comment]
As this is what appears to be the default behaviour of the installer to attempt to do this, can this be disabled in the interim with a flag or would it require just manually creating the virtual machines?

**Comment by bdobsonca** [comment]
Sorry, also it appears I cannot view that issue it says no permission.

**Comment by vrutkovs** [comment]
I think you'd have to create VMs manually at this point, yes

**Comment by magick93** [comment]
> This is tracked in https://issues.redhat.com/browse/RFE-1048

Is it possible to make this publicly viewable?

**Comment by bdobsonca** [comment]
This issue is still ongoing as of openshift-client-linux-4.5.0-0.okd-2020-09-18-202631.tar.gz

Can the issue please at least be explained here? Is there any plan to correct this long standing issue.

**Comment by LorbusChris** [comment]
@bdobsonca this is an RFE and not a bug. The Jira card is currently not prioritized. Once that changes I'll post an update here.

**Comment by aladrocMatiner** [comment]
Still experiencing the same problems on openshift... thin provision suppose to be available on installer provisioned install and it simply ignores the thing... for more info refer to https://www.reddit.com/r/openshift/comments/znso7l/ipi_install_disktype_on_installconfigyaml_thin_vs/
