### ISSUE TITLE
okd cluster failed after rebooting cluster virtual machines 

### ISSUE THREAD

**Issue by 5254565852** [openshift/okd#285]
**Describe the bug**

Hi guys
I installed an okd latest cluster on VMware vsphere but when turned off my cluster virtual machines for increase their resources and then power on them, I can't access to cluster. 
Please help me to return my cluster to healthy state
Thanks

**Comment by vrutkovs** [comment]
>I can't access to cluster

Can you access API? Can you ssh on the machines?

**Comment by 5254565852** [comment]
Thank you for reply
I can ssh to machines but no access to API.
Can i return my cluster to healthy state?

**Comment by vrutkovs** [comment]
Please collect additional information - https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-manually-gathering-logs-with-SSH_installing-troubleshooting

**Comment by 5254565852** [comment]
I collected requested information in attached files.
[master1-logs.txt](https://github.com/openshift/okd/files/5007380/master1-logs.txt)
[master0-logs.txt](https://github.com/openshift/okd/files/5007382/master0-logs.txt)
[master0-container-logs.txt](https://github.com/openshift/okd/files/5007384/master0-container-logs.txt)
[worker1-container-logs.txt](https://github.com/openshift/okd/files/5007385/worker1-container-logs.txt)
[worker1-logs.txt](https://github.com/openshift/okd/files/5007386/worker1-logs.txt)
[worker0-container-logs.txt](https://github.com/openshift/okd/files/5007387/worker0-container-logs.txt)
[worker0-logs.txt](https://github.com/openshift/okd/files/5007388/worker0-logs.txt)
[master2-container-logs.txt](https://github.com/openshift/okd/files/5007389/master2-container-logs.txt)
[master2-logs.txt](https://github.com/openshift/okd/files/5007390/master2-logs.txt)
[master1-container-logs.txt](https://github.com/openshift/okd/files/5007391/master1-container-logs.txt)

**Comment by 5254565852** [comment]
Can anyone help me?

**Comment by giatule** [comment]
I got the same issue that after the nodes are restarted, I can not login to the OKD by cli. 
The isssue happen with X509 certificate expired
"[core@api-int ~]$ oc login https://api.lab.okd.local:6443 --loglevel 6
I0825 17:00:40.197807    3589 round_trippers.go:443] HEAD https://api.lab.okd.lo                                                                                                                                                             cal:6443/  in 46 milliseconds
The server is using an invalid certificate: x509: certificate has expired or is                                                                                                                                                              not yet valid
You can bypass the certificate check, but any data you send to the server could                                                                                                                                                              be intercepted by others.
Use insecure connections? (y/n): y

I0825 17:01:27.286890    3589 round_trippers.go:443] HEAD https://api.lab.okd.local:6443/ 403 Forbidden in 12 millise                                                                                                                        conds
I0825 17:01:27.286959    3589 request_token.go:86] GSSAPI Enabled
I0825 17:01:27.289495    3589 round_trippers.go:443] GET https://api.lab.okd.local:6443/.well-known/oauth-authorizati                                                                                                                        on-server 200 OK in 2 milliseconds
I0825 17:01:27.293804    3589 round_trippers.go:443] GET https://api.lab.okd.local:6443/api/v1/namespaces/openshift/c                                                                                                                        onfigmaps/motd 403 Forbidden in 1 milliseconds
I0825 17:01:27.294923    3589 helpers.go:234] Connection error: Head https://oauth-openshift.apps.lab.okd.local: EOF
F0825 17:01:27.294984    3589 helpers.go:115] Unable to connect to the server: EOF"

**Comment by giatule** [comment]
I checked the SSL to connect to OKD api
` openssl s_client -connect api.lab.okd.local:22623 | openssl x509 -noout -text`

depth=0 CN = api-int.lab.okd.local
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = api-int.lab.okd.local
verify error:num=21:unable to verify the first certificate
verify return:1
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4245825425964118263 (0x3aec33bac4e9b0f7)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: OU = openshift, CN = root-ca
        Validity
            **Not Before: Aug 23 01:53:29 2020 GMT
            Not After : Aug 21 01:53:31 2030 GMT**
        Subject: CN = api-int.lab.okd.local

**Comment by giatule** [comment]
> > I can't access to cluster
> 
> Can you access API? Can you ssh on the machines?

I can access to all node via ssh

**Comment by thisismsreddy** [comment]
@giatule  you're right, I've faced the same issue, I've powered on my cluster after a week, then OKD services not starting because of  isssue happen with X509 certificate expired. 

We have to approve the certificates then all services started. 

```
[root@helper ~]# oc get nodes
NAME                       STATUS     ROLES    AGE   VERSION
master0.ocp4.example.com   NotReady   master   10d   v1.20.0+5fbfd19-1046
worker0.ocp4.example.com   NotReady   worker   10d   v1.20.0+5fbfd19-1046



[root@helper ~]# oc get csr
NAME        AGE     SIGNERNAME                                    REQUESTOR                                                                   CONDITION
csr-fd8gx   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-fqq6s   14m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-k55sq   7m49s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-tqbch   14m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-w4kbp   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending

[root@helper ~]# oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs oc adm certificate approve
certificatesigningrequest.certificates.k8s.io/csr-fd8gx approved
certificatesigningrequest.certificates.k8s.io/csr-fqq6s approved
certificatesigningrequest.certificates.k8s.io/csr-k55sq approved
certificatesigningrequest.certificates.k8s.io/csr-tqbch approved
certificatesigningrequest.certificates.k8s.io/csr-w4kbp approved
[root@helper ~]# oc get csr
NAME        AGE     SIGNERNAME                                    REQUESTOR                                                                   CONDITION
csr-fd8gx   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-fqq6s   14m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-k55sq   8m16s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-tqbch   14m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-w4kbp   23m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued



[root@helper ~]# oc get nodes
NAME                       STATUS   ROLES    AGE   VERSION
master0.ocp4.example.com   Ready    master   10d   v1.20.0+5fbfd19-1046
worker0.ocp4.example.com   Ready    worker   10d   v1.20.0+5fbfd19-1046


```
