### ISSUE TITLE
failed waiting for Kubernetes API

### ISSUE THREAD

**Issue by vzaharov** [openshift/okd#291]
**Describe the bug**
Cluster installation always fail. Please advise.
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get https://api.okd.corp.....:6443/apis/config.openshift.io/v1/clusteroperators: EOF
FATAL failed waiting for Kubernetes API: Get https://api.okd.corp....:6443/version?timeout=32s: EOF
on master console following output
...ignition[518]: GET https://api-int.okd.corp...:22623/config/master" : EOF

**Version**
4.5.0-0.okd-2020-07-29-070316, UPI on baremetal

**How reproducible**
100%, using howto guide by Craig Robinson at https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee
openshift-install create manifests --dir=/install_dir/
sed -i 's/mastersSchedulable: true/mastersSchedulable: False/' /install_dir/manifests/cluster-scheduler-02-config.yml
openshift-install create ignition-configs --dir=/install_dir/
cp -R /install_dir/* /var/www/html/okd4/
chown -R apache:apache /var/www/html/
chmod -R 755 /var/www/html/
openshift-install --dir=/install_dir/ wait-for bootstrap-complete --log-level=info
after bootstrap ,master and workers boot, error about api-int is unreachable reported

**Log bundle**
[log-bundle-20200806141202.tar.gz](https://github.com/openshift/okd/files/5034457/log-bundle-20200806141202.tar.gz)

**Comment by vrutkovs** [comment]
```
Aug 06 10:35:26 okd4-bootstrap.corp.cellcom.co.il release-image-download.sh[1129]: Pulling quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3...
Aug 06 10:36:29 okd4-bootstrap.okd.corp.cellcom.co.il release-image-download.sh[1131]: Error: error pulling image "quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3": unable to pull quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3: unable to pull image: Error initializing source docker://quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp 34.198.42.182:443: i/o timeout
Aug 06 10:36:29 okd4-bootstrap.okd.corp.cellcom.co.il release-image-download.sh[1129]: Pull failed. Retrying quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3...
```
Are you using some kind of proxy?

**Comment by vzaharov** [comment]
you're right, its was proxy, now works like a charm. NOTABUG :-)
