### ISSUE TITLE
Installing logging-operator fails on OKD 4.5

### ISSUE THREAD

**Issue by paulherbosch** [openshift/okd#295]
**Describe the bug**
We are trying to install the logging-operator on a fresh OKD 4.5 install following the documentation found here:
https://docs.okd.io/latest/logging/cluster-logging-deploying.html

We can't find the elasticsearch operator, nor the openshift-operators-redhat namespace.
How can we install the logging operator on a fresh OKD 4.5 cluster?

Many thanks, Paul

**Version**
OpenShift Version
4.5.0-0.okd-2020-07-29-070316
Kubernetes Version
v1.18.3
Channel
stable-4

**Comment by vrutkovs** [comment]
Logging operator is not yet available in community operators set. You may need to [enable Red Hat operators](https://github.com/openshift/okd/blob/master/FAQ.md#how-can-i-enable-the-non-community-red-hat-operators) to get access to those (note, that you need pull secret from openshift.com/try for that)

**Comment by vrutkovs** [comment]
Keeping this open so that this would be noted in documentation

**Comment by kimausloos** [comment]
I'm curious, what is the situation license-wise in this case. Are you allowed to use the Red Hat registry while setting up OKD?

**Comment by vrutkovs** [comment]
Yes, the pull secret is allowed to be used with any product other than OCP - although you're limited to community support of course

**Comment by ibotty** [comment]
> Yes, the pull secret is allowed to be used with any product other than OCP.

Maybe I am missing something.  I thought that anything you need a pull secret with, is restricted to non-commercial use.  Can I use my developer's account pull secret to install operators on production deployments?

**Comment by vrutkovs** [comment]
> I thought that anything you need a pull secret with, is restricted to non-commercial use. Can I use my developer's account pull secret to install operators on production deployments?

Restrictions set by developer subscription apply as well, I don't see any controversy here

**Comment by ibotty** [comment]
So you are "allowed to use the Red Hat registry while setting up OKD", but only for non-commercial applications.

**Comment by LorbusChris** [comment]
Yes. Note that for the core OKD installation no valid pull secret is needed, and this restriction thus does not apply in that case.

However, if you use a pull-secret that you acquired through the free-of-charge developer license to pull additional operators from the Red Hat registry, you may not use the cluster commercially.

**Comment by bobby0724** [comment]
I am also interested to setup loggin on OKD 4.5, i have a OCP 4.6 and loggin was configured successfully is there any alternate solution for OKD 4.5

**Comment by mburke5678** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/28779
