### ISSUE TITLE
OKD 4.5 UPI on GCP: cluster-provisioned load balancer fails health checks on worker nodes

### ISSUE THREAD

**Issue by andygeorge** [openshift/okd#296]
**Describe the bug**
Initially following the [UPI on GCP install docs](https://github.com/openshift/installer/blob/master/docs/user/gcp/install_upi.md), we're able to get a cluster up and running and returning a successful install-complete, but the cluster-provisioned load balancer (for the `*.apps` subdomains, including the web console) is never healthy.

Although we are doing mostly user-provided infra, we utilize MachineSets to allow the cluster to manage its own worker nodes, which come up successfully and are running the ingress pods correctly, but the health checks to those workers continue to fail, so the load balancer remains unhealthy, and we're unable to access the web console:

![](https://i.imgur.com/lBOqGxY.png)

I did confirm we have valid GCP firewall rules that match the health check in the above load balancer, and those firewall rules do correctly for work for the API load balancer, which is healthy:

![](https://i.imgur.com/1l9RBHp.png)

Although there are no failing pods, the cluster does mention the ingress CO is degraded (but available):
```
[core@os-test-f4tbl-master-1 ~]$ oc get clusteroperators
NAME                                       VERSION                            AVAILABLE   PROGRESSING   DEGRADED   SINCE
...
image-registry                             4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      35m
ingress                                    4.5.0-0.okd-2020-07-14-153706-ga   True        False         True       35m
insights                                   4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      40m
...
```

I don't have any erroring pods and don't see any obvious error events. Is there anywhere else specific I can look?

**Version**
```
4.5.0-0.okd-2020-07-14-153706-ga
```

**How reproducible**
100%

**Log bundle**
https://andygeorge.keybase.pub/openshift/must-gather.local.5489449310164096131.tar.gz?dl=1

**Comment by vrutkovs** [comment]
Right, the healthchecks are failing as 80 and 443 ports are not accessible on the nodes - due to ingress operator being degraded.

Error message from operator logs:
>ERROR	operator.dns_controller	dns/controller.go:161	failed to publish DNS record to zone	{"dnsrecord": .... ,"reason":"ProviderError","message":"The DNS provider failed to ensure the record: googleapi: Error 404: The 'parameters.managedZone' resource named 'os-test-f4tbl-private-zone' does not exist., notFound"}]}],"observedGeneration":1}}, "dnszone": {"id":"os-test-f4tbl-private-zone"}, "error": "googleapi: Error 404: The 'parameters.managedZone' resource named 'os-test-f4tbl-private-zone' does not exist., notFound"}

Make sure managedZone exists so that ingress operator could create necessary records

**Comment by andygeorge** [comment]
Thanks @vrutkovs yet again :smile:, I didn't remove `spec.privateZone` from the `manifests/cluster-dns-02-config.yml` (thought I did!), as stated in the [UPI directions](https://github.com/openshift/installer/blob/master/docs/user/gcp/install_upi.md#remove-dns-zones-optional).

**Comment by andygeorge** [comment]
I fixed :point_up: and the ingress CO now is healthy, but still seeing the original issue (worker nodes aren't healthy in the `*.apps` load balancer.

I am not sure what to troubleshoot next. What exactly serves up that health check endpoint on the worker nodes? Or is there anything else I should be looking at?
