### ISSUE TITLE
When using ingressVIP, machineconfigs 00-worker and 00-master get a faulty NetworkManager script, that leads to DNS issues

### ISSUE THREAD

**Issue by philipp1992** [openshift/okd#298]
We are using OKD4.5-GA release with vsphere cloud provider.

In our installer.yaml we have set ingressVIP and apiVIP.

Using this installation parameters, the installer will generate a 00-worker and 00-master machineconfig, that includes the following file:

/etc/NetworkManager/dispatcher.d/30-resolv-prepender

content of this file:

```
#!/bin/bash
IFACE=$1
STATUS=$2
# If $DHCP6_FQDN_FQDN is not empty and is not localhost.localdomain
[[ -n "$DHCP6_FQDN_FQDN" && "$DHCP6_FQDN_FQDN" != "localhost.localdomain" && "$DHCP6_FQDN_FQDN" =~ "." ]] && hostnamectl set-hostname --static --transient $DHCP6_FQDN_FQDN
case "$STATUS" in
    up|down|dhcp4-change|dhcp6-change)
    logger -s "NM resolv-prepender triggered by ${1} ${2}."
    NAMESERVER_IP=$(/usr/bin/podman run --rm \
        --authfile /var/lib/kubelet/config.json \
        --net=host \
        quay.io/openshift/okd-content@sha256:3c7ec93feeb79561438ef453ed25d1e00d95f67f6429eb3d475d29e8a44318c1 \
        node-ip \
        show \
        "10.0.38.200" \
        "10.0.38.201")
    DOMAIN="**<our-cluster-id>.<our-base-domain>**"
    if [[ -n "$NAMESERVER_IP" ]]; then
        logger -s "NM resolv-prepender: Prepending 'nameserver $NAMESERVER_IP' to /etc/resolv.conf (other nameservers from /var/run/NetworkManager/resolv.conf)"
        sed -e "/^search/d" \
            -e "/Generated by/c# Generated by KNI resolv prepender NM dispatcher script\nsearch $DOMAIN\nnameserver $NAMESERVER_IP" \
            /var/run/NetworkManager/resolv.conf > /etc/resolv.tmp
    else
        logger -s "Couldn't find a non-virtual IP, just updating resolv.conf"
        cp /var/run/NetworkManager/resolv.conf /etc/resolv.tmp
    fi
    mv -f /etc/resolv.tmp /etc/resolv.conf
    ;;
    *)
    ;;
esac

```

This file will lead to NetworkManager creating the following /etc/resolv.conf on our FCOS machines:

search x x x x **our-cluster-id.our-base-domain**

This resolv.conf will lead to all pods resolving any DNS entry to our ingressVIP, because the will append the wildcard dns domain to any hostname.

The $DOMAIN variable in the script should not include the cluster-id-base-domain, but just the DNS suffix or nothing at all.

**Comment by philipp1992** [comment]
this does not happen, if we dont set the ingressVIP, but use an external loadbalancer.

**Comment by vrutkovs** [comment]
This prepender would add CoreDNS entry, but `.cluster.local` resolves won't work on host

**Comment by vrutkovs** [comment]
It seems CoreDNS config has been updated in latest stable - https://github.com/openshift/machine-config-operator/commit/4c5fcbea0bb6694e4192a8dd81ffa471f8731ceb - let see if that has a fix

**Comment by EagleIJoe** [comment]
still happening on openshift-install 4.5.0-0.okd-2020-08-12-020541 using ovirt IPI ... I get this in NetworkManager log:

> NetworkManager[694]: <warn>  [1597309259.6449] dispatcher: (4) /etc/NetworkManager/dispatcher.d/30-resolv-prepender failed (failed): Script '/etc/NetworkManager/dispatcher.d/30-resolv-prepender' exited with error status 125.
