### ISSUE TITLE
[Ovirt IPI] Installer asks for DNS IP

### ISSUE THREAD

**Issue by EagleIJoe** [openshift/okd#300]
**Describe the bug**
According to the documentation[1], ovirt provider should ask for the API and Ingress IP only. The installer also asks for a DNS IP (was required previously).

[1] https://github.com/openshift/installer/blob/master/docs/user/ovirt/install_ipi.md (see requirements)

**Version**
openshift-install 4.5.0-0.okd-2020-08-12-020541

ovirt IPI

**How reproducible**
Run openshift-install create cluster and choose ovirt as provider

**Comment by vrutkovs** [comment]
`master` is tracking 4.6, where requirement for DNS IP has been removed

In [release-4.5](https://github.com/openshift/installer/blob/release-4.5/docs/user/ovirt/install_ipi.md) branch its still required.

Unfortunately we don't have a recent OKD 4.6 nightly to test it (we're working on it)
