### ISSUE TITLE
Invalid signature in 4.5.0-0.okd-2020-08-12-020541 update

### ISSUE THREAD

**Issue by eric0926005001** [openshift/okd#301]
**Describe the bug**
 oc adm upgrade , have some problems.

**Version**
4.5.0-0.okd-2020-07-29-070316

**How reproducible**

**Log bundle**

[root@bastion ~]# oc adm upgrade
info: An upgrade is in progress. Unable to apply 4.5.0-0.okd-2020-08-12-020541: the image may not be safe to use

Updates:

VERSION                       IMAGE
4.5.0-0.okd-2020-08-12-020541 registry.svc.ci.openshift.org/origin/release@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4

[root@bastion ~]# oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.0-0.okd-2020-07-29-070316   True        True          23h     Unable to apply 4.5.0-0.okd-2020-08-12-020541: the image may not be safe to use
[root@bastion ~]# oc adm upgrade --to=4.5.0-0.okd-2020-08-12-020541
info: Cluster is already at version 4.5.0-0.okd-2020-08-12-020541

[root@bastion ~]# 

yes, my configmap is also lost signatures

apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-03T03:48:13Z"
  labels:
    release.openshift.io/verification-signatures: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:release.openshift.io/verification-signatures: {}
    manager: cluster-version-operator
    operation: Update
    time: "2020-08-03T03:48:13Z"
  name: signatures-managed
  namespace: openshift-config-managed
  resourceVersion: "2416"
  selfLink: /api/v1/namespaces/openshift-config-managed/configmaps/signatures-managed
  uid: a1d02fe4-6535-4a78-a010-8cf3f4f4c38c

I try to use the command --force, could not resolved the problems.

[root@bastion ~]# oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.0-0.okd-2020-07-29-070316   True        True          30h     Unable to apply 4.5.0-0.okd-2020-08-12-020541: the image may not be safe to use
[root@bastion ~]# oc adm upgrade --to=4.5.0-0.okd-2020-08-12-020541 --force
info: Cluster is already at version 4.5.0-0.okd-2020-08-12-020541
[root@bastion ~]# oc adm upgrade
info: An upgrade is in progress. Unable to apply 4.5.0-0.okd-2020-08-12-020541: the image may not be safe to use

Updates:

VERSION                       IMAGE
4.5.0-0.okd-2020-08-12-020541 registry.svc.ci.openshift.org/origin/release@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4
[root@bastion ~]# oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.0-0.okd-2020-07-29-070316   True        True          30h     Unable to apply 4.5.0-0.okd-2020-08-12-020541: the image may not be safe to use
[root@bastion ~]#

**Comment by sportluffi** [comment]
I see the same issue. 

The cluster-version-operator in the openshift-cluster-version project hints, that the shasum signature is missing, hence can't be validated.

```
I0814 05:30:02.136943       1 store.go:74] use cached most recent signature config maps
I0814 05:30:02.215532       1 store.go:65] remember most recent signature config maps: signatures-managed
I0814 05:30:02.215762       1 store.go:116] searching for sha256-6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4 in signature config map signatures-managed
I0814 05:30:02.563757       1 verify.go:298] Unable to verify sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4 against keyring verifier-public-key-openshift-ci
E0814 05:30:02.564074       1 sync_worker.go:329] unable to synchronize image (waiting 2m52.525702462s): The update cannot be verified: unable to locate a valid signature for one or more sources
I0814 05:30:13.202297       1 cvo.go:437] Started syncing cluster version "openshift-cluster-version/version" (2020-08-14 05:30:13.202274533 +0000 UTC m=+485.248797949)
I0814 05:30:13.202551       1 cvo.go:466] Desired version from spec is v1.Update{Version:"4.5.0-0.okd-2020-08-12-020541", Image:"registry.svc.ci.openshift.org/origin/release@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4", Force:false}
```

**Comment by vrutkovs** [comment]
Seems the signing didn't work well.

Workaround: add `--force` in the CLI or set `force: true` in `desiredUpdate` section of clusterversion/cluster

**Comment by sportluffi** [comment]
Forcing worked - thank you. Is there any way we can assist to fix the underlying issue regarding the missing signatures?

**Comment by eric0926005001** [comment]
thanks a lot.
i use the command:
"oc adm upgrade --clear"
and then,
"oc adm upgrade --to=4.5.0-0.okd-2020-08-12-020541 --force"
it's update now
thank you

**Comment by vrutkovs** [comment]
This update cannot be fixed and re-signed, but new nightlies have valid signature - and next stable update should not require `force`

**Comment by vrutkovs** [comment]
Fixed in https://github.com/openshift/okd/releases/tag/4.5.0-0.okd-2020-09-04-180756
