### ISSUE TITLE
Nightly 4.6.0-0.okd-2020-08-01-065221 is reporting Kubernetes Version 1.17.0-alpha instead of 1.18.3

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#303]
Hi,

the last OKD 4.6 nightly is reporting Kubernetes Version 1.17.0-alpha with

```
sepp@pve:~/installer/bin$ oc version 
Client Version: 4.5.0-202005291417-9933eb9
Server Version: 4.6.0-0.okd-2020-08-01-065221
Kubernetes Version: v1.17.0-alpha.0.7867+649a587b0a0f5d-dirty
```

Is this only a display problem or true? Because the changelog of 

https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2020-08-01-065221

reports that it includes Kubernetes 1.18.3

Greetings,

Josef

**Comment by vrutkovs** [comment]
It seems `kube-apiserver` and `openshift-apiserver` are not in sync - when the latter gets rebased on 1.18 it would display valid version.

I'll keep this open to track other version disrepancies

**Comment by vrutkovs** [comment]
Fixed in recent nightlies, no longer happening since at least https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2020-09-16-020938
