### ISSUE TITLE
4.5 OKD document still referring OCP

### ISSUE THREAD

**Issue by Ananth-vr** [openshift/okd#305]
Document for creating a local mirror is still referring to OCP and access.redhat.com

https://docs.okd.io/latest/installing/install_config/installing-restricted-networks-preparations.html#installing-restricted-networks-preparations

RELEASE_NAME should be set to okd from OCP
PRODUCT_REPO should be openshift and not openshift-release-dev
OCP_RELEASE should point to  https://quay.io/repository/openshift/okd?tab=tags and not https://access.redhat.com/downloads/content/290/

**Comment by walidshaari** [comment]
can you share your variables and your use case for one release?

**Comment by krrypto** [comment]
OCP_RELEASE
4.5.0-0.okd-2020-08-12-020541
ARCHITECTURE
-x86_64
LOCAL_REGISTRY
192.168.1.210:5000
LOCAL_REPOSITORY
okd/okd4
ARCHITECTURE
x86_64

**Comment by vrutkovs** [comment]
Tracked in docs - https://github.com/openshift/openshift-docs/issues/27053

**Comment by walidshaari** [comment]
sorry, I was not following, is that fixed or not? it seems I go from the same issue to the other and back

**Comment by LorbusChris** [comment]
we're deferring issues from this repo to where they belong - this'll have to be fixed in the openshift-docs repo, so the linked issue is now the canonical tracker for it.
