### ISSUE TITLE
AWS UPI bootkube.sh stuck in  Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused

### ISSUE THREAD

**Issue by yonghuili1** [openshift/okd#307]
logs here:
[root@ip-172-16-0-143 ~]# journalctl -b -f -u bootkube.service
-- Logs begin at Tue 2020-08-18 02:35:08 UTC. --
8月 18 04:23:12 ip-172-16-0-143 bootkube.sh[157780]: Skipped "secret-csr-signer-signer.yaml" secrets.v1./csr-signer-signer -n openshift-kube-controller-manager-operator as it already exists
8月 18 04:23:12 ip-172-16-0-143 bootkube.sh[157780]: Skipped "secret-initial-kube-controller-manager-service-account-private-key.yaml" secrets.v1./initial-service-account-private-key -n openshift-config as it already exists
8月 18 04:23:13 ip-172-16-0-143 bootkube.sh[157780]: Skipped "secret-kube-apiserver-to-kubelet-signer.yaml" secrets.v1./kube-apiserver-to-kubelet-signer -n openshift-kube-apiserver-operator as it already exists
8月 18 04:23:13 ip-172-16-0-143 bootkube.sh[157780]: Skipped "secret-loadbalancer-serving-signer.yaml" secrets.v1./loadbalancer-serving-signer -n openshift-kube-apiserver-operator as it already exists
8月 18 04:23:14 ip-172-16-0-143 bootkube.sh[157780]: Skipped "secret-localhost-serving-signer.yaml" secrets.v1./localhost-serving-signer -n openshift-kube-apiserver-operator as it already exists
8月 18 04:23:14 ip-172-16-0-143 bootkube.sh[157780]: Skipped "secret-service-network-serving-signer.yaml" secrets.v1./service-network-serving-signer -n openshift-kube-apiserver-operator as it already exists
8月 18 04:23:15 ip-172-16-0-143 bootkube.sh[157780]: Skipped "user-ca-bundle-config.yaml" configmaps.v1./user-ca-bundle -n openshift-config as it already exists
8月 18 04:23:29 ip-172-16-0-143 bootkube.sh[157780]: E0818 04:23:29.913280       1 reflector.go:251] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: Get https://localhost:6443/api/v1/pods?watch=true: dial tcp [::1]:6443: connect: connection refused
8月 18 04:23:30 ip-172-16-0-143 bootkube.sh[157780]: E0818 04:23:30.916618       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
8月 18 04:23:31 ip-172-16-0-143 bootkube.sh[157780]: E0818 04:23:31.917745       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused

————————————
it looks like the bootstrap contianer can not connect  the api server use localhost ,but i found that this container use host network, and in the container terminal  telnet  localhost 6443  and prot open 
![image](https://user-images.githubusercontent.com/46884881/90471489-0292d800-e151-11ea-94f4-8475b793970a.png)

**Comment by vrutkovs** [comment]
Please attach the log bundle
