### ISSUE TITLE
Network policies are not applied

### ISSUE THREAD

**Issue by DaringATK** [openshift/okd#308]
**Describe the bug**
There is no effect after applying the network policy rule. In this case, the rule is applied successfully and is reflected in the console.
OKD 4,5 install on bare metall with eanble cluster proxy

**Version**
openshift-install version
openshift-install 4.5.0-0.okd-2020-08-12-020541
built from commit 699277bb61706731d687b9e40700ebf4630b0851
release image quay.io/openshift/okd@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4

oc version
Client Version: 4.5.0-0.okd-2020-08-12-020541
Server Version: 4.5.0-0.okd-2020-08-12-020541
Kubernetes Version: v1.18.3

**How reproducible**

as cluster admin
```
cat default-deny.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
```

apply rule
```
$ oc apply -f default-deny.yaml -n green
networkpolicy.networking.k8s.io/default-deny created
```

check
```
$ oc get po -n green
NAME                              READY   STATUS    RESTARTS   AGE
green-nginx-7597f48fcf-pr782      1/1     Running   0          36m
green-two-nginx-c965d8fc8-b6mxh   1/1     Running   0          48m

$oc exec green-nginx-7597f48fcf-pr782 -- curl -kv https://github.com
* Expire in 0 ms for 6 (transfer 0x5606cc2b0f50)
* Uses proxy env variable HTTPS_PROXY == 'http://172.18.252.100:8080/'
*   Trying 172.18.252.100...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5606cc2b0f50)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 172.18.252.100 (172.18.252.100) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to github.com:443
> CONNECT github.com:443 HTTP/1.1
> Host: github.com:443
> User-Agent: curl/7.64.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
```

maybe I'm doing something wrong?

**Comment by vrutkovs** [comment]
It appears Egress policy doesn't apply. Which SDN are you using? Note that default OVN provider [doesn't support Egress yet](https://docs.okd.io/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html#nw-ovn-kubernetes-matrix_about-ovn-kubernetes).

Does Ingress policy apply?

**Comment by DaringATK** [comment]
OpenShift SDN is used. Can I use calico? Network Type: OpenShift SDN in the documentation is the only option.
In terms of ingress traffic, the rules really work:

When will egress rules work?

**Comment by vrutkovs** [comment]
>OpenShift SDN is used

Could you upload a [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html) and post a link here?

> Can I use calico? 

[Yes](https://docs.projectcalico.org/getting-started/openshift/installation).

**Comment by DaringATK** [comment]
Is calico a tested and reliable OKD4.5 solution for prom deployments?
I'll attach a must-gather later.

**Comment by DaringATK** [comment]
Thanks for the help, the problem is not a bug, according to the documentation
