### ISSUE TITLE
machine-config-host-pull.service almost always fails because network is not up yet

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/okd#31]
As the title says, `machine-config-host-pull.service` almost always fails in my environment. As far as I can tell, this is because it tries to pull the pivot image before `network-online.target` is reached, so the network's not available yet.

![mcd early pull](https://user-images.githubusercontent.com/2983875/72234341-858bf880-359a-11ea-9958-486c42e708ee.png)

Please see the attached systemd boot chart for an example of this. Please also note that restarting the service manually once I can SSH into the nodes works.

**Comment by vrutkovs** [comment]
Which payload and platform are you using? What's in `machine-config-daemon-pull.service` logs?

**Comment by SriRamanujam** [comment]
I'm using baremetal UPI. Here's the `machine-config-daemon-pull.service` logs:

```
❯ cat machine-config-daemon-pull.service.txt
● machine-config-daemon-pull.service - Machine Config Daemon Install
   Loaded: loaded (/etc/systemd/system/machine-config-daemon-pull.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-01-12 01:14:10 UTC; 5min ago
  Process: 964 ExecStart=/usr/bin/sh -c /usr/bin/podman run --authfile=/var/lib/kubelet/config.json --quiet --net=host --entrypoint=cat 'quay.io/openshift/okd-content@sha256:6625bb97a35604080af348340f0788df36455352b1a039f073cb6894c548fb78' /usr/bin/machine-config-daemon >
/usr/local/bin/machine-config-daemon (code=exited, status=125)
 Main PID: 964 (code=exited, status=125)
      CPU: 207ms

Jan 12 01:14:09 localhost systemd[1]: Starting Machine Config Daemon Install...
Jan 12 01:14:10 localhost podman[965]: 2020-01-12 01:14:10.547631522 +0000 UTC m=+0.541513348 system refresh
Jan 12 01:14:10 localhost sh[964]: Error: unable to pull quay.io/openshift/okd-content@sha256:6625bb97a35604080af348340f0788df36455352b1a039f073cb6894c548fb78: unable to pull image: Error initializing source docker://quay.io/openshift/okd-content@sha256:6625bb97a35604080af
348340f0788df36455352b1a039f073cb6894c548fb78: pinging docker registry returned: Get https://quay.io/v2/: dial tcp: lookup quay.io on [::1]:53: read udp [::1]:53490->[::1]:53: read: connection refused
Jan 12 01:14:10 localhost systemd[1]: machine-config-daemon-pull.service: Main process exited, code=exited, status=125/n/a
Jan 12 01:14:10 localhost systemd[1]: machine-config-daemon-pull.service: Failed with result 'exit-code'.
Jan 12 01:14:10 localhost systemd[1]: Failed to start Machine Config Daemon Install.
```

**Comment by vrutkovs** [comment]
Right, that's initial OKD Preview release, right?

It has been using older FCOS base and while MCD binary has been extracted, Zincati has updated to latest FCOS and rebooted. This issue has been fixed in latest 4.4 release images (see https://origin-release.svc.ci.openshift.org/) and not yet backported to 4.3

**Comment by SriRamanujam** [comment]
Yes, this is the OKD preview release. Is there anything I can do to bring the cluster up correctly in this scenario?

**Comment by vrutkovs** [comment]
For now you'd have to use installer from CI releases from https://origin-release.svc.ci.openshift.org - for instance https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-13-124915

**Comment by SriRamanujam** [comment]
Okay, I was able to get the installer out by running `oc adm release extract --command 'openshift-install' registry.svc.ci.openshift.org/origin/release:4.4.0-0.okd-2020-01-13-124915`. I'll try this out later and see how it goes. Thanks!

**Comment by SriRamanujam** [comment]
Right, so I downloaded the latest nightly version of the 4.4.0 installer from [here](https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-13-234448):

```
❯ ./openshift-install version
./openshift-install unreleased-master-2041-g83ad237ee6e7aed8ef95ad7d35d501f7a2fe8202-dirty
built from commit 83ad237ee6e7aed8ef95ad7d35d501f7a2fe8202
release image registry.svc.ci.openshift.org/origin/release@sha256:b8e76171fc43c4b4cd9344b410336d50459705c5575218b2329c0b1fa10c66e7
```

It did not help. The majority of my nodes did not pull the MCD image correctly, the error is the same.

**Comment by vrutkovs** [comment]
https://github.com/openshift/machine-config-operator/pull/1301 should fix that

**Comment by SriRamanujam** [comment]
This issue was fixed with https://github.com/openshift/machine-config-operator/pull/1301 and https://github.com/openshift/machine-config-operator/pull/1374.
