### ISSUE TITLE
bootstrap never finishes

### ISSUE THREAD

**Issue by Knutm2** [openshift/okd#312]
Followed recipe at https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee

master1,master2 ready, master3 not ready
No worker came on line

Attaching the output of 
openshift-install gather bootstrap --dir=./install_dir \
--bootstrap 192.168.2.200 \
--master 192.168.2.201 \
--master 192.168.2.202 \
--master 192.168.2.20

**Describe the bug**

**Version**

**How reproducible**

**Log bundle**

**Comment by Knutm2** [comment]
have log bundle, not sure how to share it

**Comment by vrutkovs** [comment]
Please upload the bundle to any public server (GDrive, OneDisk etc) and add the link to the description

**Comment by Knutm2** [comment]
not able to supply logs in timely fashion, closing issue
