### ISSUE TITLE
cluster wide http proxy with authentication not working in OKD 4.5 ga

### ISSUE THREAD

**Issue by xander-sh** [openshift/okd#313]
**Describe the bug**
After configuration cluster wide proxy with authentication, network operator fail with error 
```shell 
"The configuration is invalid for proxy 'cluster' 
(invalid httpProxy URI: parse http://user:pass@host:3128: invalid port ":pass" after host). 
Use 'oc edit proxy.config.openshift.io cluster' to fix."
```
Loks like it bug. 
The first group user:pass is recognized as host:port.  

**Version**

OKD version: 4.5.0-0.okd-2020-07-14-153706-ga
vSphere IPI install method 

**How reproducible**

Install OKD 4.5.0-0.okd-2020-07-14-153706-ga behind transparent proxy and after that update cluster wide proxy for proxy with authentication

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.5-e2e-aws-proxy/1295873283949858816

**Log bundle**

https://drive.google.com/file/d/1IqnMWwUn4EdTaB0cLinn_DAEPdOLUpxN/view?usp=sharing

**Comment by vrutkovs** [comment]
>The configuration is invalid for proxy 'cluster' 

Where does that message come from? I don't see it anywhere in the logs. `httpProxy` is set to `http://10.16.163.200:3128`.
