### ISSUE TITLE
OKD4.5 vSphere Deployment - crypto/rsa: verification error

### ISSUE THREAD

**Issue by Les-Linux** [openshift/okd#314]
Good Afternoon,

Trying to build a new instance of OKD4.5 based on the guideline posted [here](https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee).

I am seeing the following in the debug output:

> DEBUG Still waiting for the Kubernetes API: Get https://api.lab.okd.local:6443/version?timeout=32s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")

Not quiet sure what is causing this.

Les

**Comment by vrutkovs** [comment]
Please collect [necessary troubleshooting information](https://docs.okd.io/latest/installing/installing-troubleshooting.html) and attach / link here

**Comment by Les-Linux** [comment]
nvm, started from scratch and this time it has progressed. thanks for responding.
