### ISSUE TITLE
bootstrap never finishes

### ISSUE THREAD

**Issue by Knutm2** [openshift/okd#316]
Followed recipe at https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee

master1,master2 ready, master3 not ready
No worker came on line

Attaching the output of
openshift-install gather bootstrap --dir=./install_dir
--bootstrap 192.168.2.200
--master 192.168.2.201
--master 192.168.2.202
--master 192.168.2.20

**Describe the bug**

**Version**

**How reproducible**

**Log bundle**

**Comment by Knutm2** [comment]
[admin@okd4-services ~]$ oc get nodes
NAME                   STATUS     ROLES    AGE     VERSION
okd4-compute-2         Ready      worker   174m    v1.18.3
okd4-control-plane-1   Ready      master   3h31m   v1.18.3
okd4-control-plane-2   Ready      master   3h47m   v1.18.3
okd4-control-plane-3   NotReady   master   3h24m   v1.18.3

**Comment by Knutm2** [comment]
Link to log bundle:
[https://drive.google.com/file/d/11pFQ1jq4WxhjpYGuUarPif-d9kjuTNxl/view?usp=sharing](url)

**Comment by vrutkovs** [comment]
Your masters have only 2 vCPUs and 2GB RAM, you'd have to bump those to 4 vCPU and 16 GB (see https://docs.okd.io/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#minimum-resource-requirements_installing-restricted-networks-bare-metal)

**Comment by Knutm2** [comment]
Great thanks for feedback! I will assemble some more machine horsepower and
try again

On Tue, Sep 1, 2020 at 4:09 AM Vadim Rutkovsky <notifications@github.com>
wrote:

> Your masters have only 2 vCPUs and 2GB RAM, you'd have to bump those to 4
> vCPU and 16 GB (see
> https://docs.okd.io/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#minimum-resource-requirements_installing-restricted-networks-bare-metal
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.okd.io_latest_installing_installing-5Fbare-5Fmetal_installing-2Drestricted-2Dnetworks-2Dbare-2Dmetal.html-23minimum-2Dresource-2Drequirements-5Finstalling-2Drestricted-2Dnetworks-2Dbare-2Dmetal&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=uvj3SwkiNCfyBqHjCuUTCLdRut5pf9wxPfVVJhSBzKc&m=7SVXI4vRdgD-Uu-RUbYkAd7s_hQ8ywOdAmp6vUQ-mVw&s=pUxcpc6LHYWJPcL9HLqonMXNApSJkupVJmtO_Sqhcqk&e=>
> )
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_openshift_okd_issues_316-23issuecomment-2D684626535&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=uvj3SwkiNCfyBqHjCuUTCLdRut5pf9wxPfVVJhSBzKc&m=7SVXI4vRdgD-Uu-RUbYkAd7s_hQ8ywOdAmp6vUQ-mVw&s=vfWq3zWgF6sI7G5eF7VeDsaCvGlWtr16xw8MfqBOGag&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQXLCQT3A3KLYAXGQBPUOR3SDS24BANCNFSM4QQ3FRWQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=uvj3SwkiNCfyBqHjCuUTCLdRut5pf9wxPfVVJhSBzKc&m=7SVXI4vRdgD-Uu-RUbYkAd7s_hQ8ywOdAmp6vUQ-mVw&s=eU5LZvFbg3InphFFffAcjBFsW8UD6dTmirZOxRgC8Dc&e=>
> .
>


-- 
<http://www.verizon.com/>

Knut Meidal

Storage Engineer

Systems & Maintenance Engineering

M (805) 807-9178
1600 Solana Blvd
STE 400
Westlake, TX 76262
