### ISSUE TITLE
How to use SR-IOV on OKD 4.5 GA 

### ISSUE THREAD

**Issue by rupang790** [openshift/okd#317]
**Describe the bug**

I tried to use SR-IOV on OKD 4.5 GA Version.
I followed below links but it seems not working on my cluster.
https://docs.okd.io/latest/networking/hardware_networks/installing-sriov-operator.html

When I execute  command to create a Subscription CR for the SR-IOV Network Operator and check the status as below, It does not come anything.
![image](https://user-images.githubusercontent.com/40801176/91829106-fabc5300-ec7b-11ea-87f9-0ad8516625ad.png)

Anyone tried to use SR-IOV on GA version? 
Please help to use SR-IOV on OKD cluster.

**Version**

Client Version: 4.5.0-0.okd-2020-08-12-020541
Server Version: 4.5.0-0.okd-2020-08-12-020541

**How reproducible**

**Log bundle**

**Comment by vrutkovs** [comment]
Please collect necessary information with `oc adm must-gather` - see https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data

**Comment by rupang790** [comment]
Thanks for information.
I tried to collect the logs by 'oc add must-gather' command but it collected all the logs about cluster, and I don't know well which logs I can check for this issue. Would you please give me some advise to collect related information to solve this issue?

**Comment by rupang790** [comment]
After update the cluster to "4.5.0-0.okd-2020-09-04-180756" version which is updated last Friday, SR-IOV plug-in was installed well by following links. 
https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md

However, the way to install which is introduced on OKD official docs, it is still not work for me.

**Comment by ianb-mp** [comment]
I just encountered this issue. AFAIK this operator is not available via the community operator repos (either [Redhat community](https://github.com/redhat-openshift-ecosystem/community-operators-prod) or [Operatorhub.io](https://operatorhub.io)) and so manual installation is required when using OKD (either via [quickstart steps](https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md) or using [Helm chart](https://github.com/openshift/sriov-network-operator/tree/master/deployment/sriov-network-operator)).

Given that people using OKD are unlikely to have Redhat subscription, it would be good to update the OKD doco to mention the alternative source for this operator: https://docs.okd.io/4.14/networking/hardware_networks/installing-sriov-operator.html
