### ISSUE TITLE
AWS - openshift-install does not honour ~/.aws/credentials

### ISSUE THREAD

**Issue by vikas027** [openshift/okd#320]
**Describe the bug**
I have my assumed role AWS Credentials set in `~/.aws/credentials` and which are working fine but `openshift-install` still looks for AWS Access keys

The credentials have full administrator rights

```
$ cat ~/.aws/credentials
[default]
role_arn              = arn:aws:iam::<account_id>:role/assume-role
source_profile        = parent
region                = ap-southeast-2

[parent]
aws_access_key_id        = <redacted>
aws_secret_access_key    = <redacted>
aws_session_token        = <redacted>
aws_security_token       = <redacted>
x_principal_arn          = arn:aws:sts::<parent_account_id>:assumed-role/administrator/<user>
x_security_token_expires = 2020-09-03T00:53:15+10:00
$
```

I have also tried just assumed role's AWS Access keys and Session Token
```
[default]
region                = ap-southeast-2
aws_access_key_id     = <redacted>
aws_secret_access_key = <redacted>
aws_session_token     = <redacted>
```

**Version**
```
$ openshift-install version
openshift-install 4.5.0-0.okd-2020-08-12-020541
built from commit 699277bb61706731d687b9e40700ebf4630b0851
release image quay.io/openshift/okd@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4
$
```

**How reproducible**

Use an assumed role, shown above. It looks `openshift-install` specifically looks for keywords `aws_access_key_id` and `aws_secret_access_key` in `~/.aws/credentials`

If I just use the assumed role's AWS Access keys and Session Token, I get below error.

```
DEBUG   Generating Platform Permissions Check...   
INFO Credentials loaded from the "default" profile in file "/home/ec2-user/.aws/credentials" 
FATAL failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Permissions Check": validate AWS credentials: checking install permissions: error gathering AWS credentials details: error querying username: ValidationError: Must specify userName when calling with non-User credentials
        status code: 400, request id: 47a70b8b-8ebd-44d1-9d7d-af3a1xxxxxf

**Comment by vrutkovs** [comment]
See https://docs.okd.io/latest/installing/installing_aws/installing-aws-account.html#installation-aws-iam-user_installing-aws-account - assumed role creds are not supported, `The cluster continues to use your current AWS credentials to create AWS resources for the entire life of the cluster, so you must use key-based, long-lived credentials`

**Comment by vikas027** [comment]
hey @vrutkovs - Can we take this as a feature request? Long-lived credentials are not good for security.

**Comment by vrutkovs** [comment]
>Can we take this as a feature request?

That would affect OCP, so start with a customer case (if possible) or file a bug at https://bugzilla.redhat.com
