### ISSUE TITLE
OpenStack IPI deployment - VIPs jumping, masters+workers go NotReady

### ISSUE THREAD

**Issue by cloudbustinguk** [openshift/okd#321]
**Describe the bug**
Pretty sure this isn't a bug, but thought it best to report here. All nodes (1 worker seems to be always spared) eventually go NotReady after a protracted VIP-hopping frenzy. API always ends up down, but ingress survives on one worker so far..

**Background**
OpenStack IPI, I have no admin rights whatsoever on this RHOSP platform. Also, a custom DNS delegation was given for this cluster (no PTR unfortunately), as it is a test cluster to prove the platform viability (RHOSP+OKD).

Often there are `etcdserver` timeouts. We also experience the VIPs jumping between masters, and also the VIPs on the two workers also jump very frequently. Eventually, all nodes (master+workers) go NotReady. A reboot of the instance itself brings them back. We suspect potentially the disks are too slow for etcd, but are not 100% sure if this is the only problem.

As mentioned, I have very few rights on this RHOSP instance, so cannot debug further.

A must-gather often times out. It was a miracle I even got the one linked herein:

```
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/okd-content@sha256:5a9b4b4cdd15e8587d02490cf753c385213e6a97e5c2bf7babf416585e42fd70
[must-gather      ] OUT namespace/openshift-must-gather-kktr6 created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-ppsc2 created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/okd-content@sha256:5a9b4b4cdd15e8587d02490cf753c385213e6a97e5c2bf7babf416585e42fd70 created
[must-gather-whtq7] OUT gather did not start: timed out waiting for the condition
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-ppsc2 deleted
[must-gather      ] OUT namespace/openshift-must-gather-kktr6 deleted
error: gather did not start for pod must-gather-whtq7: timed out waiting for the condition
```

There is high churn on the master pods (most of the following pods don't tend to live more than a few minutes before cycling, "custom samples" problem notwithstanding - the other pods tend to live ~10 hours+ before cycling):

```
[root@okd1-vhd7x-master-2 ~]# crictl ps                                        
CONTAINER           IMAGE                                                              CREATED              STATE               NAME                                          ATTEMPT             POD ID       
fb9a21559bea4       014e4d750953857f7cb672f468b61d06f4845a91f8944fb4f058dab00654fd97   3 seconds ago        Running             marketplace-operator                          18                  c7de492331869
a58d7d104c109       28a7ff5dda3f45927cdbfe65c7f82a1527699b822fc2b8e2d2b01f13f4365706   4 seconds ago        Running             operator                                      3                   2cd8dec9d5442
0921bf254baeb       df49e0d72177ea229818d582dd99ead12a917a8383e98fa6f7d682ad1ec53769   6 seconds ago        Running             kube-scheduler-operator-container             2                   8de6db234c6c4
dfec38ab87448       ef5d2cb4d7e416da7e764c70e3b5af4daa63e6523c447acba1f2047aa3508c36   19 seconds ago       Running             operator                                      2                   c4847ef30912d
4ca45b684efdf       4b16e5e1ae68ab19a31819a64b48c753b5261dd7d6b6a36bed229b02d2d3bc77   About a minute ago   Running             kube-controller-manager-recovery-controller   1                   da43e47a8e481
96033381de56e       f83587335a38ff419a786b7cc737c3cadf231d702095e870fd9c53d59e97f228   37 minutes ago       Running             kube-scheduler                                31                  81519167158fd
a6c22f8a80c75       f83587335a38ff419a786b7cc737c3cadf231d702095e870fd9c53d59e97f228   42 minutes ago       Running             kube-controller-manager                       24                  da43e47a8e481
c75fd3db028c8       e1f61167d7ccbb9db6c01e8520c6db3685576c3c86a7758d046c57c3d1365538   3 hours ago          Running             operator                   
...........    
```
Current state after having rebooted two master nodes just to get the ability to `oc get nodes`:

```
NAME                      STATUS     ROLES    AGE   VERSION
okd1-vhd7x-master-0       Ready      master   14d   v1.18.3         <- just rebooted
okd1-vhd7x-master-1       Ready      master   14d   v1.18.3         <- just rebooted
okd1-vhd7x-master-2       NotReady   master   14d   v1.18.3
okd1-vhd7x-worker-76jwk   Ready      worker   14d   v1.18.3
okd1-vhd7x-worker-px4xx   NotReady   worker   14d   v1.18.3
```

**Version**

4.5.0-0.okd-2020-08-12-020541

RHOSP IPI

**How reproducible**

I should really re-deploy to see if this is a one-off. However, the cluster is, bizarrely, fairly usable (barring the odd timeout) when it's not dying horribly, so I have allowed basic dev deployments to happen while we debug.

**Log bundle**

MG can be found here: https://cloudbustinguk-public-1.s3-eu-west-1.amazonaws.com/mg1.tar.xz

Many thanks for any insights.

**Comment by vrutkovs** [comment]
>Often there are etcdserver timeouts.

Is etcd backed up by a fast enough storage? If its insufficient it may change leader, causing VIP jump

**Comment by cloudbustinguk** [comment]
Hi @vrutkovs,

This is the same cluster that you and I briefly discussed on [slack](https://kubernetes.slack.com/archives/C6AD6JM17/p1600416943003600) yesterday.

I believe this is the root cause - Cinder volumes which are not fast enough, but wanted to be sure, as the pod attrition on each master looks quite thrashy, in that the masters appear to simply collapse into `NotReady`-ness after an indeterminate period of time (i.e., `crictl ps | wc -l` rises and falls almost constantly), and DNS delegation for the floating IPs was not initially available when the cluster was built, so we assumed this was also co-indicated in the failures (PTR records still not available).

The outcome of our discussion yesterday was that there is presently no way to adjust the etcd tolerance threshold.

Are there currently any best practices for benchmarking 4.x etcd performance? There are a few for 3.x, but nothing concrete for 4.x it seems.

Cheers
Dan

**Comment by vrutkovs** [comment]
>Are there currently any best practices for benchmarking 4.x etcd performance? 

https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md
