### ISSUE TITLE
Old version of CLI tools provided by console

### ISSUE THREAD

**Issue by bdlink** [openshift/okd#322]
**Describe the bug**
Using console, click on question mark in menu bar, select Command Line Tools
Under header "oc - OpenShift Command Line Interface (CLI)" select "Download oc for Mac for x86_64"
Download resulting file and unzip it.
execute ./oc version
result is "Client Version: v4.2.0-alpha.0-625-ge40bd2d"
should be "Client Version: 4.5.0-0.okd-2020-09-04-180756"

These should all be reviewed to be current.  Or change to refer to https://github.com/openshift/okd/releases

**Version**
OKD version 4.5.0-0.okd-2020-09-04-180756, UPI on vSphere 6.7

**How reproducible**
100%

**Log bundle**
will provide if needed (must-gather zip is 500MB)

**Comment by kai-uwe-rommel** [comment]
Same here, with Windows client, downloaded from a 2020-08-12 cluster.

**Comment by vrutkovs** [comment]
`oc` reports invalid base version, although the commit is recent - https://github.com/openshift/oc/commit/e40bd2d.

@soltysh do you know if `oc` build script needs some variables set to have the version updated?

**Comment by soltysh** [comment]
@vrutkovs yeah, I'd suggest at least setting `$(SOURCE_GIT_TAG)` when invoking `make`

**Comment by bdlink** [comment]
Problem still present in 4.6.0-0.okd-2021-01-17-185703

**Comment by vrutkovs** [comment]
Interesting, the bot has reverted our commit - https://github.com/openshift/release/pull/11851

**Comment by bdlink** [comment]
Still present in 4.6.0-0.okd-2021-01-23-132511 at least for Download oc for Mac for x86_64:

./oc version
Client Version: v4.2.0-alpha.0-833-g5797eae
Kubernetes Version: v1.20.0

**Comment by vrutkovs** [comment]
doh, we need a new commit in `oc` to rebuild it.

We're planning a rebuild as a part of #402 fix anyway

**Comment by bdlink** [comment]
do I get a badge for the most trivial but persistent bug? :-)
