### ISSUE TITLE
RouteHealthDegraded - 503 Service Unavailable

### ISSUE THREAD

**Issue by Les-Linux** [openshift/okd#325]
**Describe the bug**
OKD4 web-console inaccessible

I deployed this cluster around 2 weeks ago and it hosts eclipse che, which is accessible. The web-console for OKD4 however is not and I am not quiet sure how to resolve this matter.
[ClusterOperator-Console-Output.txt](https://github.com/openshift/okd/files/5184705/ClusterOperator-Console-Output.txt)

No changes have been made by me directly, since I last logged into the console successfully.

**Version**
Client Version: 4.5.0-0.okd-2020-08-12-020541
Server Version: 4.5.0-0.okd-2020-08-12-020541

**How reproducible**
100% reproducible

**Log bundle**
The server is currently unable to handle the request (get imagestreams.image.openshift.io must-gather)

**Comment by Les-Linux** [comment]
I also was wondering if the slack channel is an open or private channel?

**Comment by vrutkovs** [comment]
Is it still happening on latest stable release? Is etcd complaining about slow queries (check pod logs)?

**Comment by Les-Linux** [comment]
I re-deployed the instance and it seems stable now. I have noticed an issue with the image pruner now and will file a new bug report.
