### ISSUE TITLE
co downloading update graph is not using (ignoring) installed pki root certificates

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#326]
**Describe the bug**
I installed an OKD cluster in an environment where there is a transparent inspecting/filtering web proxy integrated in the default gateway (firewall). This proxy does TLS termination and re-encryption so when the cluster installation downloads packages, the files retrieved are signed by a certificate created by an internal corporate CA. To handle this, I installed that corporate CA's root certificate into the local FCOS instances with the initial ignition. This worked fine and the installation went through successfully. For previous installations in that environment we had to ask the network admins to set an exception and let anything through from quay.io etc. unfiltered, what they did not like, obviously. So this is a solution to this problem.
However, now that the cluster is up and running, it can't check for updates:
![grafik](https://user-images.githubusercontent.com/26381804/92570919-c1d73c00-f282-11ea-9d61-974f710d03f3.png)
Apparently, the cluster operator that is downloading the update graph is ignoring the root certificates in /etc/pki/ca-trust in the node's OS. Is there anything we can do to fix this?

**Version**
4.5 2020-08-12

**How reproducible**
100%

**Log bundle**
Will do if really needed.

**Comment by vrutkovs** [comment]
This affects OCP as well, lets track this in bugzilla - https://bugzilla.redhat.com/show_bug.cgi?id=1766907

**Comment by kai-uwe-rommel** [comment]
But the bug you link to above sounds quite different. Are you really sure this is related?
Or do you just mean I should create a new one?
I can also open a support case at Red Hat for OCP.

**Comment by vrutkovs** [comment]
Oh wait, its not a proxy configured in the cluster, right?

> To handle this, I installed that corporate CA's root certificate into the local FCOS instances with the initial ignition

This won't work - CVO pod doesn't use host CA. You need to configure [proxy with custom CA](https://docs.okd.io/latest/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki)

**Comment by kai-uwe-rommel** [comment]
No, so far we did not have/need a proxy.
The node OS (host) CA certificates have been used (apparently) during installation, without problems (see above).
So there is not much missing ... can I create a RFE somewhere for the CVO to use the host CAs?
It would be a pity if we would need a proxy just for that little bit.

**Comment by wking** [comment]
> The node OS (host) CA certificates have been used (apparently) during installation...

Since [rhbz#1797123]][1] (OCP 4.6 and later, I dunno how OKD is numbered), you can configure `trustedCA` in the `Proxy` object to tell the CVO (and other `Proxy` consumers) about any additional trusted CAs.  That seems appropriate for me, since you are in fact using a proxy in your environment.  The CVO's trust store is decoupled from the node's, I don't think we will grow a knob to connect them.

This is all orthogonal to installation, because the CVO's makes external requests for release signatures and recommended updates, neither of which are part of the install flow.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1797123#c15

**Comment by kai-uwe-rommel** [comment]
You may call that a proxy but it is a transparent proxy. That means, the cluster is configured like if there were no proxy at all. It is simply integrated into the default gateway. 
What we definitely do not want to do is to set up all the gear (and invest the work) to set up a real proxy like for installing a cluster in a disconnected environment - just because of THIS minor problem.
So if with 4.6 we can solve the problem by simply declaring the trusted CA for CVO alone, without the real proxy, then we are all set.
I will definitely check that once 4.6 is out!
