### ISSUE TITLE
4.5 bare-metal bootstrap aws MachineConfigServer not starting

### ISSUE THREAD

**Issue by koceg** [openshift/okd#328]
**VERSION**
4.5.0-0.okd-2020-09-04-180756
**Fedora CoreOS**
32.20200824.3.0
**aws image** 
ami-04dc8dd1c6f6521ff
**How reproducible**
100%

Hello, I'm using the bare metal approach to create my OKD cluster inside AWS using ansibe with the following repos
[aws.openshift.okd](https://github.com/koceg/aws.openshift.okd) and [ansibleAWS](https://github.com/koceg/ansibleAWS) for my working environment. 
I'm using the recommended minimum size for the nodes and this has worked for me in the past, last successful attempt was  05.06.2020 don't know which version of OKD I used.
Now I try to reproduce the same steps, bootstrap node starts goes past the login prompt that you get after initial configuration and then I start getting these errors:

```
[  183.436415] audit: type=1130 audit(1599746142.161:246): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=kubelet comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  183.533451] audit: type=1131 audit(1599746142.168:251): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=zincati comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed
```
now the result varies but this is the endless output that I get on log console.

After logging into the bootstrap node the is no indication that there is bootstrap activity on the node (no cpu load) and MachineConfigServer is not running and there are no pods running as well. 

In the meantime the master nodes attempt to get their configuration but nothing happens as nobody listens on port 22623

Is there something that has changed and not reflected in installation steps?

**Comment by vrutkovs** [comment]
Please collect necessary info - https://docs.okd.io/latest/installing/installing-troubleshooting.html and attach/link log bundle here

**Comment by koceg** [comment]
Sorry I didn't provide extra info, with the provided link for log bundle I detected a hard coded value that was pointing to the wrong bootstrap file, this was a mistake on my end.
