### ISSUE TITLE
Installation of OKD 4.5 fails on vSphere with "cluster not found"

### ISSUE THREAD

**Issue by aholen** [openshift/okd#332]
**Describe the bug**

Trying to install okd 4.5 as described https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html - but the provisioning fails when trying to create categories in vsphere.

Version

./openshift-install version
./openshift-install 4.5.0-0.okd-2020-09-04-180756
built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
release image quay.io/openshift/okd@sha256:eeb7ba7c0ca5749f2e27e0951da70263658301f5bfa4fdd86524d73bfdeb7cac

How reproducible
Reproducable 100% in my environment.

Log bundle
./openshift-install create cluster --dir=install_dir
? SSH Public Key /Users/user/.ssh/id_rsa.pub
? Platform vsphere
? vCenter vcenterXXX.example.com
? Username user@example.com
? Password [? for help] ****************
INFO Connecting to vCenter vcenterXXX.example.com
INFO Defaulting to only available datacenter: XXX
? Cluster YYYCluster-XXX
? Default Datastore VSPEX_Dist_Compr_YYY03
? Network YYY72
? Virtual IP Address for API 10.96.60.2
? Virtual IP Address for Ingress 10.96.60.3
? Base Domain okd.yyy.no
? Cluster Name deve
INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200629.3.0/x86_64/fedora-coreos-32.20200629.3.0-vmware.x86_64.ova?sha256=172f299a3e28be360740ff437a5ea9bfc246f52ea8f313d4138c5d16fd4b11e1'
INFO The file was found in cache: /Users/user/Library/Caches/openshift-installer/image_cache/062bfe3785d26fa220e2e6e72d1b3562. Reusing...
INFO Creating infrastructure resources...
ERROR
ERROR Error: failed to find provided vSphere objects: cluster '/XXX/host/YYYCluster-XXX' not found
ERROR
ERROR   on ../../../../var/folders/gc/_10kfk2x0471h9pv4jmmyd340000gn/T/openshift-install-276131820/main.tf line 43, in resource "vsphereprivate_import_ova" "import":
ERROR   43: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change

**Comment by vrutkovs** [comment]
Please attach `.openshift_install.log`

**Comment by aholen** [comment]
[openshift_install-redacted.log](https://github.com/openshift/okd/files/5238792/openshift_install-redacted.log)

**Comment by vrutkovs** [comment]
```
./openshift-install version
./openshift-install 4.5.0-0.okd-2020-09-04-180756
```
but the log says
```
time="2020-07-23T15:13:02+02:00" msg="OpenShift Installer 4.5.0-0.okd-2020-07-14-153706-ga"
```

Are you sure `install_dir` is brand new and doesn't have any hidden files?

**Comment by aholen** [comment]
Sorry, that was an old log, attaching the current.
[openshift_install-redacted.log](https://github.com/openshift/okd/files/5238842/openshift_install-redacted.log)

**Comment by vrutkovs** [comment]
hmm, fails on OVA import and doesn't have more info other than `cluster '/XXX/host/yyyCluster-XXX' not found`. Check credentials / permissions?

Try uploading OVA manually and use [OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE](https://github.com/openshift/installer/blob/release-4.5/docs/dev/openstack/customization.md)?

**Comment by penguinpages** [comment]
did you import key from vcenter into cluster configuration?

Example:
# Add vCenter root CA certificate to system trust
wget https://vc01.aessatl.acme.com/certs/download.zip --no-check-certificate
mv download.zip ibmvc01_vCenter_cert.zip
unzip ibmvc01_vCenter_cert.zip
sudo cp certs/lin/* /etc/pki/ca-trust/source/anchors
sudo update-ca-trust extract


Then openshift install wizard will connect to vCenter to pull live the enviornment settings

**Comment by aholen** [comment]
@penguinpages Yes, I have installed the CA's and verified by comparing the serial# from the file certs/mac/0b28ac86.0 and the certificate in the mac's KeyChain.

The installer has already pulled the live environment settings from vcenter, so that's another confirmation that the CA is installed.

**Comment by aholen** [comment]
@vrutkovs Thanks, will try that. What would be the correct OVA to download and import?

**Comment by penguinpages** [comment]
With IPI ... their is no need to pull down an OVA anymore.   The terraform scripts do that for you..  So long as your systems have internet connection.

One thing I have / am running into is the deployment is very  brittle when it comes to pulling the updates for RHCOS... once the VMS for 3 x masters are created.. they reach out to update themselves ..  and though basic IP / routing works... one of my vSphere nodes seems to have enough delay that it gags the installer... result is flaky deployment.    I have not root caused why basic download from wget as test work.. but the terriform ones are very picky or have issues with latency and so fail...    

End result is hung deployment.. in loop of trying to provision masters..    Still trying to root cause

**Comment by aholen** [comment]
@penguinpages I know, but this is bc the troubleshooting-steps described by @vrutkovs above.

**Comment by penguinpages** [comment]
Not sure with IPI deployment how you could point to existing image with Hypervisor.    I have tried to find stanza to add to "install-config.yaml"  for both VMWare and oVirt where I could just bypass a 8GB download ... and use one existing.  Not only would this make it go much faster, but when your setting up a 5 person class ... that would really streamline install time. 


If anyone knows how to do this... let me know.   Me...  I would just let IPI deploy..  "rename" the one it deploys.. to then call for subsequent installs.   

As for how to get OVA and deploy... see bellow notes from UPI that you do to bring in OVA ... what I have not investigated is if the terraform script pulls base then modifies the 

# Pull OVA
wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-4.5.6-x86_64-vmware.x86_64.ova

# UPI OVA modificiations for VMs

guestinfo.ignition.config.data | <changeme>
-- | --
guestinfo.ignition.config.data.encoding | base64
disk.EnableUUID | TRUE


personally... I would just direct import OVA and bind to storage and port group that is target...   Please post once you learn if / how to modify install-config.yaml to use this template.

**Comment by turguns** [comment]
Hi team,
During IPI installation on Vmware Vshpere  got the same error.  
INFO Creating infrastructure resources...         
ERROR                                              
ERROR Error: failed to lease wait: Invalid configuration for device '0'. 
ERROR                                              
ERROR   on ../../../tmp/openshift-install-585067796/main.tf line 43, in resource "vsphereprivate_import_ova" "import": 
ERROR   43: resource "vsphereprivate_import_ova" "import" { 
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 

On Vmware Vpshere events the error is: " Invalid configuration for device '0' Device: Virtual Disk"
 I can manually deploy the ova with service account.(it has administrator right) . So there is no issue with permissions.
Certificates of Vsphere are also trusted.
Any clue?
Regards,
![deploy-error-when-import-ova](https://user-images.githubusercontent.com/36400060/97792133-56a74780-1beb-11eb-8738-9aad941598ab.PNG)
![deploy-error-when-import-ova-cli](https://user-images.githubusercontent.com/36400060/97792134-58710b00-1beb-11eb-9316-9c09af0c1b28.PNG)
[.openshift_install.log](https://github.com/openshift/okd/files/5469978/default.openshift_install.log)

**Comment by gunjangarge** [comment]
@penguinpages  I believe local OVA image url can be given in "install-config.yaml" as value to clusterOSImage key under platform.vsphere. You will need to download OVA image and host it on local web server.

```
$ openshift-install explain installconfig.platform.vsphere.clusterOSImage
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <string>
  ClusterOSImage overrides the url provided in rhcos.json to download the RHCOS OVA
```

**Comment by leewx95** [comment]
[openshift_install.log](https://github.com/openshift/okd/files/6215995/openshift_install.log)
In my scenarios, certs are valid and vcenter connection stage has past, was able to see the cluster being created in vcenter. But hit this error (as attached). Am using openshift-install-linux-4.7.0-0.okd-2021-03-21-094146.tar.gz installer.

`[root@rhel8 ~]# ./openshift-install create cluster --dir=/opt/okd/ --log-level=info
INFO Creating infrastructure resources...
ERROR
ERROR Error: failed to upload: Post "https://192.168.13.22/nfc/520c3a9f-94a0-99e0-2830-ffe7940099f1/disk-0.vmdk": dial tcp 192.168.13.22:443: connect: connection timed out
ERROR
ERROR   on ../tmp/openshift-install-798229981/main.tf line 43, in resource "vsphereprivate_import_ova" "import":
ERROR   43: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
[root@rhel8 ~]#`
