### ISSUE TITLE
community-operators is failing / OperatorHub does not show operators

### ISSUE THREAD

**Issue by Born2Bake** [openshift/okd#333]
*Describe the bug**
openshift-marketplace/community-operators pod is failing therefore, OperatorHub page does not show anything.

**Version**
4.5.0-0.okd-2020-09-04-180756

**How reproducible**
Deployed OKD using this guide https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee

**Log bundle**
openshift-marketplace/community-operators pod logs: http://paste.openstack.org/show/797992/
Screenshots: https://prnt.sc/uiuhn8 https://prnt.sc/uiui67 https://prnt.sc/uiuiia

Gathering data link: https://mega.nz/file/yF1SFQzK#-9-WwNjuWUIh6L12BoxW7i69sArvInGfxr2Bq6akE-4

**Comment by vrutkovs** [comment]
```
queueinformer_operator.go:290] sync {"update" "openshift-marketplace/community-operators"} failed: etcdserver: request timed out
```
in OLM pods and 
```
2020-09-17T10:52:09.078050722Z 2020-09-17 10:52:09.077938 W | etcdserver: read-only range request "key:\"/kubernetes.io/serviceaccounts/openshift-kube-scheduler/localhost-recovery-client\" " with result "range_response_count:1 size:407" took too long (451.82714ms) to execute
```
in etcd pods with a bunch of 
```
2020-09-17T09:26:59.182333486Z raft2020/09/17 09:26:59 INFO: raft.node: 120943161d89e75c lost leader 4e3825eb484fd55d at term 108
```
(approx. every 5 mins or so leader is lost and all connections are being broken).

Is etcd backed up by a fast enough storage? Check etcd metrics dashboard

**Comment by Born2Bake** [comment]
> 
> 
> ```
> queueinformer_operator.go:290] sync {"update" "openshift-marketplace/community-operators"} failed: etcdserver: request timed out
> ```
> 
> in OLM pods and
> 
> ```
> 2020-09-17T10:52:09.078050722Z 2020-09-17 10:52:09.077938 W | etcdserver: read-only range request "key:\"/kubernetes.io/serviceaccounts/openshift-kube-scheduler/localhost-recovery-client\" " with result "range_response_count:1 size:407" took too long (451.82714ms) to execute
> ```
> 
> in etcd pods with a bunch of
> 
> ```
> 2020-09-17T09:26:59.182333486Z raft2020/09/17 09:26:59 INFO: raft.node: 120943161d89e75c lost leader 4e3825eb484fd55d at term 108
> ```
> 
> (approx. every 5 mins or so leader is lost and all connections are being broken).
> 
> Is etcd backed up by a fast enough storage? Check etcd metrics dashboard

I assume that happened once I ve added nfs storage for internal-registry. I had a lot of alerts related to api/controllers/etcd... and do not have them any more: https://prnt.sc/uivhzc ; https://prnt.sc/uivi68

**Comment by vrutkovs** [comment]
This might have caused a lot of new pods, yes. There isn't much we can do about it though, you need faster etcd storage / network
