### ISSUE TITLE
ip address of vcenter platform  after installating of okd 4.5

### ISSUE THREAD

**Issue by behnm** [openshift/okd#335]
I installed okd with vmware UPI to use dynamic pvc feature.

My cluster is up and running Now. However I need to change ip address of vcenter which is presented to okd 4.5.
The ip address is not defined at storage operator and config operator too.

**Comment by kai-uwe-rommel** [comment]
It is (on each cluster node) in /etc/kubernetes/cloud.conf ... not easy to change.
See here: https://github.com/openshift/okd/issues/224

**Comment by behnm** [comment]
> 
> 
> It is (on each cluster node) in /etc/kubernetes/cloud.conf ... not easy to change.
> See here: #224

The issue #224 tells , "Its not supported".However you said its not easy to change. Is it possible or impossible?

**Comment by kai-uwe-rommel** [comment]
You probably can do it, but you need to do it manually on each master node.
I'm just a user like you. The OKD team told "it is not supported" - as you can see in #224 
I only wanted to point you to the older issue which I had opened.

**Comment by behnm** [comment]
> 
> 
> You probably can do it, but you need to do it manually on each master node.
> I'm just a user like you. The OKD team told "it is not supported" - as you can see in #224
> I only wanted to point you to the older issue which I had opened.

Thanks. 
However I changed the config on all nodes. However the config did not worked .

**Comment by kai-uwe-rommel** [comment]
Did you restart kubelet on the nodes? Perhaps that's sufficient?

**Comment by behnm** [comment]
> 
> 
> Did you restart kubelet on the nodes? Perhaps that's sufficient?

all restarted whole the cluster. but it didnt change.

**Comment by vrutkovs** [comment]
Dupe of #224
