### ISSUE TITLE
Image Pruner - Taking Longer than 12 hours to complete / or complete failure

### ISSUE THREAD

**Issue by Les-Linux** [openshift/okd#336]
**Describe the bug**
I am seeing the following to entries in the status viewer, in a newly deployed OKD4 instance
1. Job openshift-image-registry/image-pruner-1600214400 is taking more than 12 hours to complete
2. Job openshift-image-registry/image-pruner-1600128000 failed to complete

**Version**
4.5.0-0.okd-2020-09-18-202631

**How reproducible**
This is a new deployment, cluster, control plane and operators show to be in a green state

**Log bundle**
https://drive.google.com/drive/folders/1x4sIYpiOU1XmP0NlhoBq05sii1T44RtT?usp=sharing

**Comment by vrutkovs** [comment]
This seems to affect OCP as well, please file a bug at https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform, component: "image registry"
