### ISSUE TITLE
After Having OKD 4.5.0-0.okd-2020-09-18-202631 shutdown for a day

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#337]
After Having OKD 4.5.0-0.okd-2020-09-18-202631 shutdown for a day.
When I try to bring it back back up the API Server comes up, but the Config server doesn't

<img width="1118" alt="2020-09-22_16-46-46" src="https://user-images.githubusercontent.com/23619505/93935866-4a2df600-fcf3-11ea-93f7-98e7187f0ef0.png">

**Comment by vrutkovs** [comment]
Machine config server didn't come up. See [troubleshooting information](https://docs.okd.io/latest/installing/installing-troubleshooting.html)

**Comment by johnlongo** [comment]
Had to break it up into individual zip files, because the original file was 30 meg

[bootstrap.zip](https://github.com/openshift/okd/files/5264236/bootstrap.zip)
[control-plane.zip](https://github.com/openshift/okd/files/5264237/control-plane.zip)
[rendered-assets.zip](https://github.com/openshift/okd/files/5264238/rendered-assets.zip)
[resources.zip](https://github.com/openshift/okd/files/5264240/resources.zip)
[unit-status.zip](https://github.com/openshift/okd/files/5264241/unit-status.zip)
[failed-units.txt](https://github.com/openshift/okd/files/5264242/failed-units.txt)

**Comment by vrutkovs** [comment]
Your cluster has completed the install, you must [remove the bootstrap node](https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-installing-bare-metal_installing-bare-metal) before starting worker nodes.

All of the nodes are posting "unreachable" status, as [CSRs were not approved](https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-approve-csrs_installing-bare-metal)

**Comment by johnlongo** [comment]
I know the cluster was up and running for a couple of days and then I shut it down and kept it down for a day. I then tried to bring it back up and it didn't come up. I started the bootstrap just to create the debug info for you.

**Comment by vrutkovs** [comment]
>I know the cluster was up and running for a couple of days ... I started the bootstrap just to create the debug info for you

In that case you need to collect [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html). Don't rush with it yet, did CSR approval fix it?

**Comment by johnlongo** [comment]
I cant login to the server
oc adm must-gather
[must-gather      ] OUT Unauthorized
[must-gather      ] OUT
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/origin-must-gather:latest
error: You must be logged in to the server (Unauthorized)
[root@okd4-config install]#

**Comment by johnlongo** [comment]
I ended up just recreating the cluster, thank you for your time.

**Comment by LorbusChris** [comment]
@johnlongo it looks like you weren't logged in to your cluster with `oc`. The `openshift-install` command tells you how to do that (export KUBECONFIG env var and grab a token from the webconsole).
