### ISSUE TITLE
Node status NotReady after rebooting master node

### ISSUE THREAD

**Issue by achilles-git** [openshift/okd#338]
**Describe the bug**

 I am using OKD 4.5 with FCOS ,recently I rebooted a master node and now the master node status is NotReady.
i ran the `$oc describe master1.node.com` and output was kubelet stopped posting status.
also I tried to check if there are any pending CSR requests by `$oc get csr` found that there are csr requests from `system:node:localhost` ,but I have no node named localhost in the cluster.(kubelet might have started before the hostname stabilizes)
also restarting  kubelet `$systemctl restart kubelet` is not helping
**Version**

Server Version: 4.5.0-0.okd-2020-07-29-070316

**How reproducible**

Restarting the master node 
**Log bundle**

attaching kubelet logs from master1 for reference

[master1.log.zip](https://github.com/openshift/okd/files/5267752/master1.log.zip)

**Comment by behnm** [comment]
I have the same issue. 
Does not have any solution ?

**Comment by achilles-git** [comment]
In my case, i had to delete the node resource and add it back to the cluster

**Comment by vrutkovs** [comment]
No log bundle provided, closing

**Comment by dcdh** [comment]
> In my case, i had to delete the node resource and add it back to the cluster

How did you did it ?

**Comment by achilles-git** [comment]
@dcdh 
you can delete a node by `oc delete node node_name`

and the new node will be automatically added to cluster when you bootup(you just have to approve csr)

**Comment by aelek73** [comment]
I faced with the same issue, which has been solved by approve all CSR:
`oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs oc adm certificate approve`
