### ISSUE TITLE
oc rsh doesn't work as the help info says it should

### ISSUE THREAD

**Issue by lousyd** [openshift/okd#339]
**Describe the bug**
I get an error when I use `oc rsh` the way --help info says it should be used. `oc rsh --help` says this:

```bash
$ oc rsh --help
[...]
Usage:
  oc rsh (POD | TYPE/NAME) [-c CONTAINER] [flags] -- COMMAND [args...]
[...]
```

So I do this:

```bash
$ oc get pod/myname-web-7-4j5jq -n myname-test1 -o json | jq -r '.spec.containers[].name'
php-fpm
nginx

$ oc rsh pod/myname-web-7-4j5jq -c php-fpm
Defaulting container name to php-fpm.
Use 'oc describe pod/myname-web-7-4j5jq -n myname-test1' to see all of the containers in this pod.
ERRO[0000] exec failed: container_linux.go:349: starting container process caused "exec: \"-c\": executable file not found in $PATH" 
exec failed: container_linux.go:349: starting container process caused "exec: \"-c\": executable file not found in $PATH"
command terminated with exit code 1
```

I've tried variations of the `oc rsh` command. What does work is when I put "-c php-fpm" between "rsh" and "pod/...".

```bash
$ oc rsh -c php-fpm pod/myname-web-7-4j5jq
/var/www/html #
```

If it really should work with the "-c containername" at the end, then maybe this is a bug. But if "-c containername" should be before the pod name, then maybe the "--help" info just needs to clarify that.

**Version**
4.4.0-0.okd-2020-05-23-055148-beta5
IPI

**How reproducible**
100%

**Log bundle**
Do you need `oc adm must-gather` info for this? If so I can do that.

**Comment by vrutkovs** [comment]
>If it really should work with the "-c containername" at the end, then maybe this is a bug

There is no way for `oc` to distinct `-c` as a param for oc and your custom command. Please file a bug at https://github.com/openshift/oc

**Comment by lousyd** [comment]
Will do. Thank you.
