### ISSUE TITLE
Disaster recovery process failed on okd 4.5  

### ISSUE THREAD

**Issue by behnm** [openshift/okd#340]
Hi
I needed backup and restore my cluster and use the below links for these processes.
https://docs.okd.io/latest/backup_and_restore/backing-up-etcd.html
https://docs.okd.io/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html

I did several steps and mentioned at below.

**1. for backup**

```
oc debug node/master1.dev.cloud.local
chroot /host
/usr/local/bin/cluster-backup.sh /home/core/backup
```
**2. for restore**
after backing up the cluster. I removed whole the cluster and implement the new cluster without any specific config. After launching the new cluster I did the below steps.

_on master recovery node:_
`scp /openshift/backup/ core@X.X.X.211:/home/core/`

_on other master nodes except recovery node:_
```
sudo mv /etc/kubernetes/manifests/etcd-pod.yaml /tmp
sudo crictl ps | grep etcd
sudo mv /etc/kubernetes/manifests/kube-apiserver-pod.yaml /tmp
sudo crictl ps | grep kube-apiserver
sudo mv /var/lib/etcd/ /tmp
```
_on master recovery node:_
`sudo -E /usr/local/bin/cluster-restore.sh /home/core/backup`

_on all master nodes_
`sudo systemctl restart kubelet.service`

_on master recovery node:_
```
sudo crictl ps | grep etcd
oc get pods -n openshift-etcd | grep etcd
```

In this step, albeit all previous steps did successfully, I faced with below error after command "oc get pods -n openshift-etcd | grep etcd"
`[Error from server (InternalError): an error on the server ("") has prevented the request from succeeding]`

Why these process failed ?

**Comment by vrutkovs** [comment]
Please don't use bugtracker as a support tool. Is this a documentation issue or an OKD-specific bug? Is this issue happening on OCP?

If its an OKD-specific bug please attach necessary debug information - version, your cluster configuration (platform, number of nodes) must-gather (if possible) or apiserver / etcd pod logs.

**Comment by behnm** [comment]
It could be doc issue, but i'm not sure. 
I did disaster plan step by step, but at "etcd running" step, apiserver on port 6443 couldn't be started again.

- okd version: OKD4.5-2020-09-04
- my cluster has 5 nodes (3 masters and 2 workers)

I could not gather logs, because apiServer isn't running.
