### ISSUE TITLE
4.6: use cri-o 1.19

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#341]
* [x] Use [Fedora package](https://koji.fedoraproject.org/koji/packageinfo?packageID=24240)
  It appears its outdated and available for F33
* [ ] Use [OBS](https://build.opensuse.org/project/show/devel:kubic:libcontainers)
  Doesn't seem to have packages for Fedora
* [ ] Use [static binaries](https://github.com/cri-o/cri-o/releases/tag/v1.19.0)

@haircommander @lsm5 @dustymabe what would the best way to install CRI-O? 
Also, in 4.7 we'd probably want to use latest tested commit - I guess we should be picking it from [GCS](https://console.cloud.google.com/storage/browser/k8s-conform-cri-o/artifacts)?

**Comment by lsm5** [comment]
There's a nightly job running for cri-o 1.19, but looks like there were some dist-git push issues. I'll fix them right away.

I'll defer to @haircommander for long term plans.

**Comment by haircommander** [comment]
It seems long term we're planning on keeping the native fedora packages, assuming we find someone to take it over, as I do not have time. if that falls through, it'll be OBS

**Comment by vrutkovs** [comment]
Seems there is a F33 module (we'll use it), but no bodhi release, so we can't use `dnf module enable crio:1.19` - @lsm5 could you create a new release in bodhi?

**Comment by vrutkovs** [comment]
Included in https://amd64.origin.releases.ci.openshift.org/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2020-11-27-102402
