### ISSUE TITLE
Vsphere IPI fails

### ISSUE THREAD

**Issue by coppin-j** [openshift/okd#342]
**Describe the bug**
openshift-install-4.5 create cluster --dir=okd-install
INFO Consuming Install Config from target directory 
INFO Obtaining RHCOS image file from 'https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20200629.3.0/x86_64/fedora-coreos-32.20200629.3.0-vmware.x86_64.ova?sha256=172f299a3e28be360740ff437a5ea9bfc246f52ea8f313d4138c5d16fd4b11e1' 
INFO The file was found in cache: /home/jcoppin/.cache/openshift-installer/image_cache/062bfe3785d26fa220e2e6e72d1b3562. Reusing... 
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd.radiumnetwork.corp:6443... 
INFO API v1.18.3 up                               
INFO Waiting up to 40m0s for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 30m0s for the cluster at https://api.okd.radiumnetwork.corp:6443 to initialize... 
ERROR Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingEndpoints::RouteStatus_FailedHost: IngressStateEndpointsDegraded: No endpoints found for oauth-server
RouteStatusDegraded: route is not available at canonical host oauth-openshift.apps.okd.radiumnetwork.corp: [] 
INFO Cluster operator authentication Progressing is Unknown with NoData:  
INFO Cluster operator authentication Available is Unknown with NoData:  
INFO Cluster operator console Progressing is True with DefaultRouteSync_FailedAdmitDefaultRoute::OAuthClientSync_FailedHost: DefaultRouteSyncProgressing: route "console" is not available at canonical host []
OAuthClientSyncProgressing: route "console" is not available at canonical host [] 
INFO Cluster operator console Available is Unknown with NoData:  
INFO Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available. 
INFO Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available. 
ERROR Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: default 
INFO Cluster operator insights Disabled is True with Disabled: Health reporting is disabled 
INFO Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available 
INFO Cluster operator monitoring Available is False with :  
INFO Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack. 
ERROR Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager Route to become ready failed: waiting for RouteReady of alertmanager-main: no status available for alertmanager-main 
FATAL failed to initialize the cluster: Some cluster operators are still updating: authentication, console, csi-snapshot-controller, ingress, kube-storage-version-migrator, monitoring 

3 master nodes are deployed, no worker nodes

Vsphere Version:	7.0D	Build:	16749670

**Version**
Tried multiple versions, latest 4.5 stable, latest 4.5 nightly,  latest 4.6 nightly

**How reproducible**
openshift-install create cluster --dir=okd-install

install-config.yml
`apiVersion: v1
baseDomain: radiumnetwork.corp
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 8196
      osDisk:
        diskSizeGB: 120
  replicas: 5
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 6
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 3
metadata:
  creationTimestamp: null
  name: okd
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 172.16.10.200
    cluster: Cluster
    datacenter: Radium
    defaultDatastore: SSD-DS1
    ingressVIP: 172.16.10.201
    network: VLAN10
    password: removed
    username: administrator@vsphere.local
    vCenter: vsphere.radiumnetwork.corp
publish: External
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: |
`

**Log bundle**

**Comment by coppin-j** [comment]
[must-gather.tar.gz](https://github.com/openshift/okd/files/5296473/must-gather.tar.gz)

**Comment by vrutkovs** [comment]
Workers were not created - machine-api fails to reconcile with
```
2020-09-29T04:40:56.88727627Z I0929 04:40:56.887232       1 actuator.go:80] okd-4txlj-master-2: actuator checking if machine exists
2020-09-29T04:40:56.904440519Z E0929 04:40:56.904354       1 controller.go:272] okd-4txlj-master-2: failed to check if machine exists: okd-4txlj-master-2: failed to create scope for machine: failed to create vSphere session: error setting up new vSphere SOAP client: Post https://vsphere.radiumnetwork.corp/sdk: dial tcp 172.16.10.201:443: connect: connection refused
```

Check your firewall settings?

**Comment by coppin-j** [comment]
No firewall involved, all servers in the same network. 
VSphere is running on the same esx host as the master nodes, in the same vlan
Master nodes are able to access vsphere sdk, this is Vsphere 7.0D 
[core@okd-4txlj-master-0 ~]$ curl https://vsphere.radiumnetwork.corp/sdk/vimService.wsdl
<?xml version="1.0" encoding="UTF-8" ?>

<definitions targetNamespace="urn:vim25Service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:interface="urn:vim25"
>
   <import location="vim.wsdl" namespace="urn:vim25" />
   <service name="VimService">
      <port binding="interface:VimBinding" name="VimPort">
         <soap:address location="https://localhost/sdk/vimService" />
      </port>
   </service>
</definitions>

**Comment by vrutkovs** [comment]
Your `ingressVIP` is set to 172.16.10.201. Is this the correct address for the LB? Does `vsphere.radiumnetwork.corp/sdk/vimService.wsdl` get resolved to this address on your machine too?

**Comment by coppin-j** [comment]
Post https://vsphere.radiumnetwork.corp/sdk: dial tcp 172.16.10.201:443: connect: connection refused
For some reason it is resolving everything in basedomain to the ingress controller

i had an additional wildcard for *.cluster.basedomain as well ass  *.app.cluster.basedomain once i deleted this extra wildcard dns entry the workers started to deploy

**Comment by vrutkovs** [comment]
>i had an additional wildcard for *.cluster.basedomain

Ah, yes, that would break hostname resolution. Closing
