### ISSUE TITLE
The post-installation section of the documentation does not include any information on adding additional FCOS nodes

### ISSUE THREAD

**Issue by JaimeMagiera** [openshift/okd#344]
**Describe the bug**

The post-installation section of the documentation does not include any information on adding additional FCOS nodes < or > 24 hours.

**Version**

The "4.5 Latest" version of the documentation. 

**How reproducible**

100%

**Log bundle**

https://docs.okd.io/latest/post_installation_configuration/node-tasks.html

Comments: 

It might seem tangential at first, but it's a common question. Adding this would help fill out the documentation, thereby helping adoption.

**Comment by bdlink** [comment]
OKD latest re 4.6.0-0.okd-2021-01-17-185703 still does not seem to discuss adding new nodes to a UPI cluster.

**Comment by mburke5678** [comment]
@JaimeMagiera @vrutkovs Do we have anything written down on how to add FCOS nodes?

**Comment by vrutkovs** [comment]
This partially covered in https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#creating-machines-bare-metal during installation.

I think we need a special section in `Nodes -> Working with nodes` mentioning that UPI cluster can be extended by booting more nodes with worker.ign (and scaling the machineset in IPI or where available). This is also affecting OCP I suppose

**Comment by mburke5678** [comment]
We have this Adding compute machines to bare metal
https://docs.okd.io/latest/machine_management/user_infra/adding-bare-metal-compute-user-infra.html

**Comment by vrutkovs** [comment]
Ah, perfect, I don't think I saw it in 4.5. Thanks, closing

**Comment by mburke5678** [comment]
@vrutkovs What is we just include the _Adding compute machines to bare metal_ topic to the _Post-installation node tasks_ topic, so the material is in both sections? 
http://file.rdu.redhat.com/~mburke/issue-344/post_installation_configuration/node-tasks.html (internal RH link)

**Comment by vrutkovs** [comment]
Yeah, that sounds like a good idea. Its not trivial to discover some sections, so I'm in favor of mentioning some twice
