### ISSUE TITLE
Enabling Octavia (Openstack) support in a cluster AFTER initial deployment?

### ISSUE THREAD

**Issue by gerr1t** [openshift/okd#349]
**Describe the bug**
Currently, the support for OpenStack Octavia is set in the openshift-install configuration, with the option: octaviaSupport. That option is automatically set to 0 or 1, depending on whether that service is available in the OpenStack cluster.
I have an OKD 4 cluster deployed on an OpenStack cluster without Octavia support. However, recently we deployed Octavia in the OpenStack cluster and therefore I would like to enable Octavia support in the existing cluster.

I have read the following documentation, however, it is related to a Kuryr deployment, which we are not using:
https://docs.okd.io/latest/networking/load-balancing-openstack.html

Is it possible to enable support for Octavia AFTER the OKD cluster has been deployed without that support? 

**Version**
4.5.0-0.okd-2020-09-04-180756

**Comment by mandre** [comment]
Hi @gerr1t , sorry for the delay, hopefully you have found your answer by now. It's possible to enable Octavia integration after the fact.

You'll need to edit your openstack cloud provider configuration:
```
oc edit cm cloud-provider-config -n openshift-config
```

And make sure that under `data.config` you have:
```
[LoadBalancer]
use-octavia = true
```

See the [cloud provider documentation](https://v1-18.docs.kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancer) for available configuration options.

The `use-octavia` is currently not enabled by default, but will be in future versions of OKD.

**Comment by vrutkovs** [comment]
We're using this trick in CI (to pass service distruption tests), so it works
