### ISSUE TITLE
MCO reporting node not found after restart of mcd pods

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#35]
While debugging an issue related to pull secrets in MCO, the machine config daemon did not come back up after a pod delete and instead reported the following:

```
W0115 15:30:05.615694 2039508 daemon.go:557] Got an error from auxiliary tools: error: cannot apply annotation for SSH access due to: unable to update node "nil": node "master-0" not found
```
The same log can be found on all mcd pods in the cluster post-reboot.
Is this related to the fork changes for MCO?

Version: registry-svc-ci-openshift-org-origin-4-4-2020-01-14-215321

----------------------

Interesting, on a brand new install without any changes, I can't get any worker nodes to join at all:
```
Jan 15 16:40:43 worker-1 hyperkube[31249]: E0115 16:40:43.533178   31249 reflector.go:156] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://api-int.okd.blah.net:6443/api/v1/nodes?fieldSelector=metadata.name%3Dworker-1&limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")
Jan 15 16:40:43 worker-1 hyperkube[31249]: E0115 16:40:43.543711   31249 kubelet.go:2271] node "worker-1" not found
```
EDIT: Still not sure why it happens, it has happened multiple times since then, and I seem to get it to work by re-running ignition script and therefore re-installing fcos on the node in question.

**Comment by vrutkovs** [comment]
Is it still happening in recent builds?

**Comment by jdhirst1** [comment]
This hasn't occurred in recent test last night. This should be able to be closed.
