### ISSUE TITLE
OKD4.5 update failed-machine config operator

### ISSUE THREAD

**Issue by MerveeYilmaz** [openshift/okd#351]
Hi all,

I updated Okd4.5 cluster to version 4.5.0-0.okd-2020-09-18-202631. But the current version appears to be 4.5.0-0.okd-2020-08-12-020541.

As I noticed this later, I tried to update the cluster to the newest version 4.5.0-0.okd-2020-10-03-012432 after the first update but it was not successful. The machine config operator gives an error as below.

Unable to apply 4.5.0-0.okd-2020-10-03-012432: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: controller version mismatch for rendered-master-

Anyone have any suggestion?

**Comment by vrutkovs** [comment]
Please collect [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html) and link it here
