### ISSUE TITLE
GCP Builds Fail since 4.6.0-0.okd-2020-10-08-055226

### ISSUE THREAD

**Issue by bdurrow** [openshift/okd#352]
**Describe the bug**

Master nodes do not provision because they an not connect to the internal api endpoint with logged errors like this:

.//control-plane/10.124.0.3/journals/kubelaet.log:Oct 13 15:02:01 fedora hyperkube[1290]: E1013 15:02:01.565148    1290 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://api-int.cluster.mycompany.com:6443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 10.124.0.4:6443: connect: connection refused

I could hit port 6443 on the bootstrap node from master-0 directly but not through the load balancer (connection refused).  When I updated the gca-dev4-497xf-api-internal load balancer to remove the master nodes from the available backends I could get hit port 6443 both to the bootstrap node directly and through the endpoint.

I have seen this before where when a backend tries to hit a load balancer it is reflected back to the backend regardless of health check status. This behavior is documented in [1] and [2]. I believe this is what is happening.  I was not able to install tcpdump on the bootstrap node or the master-0 node to confirm this was what was happening.

[1] https://cloud.google.com/load-balancing/docs/internal#single_client_tests

[2] https://cloud.google.com/load-balancing/docs/internal/setting-up-internal#test-from-backend-vms

To work around this limitation with the smallest changeset I modified the gcp/network/lb-private.tf template for the api_internal backend service initially only contains the bootstrap instance group.  Later when we set var.bootstrap_lb to false during bootstrap teardown the bootstrap instance group is replace with the master instance groups.

Doing this allowed me to get further but bootstrapping still fails.

**Version**

4.6-2020-10-13-143951 IPI on GCP
**How reproducible**

Always
**Log bundle**

**Comment by bdurrow** [comment]
It looks like the hostname is not set correctly for the masters.  It is set to fedora.  This causes the problem mentioned in this log line:
```
Oct 13 20:21:25 gca-dev4-zvqzf-master-0 hyperkube[10974]: I1013 20:21:25.464018   10974 csi_plugin.go:994] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "gca-dev4-zvqzf-master-0" is forbidden: User "system:node:fedora" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node
```
If I manually set the hostname during the bootstrap process the master nodes will provision and we clear the bootstrap gate.

**Comment by bdurrow** [comment]
Further investigation found that the hostname is set correctly during firstboot but not after pivot.  I don't have the skills to figure out what went wrong.  I'm testing this workaround (applied after `openshift-installer create manifest --dir ${OKD_INSTALLER_DIR}`

```
for role in master worker; do
echo "Creating ${OKD_INSTALLER_DIR}/openshift/99_openshift-machineconfig_99-${role}-hostname-workaround.yaml"
cat > ${OKD_INSTALLER_DIR}/openshift/99_openshift-machineconfig_99-${role}-hostname-workaround.yaml <<HOSTNAME_UNIT
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: null
  labels:
    machineconfiguration.openshift.io/role: ${role}
  name: 99-{role}-hostname-workaround
spec:
  config:
    ignition:
      version: 3.1.0
    units:
      - name: afterburner-hostname.service
        enabled: true
        contents: |
          [Unit]
          Description=Afterburn Hostname
          Before=network-online.target
          Before=node-valid-hostname.service
          ConditionPathExists=/sysroot/etc/hostname

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          User=root
          ExecStart=/usr/bin/afterburn --cmdline --hostname=/sysroot/etc/hostname
          TimeoutSec=300

          [Install]
          WantedBy=multi-user.target
          RequiredBy=network-online.target
  extensions: null
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""
HOSTNAME_UNIT
done
```

**Comment by vrutkovs** [comment]
GCP builds indeed fail, but iiuc https://github.com/openshift/machine-config-operator/pull/2158 is the reason for this

**Comment by vrutkovs** [comment]
Still not sure what's causing it, some observations:
* doesn't happen on AWS
* worked as expected on F32 content, so most likely its some change in afterburn
* NetworkManager-ovs installation on start might be related

**Comment by bdurrow** [comment]
With these two changes I can build a cluster in GCP (with 4.6.0-0.okd-2020-10-14-045316).  I haven't had time to test without the load balancer change. I think that the load balancer problem will present itself when trying to replace a failed master so I'll test that scenario today.

**Comment by bdurrow** [comment]
Rebased https://github.com/openshift/machine-config-operator/pull/2158 in https://github.com/openshift/machine-config-operator/pull/2160

**Comment by bdurrow** [comment]
I was able to create a cluster with just the hostname workaround.  I will close openshift/installer#4267.

**Comment by vrutkovs** [comment]
whew, this is fixed in https://amd64.origin.releases.ci.openshift.org/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2020-11-15-130950.

In https://github.com/openshift/okd-machine-os/pull/9 we're running Afterburn to set short hostname. If that fix would work for OKD, it would be used by [MCO](https://github.com/openshift/machine-config-operator/pull/2217). Finally, when NM fix lands we'll remove additional services when required.

Terribly sorry that it took so long to fix this in an important platform :/
