### ISSUE TITLE
docs: FCOS VMDK version confusion when installing OKD on AWS

### ISSUE THREAD

**Issue by marshallford** [openshift/okd#356]
**Describe the bug**

I was requested by @vrutkovs to submit a docs bug around a confusing step for "Uploading a custom FCOS AMI in AWS" that appears a couple of times on the OKD docs website.

The sentence:
> The FCOS VMDK file must be the highest version that is less than or equal to the OKD version you are installing.

My question on slack: FCOS stable is currently at version 32, while OKD is at 4.5. How do these two versions relate? How can I make sure I am downloading the correct FCOS image for a particular version of OKD?

The recommendation/answer: it makes sense for OCP but needs to be removed from OKD docs. In OKD case you'd pick the latest stable VMDK

Pages I found that had this step listed:

1. https://docs.okd.io/latest/installing/installing_aws/installing-aws-user-infra.html#installation-aws-upload-custom-rhcos-ami_installing-aws-user-infra
2. https://docs.okd.io/latest/installing/installing_aws/installing-aws-government-region.html#installation-aws-upload-custom-rhcos-ami_installing-aws-government-region

Thank you!

**Version**

N/A

**How reproducible**

N/A

**Log bundle**

N/A

**Comment by vrutkovs** [comment]
Right, this section needs to be hidden in OKD docs

**Comment by mburke5678** [comment]
@vrutkovs @marshallford PTAL 
https://github.com/openshift/openshift-docs/pull/28731

**Comment by mburke5678** [comment]
Close

**Comment by mburke5678** [comment]
close
