### ISSUE TITLE
Missing operators

### ISSUE THREAD

**Issue by devtech0101** [openshift/okd#358]
Most of operators are missing from OKD 4.5 latet release installation. The "Openshift Pipeline Operator" as mentioned here is not available for install. 

https://docs.okd.io/latest/pipelines/installing-pipelines.html

**Comment by cgruver** [comment]
It is annoying that we don't have all of the operators available for OKD yet.  We are working on it, but it's going to take some time to coordinate with all of the teams involved.

In the mean time, you can manually install the operator like I have done: https://github.com/cgruver/tekton-pipeline-okd4

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd/blob/master/FAQ.md#how-can-i-enable-the-non-community-red-hat-operators

**Comment by ibotty** [comment]
Sorry, that's not a resolution at all.  AFAICT, one cannot legally use the redhat operators on production setups without a (paid) redhat subscription.  Can we please leave an issue open that tracks the progress?  Or is there another place that contains the information?

**Comment by vrutkovs** [comment]
>one cannot legally use the redhat operators on production setups

That's correct. ToS for the token still applies to OKD.

>Can we please leave an issue open that tracks the progress? Or is there another place that contains the information?

I'm not sure what's the expected result - all Red Hat operators have community counterparts? That needs to be implemented by respective operator teams and submitted to community-operators repo. This happens async to OKD releases, so it shouldn't be tracked on OKD side imo
