### ISSUE TITLE
kube-apiserver not starting

### ISSUE THREAD

**Issue by 94DanielBrown** [openshift/okd#359]
**Describe the bug**

The kube-apiserver pod is not coming up correctly, the pertinent error seems to be:
`1 reflector.go:178] github.com/openshift/client-go/user/informers/externalversions/factory.go:101: Failed to list *v1.Group: the server could not find the requested resource (get groups.user.openshift.io)`
I have found several issues already raised with the same error message but the context seems different and the solution not applicable to this case.

This is causing the bootkube.service to fail with the following error because of course the kube-apiserver is not reachable:
`1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused`
```
[core@bootstrap ~]$ sudo crictl ps
CONTAINER           IMAGE                                                                                           CREATED             STATE               NAME                             ATTEMPT             POD ID
d3f7becb1b15a       fa5810b74cca75160ccc31d9d3ac7b242b4070f0ec2383ac19d9d1e2ebc050e7                                15 minutes ago      Running             cloud-credential-operator        3                   a51ebbaf7be8b
8c205d0335529       0d67431212aa49df6db29ffcd340f32ca7eb72403463afb942ed7f54d22ddb6e                                15 minutes ago      Running             kube-apiserver-insecure-readyz   3                   0517ff586e43f
1052b8254c061       f83587335a38ff419a786b7cc737c3cadf231d702095e870fd9c53d59e97f228                                16 minutes ago      Running             kube-apiserver                   58                  0517ff586e43f
ab2311882c1c4       quay.io/openshift/okd@sha256:6974c414be62aee4fde24fe47ccfff97c2854ddc37eb196f3f3bcda2fdec17b4   16 minutes ago      Running             cluster-version-operator         1                   3f5a1e65c44eb
dad4b65bb363b       f83587335a38ff419a786b7cc737c3cadf231d702095e870fd9c53d59e97f228                                16 minutes ago      Running             kube-scheduler                   1                   d0f83eb25b2d9
1ac2f5dca58cd       f83587335a38ff419a786b7cc737c3cadf231d702095e870fd9c53d59e97f228                                16 minutes ago      Running             kube-controller-manager          1                   e0072368f3d53
cdb0fbd538d99       f06b568f2423c2398529fdae134c5544da43c8c12a76b32ff878375e82dde489                                20 hours ago        Running             etcd-metrics                     0                   934a8c807096e
a55b0ae669a96       f06b568f2423c2398529fdae134c5544da43c8c12a76b32ff878375e82dde489                                20 hours ago        Running             etcd-member                      0                   934a8c807096e
1f09fca501d2f       2a7ab4efbaf182c1c786e5ce69486879c6e38914587e91c228cd3640ef669199                                20 hours ago        Running             machine-config-server            0                   58b5fb5baedd2
```

**Version**

I am doing a vsphere UPI install, static networking config
 is set via network manager files created by ignition. Using an already provisioned F5 load balancer. DNS entries are set.
```
openshift-install version
openshift-install 4.5.0-0.okd-2020-08-12-020541
```

**How reproducible**

100%

**Log bundle**

Unable to do a must-gather as kube-apiserver is the problem. Here are the kube-apiserver logs:
[kube-apiserver.gz](https://github.com/openshift/okd/files/5395532/kube-apiserver.gz)

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.openshift.com/container-platform/4.5/installing/installing-troubleshooting.html)

**Comment by 94DanielBrown** [comment]
Apologies,
[log-bundle-20201017133633.tar.gz](https://github.com/openshift/okd/files/5395676/log-bundle-20201017133633.tar.gz)

**Comment by vrutkovs** [comment]
Bootstrap started, but master(s) never requested Ignition and apparently didn't boot.

Check LB setup and make sure master nodes have booted.

**Comment by 94DanielBrown** [comment]
Master nodes had booted and weren't getting there config, I assumed the kube-apiserver had to come up first for some reason.
This was a LB setup problem port 22623 wasn't set up. Sorry I didn't have direct access and was under the impression it was.
