### ISSUE TITLE
MCO /etc/crio/crio.conf file conflict upon upgrading releases

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#36]
When updating from 4.4.0-0.okd-2020-01-14-215321 to 4.4.0-0.okd-2020-01-15-152306, (not sure if it happens for other release differences), an issue occurs where MCO attempts to overwrite the /etc/crio/crio.conf file but fails due to nodes containing different versions of this file than expected.

Couldn't fit log output due to size of config files, find it here: https://pastebin.com/kkdwSye7

**Comment by vrutkovs** [comment]
Ah, it seems we need to backport https://github.com/openshift/machine-config-operator/pull/1320 to `fcos` branch

**Comment by vrutkovs** [comment]
Should be fixed by https://github.com/openshift/machine-config-operator/pull/1372

**Comment by jdhirst1** [comment]
Issue fixed and merged, closing.
