### ISSUE TITLE
Cannot pull okd 4.5 image from registry

### ISSUE THREAD

**Issue by llomgui** [openshift/okd#360]
Hello,

I tried to update the cluster (okd 4.5 10-03) to the latest version (okd 4.5 10-15).
The update process is stuck at pulling the image from the registry.

Error: `Failed to pull image "registry.svc.ci.openshift.org/origin/release@sha256:67cc7cb47d56237adcf0ecc2ee76446785add5fa236cd08746b55f578b9200a5": rpc error: code = Unknown desc = Error reading manifest sha256:67cc7cb47d56237adcf0ecc2ee76446785add5fa236cd08746b55f578b9200a5 in registry.svc.ci.openshift.org/origin/release: received unexpected HTTP status: 500 Internal Server Error`

Do you have the same error? Is it on registry side?

**Comment by vrutkovs** [comment]
Yeah, `registry.svc.ci.openshift.org` is having an outage. It should be available shortly

**Comment by vrutkovs** [comment]
This has been resolved. Not changes necessary, the cluster would pull the image now
