### ISSUE TITLE
Include ''policycoreutils-python-utils" to install semanage on FCOS for KubeVirt

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#361]
Hi,

I tried to install KubeVirt (OpenShift Virtualization Operator from the Red Hat Catalog) on FCOS (OKD 4.6 latest nightly). The "virt-handler" pods are constantly crashlooping because they can't find the tool 'semanage' on the FCOS hosts.

I had to install the package 'policycoreutils-python-utils' to get it working:

```
rpm-ostree install policycoreutils-python-utils -r 
```

After that the virt-handler pods entered running state and KubeVirt worked.

Could you add this package to FCOS, please?

Greetings,

Josef

**Comment by jomeier** [comment]
https://github.com/kubevirt/kubevirt/issues/3129

should take care about it but it seems to be missing in latest OKD 4.6 nightlies.

**Comment by LorbusChris** [comment]
Where did you get the operator from? Or did you build it yourself? Please report a build commit and/or version.

There is no dependency on `semanage` in kubevirt as of https://github.com/kubevirt/kubevirt/pull/2694.

No non-core operators are included in the OKD release payload.
The hyperconverged cluster operator currently does not get released to the `community-operator` catalog which is installed on OKD by default (is that what you mean by the operator being missing?).

You may want to follow: https://github.com/kubevirt/hyperconverged-cluster-operator/issues/606
You'll also find instructions on how to build the operator in that repo.

**Comment by jomeier** [comment]
Hi @LorbusChris ,

I installed the OpenShift Virtualization Operator from the Red Hat Catalog. 

Greetings,

Josef

**Comment by cgruver** [comment]
@jomeier You need to go upstream to get KubeVirt working on OKD 4.5

The current supported version from Red Hat has Python dependencies, i.e. semanage, which you hit.  FCOS does not include those dependencies, no will RHCOS in future releases, to my knowledge...

I have deployed it using the 4.6 version of the operator.  I had to build the registry bundle from source.

I haven't documented it well yet, but you can find my notes here: https://github.com/cgruver/okd4-upi-lab-setup/blob/master/docs/pages/Notes.md. Scroll to the KubeVirt section.

Note:  It's also dependent on the Node Maintenance Operator, which is included in the notes.

**Comment by jomeier** [comment]
@cgruver:
Thank you for that. I'll try to build it on my own. 

Do your instructions show of how to build every upstream component of the hyperconverged operator? Because I don't think that e.g. virt-handler (with the python dependency) is built together with the hyperconverged operator.

Greetings,

Josef

**Comment by cgruver** [comment]
You don't need to build all of the components.  Just the image registry bundle.  The 4.6 release removes the python dependencies on python in FCOS.

**Comment by jomeier** [comment]
Ok. Good to know. I will try that.
