### ISSUE TITLE
4.5.0-0.okd-2020-08-12-020541 Vsphere UPI

### ISSUE THREAD

**Issue by 94DanielBrown** [openshift/okd#365]
**Describe the bug**

Many of the cluster operators are not coming up one of these is etcd which I imagine is the problem.
I can see the installer pod doesn't seem to be working. I checked the etcd-member container logs in the log bundle and I have found what appears to be the pertinent error:
rejected connection from "10.20.136.228:47554" (error "remote error: tls: bad certificate", ServerName "")
I don't know why the ServerName is empty I can't find anything that I've missed in the docs and I'm not sure where it's meant to be getting it from?
hostname is set correctly on control plane hosts

**Version**

Vsphere UPI - openshift-install 4.5.0-0.okd-2020-08-12-020541

**How reproducible**

100%

**Comment by vrutkovs** [comment]
2020-08-12 is 10 weeks old, is it reproducible on latest version?
