### ISSUE TITLE
UDP/NAT problems when performing DNS resolution

### ISSUE THREAD

**Issue by mic4ael** [openshift/okd#368]
**Describe the bug**

To reproduce the problem (in our case):
- run a pod (make sure curl is installed)
- `curl <any domain>`

`curl` takes more than 5 seconds to return a response. I debugged it and can confirm the timeout occurs during `getaddrinfo`.

It seems like UDP NAT used for IP load balancing of K8s `clusterIp` services (in this case the DNS) fails to properly rewrite the source IP/port of the response packets (DNS response) in some cases.

The problem might be triggered because getaddrinfo sends 2 UDP packets in a very short time (the 2 queries for A and AAAA records) from the same UDP port, and the NAT fails to configure itself to rewrite the source IP/port of the responses in time to apply it to the first response. It seems that after some DNS queries "warmed" the NAT, the problem is a lot less likely to occur; after a quiet period without DNS queries, the problem is more likely to happen.

The archive below contains two network traces. One showing a case without timeout (NAT done properly) and one with timeout (one of the packets has wrong headers).

[Network traces](https://github.com/openshift/okd/files/5451246/Archive.zip)

The whole issue seems to be resolved when using the following resolv.conf options:
- use-vc (use TCP instead of UDP)
- single-request - send DNS queries sequentially (use UDP)
- single-request-reopen - try to send requests using the same socket and open a new one in case of an error

(These options are only respected by resolvers using glibc `getaddrinfo`; musl libc getaddrinfo unfortunately doesn't respect these options)

**Version**
Version: 4.5.0-0.okd-2020-10-15-235428
Infrastracture: OpenStack

**Comment by vrutkovs** [comment]
I'm not sure how to approach this - do we need some other defaults in `resolve.conf`?

**Comment by mic4ael** [comment]
> I'm not sure how to approach this - do we need some other defaults in `resolve.conf`?

Hey! Nope. It happens on the default resolv.conf configuration (which is CoreDNS service ip as the single nameserver)

**Comment by mic4ael** [comment]
I can't reproduce the same issue on a local cluster created with `crc`. Is there anything I should check on the infra where the problem occurs?

**Comment by mic4ael** [comment]
Any update on this?

**Comment by mic4ael** [comment]
Seems like the issue is gone?

**Comment by vrutkovs** [comment]
Do we believe its OKD specific issue? Please file a bugzilla for OCP, provide necessary information (must-gather) there and we'll continue here if OKD needs fixing

**Comment by mic4ael** [comment]
Hm.. can't reproduce it anymore..
