### ISSUE TITLE
Not able to boot bootstrap server --bootstrap ignition file its running in loop and starting with emergency mode

### ISSUE THREAD

**Issue by darpan91** [openshift/okd#369]
We are installing OKD 4.5.0 Openshift version on RHCOS 4.5.2 & RHEL 7.8 (service server) Operating system . we are planning to create 3 master and 2 worker node.

We have created Service server (Helper node) with RHEL OS.
Ignition files(bootstrap ,master and worker) has been created on Same server.

While running kernel command with bootstrap ignition file its running in loop and starting with emergency mode on bootstrap server .

We are unable to boot the bootstrap node .

Attached error screenshot . Please help us to resolve the issue.
![bootstrap node error](https://user-images.githubusercontent.com/65757312/97539595-3ce9e280-19e8-11eb-8b1b-a7e234362c65.JPG)

**Comment by vrutkovs** [comment]
>OKD 4.5.0 Openshift version on RHCOS 4.5.2 

OKD doesn't have 4.5.0 version and it doesn't use RHCOS. See [installer troubleshooting](https://docs.okd.io/latest/installing/installing-troubleshooting.html)

**Comment by darpan91** [comment]
Hi Vadim, 
We have download OKD 4.5.0 software from below link. 
https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-07-29-070316/openshift-client-linux-4.5.0-0.okd-2020-07-29-070316.tar.gz

https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-07-29-070316/openshift-install-linux-4.5.0-0.okd-2020-07-29-070316.tar.gz
![image](https://user-images.githubusercontent.com/65757312/97586806-b1407800-1a20-11eb-8045-2b0902e4146a.png)

**Comment by gunjangarge** [comment]
As per documentation FCOS is only supported operating system.

https://docs.okd.io/latest/architecture/architecture-rhcos.html#rhcos-about_architecture-rhcos

_FCOS is the only supported operating system for OKD control plane, or master, machines. While FCOS is the default operating system for all cluster machines, you can create compute machines, which are also known as worker machines, that use Fedora as their operating system_
