### ISSUE TITLE
Duplicate file in GCP bootstrap ignition

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/okd#37]
With the current OKD installer there is a duplicate file in the GCP bootstrap proces. This file https://github.com/openshift/installer/blob/fcos/data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh needs to be removed or the bootstrap machine segfaults in its configuring fase before the machine is usable. 

GCP support master ticket #11

**Comment by vrutkovs** [comment]
This affects all systems: seems forked terraform ignition provider is incorrectly merging files, so bootstrap's motd is duplicated.

**Comment by LorbusChris** [comment]
we recently switched tf ignition provider forks, so this might work now?

Otherwise, it could be related to https://github.com/terraform-providers/terraform-provider-ignition/pull/66#issuecomment-579714329

**Comment by LorbusChris** [comment]
xref: https://github.com/openshift/okd/issues/11
