### ISSUE TITLE
How to use Image-registry on OKD 4.5GA (feat. gpu-operator plugin) ?

### ISSUE THREAD

**Issue by rupang790** [openshift/okd#372]
**Describe the bug**

Installed OKD 4.5 GA '4.5.0-0.okd-2020-10-15-235428' version followed the link which Craig Robinson wrote as below:
https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee

After Installation, I created image registry by NFS and check PV/PVC were created and bounded correctly and also check Podman login was succeed from the worker nodes.
Then I tried to login by Podman command from Bastion VM but it shows the error as 
```
[root@okd4-services ~]# podman login -u $(oc whoami) -p $(oc whoami -t) --tls-verify=false $HOST
error: no token is currently in use for this session
Error: error authenticating creds for "default-route-openshift-image-registry.apps.lab.okd.local": error pinging docker registry default-route-openshift-image-registry.apps.lab.okd.local: Get https://default-route-openshift-image-registry.apps.lab.okd.local/v2/: x509: certificate signed by unknown authority
```

What I would like to do is to push the image from bastion VM and access to pull that image when I install gpu-operator plugin.
(During Install the gpu-operator plugin, there is OS version problem to create gpu driver pod. So I would like to build the driver image for FCOS and use it for gpu-operator plugin installation.)
Please some help.

**Version**

**How reproducible**

**Log bundle**

**Comment by vrutkovs** [comment]
Please don't use bugtracker for support questions. See https://github.com/openshift/okd/blob/master/FAQ.md#where-do-i-seek-support
