### ISSUE TITLE
Stable 4.5,when will it be?

### ISSUE THREAD

**Issue by bingbhu** [openshift/okd#374]
We need a version like 3.11 that can be used directly as a production environment, not just for testing and development. Version 4 is obviously not up to date yet, when will it be?

**Comment by vrutkovs** [comment]
Please don't use bugtracker as support tool, see https://github.com/openshift/okd/blob/master/FAQ.md#where-do-i-seek-support

https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.5.0-0.okd-2020-10-15-235428 is our latest 4.5 stable.
