### ISSUE TITLE
Master servers could be run on port 6443 

### ISSUE THREAD

**Issue by behnm** [openshift/okd#377]
Hello
I installed my cluster (UPI on vmware- okd 4.5-2020-10-15).  All the installation process has been successfully done. But after reboot the master nodes gracefully,  My master nodes on 6443  repeatedly up and down. 
I check crio and kubelet service on master nodes, both of them are in ACTIVE state.Albeit, I see some errors in logs:

` Unable to get Process Stats: couldn't open cpu cgroup procs file /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod75f654bbca2231c82>
andler.go:87] 
Unable to get network stats from pid 27603: couldn't read network stats: failure opening /proc/27603/net/dev: open /proc/27603/net/dev: no such file or directory`

I can't use **oc adm must-gather** because the result is **Request timeout**

after this command, I noticed the kube-api didn't existed on list of PODs

` sudo crictl ps | grep kube-apiserver`

This issue has been happened in serveral implementation of OKD 4.5

**Comment by behnm** [comment]
After some Search, I noticed this error on **apiServer deployment**


` failed to create pod network sandbox k8s_apiserver-7f7bb77fb6-8gnxf_openshift-apiserver_921fa82e-3211-43e0-87ca-f536caab0485_0(5a9cec2e3afca80807f9c73e284076e2d8b7382f4abb71b7d4e2ed07ffba189c): fork/exec /var/lib/cni/bin/multus: text file busy`

**Comment by vrutkovs** [comment]
Is it reproducible on OKD 4.6?
