### ISSUE TITLE
FCOS on GCP is missing gcp-routes.sh and gcp-routes.service

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/okd#38]
Fedora CoreOS is missing the following files on GCP:

gcp-routes.sh and gcp-routes.service.

Without these files the bootstrap and masters are never reported healthy to the loadbalancer. I have add the needed files and the bootstrap means instantly reports healthy

**Comment by Rikbruggink** [comment]
#11

**Comment by vrutkovs** [comment]
IIRC RHCOS is mixing these in to machine-os-content, OKD should do the same

**Comment by Rikbruggink** [comment]
👍

**Comment by cgwalters** [comment]
We should probably move those scripts into the MCO itself.

**Comment by LorbusChris** [comment]
xref: https://github.com/openshift/okd/issues/65#issuecomment-581431399

@cgwalters my plan is to move those scripts into MCO's GCP templates, not the MCD binary. Do you think that is adequate?

**Comment by vrutkovs** [comment]
https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-02-28-165101 should have the fix for that

**Comment by vrutkovs** [comment]
Fixed by PRs to installer / MCO. https://github.com/openshift/installer/pull/3209 would fix the duplicate files issue for GCP
