### ISSUE TITLE
Installing an OKD 4.5 Cluster on home lab (VMs on ESXi 6.5 host)

### ISSUE THREAD

**Issue by anshukapoor** [openshift/okd#381]
**Describe the bug**

I am following this guide to install OKD 4.5 Cluster on home lab https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee
Some changes I have compared to the guide are:
1. I have only one master node. For this I changed controlPlane replicas to 1 in install-config.yaml
2. My home network is using 192.168.1.0/24, so I skipped the pfsense install. To assign static IPs for bootstrap, control-plane and worker nodes, I added following extra details to kernel boot options while starting up bootstrap, control-plan and worker nodes: `ip=192.168.1.200::192.168.1.1:255.255.255.0:::none nameserver=192.168.1.72 coreos.inst.install_dev=/dev/sda coreos.inst.image_url=http://192.168.1.72:8080/okd4/fcos.raw.xz coreos.inst.ignition_url=http://192.168.1.72:8080/okd4/bootstrap.ign`

The bootstrap server continuously shows following errors:
 [Error Image: ](https://github.com/anshukapoor/okd-home-lab-install/blob/master/Issues/bootstrap%20server%20start/bootstrap-error-screenshot.png)

**Version**
OKD - 4.5.0-0.okd-2020-10-15-235428
CoreOS - 32.20201104.3.0
ESXi - 6.7

**How reproducible**
I have tried this multiple times completely deleting and recreating the VMs. I got same issue with OKD version 4.5.0-0.okd-2020-07-29-070316.

**Log bundle**
[log-bundle-20201120212245.tar.gz](https://github.com/anshukapoor/okd-home-lab-install/blob/master/Issues/bootstrap%20server%20start/log-bundle-20201120212245.tar.gz)

**Comment by vrutkovs** [comment]
>OKD - 4.5.0-0.okd-2020-10-15-235428

Your bootstrap is using older image:
>Nov 21 02:20:47 okd4-bootstrap.lab.okd.local release-image-download.sh[977]: Pulling quay.io/openshift/okd@sha256:6565b6eb19a82f4c9230641286c27f003625b79984ed8e733b011c72790a5eb3...

which has

>"io.openshift.release": "4.5.0-0.okd-2020-07-29-070316",

label.

Make sure you're using updated installer from 4.5.0-0.okd-2020-10-15-235428 and cleaned up the dir from previous installation (including hidden files like `.openshift...`) or preferably a new [installation directory](https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-initializing-manual_installing-bare-metal).

Also your installer is built from a commit in July, so you'd need to extract it from latest stable release of OKD.

Please provide a new log bundle if this keeps failing.

**Comment by anshukapoor** [comment]
Thank you for the response. I deleted and recreated the install directory.
I am still getting the same error.

installer version:
```
[akapoor@okd4-services ~]$ oc version
Client Version: 4.5.0-0.okd-2020-10-15-235428
[akapoor@okd4-services ~]$ openshift-install version
openshift-install 4.5.0-0.okd-2020-10-15-235428
built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
release image quay.io/openshift/okd@sha256:67cc7cb47d56237adcf0ecc2ee76446785add5fa236cd08746b55f578b9200a5
```

Error screen shot: [bootstrap-error-screenshot_20202111_002](https://github.com/anshukapoor/okd-home-lab-install/blob/master/Issues/bootstrap%20server%20start/bootstrap-error-screenshot_20202111_002.png)

Log bundle: [log-bundle-20201121135602.tar.gz](https://github.com/anshukapoor/okd-home-lab-install/blob/master/Issues/bootstrap%20server%20start/log-bundle-20201121135602.tar.gz)

**Comment by vrutkovs** [comment]
Correct installer and correct payload used this time, but now its stuck on:

>Nov 21 18:55:13 okd4-bootstrap.lab.okd.local release-image-download.sh[1783]: I1121 18:55:13.471879    1783 run.go:16] Running: podman pull -q quay.io/openshift/okd-content@sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2

Try [mirroring](https://docs.okd.io/latest/installing/install_config/installing-restricted-networks-preparations.html) the payload and forbidding access to quay.io?

**Comment by anshukapoor** [comment]
I started the install again (by deleting and recreating the bootstrap and control-plane-1 VMs) and let it run for about 3 hrs now.
The release-image.log shows that OpenShift release image was downloaded:
```
Nov 22 20:30:28 okd4-bootstrap.lab.okd.local systemd[1]: Starting Download the OpenShift Release Image...
Nov 22 20:30:28 okd4-bootstrap.lab.okd.local release-image-download.sh[906]: Pulling quay.io/openshift/okd@sha256:67cc7cb47d56237adcf0ecc2ee76446785add5fa236cd08746b55f578b9200a5...
Nov 22 20:30:34 okd4-bootstrap.lab.okd.local release-image-download.sh[921]: 4b87b7e417da6431332f99a8e0eb0b19d02d3e04096c09a824a176a4522c2107
Nov 22 20:30:34 okd4-bootstrap.lab.okd.local systemd[1]: Finished Download the OpenShift Release Image.

```
But the install screen shot still shows the same error messages with hostname, address and terminal as question marks (?).

New error screen shot: [bootstrap-error-screenshot_20202211_001](https://github.com/anshukapoor/okd-home-lab-install/blob/master/Issues/bootstrap%20server%20start/bootstrap-error-screenshot_20202211_001.png)
Log Bundle: [log-bundle-20201122180104.tar.gz](https://github.com/anshukapoor/okd-home-lab-install/blob/master/Issues/bootstrap%20server%20start/log-bundle-20201122180104.tar.gz)

**Comment by jomeier** [comment]
"New error screen shot": This looks the same on my side. This audit logs seem to be normal behaviour.

**Comment by anshukapoor** [comment]
Just to confirm the messages with hostname, address and terminal as question marks (?) are normal behavior?
When I monitor for bootstrap installation I am getting following error:
```
[akapoor@okd4-services ~]$ openshift-install --dir=install_dir/ wait-for bootstrap-complete --log-level=info
INFO Waiting up to 20m0s for the Kubernetes API at https://api.lab.okd.local:6443...
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get https://api.lab.okd.local:6443/apis/config.openshift.io/v1/clusteroperators: x509: certificate has expired or is not yet valid
INFO Use the following commands to gather logs from the cluster
INFO openshift-install gather bootstrap --help
FATAL failed waiting for Kubernetes API: Get https://api.lab.okd.local:6443/version?timeout=32s: x509: certificate has expired or is not yet valid
```

I also tried to access the link https://api.lab.okd.local:6443/apis/config.openshift.io/v1/clusteroperators from browser I am getting 404 error.

**Comment by anshukapoor** [comment]
I got this working. I had insufficient resources allocated. After spending another $200 to get more RAM, OKD is successfully installed.
