### ISSUE TITLE
OKD setup failed on GCP - can't find specified CoreOS image file

### ISSUE THREAD

**Issue by vfabi** [openshift/okd#385]
**Describe the bug**
GCP environment setup.  
OKD setup failed with error raised: 
`ERROR Error: Error waiting to create Image: Error waiting for Creating Image: The resource 'https://storage.googleapis.com/fedora-coreos-cloud-image-uploads/image-import/fedora-coreos-32-20200629-3-0-gcp-x86-64.tar.gz' of type 'Google Cloud Storage object' was not found.`  

I tried to find specified CoreOS image at https://storage.googleapis.com/fedora-coreos-cloud-image-uploads/ but no luck :(  
As you can see there are other CoreOS versions in it, but no fedora-coreos-32-20200629-3-0-gcp-x86-64.tar.gz

**Version**
4.5.0-0.okd-2020-10-15-235428

**How reproducible**
Just run OKD installer `./openshift-install create cluster --dir=<PATH> --log-level=info`

**Log bundle**
OKD installer CLI:  

> INFO Credentials loaded from file "/home/fabi/.gcp/osServiceAccount.json"
> INFO Consuming Install Config from target directory
> INFO Creating infrastructure resources...
> ERROR                                              
> ERROR Error: Error waiting to create Image: Error waiting for Creating Image: The resource 'https://storage.googleapis.com/fedora-coreos-cloud-image-uploads/image-import/fedora-coreos-32-20200629-3-0-gcp-x86-64.tar.gz' of type 'Google Cloud Storage object' was not found. 
> ERROR                                              
> ERROR                                              
> ERROR   on ../../../../../tmp/openshift-install-184247086/main.tf line 93, in resource "google_compute_image" "cluster": 
> ERROR   93: resource "google_compute_image" "cluster" { 
> ERROR                                              
> ERROR                                              
> FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 

OKD installer logfile (truncated):  
[.openshift_install.log](https://github.com/vfabi/filestorage/blob/main/openshift_install.log)

**Comment by hervedevos** [comment]
Same problem here

**Comment by vrutkovs** [comment]
Fixed in OKD 4.6 - https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.6.0-0.okd-2020-11-27-200126 uses latest FCOS Stable instead of outdated GCP image
