### ISSUE TITLE
openshift-install not creating the worker vm using IPI

### ISSUE THREAD

**Issue by bobby0724** [openshift/okd#386]
**Describe the bug**
I am trying to deploy a new cluster into my vsphere infrastructure using IPI 
Bootstrap process completes but the workers are never created

**Version**

openshift-install 4.5.0-0.okd-2020-10-15-235428
IPI installation
**How reproducible**

i have try 10 times bootstrap completes but the workers are never created

this is my install-config.yml
apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 4
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
        
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 4
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120

networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16

**Log bundle**

DEBUG Still waiting for the cluster to initialize: Working towards 4.5.0-0.okd-2020-10-15-235428: 86% complet

**Comment by fortinj66** [comment]
No workers are created in VMWare or in the cluster?

**Comment by bobby0724** [comment]
> No workers are created in VMWare or in the cluster?

no vm workers are created, only the masters, i also notice that the ingress operator never startup

**Comment by fortinj66** [comment]
what does the VMWare terminal indicate logwise for the masters?

can you run `oc get nodes` and `oc get events`

**Comment by bobby0724** [comment]
> what does the VMWare terminal indicate logwise for the masters?
> 
> can you run `oc get nodes` and `oc get events`

give me 10 min i will ran the installation and i can get you all the info

**Comment by fortinj66** [comment]
It doesn't looks like the bootstrap process has finished...  Nodes get created after the bootstrap process is complete...


try running ` ./openshift-install gather bootstrap --dir=<installation_directory>` and post the results...

(https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

**Comment by fortinj66** [comment]
also, if possible, you may want to make sure all the nodes are running on different VMWare hosts, or as much as possible...  I've had issues were OKD hosts saturated the VMWare host CPU and it caused issues...

**Comment by bobby0724** [comment]
> It doesn't looks like the bootstrap process has finished... Nodes get created after the bootstrap process is complete...
> 
> try running ` ./openshift-install gather bootstrap --dir=<installation_directory>` and post the results...
> 
> (https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

it does finish look

DEBUG OpenShift Installer 4.5.0-0.okd-2020-10-15-235428
DEBUG Built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
INFO Waiting up to 20m0s for the Kubernetes API at https://api.lab.okd.local:6443...
DEBUG Still waiting for the Kubernetes API: Get https://api.lab.okd.local:6443/version?timeout=32s: dial tcp 192.168.1.201:6443: connect: connection refused
INFO API v1.18.3 up
INFO Waiting up to 40m0s for bootstrapping to complete...                                                                                                                                          DEBUG           Bootstrap status: complete
INFO Destroying the bootstrap resources...
DEBUG Symlinking plugin terraform-provider-aws src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-aws"
DEBUG Symlinking plugin terraform-provider-google src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-google"
DEBUG Symlinking plugin terraform-provider-openstack src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-openstack"
DEBUG Symlinking plugin terraform-provider-vsphere src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-vsphere"
DEBUG Symlinking plugin terraform-provider-random src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-random"
DEBUG Symlinking plugin terraform-provider-vsphereprivate src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-vsphereprivate"
DEBUG Symlinking plugin terraform-provider-azurerm src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-azurerm"
DEBUG Symlinking plugin terraform-provider-azureprivatedns src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-azureprivatedns"
DEBUG Symlinking plugin terraform-provider-ignition src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-ignition"
DEBUG Symlinking plugin terraform-provider-local src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-local"
DEBUG Symlinking plugin terraform-provider-ovirt src: "/usr/local/bin/openshift-install" dst: "/tmp/openshift-install-612627491/plugins/terraform-provider-ovirt"
DEBUG Initializing modules...
DEBUG - bootstrap in ../../../tmp/openshift-install-612627491/bootstrap
DEBUG - master in ../../../tmp/openshift-install-612627491/master

**Comment by fortinj66** [comment]
The image you sent and the logs didn't show that completing...  Bootstrap node was still there...

what vmware hosts are created now?

**Comment by bobby0724** [comment]
> The image you sent and the logs didn't show that completing... Bootstrap node was still there...
> 
> what vmware hosts are created now?

No, that is the issue I am having bootstrap completes but workers are never created, the cluster provisioning never completes

**Comment by fortinj66** [comment]
can you run `oc adm must-gather`

and another shot of your currently created VMWare nodes?

**Comment by bobby0724** [comment]
> can you run `oc adm must-gather`
> 
> and another shot of your currently created VMWare nodes?
> 
> and check `oc get csr`

$ oc get csr
NAME        AGE     SIGNERNAME                                    REQUESTOR                                                                   CONDITION
csr-2mvx2   8m58s   kubernetes.io/kubelet-serving                 system:node:lab-5jjb9-master-1                                              Approved,Issued
csr-8qvkh   9m17s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-x6b4s   8m38s   kubernetes.io/kubelet-serving                 system:node:lab-5jjb9-master-2                                              Approved,Issued
csr-xxx7v   9m3s    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-zbt4g   9m1s    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-zp5l2   8m40s   kubernetes.io/kubelet-serving                 system:node:lab-5jjb9-master-0                                              Approved,Issued

the output of the gather command is to big to paste it here what are you looking for
bootstrap vm is deleted every time

**Comment by fortinj66** [comment]
Do you have dropbox or similar you can put that logfile in?

**Comment by bobby0724** [comment]
> Do you have dropbox or similar you can put that logfile in?

sure

https://www.dropbox.com/s/w09xr5js43btt29/gather.txt?dl=0

**Comment by fortinj66** [comment]
There should have been a directory created that you need to tar/gzip up...  That's what you need to put there:

[](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data)

**Comment by bobby0724** [comment]
> There should have been a directory created that you need to tar/gzip up... That's what you need to put there:
> 
> (https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data)

got it i just upload it
https://www.dropbox.com/sh/5vme5hm379excb9/AAAtfJnhJuIlEvsF7G8qpNcBa?dl=0

**Comment by bobby0724** [comment]
Bootstrap log

$ openshift-install --dir=/home/okdadmin/okd4lab/vsphere wait-for bootstrap-complete --log-level=debug
DEBUG OpenShift Installer 4.5.0-0.okd-2020-10-15-235428
DEBUG Built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
INFO Waiting up to 20m0s for the Kubernetes API at https://api.lab.okd.local:6443...
INFO API v1.18.3 up
INFO Waiting up to 40m0s for bootstrapping to complete...
DEBUG Bootstrap status: complete
INFO It is now safe to remove the bootstrap resources
INFO Time elapsed: 0s

**Comment by fortinj66** [comment]
can you post the installer log?   should be `<install_dir>/.openshift_install.log`

**Comment by fortinj66** [comment]
I'm looking at my config:

```
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 1
      memoryMB: 24576
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
```
Other than memory, the only difference is `coresPerSocket: 1`

Can you try that rather than `coresPerSocket: 4`

**Comment by bobby0724** [comment]
Yes that not the issue
for some reason the installer is not creating the worker nodes, but also the cluster is not getting ready the ingress project never comes up :( i will stop here at least the UPI is working

**Comment by fortinj66** [comment]
Ingress won't come up without worker nodes...

I just rebuilt my cluster with IPI without issues...  and with coresPerSocker at 4...


what happens if you run  `oc get events --all-namespaces | grep openshift-machine-api`

I get 

```
[root@os-utils-d02 logs]# oc get events --all-namespaces | grep  "Created Machine"
openshift-machine-api                              32m         Normal    Create                                       machine/dev-c1v4-mfpr9-worker-jmk8q                               Created Machine dev-c1v4-mfpr9-worker-jmk8q
openshift-machine-api                              32m         Normal    Create                                       machine/dev-c1v4-mfpr9-worker-rw6pt                               Created Machine dev-c1v4-mfpr9-worker-rw6pt
openshift-machine-api                              32m         Normal    Create                                       machine/dev-c1v4-mfpr9-worker-xbmgg                               Created Machine dev-c1v4-mfpr9-worker-xbmgg
[root@os-utils-d02 logs]#
```

**Comment by fortinj66** [comment]
The only other thing I would try would be to take out the worker changed you made and try vanilla:
```
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
```

**Comment by fortinj66** [comment]
Here's your issue.  

There are a bunch of these in must-gather.local.331163555932549138/quay-io-openshift-okd-content-sha256-5a9b4b4cdd15e8587d02490cf753c385213e6a97e5c2bf7babf416585e42fd70/namespaces/openshift-machine-api/pods/machine-api-controllers-6c4f6c6dc8-vd8x5/machine-controller/machine-controller/logs/current.log:

`namespaces/openshift-machine-api/pods/machine-api-controllers-6c4f6c6dc8-vd8x5/machine-controller/machine-controller/logs/current.log:2020-11-24T21:13:43.289573655Z E1124 21:13:43.289519       1 controller.go:272] lab-5jjb9-worker-v9sp8: failed to check if machine exists: lab-5jjb9-worker-v9sp8: failed to create scope for machine: failed to create vSphere session: error setting up new vSphere SOAP client: Post https://sacla300.sac.flex.com/sdk: dial tcp: lookup sacla300.sac.flex.com on 172.30.0.10:53: no such host
`

It can't find your vSphere host in DNS

**Comment by bobby0724** [comment]
> Here's your issue.
> 
> There are a bunch of these in must-gather.local.331163555932549138/quay-io-openshift-okd-content-sha256-5a9b4b4cdd15e8587d02490cf753c385213e6a97e5c2bf7babf416585e42fd70/namespaces/openshift-machine-api/pods/machine-api-controllers-6c4f6c6dc8-vd8x5/machine-controller/machine-controller/logs/current.log:
> 
> `namespaces/openshift-machine-api/pods/machine-api-controllers-6c4f6c6dc8-vd8x5/machine-controller/machine-controller/logs/current.log:2020-11-24T21:13:43.289573655Z E1124 21:13:43.289519 1 controller.go:272] lab-5jjb9-worker-v9sp8: failed to check if machine exists: lab-5jjb9-worker-v9sp8: failed to create scope for machine: failed to create vSphere session: error setting up new vSphere SOAP client: Post https://sacla300.sac.flex.com/sdk: dial tcp: lookup sacla300.sac.flex.com on 172.30.0.10:53: no such host `
> 
> It can't find your vSphere host in DNS

Thank you i really appreciate that you take the time to review the logs i was also doing that, i think i know why is that happening i will apply a workaround a retry rebuild

**Comment by fortinj66** [comment]
You're welcome!  

I'm learning too and it give me the opportunity to deep dive into issues to better understand the systems...

**Comment by fortinj66** [comment]
Were you able to resolve the DNS issue and complete the install?

**Comment by bobby0724** [comment]
> Were you able to resolve the DNS issue and complete the install?

yes adding internal forwarder fix the issue

**Comment by fortinj66** [comment]
awesome!  good luck!

**Comment by mikelo** [comment]
/open 

I think this issue should be reopened. I had misconfigured DNS (vcenter DN was not getting resolved) but the installer worked fine until it was time to create the worker nodes, which AFAIK is done by the master nodes.

This means the installer uses a different DNS VS the master nodes, the installer IMO should run a `dig vCenter.url` at the beginning and stop in case the resolution fails.

cc @mariosomma

**Comment by swefredde** [comment]
Hi!

Thank you guys for this informative troubleshooting. I have the exact same symptoms as @bobby0724 but running in ovirt. By following the steps taken by @fortinj66 i found the likely error in the logs from

namespace: openshift-machine-api
pod: machine-api-controllser-XYXYXY
container: machine-controller

{"level":"error","ts":1613987970.6140544,"logger":"controller","msg":"Reconciler error","controller":"provdierID-controller","name":"shift-4prmr-master-1","namespace":"","error":"failed getting VM from oVirt: Failed to parse CA Certificate in file '/tmp/ovirt-ca-bundle933032459'","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/cluster-api-provider-ovirt/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/cluster-api-provider-ovirt/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/cluster-api-provider-ovirt/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/cluster-api-provider-ovirt/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/cluster-api-provider-ovirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/cluster-api-provider-ovirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/cluster-api-provider-ovirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/cluster-api-provider-ovirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}

I made a custom install andI pasted the oVirt CA in the file ovirt-config.yaml and my private CA in the file install-config.yaml.

I have a "base" like sub.domain.tld where i install all openshift nodes but my ovirt API is at domain.tld (both in private IP-range (192.168.0.0/16)). I have all DNS issues resolved (finally) so I can resolve hosts and IP's from both domain.tld and sub.domain.tld. 

Any suggestions why there is a failure to parse my ovirt certificate?

My CA's are self signed and before when I ran code ready containers I had to give a secret with an annotation to be able to download source from my private git server but I thought that was what I was doing by adding my CA's to the custom config files before running the installation. Did I miss anything?

Regards and happy hacking,
/F

**Comment by swefredde** [comment]
Hmm, didn't realize this was closed... 

If someone stumble on this I thought I could tell what was the problem.

When giving the info in the beginning of the installation I gave the FQDN[:PORT] to my ovirt-engine. Since I gave port 443 a Certificate was presented and I was asked if I wanted to trust it or not. Since I just had given the URL to my ovirt-engine where I have my custom certificate and the cn=fqdn was correct I accepted (a little to fast it showed). I assumed the presented certificate was my installed custom certificate but it must have been either the original ovirt certificate or an installer generated cert.

However, when I answered No I was asked to paste the real cert and then it worked.

/F

**Comment by purab-git** [comment]
https://github.com/openshift/okd/issues/386#issuecomment-733397019 
I have one question on the same if DNS was the culprit how master node got created?

**Comment by kulkarma** [comment]
> [#386 (comment)](https://github.com/okd-project/okd/issues/386#issuecomment-733397019) I have one question on the same if DNS was the culprit how master node got created?

Even I have the same question. The masters created but why not Workers and when I check into the Machine config I founf the worker count as 0 against 3 replicas set in the yaml?? This is bug in IPI install.

**Comment by jcpowermac** [comment]
@kulkarma you may want to create a new discussion in regards to this since this issue is closed.
