### ISSUE TITLE
OKD operators hub list is not available

### ISSUE THREAD

**Issue by sairbabu58** [openshift/okd#387]
**Describe the bug**

**Version**

**How reproducible**

**Log bundle**

**Comment by sairbabu58** [comment]
HI team,

I have install okd 4.5 version and its working fine. but there is some issue is on operator hub list. unable to find any operators

**Comment by jomeier** [comment]
Does your cluster have an internet connection or does it run in an offline setup?

If offline you must mirror all operators (and patch /etc/containers/registries.conf to point to your mirror registry).

**Comment by sairbabu58** [comment]
Yes, internet is available on the cluster
