### ISSUE TITLE
 How to enable PROXY protocol in OKD4? 

### ISSUE THREAD

**Issue by romankspb** [openshift/okd#390]
In OKD3 it may be enabled by setting environment ROUTER_USE_PROXY_PROTOCOL=true and this described in docs https://docs.okd.io/3.11/install_config/router/proxy_protocol.html, but i can't find this feature in OKD4.

**Comment by vrutkovs** [comment]
See https://issues.redhat.com/browse/RFE-401

**Comment by myg0v** [comment]
> See https://issues.redhat.com/browse/RFE-401
With my free personal RadHat-Account I'm not able to see the status of the ticket:

_You can't view this issue
It may have been deleted or you don't have permission to view it._

Can we expect a release of the proxy protocol in OKD?

**Comment by LorbusChris** [comment]
fyi @myg0v the issue links to the following PR: https://github.com/openshift/cluster-ingress-operator/pull/354
