### ISSUE TITLE
vSphere UPI install - bootstrap doesn't  complete

### ISSUE THREAD

**Issue by 94DanielBrown** [openshift/okd#393]
**Describe the bug**

Bootstrap process does not complete
Errors in bootkube.service include:
Error: error while checking pod status: timed out waiting for the condition
E1128 13:56:49.489232       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused

**Version**

vSphere UPI 4.5.0-0.okd-2020-10-15-235428

**How reproducible**

100%

**Log bundle**

[log-bundle-20201128133740.tar.gz](https://github.com/openshift/okd/files/5610707/log-bundle-20201128133740.tar.gz)

**Comment by vrutkovs** [comment]
Masters didn't boot:

```
E1128 12:54:58.591710       1 api.go:117] couldn't get config for req: {worker}, error: refusing to serve bootstrap configuration to pool "worker"
I1128 12:55:00.647109       1 api.go:111] Pool master requested by address:"10.20.211.181:52514" User-Agent:"Ignition/2.6.0"
I1128 12:55:00.647179       1 bootstrap_server.go:64] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I1128 12:55:00.647433       1 bootstrap_server.go:84] reading file "/etc/mcs/bootstrap/machine-configs/rendered-master-81ed786c992105d7eb3319c5e0a7457d.yaml"
E1128 12:55:00.669380       1 api.go:147] failed to write {master} response: write tcp 10.20.136.245:22623->10.20.211.181:52512: write: broken pipe
```

Possibly a bad network configuration? 

Also, please give a [OKD 4.6](https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.6.0-0.okd-2020-11-27-200126) a try

**Comment by 94DanielBrown** [comment]
I have tried with 4.6 but am unable to gather the log with the installer for some reason, I can still ssh onto the bootstrap node no problem but get the following error when attempting to get the logs using the 4.6 installer (I have never had this before and have tried many versions):
'FATAL failed to create SSH client: failed to use pre-existing agent, make sure the appropriate keys exist in the agent for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain'
I have tried specifying key as an argument to the command as well.

Masters appear to be getting there config files because I can see in vsphere they are getting the static ips and I have put in the ignition configs I don't know why they aren't coming up... I can't find anything wrong with network configuration, could the fact that I am using a vpn be an issue at all this is the only avenue I haven't gone down, I am running openshift-installer from my machine so this will be going over vpn?

**Comment by 94DanielBrown** [comment]
Error messages were not sending me in the right direction. The issue was the the control nodes only had 1CPU and the minimum requirement is 4, deployed with 4 and bootstrap completes...
