### ISSUE TITLE
gcp-hostname service should run on GCP only

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#396]
On fresh installs/upgrades `gcp-hostname` service is started regardless of cluster platform: https://github.com/openshift/okd-machine-os/pull/16 didn't add a platform guard.

This doesn't modify hostname or anything, this failing unit can be ignored.

**Comment by chun-yin** [comment]
I Install a cluster on bare metal ,upgrade 4.6.0-0.okd-2020-11-27-200126 from 4.5.0-0.okd-2020-10-15-235428, is there any workaround to fix this issue.

**Comment by MR-Os1** [comment]
same problem here 
any solution yet ??

**Comment by ssams** [comment]
> same problem here
> any solution yet ??

also ran into this issue when upgrading from latest 4.5 to 4.6 on bare metal - at some point during the upgrade the hosts used the default hostname `fedora` and reported the failed `gcp-hostname` service.

Seems it's sufficient to log into the nodes via SSH when they arrive at this stage, set the correct hostname via `hostnamectl set-hostname ...`, and reboot. The failed service seems to be ignorable as long as the hostname is set manually.

It may be possible that the node requests a new node-boostrapper certificate using the wrong hostname, if this gets signed things can get more complicated - see comments in #399.

**Comment by vrutkovs** [comment]
Should be fixed since https://amd64.origin.releases.ci.openshift.org/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2020-12-05-100401
