### ISSUE TITLE
Fedora repos not disabled for 4.5 to 4.6 upgrade

### ISSUE THREAD

**Issue by thurcombe** [openshift/okd#398]
**Describe the bug**
Upgrading from 4.5.0-0.okd-2020-10-15-235428 to 4.6.0-0.okd-2020-11-27-200126 fails with rpm-ostree timeouts when behind a proxy in a similar fashion to https://github.com/openshift/okd/issues/389

Adding a dropin for rpm-ostree to set proxy env vars allowed the upgrade to complete. Post installation I see that fedora repos are still enabled:

```
sh-5.0# grep enabled=1 /etc/yum.repos.d/*
/etc/yum.repos.d/fedora-cisco-openh264.repo:enabled=1
/etc/yum.repos.d/fedora-updates-archive.repo:enabled=1
/etc/yum.repos.d/fedora-updates.repo:enabled=1
/etc/yum.repos.d/fedora.repo:enabled=1
```

Confirmed that on a fresh UPI install of 4.6, this is not an issue and repos are disabled as expected:

```
sh-5.0# grep enabled=1 /etc/yum.repos.d/*
sh-5.0# 
```

**Version**

4.5.0-0.okd-2020-10-15-235428 to 4.6.0-0.okd-2020-11-27-200126

**How reproducible**
100%

**Workaround**

Either disable the yum repos manually ~~or add a dropin via machine-config for rpm-ostree to set http_proxy environment variables.~~

**Comment by vrutkovs** [comment]
We shouldn't allow external repos during updates - this may pull in unexpected packages from Fedora (OKD should provide all necessary RPMs anyway).

So ideally we'd disable all repos before upgrade instead of setting up proxy vars.

**Comment by chuyqa** [comment]
Ran into this issue while updating from `4.6.0-0.okd-2020-12-12-135354` -> `4.6.0-0.okd-2021-01-17-185703`

Cluster upgrade stalled at 97% with:
```
error: Checkout open-vm-tools-11.2.5-1.fc33.x86_64: Hardlinking 57/2d1e0.....file to VGAuthService: File exists
```

Disabling the 4 repos listed in description did the trick, thanks!

**Comment by vrutkovs** [comment]
I don't think we can fix this. If you have repos enabled you should either:
a) disable them. CI is testing installs and upgrades with repos disables (so we ensure the content remains the same). If you need to install additional RPMs this may break updates.

b) set valid proxy settings in repo files manually
