### ISSUE TITLE
hostname wrong ("fedora") when upgrading cluster on vSphere UPI which used DHCP

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#399]
**Describe the bug**
I have upgraded two clusters running 4.5 20201015 on vSphere UPI.
The upgrade went fine (except for one frozen node during upgrade, needing a VM reset) on one of the clusters which is configured using static IPs and hostnames.
The upgrade was stuck on the other cluster which has it nodes configured using DHCP (reservations) which also sets the hostname via DHCP. In this case, after FCOS upgrade, the hostname was set to "fedora" and not to the one assigned via DHCP.

**Version**
4.5 20201015 to 4.6 20201127

**How reproducible**
100%

**Log bundle**
I worked around by sshing into failed nodes, using "hostnamectl set-hostname <fqdn>" and rebooting the nodes in order to get up and running again.
I would need to reproduce with a test cluster.

**Comment by ssams** [comment]
I'm getting the same hostname issue when upgrading between the listed OKD versions (bare metal installation). Also providing hostnames via DHCP, but systems show up as *fedora* after the upgrade (which prevents the cluster from becoming operational again).

I've set the hostname using `hostnamectl set-hostname ...`, however although the system shows the correct name after a reboot logs show that it still tries (and fails) to contact the other cluster components using *fedora* as its name.

**Comment by kai-uwe-rommel** [comment]
Did you use fully qualified DNS names? E.g. including the DNS domain name suffix.
That solved it for me.

**Comment by ssams** [comment]
> Did you use fully qualified DNS names? E.g. including the DNS domain name suffix.
> That solved it for me.

Yes, I've set it to the FQDN.

I think it might be possible that a certificate request from the Machine Config Operator node-bootstrapper got signed whilst the host was still using the wrong name - I saw the following line in the output of `oc get csr` earlier during the upgrade:
```
csr-8fhsr   7s      kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
```
However now this one gone, but I see requests using the incorrect *fedora* name:
```
csr-q779v   39m     kubernetes.io/kube-apiserver-client-kubelet   system:node:fedora          Pending
```
So maybe the wrong name got embedded somewhere already and that's the reason why just updating the hostname did not work in my case? Is there any way I can force the host to redo this bootstrap phase?

**Comment by ssams** [comment]
Update: the workaround with the manual hostname setting seems to be indeed sufficient in most cases.

I've had one worker/compute node and a master/control node which were potentially stuck due to the certificate signing issue described above. I completely removed the problematic compute node and reprovisioned it via Ignition. It installed the pre-upgrade OS version and got picked up by the Machine Config Operator, which started the upgrade again. I quickly set the hostname when the node rebooted into the new OS version and restarted it once more, now it's running properly.

Now I've still got the issue remaining on the master node, I'll probably also try to delete and reinstall it if there's no other way of reverting whatever happened after the node-bootstrapper certificate got signed.

**Comment by vrutkovs** [comment]
>So maybe the wrong name got embedded somewhere already

No, `fedora` is a default hostname which node sets when it didn't get a proper one from static config / DHCP (it used to be `localhost`). There is nothing OKD can do about this

**Comment by ssams** [comment]
> > So maybe the wrong name got embedded somewhere already
> 
> No, `fedora` is a default hostname which node sets when it didn't get a proper one from static config / DHCP (it used to be `localhost`). There is nothing OKD can do about this

What I was trying to say is that it might have been embedded in some configuration after the node-bootstrapper certificate got signed. So the default got copied somewhere into the system as it was not updated properly beforehand. But this seems to be some side effect, not sure why the bootstrapper certificate appeared and got signed at all. The primary issue is that the correct hostname is not picked up automatically, although it was working before (no changes to the environment at the time around the upgrade in my case).

**Comment by kai-uwe-rommel** [comment]
I'll go forward and even for clusters where we use DHCP I will always configure a static hostname for each node via ignition (in /etc/hostname and /etc/hosts).

**Comment by kai-uwe-rommel** [comment]
But probably the bug report should be forwarded to the FCOS team for fixing?
So that it will again apply a DHCP-assigned hostname.

**Comment by amelie1979** [comment]
I think the VMHOST doest not get read properly/anymore (guest vmname to set the hostname), also I notice the ignition of the worker still 2.1 not 3. (serve by machineconfigserver: 22623)
We are using Vmware 6.7, migrate from 4.5 to 4.6 (We can not create worker anymore, since hostname does not get set).

**Comment by vrutkovs** [comment]
>I think the VMHOST doest not get read properly/anymore (guest vmname to set the hostname)

Is open-vm-agent service running after the node has updated? Seems vSphere deployments which don't really have DHCP hostname set and being set by the agent instead. And if the service is not running you'd get `fedora` instead. Could anyone confirm this?

**Comment by kai-uwe-rommel** [comment]
> 
> 
> I think the VMHOST doest not get read properly/anymore (guest vmname to set the hostname), also I notice the ignition of the worker still 2.1 not 3. (serve by machineconfigserver: 22623)
> We are using Vmware 6.7, migrate from 4.5 to 4.6 (We can not create worker anymore, since hostname does not get set).

IMO, the VM name should not be used for hostname at all, anyway. 
If any automatic assignment, then DHCP.

**Comment by vrutkovs** [comment]
Lets use one ticket to track hostname issues on vSphere. Closing as dupe for #394
