### ISSUE TITLE
OKD 4.6 Build of CodeReady Containers fails on rpm-ostree

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#400]
During the build of a CRC bundle for OKD, we install the drivers for HyperV.  The drivers are installed from locally sourced rpms that are copied into the OKD node.

The execution of rpm-ostree is failing on GlusterFS packages.

FCOS: `5.9.10-200.fc33.x86_64`. 

```bash
Checking out tree b0ae45f...done
Enabled rpm-md repositories: updates-archive
Updating metadata for 'updates-archive'...done
rpm-md repo 'updates-archive'; generated: 2020-11-30T02:34:57Z
Importing rpm-md...done
error: Packages not found: glusterfs, glusterfs-fuse
```

This can be mitigated by enabling the `fedora` repo in /etc/yum.repos.d, but that feels like a bit of a hack.

**Comment by vrutkovs** [comment]
OKD 4.6 is shipping these RPMs by [fetching them](https://github.com/openshift/okd-machine-os/blob/master/entrypoint.sh#L90-L96) and storing a repo in [/extension folder of machine-os-content](https://github.com/openshift/okd-machine-os/blob/master/Dockerfile#L14).

Could CRC mount that image during build and enable this repo? We could use fedora/updates repos too, but it might cause a slight desync between package versions (not really important for glusterfs/glusterfs-fuse, but might be critical for NetworkManager-ovs)

**Comment by cgruver** [comment]
Yes, that is doable.

I believe that this is potentially a larger issue with the FCOS image that we are using.

That error is thrown with any rpm-ostree install command.  for example:

```bash
yum.repos.d]# rpm-ostree install tar --allow-inactive
Inactive requests:
  libvarlink-util (already provided by libvarlink-util-19-3.fc33.x86_64)
  tar (already provided by tar-2:1.32-6.fc33.x86_64)
Checking out tree b0ae45f... done
Enabled rpm-md repositories: updates updates-archive
rpm-md repo 'updates' (cached); generated: 2020-11-30T00:47:11Z
rpm-md repo 'updates-archive' (cached); generated: 2020-11-30T02:34:57Z
Importing rpm-md... done
error: Packages not found: glusterfs, glusterfs-fuse
```

**Comment by cgruver** [comment]
BTW, I enabled `updates` while debugging.  Originally, only `updates-archive` was enabled.

**Comment by cgruver** [comment]
Thanks @dustymabe, it has not been modified.

It's the image bundled with OKD 4.6.  I'm not sure how to extract the exact build.

`5.9.10-200.fc33.x86_64` is the output from uname.

**Comment by dustymabe** [comment]
> Thanks @dustymabe, it has not been modified.
> 
> It's the image bundled with OKD 4.6. `33.20201128.10.0`

I'm fairly certain the OKD release process modifies the image slightly. I don't see this issue with that image when downloading it from the FCOS release browser: https://github.com/coreos/fedora-coreos-tracker/issues/684#issuecomment-735838790

**Comment by cgruver** [comment]
We'll have to look at the OKD release process then.  I wonder if there is a pending install of glusterfs, and glusterfs-fuse that is stuck.

@vrutkovs Do you have any ideas?

Regardless of what you try to install, you will get this error: `error: Packages not found: glusterfs, glusterfs-fuse`

**Comment by vrutkovs** [comment]
> I wonder if there is a pending install of glusterfs, and glusterfs-fuse that is stuck.

OKD requests installing these RPMs via OS extension, so it happens on firstboot. What we need here is to enable extensions repo (MCD is [doing that](https://github.com/openshift/machine-config-operator/blob/5b694bd01f4482c474a9ec85c1a07d60fd135a34/pkg/daemon/update.go#L213-L219) during node update/install)

**Comment by cgruver** [comment]
OK, I'll try your recommendation above and see if that will work.

> OKD 4.6 is shipping these RPMs by [fetching them](https://github.com/openshift/okd-machine-os/blob/master/entrypoint.sh#L90-L96) and storing a repo in [/extension folder of machine-os-content](https://github.com/openshift/okd-machine-os/blob/master/Dockerfile#L14).
> 
> Could CRC mount that image during build and enable this repo? We could use fedora/updates repos too, but it might cause a slight desync between package versions (not really important for glusterfs/glusterfs-fuse, but might be critical for NetworkManager-ovs)

**Comment by cgruver** [comment]
I solved this by simply enabling the fedora and fedora-updates repos.  Since it's only installing driver support for hyperV, this solution works fine.

**Comment by vrutkovs** [comment]
Ideally we'd include hyper-v agent in https://github.com/openshift/okd-machine-os (unless it has a lot of dependency RPMs)
