### ISSUE TITLE
4.6 Install Bare Metal Console it's getting created

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#403]
4.6 Install Bare Metal Console it's getting created.
See attached/
<img width="1155" alt="OKD_4 6_INSTALL" src="https://user-images.githubusercontent.com/23619505/100771889-f0ba0580-33cc-11eb-9dd3-4f45d5a3313d.png">

**Comment by johnlongo** [comment]
Tried, but it's timing out.
oc adm must-gather
[must-gather      ] OUT the server is currently unable to handle the request (get imagestreams.image.openshift.io must-gather)
[must-gather      ] OUT
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/origin-must-gather:latest
[must-gather      ] OUT namespace/openshift-must-gather-xgxjv created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-mphwb created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/origin-must-gather:latest created
[must-gather-hnlv9] OUT gather did not start: timed out waiting for the condition
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-mphwb deleted
[must-gather      ] OUT namespace/openshift-must-gather-xgxjv deleted
error: gather did not start for pod must-gather-hnlv9: timed out waiting for the condition

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html)

**Comment by johnlongo** [comment]
Not able to create the bundle.
Is there anything different between 4.5 & 4.6 installation procedures? 
Because I'm doing exactly what I did to install 4.5 (Same install-config.yaml) just different versions of the software (i.e. Install, client & fedora coreos).

What I'm noticing after allowing it to run 43 hours:
Package Server, Monitoring, Console & Authentication Cluster Operators never become available. But all the nodes are in the ready state. So I'm pretty much stuck

<img width="1069" alt="OKD_4 6_INSTALL-2" src="https://user-images.githubusercontent.com/23619505/101126753-211ac300-35ca-11eb-9b57-e00051274096.png">

<img width="1069" alt="OKD_4 6_INSTALL-1" src="https://user-images.githubusercontent.com/23619505/101126735-1829f180-35ca-11eb-9a29-233e31c6d1f4.png">
