### ISSUE TITLE
Upgrade 4.5 -> 4.6 hangs on ovirt IPI at CSI Driver Operator

### ISSUE THREAD

**Issue by EagleIJoe** [openshift/okd#406]
**Describe the bug**
Triggered an upgrade within the console of a 4.5.0-0.okd-2020-10-15-235428 cluster towards 4.6. Upgrade went fine until storage is stuck with the error: OVirtCSIDriverOperatorCRProgressing: OvirtDriverControllerProgressing: Waiting for Deployment to deploy controller pods.

Cluster operators dns, machine-config, and network are still on 4.5. All others report as 4.6.

**Version**
4.6.0-0.okd-2020-11-27-200126 ovirt IPI

**How reproducible**
Can't reproduce as resources not available

**Log bundle**

must-gather: https://1drv.ms/u/s!AhsStU0_yWDegUXpTfbwE7Bq67IV

**Comment by vrutkovs** [comment]
That seems to be affecting OCP as well - https://bugzilla.redhat.com/show_bug.cgi?id=1904385.

Lets track the issue there as its not OKD-specific
