### ISSUE TITLE
OKD 4.6 installation on vSphere UPI, machineset/machine objects still wrong?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#408]
**Describe the bug**
Like in previous releases, when installing on vSphere UPI, the machineset and machine objects are wrong after installation:
```
C:\Work>oc get machineset -A                                                                          
NAMESPACE               NAME                    DESIRED   CURRENT   READY   AVAILABLE   AGE           
openshift-machine-api   kur-test-w7vg4-worker   0         0                             8h            
                                                                                                      
C:\Work>oc get machine -A                                                                             
NAMESPACE               NAME                      PHASE          TYPE   REGION   ZONE   AGE           
openshift-machine-api   kur-test-w7vg4-master-0   Failed                                8h            
openshift-machine-api   kur-test-w7vg4-master-1   Provisioning                          8h            
openshift-machine-api   kur-test-w7vg4-master-2   Provisioning                          8h            
                                                                                                      
C:\Work>oc get node                                                                                   
NAME                        STATUS   ROLES    AGE   VERSION                                           
master-01.kur-test.ars.de   Ready    master   8h    v1.19.0-rc.2+9f84db3-1075                         
master-02.kur-test.ars.de   Ready    master   8h    v1.19.0-rc.2+9f84db3-1075                         
master-03.kur-test.ars.de   Ready    master   8h    v1.19.0-rc.2+9f84db3-1075                         
worker-01.kur-test.ars.de   Ready    worker   8h    v1.19.0-rc.2+9f84db3-1075                         
worker-02.kur-test.ars.de   Ready    worker   8h    v1.19.0-rc.2+9f84db3-1075                         
worker-03.kur-test.ars.de   Ready    worker   8h    v1.19.0-rc.2+9f84db3-1075                         

```
This also leads to alerts firing because of this.
In previous versions, the workaround was to delete these objects. In 4.6, this is no longer possible.
While I can delete the machineset object, the machine objects can not be deleted.
The oc delete command hangs eternally and the objects are stuck in "Deleting" state (in the PHASE column).

**Version**
OKD 4.6 20201127 on vSphere UPI

**How reproducible**
100%

**Log bundle**
Can provide if needed.

**Comment by romankspb** [comment]
Did you forget remove the Kubernetes manifest files that define the control plane machines and compute machineSets?

[Creating the Kubernetes manifest and Ignition config files](https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere.html#installation-user-infra-generate-k8s-manifest-ignition_installing-vsphere)

**Comment by vrutkovs** [comment]
>Can provide if needed.

Please provide log-bundle / must-gather for _all_ bugs

**Comment by kai-uwe-rommel** [comment]
@romankspb Thanks for the pointer. Perhaps that was not yet documented at the time when I started creating my cluster meta installer (back in April). And later I did not re-read this. And until now, deleting these objects afterwards was easy. So I have fixed it now following this official way.

@vrutkovs I know. But in most of my cases it was a matter of discussing it because there was lack of documentation, for example. In other cases capturing a must-gather did not even work. For me, it is important to fight for every 10 minutes of time I can save, given my workload and backlog. So if I can save that, great. But should after the initial words of checking a new case it becomes clear that a must-gather will be helpful, I will of course always provide one.

**Comment by LorbusChris** [comment]
@kai-uwe-rommel please do not assume you're the only with high workload and a large backlog.
If e.g. must-gather doesn't work, please state so in the description.
Do the due diligence when opening issues as described in the issue template.
That saves _us_ the minutes spent on reminding to add vital info.

**Comment by kai-uwe-rommel** [comment]
@LorbusChris, sure you are right in general.
But several of my issues in the last months have been because of problems with the documentation. Such as that it was simply copied over from OCP and not adjusted for OKD and therefore things were not working liek documented or not clear how to apply for OKD.
A must-gather does not make any sense for such an issue. But is there a different way of opening an issue (such as with a different template) in such cases?
