### ISSUE TITLE
Failed to pull image "docker.io/openshift/origin-deployer:v3.11.0"

### ISSUE THREAD

**Issue by antonioribezzi** [openshift/okd#410]
Since November 20th, I regularly get this error when trying to deploy some images to an OKD 3.11 cluster. It's due to the pull rate llimit introduced on docker hub. It means that one should create a paid account on docker hub, and add a pull secret to every project in the cluster to make it work. Probably it would be better also to migrate images used by OKD 3.11 to quay.io, or some other registry.

How can we solve this issue?

**Comment by vrutkovs** [comment]
This repo is for OKD4 bugs, please report OKD 3.11 issues at https://github.com/openshift/openshift-ansible
