### ISSUE TITLE
Add second NIC thru machine config is not working

### ISSUE THREAD

**Issue by bobby0724** [openshift/okd#413]
**Describe the bug**

I am trying to add  a second NIC adapter to my worker nodes because my NFS runs on isolated network
the machine config i am using is an example that we use on OCP 4.6 and works but in OKD 4.5 the worker never get the ip up

**Version**
4.5.0-0.okd-2020-10-15-235428

**How reproducible**
Here is the yml file i am using

**Log bundle**

[99-bkp-network.txt](https://github.com/openshift/okd/files/5646587/99-bkp-network.txt)

**Comment by bobby0724** [comment]
This is the error on the worker node
systemd Failed Units 1 NetworkManager-wait-online.service

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive
