### ISSUE TITLE
IPI on vSphere: vmtoolsd service is not started on bootstrap node

### ISSUE THREAD

**Issue by damhau** [openshift/okd#415]
**Describe the bug**
On an IPI deployment on vSphere the systemd service vmtoolsd is not started on the bootstrap node.
My understanding is that the installer expect to be able to get the ip address of the node from the vcenter api and for this it needed that all the node run vmtoolsd.

**Version**
IPI
4.6.0-0.okd-2020-12-06-204258

**How reproducible**
100%

**Log bundle**
I'll add the log bundle as soon as possible

**Comment by vrutkovs** [comment]
https://github.com/openshift/okd-machine-os/pull/36 would fix that

**Comment by damhau** [comment]
great thanks

**Comment by damhau** [comment]
i'll close this issue.

**Comment by vrutkovs** [comment]
Lets keep it open for tracking (it need 4.6 cherrypick too)

**Comment by vrutkovs** [comment]
Fixed in https://amd64.origin.releases.ci.openshift.org/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2020-12-08-104416 (a proper vsphere deployment still needs a few more fixes)
