### ISSUE TITLE
IPI 4.6 on vSphere: node-valid-hostname service fail on first boot on master

### ISSUE THREAD

**Issue by damhau** [openshift/okd#416]
**Describe the bug**
On a fresh deployment with IPI on vSphere, on the first boot the systemd service node-valid-hostname fails.

My understanding is that it is related to the honstmae being set by default to "fedora" instead of "localhost" on FC33.

Here is the function "wait_localhost" of /usr/local/sbin/set-valid-hostname.sh (this is called by node-valid-hostname service):

```
wait_localhost() {
    log "waiting for non-localhost hostname to be assigned"
    while [[ "$(< /proc/sys/kernel/hostname)" =~ (localhost|localhost.localdomain) ]];
    do
        sleep 1
    done
    log "node identified as $(</proc/sys/kernel/hostname)"
    exit 0
}
```
As the hostname is never "localhost" the check fails and after the timeout of 300 sec configured in the systemd service the service stop with the error "Failed to start Ensure the node hostname is valid for the cluster."

I think that this probably slows down the whole bootstrap of the node, the deployment was much faster in 4.5.

**Version**
IPI
4.6.0-0.okd-2020-12-06-204258

**How reproducible**
100%

**Log bundle**
What kind of log is needed ?

**Comment by vrutkovs** [comment]
Isn't this being tracked in https://github.com/openshift/okd/issues/392?

**Comment by damhau** [comment]
I was not sure if they were 100% the same, if yes I can close this.

Btw, any estimation on when the build with the fix for "fedora" hostname will be ready ?
