### ISSUE TITLE
The OKD4 web console run for 3 days and crash

### ISSUE THREAD

**Issue by lucmike** [openshift/okd#417]
I just followed the guide to install OKD 4.5 cluster by Graig Robinson.  the OKD web console ran for 3 day and crashed.
the 
all I can see is the message below:

{
   "kind":  "Status",
   "apiVersion": "v1",
   "metadata": {

   },
   "status": "Failure",
   "message":  "forbidden: User \"system:anonymous\" cannot get path \"/\"",
   "reason":  "Forbidden",
   "details":  {
   }
   "code":  403
}

**Describe the bug**

**Version**

**How reproducible**

**Log bundle**

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)
