### ISSUE TITLE
vSphere install - Not all worker nodes get started at creation

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#419]
**Describe the bug**

I'm not sure whether this is a bug or not.  It could be my vSphere environment...

When the worker nodes are created,  it is quite often the case that one or more worker nodes are created but not powered on.  This is an issue because if you install with all defaults  (3 master/3 workers) and only one worker starts, the cluster install will not complete due to resource constraints on the one worker having only 8 Gig memory.

Occasionally, all workers will start and sometimes no workers will start.

Logs indicate that the worker nodes are all created successfully.

The cloning code seems to indicate that the worker should be powered on after cloning:

https://github.com/openshift/machine-api-operator/blob/release-4.6/pkg/controller/vsphere/reconciler.go
```
	spec := types.VirtualMachineCloneSpec{
		Config: &types.VirtualMachineConfigSpec{
			Annotation: s.machine.GetName(),
			// Assign the clone's InstanceUUID the value of the Kubernetes Machine
			// object's UID. This allows lookup of the cloned VM prior to knowing
			// the VM's UUID.
			InstanceUuid:      string(s.machine.UID),
			Flags:             newVMFlagInfo(),
			ExtraConfig:       extraConfig,
			DeviceChange:      deviceSpecs,
			NumCPUs:           numCPUs,
			NumCoresPerSocket: numCoresPerSocket,
			MemoryMB:          memMiB,
		},
		Location: types.VirtualMachineRelocateSpec{
			Datastore:    types.NewReference(datastore.Reference()),
			Folder:       types.NewReference(folder.Reference()),
			Pool:         types.NewReference(resourcepool.Reference()),
			DiskMoveType: diskMoveType,
		},
		PowerOn:  true,
		Snapshot: snapshotRef,
	}

	task, err := vmTemplate.Clone(s, folder, s.machine.GetName(), spec)
```

If I power the node on manually it joins the cluster successfully.

Workaround is to start the nodes manually...

**Version**
vSphere 6.5 IPI
Pretty much all 4.5/4.6 vSphere versions I have tried...

**How reproducible**
almost every install

**Comment by vrutkovs** [comment]
That looks like some machine-api issue, perhaps @elmiko could have a look

**Comment by elmiko** [comment]
thanks for the ping @vrutkovs, i'll add it to my queue ;)

**Comment by elmiko** [comment]
@fortinj66 what type of installation is this (UPI/IPI)?

**Comment by fortinj66** [comment]
This is IPI...   

I don't think its a bug necessarily...   I think it is trying to power-on the VM, but I now see an error in vSphere (with no details of course).  I'm looking further and will update...

**Comment by fortinj66** [comment]
I also saw a similar issue when I added a worker machine ...  I'll add details for that also when the cluster is up...

**Comment by elmiko** [comment]
ack, thanks. my gut feeling is that this is probably something related to your specific configuration. we do run automated installs of vsphere and i haven't seen this issue recently. that said, i know vsphere has a wide matrix of configurations, so i would be happy to learn more details about your config and perhaps incorporate anything we find.

**Comment by vrutkovs** [comment]
Since its not related to our changes in installer or FCOS I'm pretty sure it affects OCP too. Lets file a bugzilla to track that

**Comment by fortinj66** [comment]
The funny thing is that I never have an issue with the masters. Only the nodes...  So whatever process is used to create those with openshift_installer it seems to work seemlessly

**Comment by elmiko** [comment]
the main thing that is concerning me here is that @fortinj66 sees this issue on every install and we have not experienced this in our installer tests. or at the least it hasn't happened enough that we've noticed.

one big difference between the control plane nodes and the worker nodes is that the workers all belong to machinesets and are managed through that mechanism, whereas the control plane is handled differently. given that this is only happening on the workers, it seems directly related to _something_ in the machine-api, or a vsphere config.

**Comment by fortinj66** [comment]
and here is a case when all the workers failed to start.  They all have the following:

![image](https://user-images.githubusercontent.com/8594283/101678639-36f61100-3a2c-11eb-99f5-53e0037f6a0a.png)

The cloning works fine and there is an attempt to start them but they fail...

Our initial thought was that we may have had issues with swap space and that was causing the VMs to not start as swap is allocated when the vm starts...  https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.troubleshooting.doc/GUID-2742CE14-20FD-416F-B89C-A156053A973F.html

But we increased the datastore to more than enough and the issue still occurs...  And I can start the VMs manually...

I'm going to bring the cluster the rest of the way up and test creating a new machine and see what happens.

**Comment by fortinj66** [comment]
I added another machine to the machineset and it provisioned and started successfully...

![image](https://user-images.githubusercontent.com/8594283/101681629-7161ad00-3a30-11eb-8556-292465ee4043.png)


Maybe its a timing issue with the initial worker nodes starting all at the same time?

**Comment by fortinj66** [comment]
Well, I was able to reproduce the when adding three new machines.  All three were created, but only one was powered on.  

![image](https://user-images.githubusercontent.com/8594283/101683682-47f65080-3a33-11eb-8a83-1102edacbf42.png)

I did it again and two were powered on and one off...

If I delete the machines that are powered off and wait 30 seconds between, they will be (usually) be recreated in a powered on state.  Shorter than that and good chance they'll be powered off...

This is pretty repeatable for me...

**Comment by elmiko** [comment]
really interesting about the timing, it seems like that has a direct bearing on what is happening.

**Comment by fortinj66** [comment]
We've opened a case with VMWare for help in determining the error...

**Comment by fortinj66** [comment]
I've been thinking about this for a few days...  

I am wondering why power status isn't used for remediation, especially for a node in the initial "provisioned" status.  Even if the power-on fails during the cloning process, shouldn't the remediation process cause a power-on event?  Don't we expect the node to be powered on initially?  

I see there are power-on and power-off functions in the code, but they do not seem to be used anywhere.  

I think the question would be what happens to nodes that are manually powered off outside of OKD.  Maybe a flag gets set on an initial successful power-on and remediation uses that?

Just food for thought...

**Comment by elmiko** [comment]
> I've been thinking about this for a few days...
> 
> I am wondering why power status isn't used for remediation, especially for a node in the initial "provisioned" status. Even if the power-on fails during the cloning process, shouldn't the remediation process cause a power-on event? Don't we expect the node to be powered on initially?
> 
> I see there are power-on and power-off functions in the code, but they do not seem to be used anywhere.
> 

not so sure about this, i can certainly look into it more.

> I think the question would be what happens to nodes that are manually powered off outside of OKD. Maybe a flag gets set on an initial successful power-on and remediation uses that?
> 
> Just food for thought...

to your last question, this [FAQ entry](https://github.com/openshift/machine-api-operator/blob/master/FAQ.md#what-happens-if-i-delete-an-instance-or-vm-outside-of-the-machine-api-such-as-in-the-aws-web-console) might help

**Comment by fortinj66** [comment]
> to your last question, this [FAQ entry](https://github.com/openshift/machine-api-operator/blob/master/FAQ.md#what-happens-if-i-delete-an-instance-or-vm-outside-of-the-machine-api-such-as-in-the-aws-web-console) might help

That's deletion and makes sense...  power status would seem different (maybe) ?

**Comment by elmiko** [comment]
i'm not sure it would look different to the machine-api, i'd have to do some digging

**Comment by fortinj66** [comment]
Closing...  Issue still occurs but seems to be a vSphere issue
