### ISSUE TITLE
Unable to install OKD 4.5 in Azure

### ISSUE THREAD

**Issue by sebekx** [openshift/okd#421]
**Describe the bug**
Unable to install OKD 4.5 in Azure. I've repeated installation procedure multiple time and every time it ends with the same error. I'v also tried with 4.6 but also withno luck will report separate issue as there is different error.

install-config.yaml:
`
apiVersion: v1
baseDomain: okstest.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: Standard_D2s_v3
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: Standard_D4s_v3
  replicas: 1
metadata:
  creationTimestamp: null
  name: okd1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: okd
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: westeurope
publish: External
pullSecret: '...'
sshKey: |
  ssh-rsa ...`

install command: ./openshift-install create cluster --dir=a --log-level=debug

output:
`
...
INFO Waiting up to 30m0s for the cluster at https://api.okd1.okstest.com:6443 to initialize...
DEBUG Still waiting for the cluster to initialize: Multiple errors are preventing progress:
* Could not update oauthclient "console" (363 of 596): the server does not recognize this resource, check extension API servers
* Could not update prometheusrule "openshift-cloud-credential-operator/cloud-credential-operator-alerts" (198 of 596): the server does not recognize this resource, check extension API servers
* Could not update prometheusrule "openshift-cluster-samples-operator/samples-operator-alerts" (315 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-authentication-operator/authentication-operator" (510 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-cluster-machine-approver/cluster-machine-approver" (520 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-cluster-version/cluster-version-operator" (8 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-config-operator/config-operator" (124 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-image-registry/image-registry" (516 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-machine-api/cluster-autoscaler-operator" (230 of 596): the server does not recognize this resource, check extension API servers
ERROR Cluster operator authentication Degraded is True with ConfigObservation_Error::IngressStateEndpoints_MissingEndpoints::RouterCerts_NoRouterCertSecret: RouterCertsDegraded: secret/v4-0-config-system-router-certs -n openshift-authentication: could not be retrieved: secret "v4-0-config-system-router-certs" not found
ConfigObservationDegraded: secret "v4-0-config-system-router-certs" not found
IngressStateEndpointsDegraded: No endpoints found for oauth-server
INFO Cluster operator authentication Progressing is Unknown with NoData:
INFO Cluster operator authentication Available is Unknown with NoData:
INFO Cluster operator csi-snapshot-controller Progressing is True with _AsExpected: Progressing: Waiting for Deployment to deploy csi-snapshot-controller pods
INFO Cluster operator csi-snapshot-controller Available is False with _AsExpected: Available: Waiting for Deployment to deploy csi-snapshot-controller pods
INFO Cluster operator etcd Progressing is True with NodeInstaller: NodeInstallerProgressing: 1 nodes are at revision 2; 0 nodes have achieved new revision 3
INFO Cluster operator kube-apiserver Progressing is True with NodeInstaller: NodeInstallerProgressing: 1 nodes are at revision 2; 0 nodes have achieved new revision 3
INFO Cluster operator kube-controller-manager Progressing is True with NodeInstaller: NodeInstallerProgressing: 1 nodes are at revision 5; 0 nodes have achieved new revision 6
INFO Cluster operator kube-storage-version-migrator Available is False with _NoMigratorPod: Available: deployment/migrator.openshift-kube-storage-version-migrator: no replicas are available
INFO Cluster operator machine-config Progressing is True with : Unable to apply 4.5.0-0.okd-2020-10-15-235428
ERROR Cluster operator machine-config Degraded is True with RenderConfigFailed: Unable to apply 4.5.0-0.okd-2020-10-15-235428: openshift-config-managed/kube-cloud-config configmap is required on platform Azure but not found: configmap "kube-cloud-config" not found
INFO Cluster operator machine-config Available is False with : Cluster not available for 4.5.0-0.okd-2020-10-15-235428
ERROR Cluster operator openshift-apiserver Degraded is True with APIServerDeployment_UnavailablePod: APIServerDeploymentDegraded: 1 of 1 requested instances are unavailable for apiserver.openshift-apiserver
INFO Cluster operator openshift-apiserver Progressing is True with APIServerDeployment_NewGeneration: APIServerDeploymentProgressing: deployment/apiserver.openshift-apiserver: observed generation is 0, desired generation is 1.
INFO Cluster operator openshift-apiserver Available is False with APIServerDeployment_NoPod::APIServices_PreconditionNotReady: APIServicesAvailable: PreconditionNotReady
APIServerDeploymentAvailable: no apiserver.openshift-apiserver pods available on any node.
INFO Cluster operator openshift-controller-manager Progressing is True with _DesiredStateNotYetAchieved: Progressing: daemonset/controller-manager: observed generation is 0, desired generation is 10.
Progressing: daemonset/controller-manager: number available is 0, desired number available > 1
INFO Cluster operator openshift-controller-manager Available is False with _NoPodsAvailable: Available: no daemon pods available on any node.
FATAL failed to initialize the cluster: Multiple errors are preventing progress:
* Could not update oauthclient "console" (363 of 596): the server does not recognize this resource, check extension API servers
* Could not update prometheusrule "openshift-cloud-credential-operator/cloud-credential-operator-alerts" (198 of 596): the server does not recognize this resource, check extension API servers
* Could not update prometheusrule "openshift-cluster-samples-operator/samples-operator-alerts" (315 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-authentication-operator/authentication-operator" (510 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-cluster-machine-approver/cluster-machine-approver" (520 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-cluster-version/cluster-version-operator" (8 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-config-operator/config-operator" (124 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-image-registry/image-registry" (516 of 596): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-machine-api/cluster-autoscaler-operator" (230 of 596): the server does not recognize this resource, check extension API servers`

./oc get co:
![image](https://user-images.githubusercontent.com/2842422/101799439-7300a300-3b0c-11eb-83df-a3ffec0737c4.png)

`azureuser@jumpbox:~$ ./oc get clusteroperator authentication -oyaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  creationTimestamp: "2020-12-10T12:31:28Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
      f:spec: {}
      f:status:
        .: {}
        f:extension: {}
        f:versions: {}
    manager: cluster-version-operator
    operation: Update
    time: "2020-12-10T12:31:28Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:relatedObjects: {}
    manager: authentication-operator
    operation: Update
    time: "2020-12-10T12:40:55Z"
  name: authentication
  resourceVersion: "6454"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/authentication
  uid: 7594c15e-b600-4d0e-82f7-af2ee6aead2c
spec: {}
status:
  conditions:
  - lastTransitionTime: "2020-12-10T12:40:55Z"
    message: |-
      RouterCertsDegraded: secret/v4-0-config-system-router-certs -n openshift-authentication: could not be retrieved: secret "v4-0-config-system-router-certs" not found
      ConfigObservationDegraded: secret "v4-0-config-system-router-certs" not found
      IngressStateEndpointsDegraded: No endpoints found for oauth-server
    reason: ConfigObservation_Error::IngressStateEndpoints_MissingEndpoints::RouterCerts_NoRouterCertSecret
    status: "True"
    type: Degraded
  - lastTransitionTime: "2020-12-10T12:38:53Z"
    reason: NoData
    status: Unknown
    type: Progressing
  - lastTransitionTime: "2020-12-10T12:38:53Z"
    reason: NoData
    status: Unknown
    type: Available
  - lastTransitionTime: "2020-12-10T12:38:54Z"
    reason: AsExpected
    status: "True"
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: infrastructures
  - group: config.openshift.io
    name: cluster
    resource: oauths
  - group: route.openshift.io
    name: oauth-openshift
    namespace: openshift-authentication
    resource: routes
  - group: ""
    name: oauth-openshift
    namespace: openshift-authentication
    resource: services
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-authentication
    resource: namespaces
  - group: ""
    name: openshift-authentication-operator
    resource: namespaces
  - group: ""
    name: openshift-ingress
    resource: namespaces`

**Version**
openshift-install-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz

**How reproducible**
100% reproducable

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive
