### ISSUE TITLE
4.6: Bootstrap fails due to missing crio.conf

### ISSUE THREAD

**Issue by kcchu** [openshift/okd#424]
**Describe the bug**
Trying to install OKD 4.6 on baremetal. `bootkube.service` failed to start because of an error in `crio-configure.service`

**Version**
4.6.0-0.okd-2020-11-27-200126
Current stable stream: fedora-coreos-32.20201104.3.0-live.x86_64

**How reproducible**
Install fedora-coreos-32.20201104.3.0-live.x86_64 with the ignition file generated by openshift-install

**Log bundle**
```
● crio-configure.service - Configure CRI-O to use the pause image
     Loaded: loaded (/etc/systemd/system/crio-configure.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2020-12-11 12:06:23 UTC; 14s ago
    Process: 7717 ExecStart=/usr/local/bin/crio-configure.sh (code=exited, status=2)
   Main PID: 7717 (code=exited, status=2)

Dec 11 12:06:23 localhost podman[7745]: 2020-12-11 12:06:23.132534038 +0000 UTC m=+0.090622449 container create 6b1f4379594be43781b2cb2f2b375a85c8eb9857d5ed57d887aa6d66>
Dec 11 12:06:23 localhost podman[7745]: 2020-12-11 12:06:23.211530406 +0000 UTC m=+0.169618818 container init 6b1f4379594be43781b2cb2f2b375a85c8eb9857d5ed57d887aa6d6614>
Dec 11 12:06:23 localhost podman[7745]: 2020-12-11 12:06:23.222865925 +0000 UTC m=+0.180954336 container start 6b1f4379594be43781b2cb2f2b375a85c8eb9857d5ed57d887aa6d661>
Dec 11 12:06:23 localhost podman[7745]: 2020-12-11 12:06:23.223043177 +0000 UTC m=+0.181131591 container attach 6b1f4379594be43781b2cb2f2b375a85c8eb9857d5ed57d887aa6d66>
Dec 11 12:06:23 localhost podman[7745]: 2020-12-11 12:06:23.272021693 +0000 UTC m=+0.230110103 container died 6b1f4379594be43781b2cb2f2b375a85c8eb9857d5ed57d887aa6d6614>
Dec 11 12:06:23 localhost podman[7745]: 2020-12-11 12:06:23.318867068 +0000 UTC m=+0.276955493 container remove 6b1f4379594be43781b2cb2f2b375a85c8eb9857d5ed57d887aa6d66>
Dec 11 12:06:23 localhost crio-configure.sh[7838]: sed: can't read /etc/crio/crio.conf: No such file or directory
Dec 11 12:06:23 localhost systemd[1]: crio-configure.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 11 12:06:23 localhost systemd[1]: crio-configure.service: Failed with result 'exit-code'.
Dec 11 12:06:23 localhost systemd[1]: Failed to start Configure CRI-O to use the pause image.
```

**Comment by vrutkovs** [comment]
Did `release-image-download.service` complete? What's the output of `rpm-ostree status`?

**Comment by kcchu** [comment]
The problem seems to be caused by the fact that I have rebooted the master node during the installation (because it hanged at some place).

Eventually I could install 4.5 without issues (failed to install 4.6 due to other issues). I am closing this issue.

**Comment by bretm** [comment]
I'm running into this right now, trying to install on some local vm's.  bookkube.service fails with this as a dependency, and I get nowhere.

Underlying images are using:

  fedora-coreos-33.20210217.3.0-live.x86_64.iso

Installer I'm using (with matching client):

  openshift-install-linux-4.6.0-0.okd-2021-01-17-185703.tar.gz

Is this the right combination for a stable OKD UPI install these days?
