### ISSUE TITLE
4.6.0-0.okd-2020-12-12-135354 Installation failed in vSphere at restricted network environment

### ISSUE THREAD

**Issue by SuhyunClaire** [openshift/okd#427]
**Describe the bug**
when Fresh installation 4.6.0-0.okd-2020-12-12-135354 in vSphere resstricted network environment, all the master, worker nodes are ready, but cluster operators shows weird.

![image](https://user-images.githubusercontent.com/28854717/102060569-b40ef500-3e35-11eb-911e-fc9ee50c6ead.png)

![image](https://user-images.githubusercontent.com/28854717/102060648-ca1cb580-3e35-11eb-932d-675089e6d4eb.png)

as shown command result, 'console', 'monitoring' and 'openshift-samples' do not show nothing even version.
Also, openshift-apiserver's progress and available is false but also degraded status is false too.
Is there any solution? this version is stable one?

**Version**
4.6.0-0.okd-2020-12-12-135354
 

**How reproducible**
100% reproducible 

**Log bundle**

**Comment by romankspb** [comment]
Looks like the same https://github.com/openshift/okd/issues/395

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)
