### ISSUE TITLE
No Storage Operators for Ceph in OKD 4.6

### ISSUE THREAD

**Issue by lukonjun** [openshift/okd#429]
Hi, 

I just installed a fresh Version of OKD 4.6. Accessing the Webconsole and searching for Operators under Operatorhub returns neither the Rook Operator or the Openshift Container Storage Operator. Is this software only in Openshift Enterprise accessible?

Regards Lucas

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd/blob/master/FAQ.md#how-can-i-enable-the-non-community-red-hat-operators

**Comment by lukonjun** [comment]
Thanks for your quick reply. This means I can not use the Openshift Container Storage Operator for free in Production correct, as it does not  belong to the community operators?

Rook however is as i read Opensource, why is it not included in the OperatorHub?  

Do you have recommendation for a Storage Operator, or a Storage Solution that offers Dynamic Provisioning and is free? I installed the Cluster in VMWare. 

Thanks and regards Lucas

**Comment by vrutkovs** [comment]
>Rook however is as i read Opensource, why is it not included in the OperatorHub?

That needs to be tracked in https://github.com/operator-framework/community-operators

**Comment by cgruver** [comment]
@lukonjun Until the operator is available in the OperatorHub, you can roll your own install with the files here:

https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph

I have instructions that are opinionated toward my own lab setup here:

https://github.com/cgruver/okd4-upi-lab-setup

These are not updated to the latest version of Rook/Ceph yet, but should still work.
