### ISSUE TITLE
docs: Describe current state of IPI vs UPI testing

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/okd#43]
Per discussion with @vrutkovs:

> Right, this needs careful wording in a README of okd repo.
At the moment we have 2 blocking e2e tests for okd-specific repos - AWS IPI install and vSphere UPI install in our CI. Other platforms - like gcp/azure/metal would be added as optional in order to test platform-specific things. We don't have a capacity to test all platforms at once sadly. Also note, that OKD nightlies are promoted from OCP nightlies which run all kind of platform tests, so I think we're sufficiently covered by those.
In terms of supported installs both IPI and UPI are equal (although reproducing IPI issues is easier)
Lets file a bug in okd repo to describe current state of this in the README

**Comment by vrutkovs** [comment]
Current state as of Feb 1:
CI tested:
* AWS IPI - blocking test to accept releases
* Installer / MCO forks have vSphere UPI tests (these are flaky now)

User testing:
* Baremetal seems to work
* GCP - won't bootstrap, see https://github.com/openshift/okd/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aplatform%2Fgoogle
* Azure - issues with uploading FCOS image, see https://github.com/openshift/okd/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aplatform%2Fazure
* oVirt - support should be in the installer, no user reports so far
* Openstack - ditto

**Comment by vrutkovs** [comment]
As of https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-03-13-191636 oVirt and Openstack should work, so current installer supports all installation methods.
