### ISSUE TITLE
Bootstrap never finishes

### ISSUE THREAD

**Issue by lucmike** [openshift/okd#431]
Bootstrap never finishes 
I got the following errors:

[core@okd4-bootstrap ~]$ journalctl -b -f -u release-image.service -u bootkube.service
-- Logs begin at Mon 2020-12-14 15:17:48 UTC. --
Dec 14 16:09:52 okd4-bootstrap bootkube.sh[30539]: Skipped "secret-initial-kube-controller-manager-service-account-private-key.yaml" secrets.v1./initial-service-account-private-key -n openshift-config as it already exists
Dec 14 16:09:52 okd4-bootstrap bootkube.sh[30539]: Skipped "secret-kube-apiserver-to-kubelet-signer.yaml" secrets.v1./kube-apiserver-to-kubelet-signer -n openshift-kube-apiserver-operator as it already exists
Dec 14 16:09:52 okd4-bootstrap bootkube.sh[30539]: Skipped "secret-loadbalancer-serving-signer.yaml" secrets.v1./loadbalancer-serving-signer -n openshift-kube-apiserver-operator as it already exists
Dec 14 16:09:53 okd4-bootstrap bootkube.sh[30539]: Skipped "secret-localhost-serving-signer.yaml" secrets.v1./localhost-serving-signer -n openshift-kube-apiserver-operator as it already exists
Dec 14 16:09:53 okd4-bootstrap bootkube.sh[30539]: Skipped "secret-service-network-serving-signer.yaml" secrets.v1./service-network-serving-signer -n openshift-kube-apiserver-operator as it already exists
Dec 14 16:09:58 okd4-bootstrap bootkube.sh[30539]: E1214 16:09:58.912650       1 reflector.go:251] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: Get https://localhost:6443/api/v1/pods?watch=true: dial tcp [::1]:6443: connect: connection refused
Dec 14 16:09:59 okd4-bootstrap bootkube.sh[30539]: E1214 16:09:59.917255       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Dec 14 16:10:00 okd4-bootstrap bootkube.sh[30539]: E1214 16:10:00.972557       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Dec 14 16:10:01 okd4-bootstrap bootkube.sh[30539]: E1214 16:10:01.974271       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Dec 14 16:10:02 okd4-bootstrap bootkube.sh[30539]: E1214 16:10:02.976384       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused

**Describe the bug**

**Version**

**How reproducible**

**Log bundle**

**Comment by mrshengzyzy** [comment]
same problem，and I guess this is network problem. 
I wait for a long time and then it's resolved itself :)

**Comment by lucmike** [comment]
mrshengzyzy, thank you for the tip, it is network problem. I have conflict gateway that my bootstrap did not see the internet.
