### ISSUE TITLE
OperatorHub inconsistent to Documentation

### ISSUE THREAD

**Issue by alexanderniebuhr** [openshift/okd#432]
**Describe the bug**

We are following the installation documentation of OKD and are finding out it does not match with the installed Cluster for OKD 4.6

Especially we are on the way to prepare our migration from managed Kubernetes. Currently, I am working on the VPA.
My OperatorHub does not show the VerticalPodAutoscaler, but the documentation says this here:
https://docs.okd.io/latest/nodes/pods/nodes-pods-vertical-autoscaler.html#nodes-pods-vertical-autoscaler-install_nodes-pods-vertical-autoscaler

So I guess either there is a Bug with sources of operators or the documentation is not up to date, or missing some important steps

![operatorHub](https://user-images.githubusercontent.com/45965090/102216967-38b44e80-3edc-11eb-8129-bd2d2f7ae837.png)

**Version**

4.6.0-0.okd-2020-12-12-135354

**How reproducible**

Clean install and checking OperatorHub .... i guess.

**Log bundle**

can provide later with specific request

**Comment by alexanderniebuhr** [comment]
I got a bit deeper into this Topic. Might be the same as #429 #358 #283 

With solution being: https://github.com/openshift/okd/blob/master/FAQ.md#how-can-i-enable-the-non-community-red-hat-operators

@vrutkovs I think it might be a good thing to include this FAQ part into official OKD Documentation on Website. Otherwise it looks like a bug.

**Comment by alexanderniebuhr** [comment]
So just for clarification is using pull secrets from openshift.com/try allowed for production clusters?

**Comment by mburke5678** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/28779
