### ISSUE TITLE
Install OKD 4.6 on vSphere UPI failed

### ISSUE THREAD

**Issue by romankspb** [openshift/okd#435]
**Describe the bug**

`openshift-install wait-for install-complete` failed with message:

Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthRouteCheckEndpointAccessibleController_SyncError::OAuthServerDeployment_GetFailed::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError::OAuthVersionDeployment_GetFailed::Route_FailedGet: OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded: oauth service endpoints are not ready
OAuthServiceCheckEndpointAccessibleControllerDegraded: Get "https://172.30.181.54:443/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server
OAuthRouteCheckEndpointAccessibleControllerDegraded: Get "https://oauth-openshift.apps.okd4-spb.sigma-it.local/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
OAuthServerDeploymentDegraded: Unable to get "openshift-browser-client" bootstrapped CLI OAuth client: the server is currently unable to handle the request (post oauthclients.oauth.openshift.io)
RouteDegraded: Unable to get required route openshift-authentication/oauth-openshift: the server is currently unable to handle the request (get routes.route.openshift.io oauth-openshift)
OAuthVersionDeploymentDegraded: Unable to get OAuth server deployment: deployment.apps "oauth-openshift" not found"

`$ oc get co` 
![изображение](https://user-images.githubusercontent.com/785755/102532854-a798cf80-40b5-11eb-9f7c-fc95ca38badf.png)

`$ oc get nodes`
![изображение](https://user-images.githubusercontent.com/785755/102533505-93090700-40b6-11eb-9630-f5198cc4d17a.png)

`$ oc get pods -n openshift-authentication`
`No resources found in openshift-authentication namespace.`

**Version**
4.6.0-0.okd-2020-12-12-135354 on vSphere UPI

**How reproducible**
reproducible - 100%

**Log bundle**
[must-gather](https://oc.sigma-it.ru/owncloud/index.php/s/kcW15PCuLsPhX3K)

**Comment by vrutkovs** [comment]
>Get \"https://172.30.181.54:443/healthz\": dial tcp 172.30.181.54:443: i/o timeout (Client.Timeout exceeded while awaiting headers)

Seems OpenShiftSDN installs are broken - service won't reply

**Comment by romankspb** [comment]
With the OVNKubernetes network plugin, cluster was installed successfully.

**Comment by vrutkovs** [comment]
Lets track this in #430
