### ISSUE TITLE
oauth connection to secure LDAP fails due to golang 1.15 non-SAN cert deprecation

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#443]
**Describe the bug**
Connection to a secure LDAP server I get the following error message:

```
Error authenticating "xxxx" with provider "MA-AD Secure": LDAP Result Code 200 "Network Error": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

The endpoint is a Netscaler with a self-signed internal certificate (non-SAN.)  We've had some issues with installing SAN certs on the Netscaler and would like to implement the workaround for now  (`GODEBUG=x509ignoreCN=0`)

Unfortunately, I cannot determine where to set this configuration variable.  Normally I would either set it as a config-map setting or directly as an environment variable.  However, with oauth being controlled from an operator and running as a replica set I'm at a loss as how to proceed...

As an aside, this golang 1.15 change will affect anything that uses a non-SAN certificate...

https://bugzilla.redhat.com/show_bug.cgi?id=1886892

**Version**
4.6.0-0.okd-2020-12-12-135354
vSphere IPI

**How reproducible**
100% reproducable

**Comment by fortinj66** [comment]
Any thoughts?

**Comment by fortinj66** [comment]
We have updated internal certs.  I still think this will bite people in the future

**Comment by kai-uwe-rommel** [comment]
It may become a significant problem if your LDAP server is an AD DC which gets its certificate automatically via GPO etc. from an internal CA.
