### ISSUE TITLE
Update SSH private key generation in the latest OKD installation documentation

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#445]
**Describe the bug**
To be more consistent with the sshKey parameter in the sample install-config.yaml (sshKey: 'ssh-ed25519 AAAA...'), maybe you should also replace the deprecated SSH private key generation in all "Generating an SSH private key and adding it to the agent" sections from the installation documentation. For example in https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#ssh-agent-using_installing-bare-metal

```
ssh-keygen -t rsa -b 4096 -N '' \
    -f <path>/<file_name>
```

to

```
ssh-keygen -t ed25519 -N '' \
    -f <path>/<file_name>
```

**Comment by mburke5678** [comment]
@vrutkovs @myg0v Please take a look. The request here is to replace the RSA key generation with ed2559 key generation?

**Comment by myg0v** [comment]
I think so, this is due to new crypto policies in Fedora 33 https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2

Please note "Generating an SSH private key and adding it to the agent" needs to be edited in multiple docs not only bare metal installation.

**Comment by vrutkovs** [comment]
Note that latest stable OKD allows using RSA keys (as a stop-gap measure).

However we should be recommending strong ssh keys - perhaps for OCP as well?
