### ISSUE TITLE
Bootstrap installation failed with Failed to start Configure CRI-O to use the pause image

### ISSUE THREAD

**Issue by sandervanvugt** [openshift/okd#446]
**Describe the bug**
Trying to install an OKD cluster, according to guidelines in this article: https://medium.com/swlh/guide-okd-4-5-single-node-cluster-832693cb752b. I'm not successful in getting through the installation of the bootstrap node. SSH login to the bootstrap node gives the following:

[systemd]
Failed Units: 1
  crio-configure.service

Running systemctl status crio-configure.service gives:
Dec 24 08:26:00 okd-bootstrap.okd.local crio-configure.sh[1165]: sed: can't read /etc/crio/crio.conf: No such file or directory
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: crio-configure.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: crio-configure.service: Failed with result 'exit-code'.
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: Failed to start Configure CRI-O to use the pause image.
Complete logs and debug information below

**Version**
OKD version: 4.6.0-0.okd-2020-12-12-135354
Installing a single-node cluster on KVM virtual machines, using fedora server 33 on the service node, and fcos 33 on the bootstrap and control node. 

Issue occurs 100% of all times I've tried. 

**Log bundle**
[core@okd-bootstrap ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Wed 2020-12-23 17:52:34 UTC. --
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: Dependency failed for Bootstrap a Kubernetes cluster.
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: bootkube.service: Job bootkube.service/start failed with result 'dependency'.

for pod in $(sudo podman ps -a -q); do sudo podman logs $pod; done
### no results

[core@okd-bootstrap ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Wed 2020-12-23 17:52:34 UTC. --
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: Dependency failed for Bootstrap a Kubernetes cluster.
Dec 24 08:26:00 okd-bootstrap.okd.local systemd[1]: bootkube.service: Job bootkube.service/start failed with result 'dependency'.
^C
[core@okd-bootstrap ~]$ for pod in $(sudo podman ps -a -q); do sudo podman logs $pod; done
[core@okd-bootstrap ~]$ journalctl -b -f -u kubelet.service -u crio.service
-- Logs begin at Wed 2020-12-23 17:52:34 UTC. --
Dec 24 09:10:17 okd-bootstrap.okd.local podman[33635]: 2020-12-24 09:10:17.042998245 +0000 UTC m=+0.837350243 container remove 359c2b7e790e4ebf970771bea344b18032fe044ba49d9cf65baa476584443b05 (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=eager_bose)
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: kubelet.service: Found left-over process 33671 (conmon) in control group while starting unit. Ignoring.
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: kubelet.service: Found left-over process 33701 (podman) in control group while starting unit. Ignoring.
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[33729]: kubelet.service: Failed to execute command: No such file or directory
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[33729]: kubelet.service: Failed at step EXEC spawning /usr/bin/hyperkube: No such file or directory
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 24 09:10:17 okd-bootstrap.okd.local systemd[1]: Failed to start Kubernetes Kubelet.
Dec 24 09:10:27 okd-bootstrap.okd.local systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 233.
Dec 24 09:10:27 okd-bootstrap.okd.local systemd[1]: Stopped Kubernetes Kubelet.
Dec 24 09:10:27 okd-bootstrap.okd.local systemd[1]: Starting Kubernetes Kubelet...
Dec 24 09:10:27 okd-bootstrap.okd.local podman[33775]: 2020-12-24 09:10:27.800232733 +0000 UTC m=+0.288282601 container create 813fbaa615d847df3bea07ffa4cba69ca511c7f40d6abe23682d156809b89a9c (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=great_mendel)
Dec 24 09:10:28 okd-bootstrap.okd.local podman[33775]: 2020-12-24 09:10:28.063530334 +0000 UTC m=+0.551580213 container init 813fbaa615d847df3bea07ffa4cba69ca511c7f40d6abe23682d156809b89a9c (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=great_mendel)
Dec 24 09:10:28 okd-bootstrap.okd.local podman[33775]: 2020-12-24 09:10:28.107002168 +0000 UTC m=+0.595052054 container start 813fbaa615d847df3bea07ffa4cba69ca511c7f40d6abe23682d156809b89a9c (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=great_mendel)
Dec 24 09:10:28 okd-bootstrap.okd.local podman[33775]: 2020-12-24 09:10:28.107425301 +0000 UTC m=+0.595475159 container attach 813fbaa615d847df3bea07ffa4cba69ca511c7f40d6abe23682d156809b89a9c (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=great_mendel)
Dec 24 09:10:28 okd-bootstrap.okd.local podman[33775]: 2020-12-24 09:10:28.19275537 +0000 UTC m=+0.680805267 container died 813fbaa615d847df3bea07ffa4cba69ca511c7f40d6abe23682d156809b89a9c (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=great_mendel)
Dec 24 09:10:28 okd-bootstrap.okd.local podman[33775]: 2020-12-24 09:10:28.325485646 +0000 UTC m=+0.813535565 container remove 813fbaa615d847df3bea07ffa4cba69ca511c7f40d6abe23682d156809b89a9c (image=quay.io/openshift/okd@sha256:01948f4c6bdd85cdd212eb40d96527a53d6382c4489d7da57522864178620a2c, name=great_mendel)
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: kubelet.service: Found left-over process 33811 (conmon) in control group while starting unit. Ignoring.
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: kubelet.service: Found left-over process 33845 (podman) in control group while starting unit. Ignoring.
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[33868]: kubelet.service: Failed to execute command: No such file or directory
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[33868]: kubelet.service: Failed at step EXEC spawning /usr/bin/hyperkube: No such file or directory
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 24 09:10:28 okd-bootstrap.okd.local systemd[1]: Failed to start Kubernetes Kubelet.

[core@localhost ~]$ sudo tail -f /var/log/containers/*
tail: cannot open '/var/log/containers/*' for reading: No such file or directory
tail: no files remaining

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting).

Also, is it reproducible on [latest release](https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.6.0-0.okd-2020-12-12-135354)?

**Comment by sandervanvugt** [comment]
This is the latest release. I've not been able to generate the log bundle with openshift-install, so in the above you can find the result of manually gathering the logs according to the instructions in "Manually gathering logs with SSH access". please let me know if you need anything else.

**Comment by vrutkovs** [comment]
What's the output of `journalctl -b -f release-image-download.service`?

**Comment by sandervanvugt** [comment]
journalctl -b -f release-image-download.service
Failed to add match 'release-image-download.service': Invalid argument

**Comment by vrutkovs** [comment]
sorry, a typo in journalctl params:
`journalctl -b -u release-image-download.service` is the right one

**Comment by sandervanvugt** [comment]
[core@localhost ~]$ sudo journalctl -b -u release-image-download.service
-- Logs begin at Wed 2020-12-23 17:52:34 UTC, end at Thu 2020-12-24 10:03:19 UTC. --
-- No entries --

**Comment by sandervanvugt** [comment]
I found the issue after building up a new services node. The thing that has gone wrong was in generating the ignition files. I did have my ignition files, but they were not generated the right way. I'm looking at "this is the bootstrap node" on my bootstrap node right now. Thanks

**Comment by Matilla** [comment]
Hi @sandervanvugt , I'm doing exactly the same OKD installation that you did and I run into the same issue, you mentioned that the ignition files were not correct, would you mind to elaborate a little bit about what was wrong and what you did to fix the problem? Thanks.

**Comment by NR0Q-Matt** [comment]
I'm having the same issue here as well. 
OKD with Fedora CoreOS VMs running in VirtualBox. Exact same error message. My log bundle is attached. 

[log-bundle-20210217230545.tar.gz](https://github.com/openshift/okd/files/6000395/log-bundle-20210217230545.tar.gz)

My sanitized install-config.yaml that was used to generate the rest of the files
`apiVersion: v1
baseDomain: local 
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 3
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: kube
networking:
  clusterNetwork:
  - cidr: 172.16.52.0/22
    hostPrefix: 25
  networkType: OVNKubernetes
  serviceNetwork: 
  - 172.16.56.0/22
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 
sshKey: 'ssh-rsa MYKEYISASECRET= coreos' `

**Comment by alaaalii** [comment]
I have the same issue as well, following this guide: https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee - but I'm using the latest versions.

```
[root@okd4-helper ~]# openshift-install version
openshift-install 4.7.0-0.okd-2021-03-07-090821
```

And Fedora CoreOS 33.20210217.3.0.

I believe my main issue is that `/run` on the bootstrap machine gets full when `release-image-download` is running:

```
[core@okd4-bootstrap ~]$ journalctl -b -f -u release-image.service -u bootkube.service
-- Logs begin at Thu 2021-03-11 13:08:49 UTC. --
Mar 11 13:15:41 okd4-bootstrap release-image-download.sh[2852]: Error: error mounting storage for container 44320f4606e977f36cfebbaf7196f9fd2ea233d6d1dca7208a376dc89d017ce2: write /var/run/containers/storage/overlay-layers/.tmp-mountpoints.json624984115: no space left on device
Mar 11 13:15:41 okd4-bootstrap release-image-download.sh[2852]: W0311 13:15:41.914667    2852 run.go:44] nice failed: running nice -- ionice -c 3 podman cp 44320f4606e977f36cfebbaf7196f9fd2ea233d6d1dca7208a376dc89d017ce2:/ /run/mco-machine-os-content/os-content-788764557 failed: Error: error mounting storage for container 44320f4606e977f36cfebbaf7196f9fd2ea233d6d1dca7208a376dc89d017ce2: write /var/run/containers/storage/overlay-layers/.tmp-mountpoints.json624984115: no space left on device
Mar 11 13:15:41 okd4-bootstrap release-image-download.sh[2852]: : exit status 125; retrying...
```

```
[core@okd4-bootstrap ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           2.0G   84K  2.0G   1% /dev/shm
tmpfs           785M  785M     0 100% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/sda4       120G  4.3G  116G   4% /sysroot
tmpfs           2.0G     0  2.0G   0% /tmp
/dev/sda3       364M   91M  250M  27% /boot
tmpfs           393M     0  393M   0% /run/user/1000
```

I'm not sure how to solve that.

**Comment by vrutkovs** [comment]
Make sure that your bootstrap node has at least 8GB RAM

**Comment by alaaalii** [comment]
Thanks. Though what I ended up doing is using the exact versions mentioned in that guide (oc 4.5 and fedora coreos 32) and that fixed it (well at least it fixed this issue, but I'm running into other issues still). But you are correct that all my nodes (bootstrap, masters, and workers) have 4 vCPUs and 4 GB RAM, so they're undersized and likely under the minimum openshift requirements. I'll continue digging through or somehow try to increase resources.
