### ISSUE TITLE
docs: describe how to ssh into FCOS images to troubleshoot

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/okd#45]
You can SSH into FCOS images to troubleshoot issues during initial deployment/bootstrap if you have direct access to the running machine. `ssh core@<ip address or hostname of VM>`. This is not documented anywhere except the old Container Linux CoreOS docs. It should probably be mentioned in these docs as well.

**Comment by sgreene570** [comment]
+1. Should also include instructions for ssh'ing to cluster bootstrap node when IPI is being used. (see https://github.com/openshift/installer/blob/dd770f02b5263983fe04a41a2a4cb0669b4cf25e/docs/user/troubleshooting.md)
