### ISSUE TITLE
Documentation indicates OpenShiftSDN is a (preferred) supported default network CNI Provider

### ISSUE THREAD

**Issue by bdlink** [openshift/okd#457]
**Describe the bug**
Current OKD latest document indicates two default supported network CNI Providers, OpenShiftSDN and OVNKubernetes, in that order.  In the OKD working group discussion, it seems only OVNKubernetes is regularly tested.  The document seems to imply that OpenShiftSDN is the prefered case and talks about "migrating from" and "rolling back to" between this case and OVNKubernetes.

In fact, if the install-config.yaml does not specify which to use, OVNKubernetes is selected.  This should be clarified and perhaps OpenShiftSDN should be deemphasized.  If there is a preference between these two, this should be clearly indicated.

See https://docs.okd.io/latest/networking/openshift_sdn/about-openshift-sdn.html and https://docs.okd.io/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html 

**Version**
OKD Latest documentation: https://docs.okd.io/latest/welcome/index.html
Becomes an issue with 4.6 issue  #430

**How reproducible**
Documentation issue

**Log bundle**
Not applicable

**Comment by mburke5678** [comment]
@vrutkovs We can hide the OpenShiftSDN topics if needed.

**Comment by vrutkovs** [comment]
OpenshiftSDN is a valid option in OKD, its just not being default.

I think its best to keep the examples, but its worth adding a note that OKD uses OVN by default (not sure where it would fit best, probably install instructions?)
