### ISSUE TITLE
open-vm-tools doesn't start

### ISSUE THREAD

**Issue by Reamer** [openshift/okd#46]
**Description**
I have two problems with open-vm-tools.
1) open-vm-tools are not enabled.

2) open-vm-tools are in included in 32-bit instead of 64-bit. yumdownloader should download the right binary. See [openshift/release](https://github.com/openshift/release/blob/3fb40777dbe6c5fb711e969c753330afaf64554d/ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml#L522)

**Steps to reproduce the issue:**
1. Install 4.4.0-0.okd (https://origin-release.svc.ci.openshift.org/) - [my used version ](https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-27-202345)
2. Check open-vm-tools

**Describe the results you received:**
```
[core@master1 ~]$ systemctl status vmtoolsd.service 
● vmtoolsd.service - Service for virtual machines hosted on VMware
   Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: http://github.com/vmware/open-vm-tools
```
```
[core@master1 ~]$ sudo file /usr/bin/vmtoolsd
/usr/bin/vmtoolsd: ELF 32-bit LSB pie executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=d27d5ce82743beade43af0b4ca9bd35c55a6b4ca, for GNU/Linux 3.2.0, stripped
```

**Describe the results you expected:**
open-vm-tools should run to have support for PV on vsphere

**Additional environment details (platform, options, etc.):**
- Plattform vsphere

**Comment by vrutkovs** [comment]
TODO:
* [ ] Fix yumdownloader params to use x86_64 binaries only
* [ ] Enable the vmtoolsd service for vSphere platform

**Comment by vrutkovs** [comment]
Fixed on bootstrap, iiuc masters and workers still don't start it. It should be fixed by symlinking the service to `/etc/systemd/system/multi-user.target.wants` when machine-os-content is being prepared
