### ISSUE TITLE
no AD/LDAP login after upgrading from 4.6.0-0.okd-2020-12-12-135354 to 4.6.0-0.okd-2021-01-17-185703

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#472]
**Describe the bug**
I am upgrading a cluster from 4.6.0-0.okd-2020-12-12-135354 to 4.6.0-0.okd-2021-01-17-185703. The cluster has been upgraded successfully from earlier releases already 7 times.
I have another problem with this cluster - the upgrade does not succeed, it is still stuck with the MCO not progressing. But this should IMO not affect the authentication.
For the MCO problem I opened another issue, will link it below.

Any login attempt fails like this:
```
$ oc login --server=https://api.devqs.ars.de:6443 -u user -p password
Error from server (InternalError): Internal error occurred: unexpected response: 500
```

**Version**
4.6.0-0.okd-2020-12-12-135354 to 4.6.0-0.okd-2021-01-17-185703

**How reproducible**
always

**Log bundle**
Unfortunately, must-gather fails:
```
# oc adm must-gather
[must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift/okd-content@sha256:c46390d74c9ac6152264da87b5667eacc42871cf4eb9ab444cd953ae56b81b07
[must-gather      ] OUT namespace/openshift-must-gather-lb75x created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-zz8lq created
[must-gather      ] OUT pod for plug-in image quay.io/openshift/okd-content@sha256:c46390d74c9ac6152264da87b5667eacc42871cf4eb9ab444cd953ae56b81b07 created
[must-gather-vfwbk] OUT gather did not start: Get https://api.devqs.ars.de:6443/api/v1/namespaces/openshift-must-gather-lb75x/pods/must-gather-vfwbk: unexpected EOF [must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-zz8lq deleted
[must-gather      ] OUT namespace/openshift-must-gather-lb75x deleted
error: gather did not start for pod must-gather-vfwbk: Get https://api.devqs.ars.de:6443/api/v1/namespaces/openshift-must-gather-lb75x/pods/must-gather-vfwbk: unexpected EOF
```

**Comment by fortinj66** [comment]
look at the logs for the pods in openshift-authentication.  That should probably give you an idea what's failing...

I've had issues with certs not have SAN entries and had to regenerate certs for my LDAP servers that I authenticate with.

https://github.com/openshift/okd/issues/443

**Comment by kai-uwe-rommel** [comment]
Yes, this was the case. The DC's certificate did not have SAN attribute.
Now fixed.
Thanks!

**Comment by fortinj66** [comment]
awesome!
