### ISSUE TITLE
Problem Upgrade from 4.6.0-0.okd-2020-12-12-135354 to 4.6.0-0.okd-2021-01-17-185703 on VMware

### ISSUE THREAD

**Issue by aalgera** [openshift/okd#473]
Running _oc adm upgrade --to-latest_ returns after a while:
info: An upgrade is in progress. Unable to apply 4.6.0-0.okd-2021-01-17-185703: the image may not be safe to use

At the same time the following event is generated:

> retrieving payload failed version="4.6.0-0.okd-2021-01-17-185703" image="registry.ci.openshift.org/origin/release@sha256:121b58e61104277260caf82ac09577a6321d047849f9caac632d1338aa6018a1" failure=The update cannot be verified: unable to locate a valid signature for one or more sources

**Version**
4.6.0-0.okd-2020-12-12-135354 running on VMware

**How reproducible**
100%

**Comment by vrutkovs** [comment]
See comments in #437
