### ISSUE TITLE
Unable to upgrade from version 4.5.0-0.okd-2021-01-11-180437

### ISSUE THREAD

**Issue by okovalchuk777** [openshift/okd#474]
Unable to upgrade from version 4.5.0-0.okd-2021-01-11-180437

Describe the bug
I want to upgrade from OKD version 4.5.0-0.okd-2021-01-11-180437.
Using channel 'stable-4' both GUI and CLI are showing "Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2021-01-11-180437 not found in the "stable-4" channel".

Version
oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.0-0.okd-2021-01-11-180437   True        False         4d18h   Cluster version is 4.5.0-0.okd-2021-01-11-180437

 oc get clusterversion -o json|jq ".items[0].spec"
{
  "channel": "stable-4",
  "clusterID": "9da39833-0de2-4c36-b9ff-5a97bc9e0cd5",
  "desiredUpdate": {
    "force": false,
    "image": "registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697",
    "version": "4.5.0-0.okd-2021-01-11-180437"
  },
  "upstream": "https://origin-release.svc.ci.openshift.org/graph"

oc adm upgrade
Cluster version is 4.5.0-0.okd-2021-01-11-180437

warning: Cannot display available updates:
  Reason: VersionNotFound
  Message: Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2021-01-11-180437 not found in the "stable-4" channel

We have UPI (baremetal) installation of OKD (vSphere). NFS storage is using for image repository.

Log bundle

oc describe clusterversion
 
Name:         version
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  config.openshift.io/v1
Kind:         ClusterVersion
Metadata:
  Creation Timestamp:  2020-11-24T03:54:18Z
  Generation:          9
  Managed Fields:
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:clusterID:
        f:upstream:
    Manager:      cluster-bootstrap
    Operation:    Update
    Time:         2020-11-24T03:54:18Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:channel:
        f:desiredUpdate:
    Manager:      oc
    Operation:    Update
    Time:         2021-01-13T16:36:16Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:desiredUpdate:
          f:force:
          f:image:
          f:version:
    Manager:      Mozilla
    Operation:    Update
    Time:         2021-01-13T17:32:58Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:availableUpdates:
        f:conditions:
        f:desired:
          .:
          f:force:
          f:image:
          f:version:
        f:history:
        f:observedGeneration:
        f:versionHash:
    Manager:         cluster-version-operator
    Operation:       Update
    Time:            2021-01-20T12:33:51Z
  Resource Version:  24816032
  Self Link:         /apis/config.openshift.io/v1/clusterversions/version
  UID:               e00b6266-141b-419c-9c4f-919dcb540add
Spec:
  Channel:     stable-4
  Cluster ID:  9da39833-0de2-4c36-b9ff-5a97bc9e0cd5
  Desired Update:
    Force:    false
    Image:    registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697
    Version:  4.5.0-0.okd-2021-01-11-180437
  Upstream:   https://origin-release.svc.ci.openshift.org/graph
Status:
  Available Updates:  <nil>
  Conditions:
    Last Transition Time:  2020-11-24T04:52:19Z
    Message:               Done applying 4.5.0-0.okd-2021-01-11-180437
    Status:                True
    Type:                  Available
    Last Transition Time:  2021-01-15T18:15:29Z
    Status:                False
    Type:                  Failing
    Last Transition Time:  2021-01-15T18:19:17Z
    Message:               Cluster version is 4.5.0-0.okd-2021-01-11-180437
    Status:                False
    Type:                  Progressing
    Last Transition Time:  2021-01-18T16:13:19Z
    Message:               Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2021-01-11-180437 not found in the "stable-4" channel
    Reason:                VersionNotFound
    Status:                False
    Type:                  RetrievedUpdates
  Desired:
    Force:    false
    Image:    registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697
    Version:  4.5.0-0.okd-2021-01-11-180437
  History:
    Completion Time:    2021-01-15T18:19:17Z
    Image:              registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697
    Started Time:       2021-01-13T17:33:13Z
    State:              Completed
    Verified:           true
    Version:            4.5.0-0.okd-2021-01-11-180437
    Completion Time:    2021-01-13T17:11:43Z
    Image:              registry.svc.ci.openshift.org/origin/release@sha256:3a62fb7eed2d2b783de1e0425d929908da59b77925a9cc7cd995cfef1e96179e
    Started Time:       2021-01-13T16:36:27Z
    State:              Completed
    Verified:           false
    Version:            4.5.0-0.okd-2020-12-18-145450
    Completion Time:    2020-11-24T04:52:19Z
    Image:              registry.svc.ci.openshift.org/origin/release@sha256:0335712c943723b5cb5ed57599821ab1ab185da2171e15df8d5cf8978cd322b7
    Started Time:       2020-11-24T03:54:33Z
    State:              Completed
    Verified:           false
    Version:            4.5.0-0.okd-2020-11-21-103844
  Observed Generation:  9
  Version Hash:         BCALhgbLz8I=
Events:                 <none>

**Comment by vrutkovs** [comment]
>currently installed version 4.5.0-0.okd-2021-01-11-180437 not found in the "stable-4" channel

This is a nightly 4.5, we don't have it in `stable-4` channel. Use `oc adm upgrade --to-image` at your own risk

**Comment by okovalchuk777** [comment]
Thank You SO MUCH!!!

ср, 20 янв. 2021 г., 15:35 Vadim Rutkovsky <notifications@github.com>:
