### ISSUE TITLE
Question: OKD committing running container to local registry

### ISSUE THREAD

**Issue by mark-kumoco** [openshift/okd#482]
Is Github the best place to ask a question about OKD 4.3? If not, could you point me to the correct place?

Is it possible to have a running OKD container running from an OKD image stream, tagged and then saved back to the local OKD registry?

At the moment I use docker on my local PC to:

1. pull an image to my PC
2. run that image as a container
3. amend the contents of the running container via docker exec
4. then commit the container to my local PC
5. tag the image
6. push the image back to the registry
7. update the tag in the OKD deployment YAML, then of course a new container is created with OKD.

If I could do the amendments in a running OKD container, tag it within OKD, then commit back to the local OKD registry, it would save time.

Mark

**Comment by vrutkovs** [comment]
Issues are best to track OKD problems we need to fix. I think solutions and tricks are best discussed in Slack - https://github.com/openshift/okd/blob/master/FAQ.md#where-do-i-seek-support
