### ISSUE TITLE
4.5 UPI with FCOS and fips mode supported?

### ISSUE THREAD

**Issue by disposab1e** [openshift/okd#486]
**Describe the bug**

Not sure this is a bug!

I try to install a cluster with fips mode enabled `fips: true`

As my understanding after searching the web this should be possible. But when I check the bootstrap/master/worker fips mode is not enabled.

With the same configuration and RHCOS 4.6.1 fips mode is enabled as expected.

I also tried to apply karg `fips=1` at first boot but again no fips mode available.

I'm doing something wrong or is it not supported with the versions I use?

**Version**
UPI / 4.5.0-0.okd-2020-10-15-235428 / 32.20200629.3.0

**Comment by vrutkovs** [comment]
Fedora RPMs are not fips certified, so FIPS mode doesn't do anything

**Comment by disposab1e** [comment]
@vrutkovs Thx!

fyi....

[Supporting FIPS mode in FCOS](https://github.com/coreos/fedora-coreos-tracker/issues/302#issuecomment-547636508)

[01fips: various fixes to adapt to RHCOS and FCOS](https://github.com/dracutdevs/dracut/pull/661)
