### ISSUE TITLE
Failed to pull image (Server Version: 4.5.0-0.okd-2021-01-11-180437)

### ISSUE THREAD

**Issue by okovalchuk777** [openshift/okd#489]
Failed to pull image (Server Version: 4.5.0-0.okd-2021-01-11-180437)

Describe the bug
Each time a cluster is deployed on an unstable release after a while a problem appears during application deployment "Failed to pull image "registry.ci.openshift.org/origin/"

Version
Client Version: 4.5.0-0.okd-2020-11-21-103844
Server Version: 4.5.0-0.okd-2021-01-11-180437
Kubernetes Version: v1.18.3

 oc get co
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
cloud-credential                           4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
cluster-autoscaler                         4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
config-operator                            4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
console                                    4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
csi-snapshot-controller                    4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
dns                                        4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
etcd                                       4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
image-registry                             4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
ingress                                    4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
insights                                   4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
kube-apiserver                             4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
kube-controller-manager                    4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
kube-scheduler                             4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
kube-storage-version-migrator              4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
machine-api                                4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
machine-approver                           4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
machine-config                             4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
marketplace                                4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
monitoring                                 4.5.0-0.okd-2021-01-11-180437   True        False         False      12d
network                                    4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
node-tuning                                4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
openshift-apiserver                        4.5.0-0.okd-2021-01-11-180437   True        False         False      14d
openshift-controller-manager               4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
openshift-samples                          4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
operator-lifecycle-manager                 4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
operator-lifecycle-manager-catalog         4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
operator-lifecycle-manager-packageserver   4.5.0-0.okd-2021-01-11-180437   True        False         False      11d
service-ca                                 4.5.0-0.okd-2021-01-11-180437   True        False         False      64d
storage                                    4.5.0-0.okd-2021-01-11-180437   True        False         False      11d

 oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.5.0-0.okd-2021-01-11-180437   True        False         11d     Cluster version is 4.5.0-0.okd-2021-01-11-180437

oc describe clusterversion
Name:         version
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  config.openshift.io/v1
Kind:         ClusterVersion
Metadata:
  Creation Timestamp:  2020-11-24T03:54:18Z
  Generation:          9
  Managed Fields:
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:clusterID:
        f:upstream:
    Manager:      cluster-bootstrap
    Operation:    Update
    Time:         2020-11-24T03:54:18Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:channel:
        f:desiredUpdate:
    Manager:      oc
    Operation:    Update
    Time:         2021-01-13T16:36:16Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:desiredUpdate:
          f:force:
          f:image:
          f:version:
    Manager:      Mozilla
    Operation:    Update
    Time:         2021-01-13T17:32:58Z
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:availableUpdates:
        f:conditions:
        f:desired:
          .:
          f:force:
          f:image:
          f:version:
        f:history:
        f:observedGeneration:
        f:versionHash:
    Manager:         cluster-version-operator
    Operation:       Update
    Time:            2021-01-23T14:12:29Z
  Resource Version:  26144672
  Self Link:         /apis/config.openshift.io/v1/clusterversions/version
  UID:               e00b6266-141b-419c-9c4f-919dcb540add
Spec:
  Channel:     stable-4
  Cluster ID:  9da39833-0de2-4c36-b9ff-5a97bc9e0cd5
  Desired Update:
    Force:    false
    Image:    registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697
    Version:  4.5.0-0.okd-2021-01-11-180437
  Upstream:   https://origin-release.svc.ci.openshift.org/graph
Status:
  Available Updates:  <nil>
  Conditions:
    Last Transition Time:  2020-11-24T04:52:19Z
    Message:               Done applying 4.5.0-0.okd-2021-01-11-180437
    Status:                True
    Type:                  Available
    Last Transition Time:  2021-01-15T18:15:29Z
    Status:                False
    Type:                  Failing
    Last Transition Time:  2021-01-15T18:19:17Z
    Message:               Cluster version is 4.5.0-0.okd-2021-01-11-180437
    Status:                False
    Type:                  Progressing
    Last Transition Time:  2021-01-18T16:13:19Z
    Message:               Unable to retrieve available updates: currently installed version 4.5.0-0.okd-2021-01-11-180437 not found in the "stable-4" channel
    Reason:                VersionNotFound
    Status:                False
    Type:                  RetrievedUpdates
  Desired:
    Force:    false
    Image:    registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697
    Version:  4.5.0-0.okd-2021-01-11-180437
  History:
    Completion Time:    2021-01-15T18:19:17Z
    Image:              registry.ci.openshift.org/origin/release@sha256:d35f8eb6247af3f4a6d85a17375b652ac43a7ea597973b228cd4d351699bf697
    Started Time:       2021-01-13T17:33:13Z
    State:              Completed
    Verified:           true
    Version:            4.5.0-0.okd-2021-01-11-180437
    Completion Time:    2021-01-13T17:11:43Z
    Image:              registry.svc.ci.openshift.org/origin/release@sha256:3a62fb7eed2d2b783de1e0425d929908da59b77925a9cc7cd995cfef1e96179e
    Started Time:       2021-01-13T16:36:27Z
    State:              Completed
    Verified:           false
    Version:            4.5.0-0.okd-2020-12-18-145450
    Completion Time:    2020-11-24T04:52:19Z
    Image:              registry.svc.ci.openshift.org/origin/release@sha256:0335712c943723b5cb5ed57599821ab1ab185da2171e15df8d5cf8978cd322b7
    Started Time:       2020-11-24T03:54:33Z
    State:              Completed
    Verified:           false
    Version:            4.5.0-0.okd-2020-11-21-103844
  Observed Generation:  9
  Version Hash:         BCALhgbLz8I=
Events:                 <none>

Log bundle
nginx2-1-deploy
Back-off pulling image "registry.ci.openshift.org/origin/4.5-2021-01-11-180437@sha256:ec1b8018014bef26ae6ce148a040a08a4ffb1beffaa92baa78f2c8836404142c"

Failed to pull image "registry.ci.openshift.org/origin/4.5-2021-01-11-180437@sha256:ec1b8018014bef26ae6ce148a040a08a4ffb1beffaa92baa78f2c8836404142c": rpc error: code = Unknown desc = Error reading manifest sha256:ec1b8018014bef26ae6ce148a040a08a4ffb1beffaa92baa78f2c8836404142c in registry.ci.openshift.org/origin/4.5-2021-01-11-180437: manifest unknown: manifest unknown

Please tell me what I'm doing wrong?

**Comment by vrutkovs** [comment]
>currently installed version 4.5.0-0.okd-2021-01-11-180437 not found in the "stable-4" channe

You're running on a nightly stream - and we keep nightlies for 48hrs only. So at some point CI registry removes all images and your cluster can't pull them anymore.

The safest way is to use [mirror registry](https://docs.okd.io/latest/installing/install_config/installing-restricted-networks-preparations.html) instead - or upgrade to [stable stream](https://amd64.origin.releases.ci.openshift.org/#4-stable), these are kept on quay.io and we don't have plans to remove these payloads

**Comment by okovalchuk777** [comment]
Thank You SO much!!!
