### ISSUE TITLE
 Resize FCOS image to more than 8GByte so we have enough space for Docker images

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#49]
Hi,

I'm wondering if we should resize the FCOS image size in the installer to a size which fits the needs of the users. Currently the image is only 8GByte big. Thats far to less for Docker images.

Best regards,

Josef

**Comment by jomeier** [comment]
This one is not Azure related. I changed the title.

**Comment by vrutkovs** [comment]
Image size is irrelevant to allocated disk space, see https://github.com/openshift/installer/blob/master/docs/user/azure/customization.md#machine-pools
