### ISSUE TITLE
Console bug - source code URL broken for gitlab self-hosted repositories

### ISSUE THREAD

**Issue by bdlink** [openshift/okd#490]
**Describe the bug**
In the Topology view there are icons representing pods.  If the pod was created from a source code repository, a handle is shown on the lower right of the pod circle icon.  It was the case before that clicking on this handle would open the repository holding the source code.

In a case where the pod was created in the current (4.6.0-0.okd-2021-01-23-132511) or earlier versions from the Wildfly s2i image (for example, in the catalogue), the repo URL has been modified so it is no longer correct.  

For example, a URL which used to be https://gitlab.infoteach.ca/bdlink/ch1-login/tree/master has been changed after the upgrade to https://infoteach.ca/bdlink/ch1-login/tree/master. This pod would have been created from the repo URL https://gitlab.infoteach.ca/bdlink/ch1-login.git, and identified as a gitlab repository.

**Version**
UPI installation on vSphere 6.7, was 4.6.0-0.okd-2021-01-17-185703, updated to 4.6.0-0.okd-2021-01-23-132511.

**How reproducible**
100%, effects new pods created after the update as well as pods created before the update.
Works if the repo is github.com (1 case tested)

**Log bundle**
See https://bcit.sharefile.com/d-s15ffa23bac8e4979847115d9a8d72e39

**Comment by vrutkovs** [comment]
Seems to be a 4.6 regressions, mind filing an OCP bugzilla ticket for that?

**Comment by bdlink** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1921949

**Comment by bdlink** [comment]
Closed in OCP bugzilla above, seems to work in 4.6.0-okd-2021-02-14-205305
Also works in 4.7.0-okd-2021-03-06-124908 and
4.7.0-okd-2021-03-07-090821
