### ISSUE TITLE
Create PVC Fail in vsphere volume StorageClass

### ISSUE THREAD

**Issue by zongke** [openshift/okd#494]
**Describe the bug**
The pvc always in pending,and envets get : Failed to provision volume with StorageClass "thin": could not parse "" as version .
In apiserver and storage class operator  server,not get any create pvc request.

**Version**
4.6.0-0.okd-2021-01-23-132511

**How reproducible**
In 'Persistent Volume Claim' Tab,click 'Create Persistent Volume Claim' button to create pvc

**Log bundle**

**Comment by zongke** [comment]
![image](https://user-images.githubusercontent.com/12181200/106244368-c0181000-6245-11eb-85e7-029c4cb9987b.png)

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by zongke** [comment]
Sorry，this is gather data.
[QUAY-I~1.ZIP](https://github.com/openshift/okd/files/5893046/QUAY-I.1.ZIP)

**Comment by vrutkovs** [comment]
That archive is incomplete - there's no `namespaces` so I can't check PVC details or storage controller logs

**Comment by zongke** [comment]
> That archive is incomplete - there's no `namespaces` so I can't check PVC details or storage controller logs

The **namespaces** is too large ,so I split them and packaged them.
[namespaces1.zip](https://github.com/openshift/okd/files/5896910/namespaces1.zip)
[namespaces2.zip](https://github.com/openshift/okd/files/5896911/namespaces2.zip)
[namespaces3.zip](https://github.com/openshift/okd/files/5896914/namespaces3.zip)
[namespaces4.zip](https://github.com/openshift/okd/files/5896916/namespaces4.zip)
[namespaces5.zip](https://github.com/openshift/okd/files/5896918/namespaces5.zip)
[namespaces6.zip](https://github.com/openshift/okd/files/5896920/namespaces6.zip)
[namespaces7.zip](https://github.com/openshift/okd/files/5896921/namespaces7.zip)
[namespaces8.zip](https://github.com/openshift/okd/files/5896922/namespaces8.zip)
[namespaces9.zip](https://github.com/openshift/okd/files/5896923/namespaces9.zip)

**Comment by vrutkovs** [comment]
>"Event occurred" object="default/test20210129" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="Failed to provision volume with StorageClass \"thin\": No VM found"

Looks similar to https://github.com/openshift/okd/issues/483 - `open-vm-tools` is not enabled to start by default (should be resolved in next stable release).

As a workaround you can start it now - ssh on hosts (or use `oc debug node/...`) and run `systemctl enable --now open-vm-tools`

**Comment by zongke** [comment]
Sorry for the late reply. In my environment, I used kubeedge to register the node, which was not specified when creating the node status:nodeInfo:kubeletVersion。
Kuberbetes detects node information when creating PVC, and prompts: could not parse "" as version.
The solution is to register the kubeletversion when the node is created.
But I have a question: even if the kubeletversion is not config when the node is created, why does it still report an error when the subsequent node updates the kubeletversion? why Kubeletversion must be executed at creation time?

**Comment by zongke** [comment]
This is my node.yaml

> kind: Node
apiVersion: v1
metadata:
  name: tl-virtual-1
  labels:
    kubernetes.io/hostname: tl-virtual-1
status:
  nodeInfo:
    containerRuntimeVersion: 'cri-o://1.19.0'
    kubeletVersion: v1.19.2+7070803-1008
    systemUUID: d31c0242-24e2-ff22-208d-f33efbe7816c
    kubeProxyVersion: v1.19.2+7070803-1008
    kernelVersion: 5.9.12-200.fc33.x86_64
