### ISSUE TITLE
Unable to apply 4.6.0-0.okd-2021-01-23-132511: the image may not be safe to use

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift/okd#495]
**Describe the bug**

Trying to upgrade from 4.6.0-0.okd-2020-11-27-200126 to 4.6.0-0.okd-2021-01-23-132511 from stable branch and failing on "Unable to apply 4.6.0-0.okd-2021-01-23-132511: the image may not be safe to use" leading to "The update cannot be verified: unable to locate a valid signature for one or more sources"

**Version**
Running 4.6.0-0.okd-2020-11-27-200126, trying to upgrade to 4.6.0-0.okd-2021-01-23-132511

**How reproducible**
Being a signature issue I guess this should be 100% reproducible

**Log bundle**
log bundle is 171MB compressed, which make it difficult to be shared. If you need specific details or logs please let me know.

**Comment by sandrobonazzola** [comment]
Seems related to PR #492 but 2021-01-23 is not listed there as affected version.

**Comment by vrutkovs** [comment]
Right, its #426, but affects every release before 2021-01-17, so it wasn't included in later release notes.

`--force` in `oc adm upgrade` or `.spec.desired.force` would fix that
