### ISSUE TITLE
Issues with OpenShift 3.11 oc tool

### ISSUE THREAD

**Issue by jeebitesh** [openshift/okd#496]
Bug is related to oc tool, can be more related to kubectl as well. While executing below command from - command line or command prompt or Linux shell
`oc get job JOBNAME -o=jsonpath='{.status.conditions[*].type}' `

Output should be either 'Failed' or 'Completed'

But when executing above command from shell script (*.sh) output is empty 

Investigating further I have found that "**conditions**" element is missing when command is executed from shell script

to get relevant value , you need to change the JSONPATH to

`oc get job JOBNAME -o=jsonpath='{.status.failed}'`

output: 0 or 1.

Can you tell me why JSON\YAML output are different in both the cases(shell prompt and shell script) or this is bug in kubectl itself.

**Comment by vrutkovs** [comment]
This is a repo for OKD4 issues, please use https://bugzilla.redhat.com for OKD 3.11 bugs
