### ISSUE TITLE
Undefined Node / Cluster restart from kube-apiserver-operator cert event

### ISSUE THREAD

**Issue by alexanderniebuhr** [openshift/okd#499]
**Describe the bug**

We did experience for the third time and for us undefined node / cluster restart (failure happens at 08.20UTC later ish), after scanning the logs of must-gather, it is again the kube-apiserver-operator which replaces some outdated internal serving-certs.

**Version**

4.6.0-0.okd-2020-12-12-135354

**How reproducible**

/

**Log bundle**

You can current must-gather here: (failure happens at 08.20UTC later ish)
https://drive.google.com/file/d/1Q9q-b5PTVBSyYvgBgAFfDgawKny1vLIf/view?usp=sharing

**Comment by vrutkovs** [comment]
Is it reproducible in latest OKD 4.6?

**Comment by alexanderniebuhr** [comment]
I can't tell, as I don't know how to trigger this manual?

**Comment by alexanderniebuhr** [comment]
seems to be resolved on 4.7 somehow
