### ISSUE TITLE
Azure: VMs cant resolve hostnames -> Cant pull release image

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#50]
Hi,

I sshed in my bootstrap VM and saw with journalctl that fcos cant pull the origin release image. 

A

```
curl google.de
```

ends with: 

```
curl: (6) Could not resolve host: google.de
```

There is no /etc/resolv.conf file in my bootstrap VM.

The private DNS zone was created successfully in my resource group.

Greetings,

Josef

**Comment by vrutkovs** [comment]
Seems that's https://github.com/coreos/fedora-coreos-tracker/issues/356

**Comment by jomeier** [comment]
Exactly. Thats what I also wrote in https://github.com/coreos/fedora-coreos-tracker/issues/148#issuecomment-565830139 a few month ago.

**Comment by jomeier** [comment]
This one will be fixed if the brand new FCOS image from here:

coreos/fedora-coreos-tracker#356

gets released.

**Comment by vrutkovs** [comment]
Excellent, thanks for testing that!

So on OKD side we need to update Azure VHD link. I'd like to do this after Beta is released so that we got time to stabilize it. Current workaround is to use `OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE`

**Comment by LorbusChris** [comment]
Afaik this is fixed now :)
