### ISSUE TITLE
Thanos rendering cluster unresponsive

### ISSUE THREAD

**Issue by markusdd** [openshift/okd#505]
**Describe the bug**
Prometheus Thanos is using up 50% of the masters memory, rendering the node unresponsive and ultimately crashing the cluster.

**Version**
bare metal setup, latest versions of okd and FCOS as of feb 06

**How reproducible**
happens always after some time, more prominently after node reboot

**Log bundle**

![grafik](https://user-images.githubusercontent.com/25175069/107284695-778afe80-6a5e-11eb-8261-c6e4ac91e31d.png)

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by markusdd** [comment]
Hi, I am not able to gather the archive during the problem, as everything becomes unresponsive and spawning diganostic pods fails.

I have gathered the data nevertheless after fresh boot. I have uploaded it to a public dropbox link, as it is too big for github.

https://www.dropbox.com/s/dedrawcd2z1nu5u/gather.tar.gz?dl=0

**Comment by markusdd** [comment]
Also in Thanos repo there are a lot of open and closed ticket wrt mem usage and leaks...does not look really stable to be honest...
https://github.com/thanos-io/thanos/issues?q=is%3Aissue+is%3Aopen+memory

**Comment by vrutkovs** [comment]
Upstream thanos issues are irrelevant here. Looks similar to https://bugzilla.redhat.com/show_bug.cgi?id=1918792#c7

**Comment by markusdd** [comment]
Yes indeed, that looks very much like the exact problem.

**Comment by vrutkovs** [comment]
This should be fixed in latest OKD 4.6 nighly, could you give that a try?

**Comment by markusdd** [comment]
This is a single-node trial cluster to evaluate OKD4 for migration from 3.11.

Is it possible to uppgrade such a cluster or must I redeploy?
