### ISSUE TITLE
Problem with bootstrap node

### ISSUE THREAD

**Issue by borbul2007** [openshift/okd#507]
**Describe the bug**

I'm trying to set up fresh cluster installation and after starting bootstrap node the following error occurs:

_bootkube.sh[2578131]: F0210 10:21:54.875723 1 image.go:32] error: error: Unknown name requested, could not find kube-client-agent in UpdatePayload__

the error repeats in a loop and  bootstrap could not run. I tried different versions of OKD and FCOS.

**Version**

UPI - VMWare 

OKD
4.6.0-0.okd-2021-02-05-144635
4.6.0-0.okd-2021-01-23-132511

FCOS
33.20210117.3.2
33.20210104.3.0

**How reproducible**

Provision a cluster on UPI VMWare using version above

**Log bundle**

Logging from bootstrap node console:

[core@bs ~]$ **journalctl -b -f -u release-image.service**
-- Logs begin at Tue 2021-02-09 13:03:48 UTC. --
Feb 09 13:08:32 localhost release-image-download.sh[811]: Pull failed. Retrying quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36...
Feb 09 13:08:32 localhost release-image-download.sh[4429]: Error: Error initializing source docker://quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:46964->[::1]:53: read: connection refused
Feb 09 13:08:32 localhost release-image-download.sh[811]: Pull failed. Retrying quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36...
Feb 09 13:08:32 localhost release-image-download.sh[4475]: Error: Error initializing source docker://quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:35925->[::1]:53: read: connection refused
Feb 09 13:08:32 localhost release-image-download.sh[811]: Pull failed. Retrying quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36...
Feb 09 13:08:32 localhost release-image-download.sh[4522]: Error: Error initializing source docker://quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:44842->[::1]:53: read: connection refused
Feb 09 13:08:32 localhost release-image-download.sh[811]: Pull failed. Retrying quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36...
Feb 09 13:08:34 bs podman[4581]: 2021-02-09 13:08:34.883315466 +0000 UTC m=+2.321212997 image pull  
Feb 09 13:08:34 bs release-image-download.sh[4581]: d2cc86f5bd2a517372ec145df1b59291f64713c5693adaa0877b1cdf014b45bb
Feb 09 13:08:34 bs systemd[1]: Finished Download the OpenShift Release Image.

[core@bs ~]$ **journalctl -b -f -u bootkube.service**
Feb 10 10:21:53 bs systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 10940.
Feb 10 10:21:53 bs systemd[1]: Stopped Bootstrap a Kubernetes cluster.
Feb 10 10:21:53 bs systemd[1]: Started Bootstrap a Kubernetes cluster.
Feb 10 10:21:53 bs podman[2577736]: 2021-02-10 10:21:53.531456921 +0000 UTC m=+0.158241711 container create 04e72c735752e9dba4b36ac6425819dcd8b6eaba1bd61fb58ae735198bb020c8 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=mystifying_antonelli, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:53 bs podman[2577736]: 2021-02-10 10:21:53.61497384 +0000 UTC m=+0.241758676 container init 04e72c735752e9dba4b36ac6425819dcd8b6eaba1bd61fb58ae735198bb020c8 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=mystifying_antonelli, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:53 bs podman[2577736]: 2021-02-10 10:21:53.653875504 +0000 UTC m=+0.280660408 container start 04e72c735752e9dba4b36ac6425819dcd8b6eaba1bd61fb58ae735198bb020c8 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=mystifying_antonelli, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1, io.openshift.release=4.6.0-0.okd-2021-01-23-132511)
Feb 10 10:21:53 bs podman[2577736]: 2021-02-10 10:21:53.654333681 +0000 UTC m=+0.281119018 container attach 04e72c735752e9dba4b36ac6425819dcd8b6eaba1bd61fb58ae735198bb020c8 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=mystifying_antonelli, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:53 bs podman[2577736]: 2021-02-10 10:21:53.692462654 +0000 UTC m=+0.319247679 container died 04e72c735752e9dba4b36ac6425819dcd8b6eaba1bd61fb58ae735198bb020c8 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=mystifying_antonelli)
Feb 10 10:21:53 bs podman[2577736]: 2021-02-10 10:21:53.803607578 +0000 UTC m=+0.430392391 container remove 04e72c735752e9dba4b36ac6425819dcd8b6eaba1bd61fb58ae735198bb020c8 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=mystifying_antonelli, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:53 bs podman[2577881]: 2021-02-10 10:21:53.980716533 +0000 UTC m=+0.156431931 container create 103ee65fa4ba5aa06e055675edb0968dca65c6e5f4cd0e8d0f04a93d0b7e75c9 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=jovial_swartz, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577881]: 2021-02-10 10:21:54.068430238 +0000 UTC m=+0.244145625 container init 103ee65fa4ba5aa06e055675edb0968dca65c6e5f4cd0e8d0f04a93d0b7e75c9 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=jovial_swartz, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577881]: 2021-02-10 10:21:54.087488762 +0000 UTC m=+0.263204255 container start 103ee65fa4ba5aa06e055675edb0968dca65c6e5f4cd0e8d0f04a93d0b7e75c9 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=jovial_swartz, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577881]: 2021-02-10 10:21:54.087926235 +0000 UTC m=+0.263641747 container attach 103ee65fa4ba5aa06e055675edb0968dca65c6e5f4cd0e8d0f04a93d0b7e75c9 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=jovial_swartz, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577881]: 2021-02-10 10:21:54.114350571 +0000 UTC m=+0.290066157 container died 103ee65fa4ba5aa06e055675edb0968dca65c6e5f4cd0e8d0f04a93d0b7e75c9 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=jovial_swartz)
Feb 10 10:21:54 bs podman[2577881]: 2021-02-10 10:21:54.200518323 +0000 UTC m=+0.376233738 container remove 103ee65fa4ba5aa06e055675edb0968dca65c6e5f4cd0e8d0f04a93d0b7e75c9 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=jovial_swartz, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577987]: 2021-02-10 10:21:54.370135775 +0000 UTC m=+0.148321611 container create 00ea4570f4bb88f9b1c0f041dfbb855f56676c890f00eb9311a1f76395995fb1 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=ecstatic_kowalevski, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577987]: 2021-02-10 10:21:54.455446464 +0000 UTC m=+0.233632298 container init 00ea4570f4bb88f9b1c0f041dfbb855f56676c890f00eb9311a1f76395995fb1 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=ecstatic_kowalevski, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577987]: 2021-02-10 10:21:54.474214814 +0000 UTC m=+0.252400683 container start 00ea4570f4bb88f9b1c0f041dfbb855f56676c890f00eb9311a1f76395995fb1 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=ecstatic_kowalevski, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1, io.openshift.release=4.6.0-0.okd-2021-01-23-132511)
Feb 10 10:21:54 bs podman[2577987]: 2021-02-10 10:21:54.474752095 +0000 UTC m=+0.252938172 container attach 00ea4570f4bb88f9b1c0f041dfbb855f56676c890f00eb9311a1f76395995fb1 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=ecstatic_kowalevski, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2577987]: 2021-02-10 10:21:54.502600087 +0000 UTC m=+0.280786392 container died 00ea4570f4bb88f9b1c0f041dfbb855f56676c890f00eb9311a1f76395995fb1 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=ecstatic_kowalevski)
Feb 10 10:21:54 bs podman[2577987]: 2021-02-10 10:21:54.576108373 +0000 UTC m=+0.354294183 container remove 00ea4570f4bb88f9b1c0f041dfbb855f56676c890f00eb9311a1f76395995fb1 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=ecstatic_kowalevski, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2578131]: 2021-02-10 10:21:54.747193335 +0000 UTC m=+0.150288118 container create 5c1ac00b1fc7f4c06572c4bc71ad11ba89b014981d1c43cbab739741f772f929 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=distracted_elion, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2578131]: 2021-02-10 10:21:54.837262139 +0000 UTC m=+0.240357099 container init 5c1ac00b1fc7f4c06572c4bc71ad11ba89b014981d1c43cbab739741f772f929 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=distracted_elion, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2578131]: 2021-02-10 10:21:54.856242246 +0000 UTC m=+0.259337219 container start 5c1ac00b1fc7f4c06572c4bc71ad11ba89b014981d1c43cbab739741f772f929 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=distracted_elion, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs podman[2578131]: 2021-02-10 10:21:54.856681261 +0000 UTC m=+0.259776219 container attach 5c1ac00b1fc7f4c06572c4bc71ad11ba89b014981d1c43cbab739741f772f929 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=distracted_elion, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs bootkube.sh[2578131]: F0210 10:21:54.875723       1 image.go:32] error: error: Unknown name requested, could not find kube-client-agent in UpdatePayload
Feb 10 10:21:54 bs bootkube.sh[2578131]: goroutine 1 [running]:
Feb 10 10:21:54 bs bootkube.sh[2578131]: k8s.io/klog/v2.stacks(0xc000134001, 0xc0001801c0, 0x83, 0xd7)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
Feb 10 10:21:54 bs bootkube.sh[2578131]: k8s.io/klog/v2.(*loggingT).output(0x26b16a0, 0xc000000003, 0x0, 0x0, 0xc000170070, 0x25f8744, 0x8, 0x20, 0x0)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/klog/v2/klog.go:945 +0x191
Feb 10 10:21:54 bs bootkube.sh[2578131]: k8s.io/klog/v2.(*loggingT).printf(0x26b16a0, 0x3, 0x0, 0x0, 0x19e2bb1, 0x9, 0xc000039d40, 0x1, 0x1)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
Feb 10 10:21:54 bs bootkube.sh[2578131]: k8s.io/klog/v2.Fatalf(...)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/klog/v2/klog.go:1463
Feb 10 10:21:54 bs bootkube.sh[2578131]: main.runImageCmd(0x269df60, 0xc00006c330, 0x1, 0x1)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/cmd/image.go:32 +0xf1
Feb 10 10:21:54 bs bootkube.sh[2578131]: github.com/spf13/cobra.(*Command).execute(0x269df60, 0xc00006c2f0, 0x1, 0x1, 0x269df60, 0xc00006c2f0)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
Feb 10 10:21:54 bs bootkube.sh[2578131]: github.com/spf13/cobra.(*Command).ExecuteC(0x269e200, 0x1682b1e, 0x269e200, 0xc000505f40)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/github.com/spf13/cobra/command.go:950 +0x375
Feb 10 10:21:54 bs bootkube.sh[2578131]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/github.com/spf13/cobra/command.go:887
Feb 10 10:21:54 bs bootkube.sh[2578131]: main.main()
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/cmd/main.go:26 +0x53
Feb 10 10:21:54 bs bootkube.sh[2578131]: goroutine 19 [chan receive]:
Feb 10 10:21:54 bs bootkube.sh[2578131]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x26b16a0)
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
Feb 10 10:21:54 bs bootkube.sh[2578131]: created by k8s.io/klog/v2.init.0
Feb 10 10:21:54 bs bootkube.sh[2578131]:         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/klog/v2/klog.go:416 +0xd8
Feb 10 10:21:54 bs podman[2578131]: 2021-02-10 10:21:54.88445105 +0000 UTC m=+0.287546392 container died 5c1ac00b1fc7f4c06572c4bc71ad11ba89b014981d1c43cbab739741f772f929 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=distracted_elion)
Feb 10 10:21:54 bs podman[2578131]: 2021-02-10 10:21:54.983374716 +0000 UTC m=+0.386470034 container remove 5c1ac00b1fc7f4c06572c4bc71ad11ba89b014981d1c43cbab739741f772f929 (image=quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36, name=distracted_elion, io.openshift.release=4.6.0-0.okd-2021-01-23-132511, io.openshift.release.base-image-digest=sha256:2402cf97d2b2f3626199dcc4804a2a7beb44e1be997441d8725d2a65ae2f2db1)
Feb 10 10:21:54 bs systemd[1]: bootkube.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 10 10:21:54 bs systemd[1]: bootkube.service: Failed with result 'exit-code'.

**Comment by vrutkovs** [comment]
>Feb 09 13:08:32 localhost release-image-download.sh[4522]: Error: Error initializing source docker://quay.io/openshift/okd@sha256:63289dbb5f6304df117c3962ff4185eb1081053916b32c45845260562f72dd36: error pinging docker registry quay.io: Get "quay.io/v2": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:44842->[::1]:53: read: connection refused

Bootstrap has invalid hostname

**Comment by borbul2007** [comment]
Where can I change this? In the second log (bootkube.service) the name is **bs**.

**Comment by vrutkovs** [comment]
oh, I see - it picked up the hostname later. Well, its invalid as well - it has to be a FQDN including the base domain part

**Comment by borbul2007** [comment]
How and where is the host name formed? Is it from PTR?

**Comment by borbul2007** [comment]
About FQDN.
You can see the short hostname in the log output in other issues.

**Comment by borbul2007** [comment]
After several unsuccessful attempts, the cluster have installed, but the console does not start.
Everything exactly matches the description in this issue: https://github.com/openshift/okd/issues/183

![image](https://user-images.githubusercontent.com/78852894/107846294-ac4add00-6df3-11eb-8158-947543f75803.png)

![image](https://user-images.githubusercontent.com/78852894/107846352-24b19e00-6df4-11eb-8ff0-08016c51250b.png)

**Comment by fortinj66** [comment]
try restarting the ingress routers
