### ISSUE TITLE
OKD:4.6, UPI:VMware, OVNKubernetes - Fresh install not possible (console fails to start)

### ISSUE THREAD

**Issue by borbul2007** [openshift/okd#508]
**Describe the bug**

I had successfully installed OKD 4.6 but console fails to start with error:

_2021-02-13T10:57:48Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client_

The behavior is very similar to:
 https://github.com/openshift/okd/issues/183
 https://github.com/openshift/okd/issues/159
 https://github.com/openshift/okd/issues/141

**Version**

UPI - VMware ESXi, 6.7.0, 17167734
OKD - 4.6.0-0.okd-2021-01-23-132511
FCOS - 33.20210104.3.0

**How reproducible**

100% Provision a cluster on UPI using versions above

**Log bundle**

![image](https://user-images.githubusercontent.com/78852894/107848358-d73d2d00-6e03-11eb-810a-887223e41041.png)

![image](https://user-images.githubusercontent.com/78852894/107848369-e6bc7600-6e03-11eb-8269-ab253bb951ba.png)

![image](https://user-images.githubusercontent.com/78852894/107848414-56326580-6e04-11eb-904d-8f91095a95de.png)

**oc describe pod console-654c76c58f-5tnbr -n openshift-console**
...
    State:       Running
      Started:   Sat, 13 Feb 2021 14:02:58 +0300
    Last State:  Terminated
      Reason:    Error
      Message:   uest to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:56:48Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:56:58Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:57:08Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:57:18Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:57:28Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:57:38Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
2021-02-13T10:57:48Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.dev.okd.lan/oauth/token failed: Head https://oauth-openshift.apps.dev.okd.lan: http: server gave HTTP response to HTTPS client
...

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

Also could you give https://amd64.origin.releases.ci.openshift.org/releasestream/4.6.0-0.okd/release/4.6.0-0.okd-2021-02-13-102225 a try?

**Comment by fortinj66** [comment]
as an FYI, it sometimes take a long time for authentication to come up successfully.  Console will not be available until then...

**Comment by borbul2007** [comment]
@fortinj66
1 day - is it a long time?

@vrutkovs 
log bundle ~ 300Mb. Where can I load it?

**Comment by vrutkovs** [comment]
Any file sharing service of your choice - and post a link here

**Comment by borbul2007** [comment]
@vrutkovs 
https://cloud.mail.ru/public/8Q1L/87Z38aDG9

**Comment by vrutkovs** [comment]
1) Your bootstrap has completed, you must take down that node
2) your bootstrap and masters are receiving a short name from DHCP/PTR. It should be a FQDN
3) your machineNetwork is wrong - config has `cidr: 10.0.0.0/16` but actual IPs are `192.168.0.x`

As a result, etcd rejects oauth-server connection and auth server doesn't come up

**Comment by borbul2007** [comment]
"Your bootstrap has completed, you must take down that node"
VM was started only for log-bundle.
    "your bootstrap and masters are receiving a short name from DHCP/PTR. It should be a FQDN"
    "your machineNetwork is wrong - config has cidr: 10.0.0.0/16 but actual IPs are 192.168.0.x"
Could you please provide a link to this in the documentation? I never found this description.

**Comment by borbul2007** [comment]
@vrutkovs about FQDN
 How to get FCOS to apply correct hostname settings obtained via DHCP?

**bootstrap console log**:
1. from DHCP
...
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4894] dhcp4 (ens192): option dhcp_lease_time      => '7200'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4898] dhcp4 (ens192): option domain_name          => **'dev.okd.lan'**
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4898] dhcp4 (ens192): option domain_name_servers  => '192.168.0.2'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4898] dhcp4 (ens192): option domain_search        => 'dev.okd.lan okd.lan'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4898] dhcp4 (ens192): option expiry               => '1613409580'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4898] dhcp4 (ens192): option host_name            => **'bs'**
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4898] dhcp4 (ens192): option ip_address           => '192.168.0.10'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4899] dhcp4 (ens192): option next_server          => '192.168.0.2'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4899] dhcp4 (ens192): option requested_broadcast_address => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4899] dhcp4 (ens192): option requested_domain_name => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4899] dhcp4 (ens192): option requested_domain_name_servers => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4899] dhcp4 (ens192): option requested_domain_search => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4899] dhcp4 (ens192): option requested_host_name  => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4900] dhcp4 (ens192): option requested_interface_mtu => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4900] dhcp4 (ens192): option requested_ms_classless_static_routes => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4900] dhcp4 (ens192): option requested_nis_domain => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4900] dhcp4 (ens192): option requested_nis_servers => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4900] dhcp4 (ens192): option requested_ntp_servers => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4900] dhcp4 (ens192): option requested_rfc3442_classless_static_routes => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4901] dhcp4 (ens192): option requested_root_path  => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4901] dhcp4 (ens192): option requested_routers    => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4901] dhcp4 (ens192): option requested_static_routes => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4901] dhcp4 (ens192): option requested_subnet_mask => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4902] dhcp4 (ens192): option requested_time_offset => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4902] dhcp4 (ens192): option requested_wpad       => '1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4902] dhcp4 (ens192): option routers              => '192.168.0.1'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4902] dhcp4 (ens192): option subnet_mask          => '255.255.255.0'
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4902] dhcp4 (ens192): state changed unknown -> bound
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.4929] device (ens192): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
...

2. Network Manager Script Dispatcher
...
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5130] manager: NetworkManager state is now CONNECTED_LOCAL
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5141] manager: NetworkManager state is now CONNECTED_SITE
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5142] policy: set 'Wired connection 1' (ens192) as default for IPv4 routing and DNS
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5144] policy: set-hostname: set hostname to '**bs**' (from DHCPv4)
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5149] device (ens192): Activation: successful, device activated.
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5156] manager: NetworkManager state is now CONNECTED_GLOBAL
Feb 15 15:19:51 localhost NetworkManager[805]: <info>  [1613402391.5163] manager: startup complete
...

3.  Starting Hostname Service...
...
Feb 15 15:19:51 bs systemd[1]: Started Hostname Service.
Feb 15 15:19:51 bs systemd-resolved[720]: System hostname changed to '**bs**'.
Feb 15 15:19:51 bs systemd-hostnamed[3680]: Changed hostname to '**bs**'
...

**Comment by borbul2007** [comment]
I added hostname as the kernel arguments and machineNetwork: - cidr: 192.168.0.1/24 to the install-config.yaml. Nothing changed.

**Comment by borbul2007** [comment]
I checked it on new release. **Nothing changed**.

**Version**
UPI - VMware ESXi, 6.7.0, 17167734
OKD - 4.6.0-0.okd-2021-02-14-205305
FCOS - 33.20210117.3.2

**Log bundle**
https://cloud.mail.ru/public/YFoT/BZiBTJ8fh

**Issue**
https://github.com/openshift/okd/issues/513

**Comment by fortinj66** [comment]
@borbul2007 Is this still an issue?
