### ISSUE TITLE
Latest 4.6 installer for openstack/ovirt doesn't set internal nameserver via systemd-resolved

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#509]
Similar to https://github.com/openshift/installer/pull/4584 installer needs to be updated to set nameserver via systemd-resolved.

The whole implementation should be reworked to check if the service is active - see https://github.com/openshift/machine-config-operator/pull/2356

**Comment by fortinj66** [comment]
vsphere also

**Comment by vrutkovs** [comment]
Right, vsphere should work, but the script needs to be updated to use `systemctl is-active systemd-resolved` instead of sourcing /etc/os-release

**Comment by fortinj66** [comment]
latest nightlies have the fix and work as expected

**Comment by vrutkovs** [comment]
Resolved in 4.6 nightlies / 4.7.0-0.okd-2021-02-25-144700
