### ISSUE TITLE
Update from 4.6.0-0.okd-2021-01-23-132511 to 4.6.0-0.okd-2021-02-14-205305: The update cannot be verified: unable to locate a valid signature for one or more sources

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#510]
**Describe the bug**
I tried to upgrade from from 4.6.0-0.okd-2021-01-23-132511 to 4.6.0-0.okd-2021-02-14-205305 and receive a ImageVerificationFailed-Error: 
The update cannot be verified: unable to locate a valid signature for one or more sources
Unable to apply 4.6.0-0.okd-2021-02-14-205305: the image may not be safe to use

Do I need to execute the steps from https://github.com/openshift/okd/blob/master/KNOWN_ISSUES.md#invalid-signature-error-when-attempting-cluster-updates ? (oc adm upgrade --reset throw an Error: unknown flag: --reset)

**Version**
4.6.0-0.okd-2021-01-23-132511

**Comment by vrutkovs** [comment]
Signature generator is temporarily offline, should be back in a couple of hours.

You can run `oc adm upgrade ... --force` to skip this - or set `force: true` in ClusterVersion spec

**Comment by vrutkovs** [comment]
Fixed:
```
url -Ls https://storage.googleapis.com/openshift-ci-release/releases/signatures/openshift/release/sha256\=${DIGEST}/signature-1 | gpg -d
{
  "critical": {
    "type": "atomic container signature",
    "image": {
      "docker-manifest-digest": "sha256:6640a4daf0623023b9046fc91858d018bd34433b5c3485c4a61904a33b59a3b9"
    },
    "identity": {
      "docker-reference": "quay.io/openshift/okd:4.6.0-0.okd-2021-02-14-205305"
    }
  },
  "optional": {
    "creator": "openshift release-controller",
    "timestamp": 1613401973
  }
}gpg: Signature made Mon 15 Feb 2021 16:12:53 CET
gpg:                using RSA key 28B76E05B923888E
gpg: Good signature from "openshift-ci" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D047 61B1 1620 3B0C 0859  B616 28B7 6E05 B923 888E

```
