### ISSUE TITLE
[MCO] Images in new Dockerfile not accessible to public

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#514]
MCO Pull https://github.com/openshift/machine-config-operator/pull/2400 changes the various image paths in the Dockerfile.  These images are not available publicly.

**Describe the bug**
Unable to build MCO image as build images in the Dockerfile are unavailable.

```
# make image
hack/build-image
No previous build
HEAD commit: 47d8c4f45009e19f230245c2c55264ed3c002e08
podman build -t localhost/machine-config-operator:latest --no-cache . --label=io.openshift.build.commitauthor= --label=io.openshift.build.commitdate= --label=io.openshift.build.commitid= --label=io.openshift.build.commitmessage= --label=io.openshift.build.commitref= --label=vcs-ref=47d8c4f45009e19f230245c2c55264ed3c002e08 --label=vcs-type=git --label=vcs-url=
STEP 1: FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.8 AS builder
STEP 2: FROM registry.ci.openshift.org/ocp/4.8:base
Error: error creating build container: Error initializing source docker://registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.8: Error reading manifest rhel-8-golang-1.15-openshift-4.8 in registry.ci.openshift.org/ocp/builder: unauthorized: authentication required
make: *** [Makefile:38: image] Error 125
```
These are the two images that are not available:
```
# grep registry Dockerfile
FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.8 AS builder
FROM registry.ci.openshift.org/ocp/4.8:base
```

**Comment by vrutkovs** [comment]
Right, we should be using `registry.ci.openshift.org/origin/builder:golang-1.15` and `registry.ci.openshift.org/origin/4.8:base`. I'll work with CI team to simplify this.

**Comment by fortinj66** [comment]
For example, what is the equivalent to `registry.ci.openshift.org/origin/builder:golang-1.17-openshift-4.10` (from MCO)

I tried `registry.ci.openshift.org/origin/builder:golang-1.17` which doesn't exist

**Comment by LorbusChris** [comment]
`http://registry.ci.openshift.org/openshift/release:golang-1.17` should be what you're looking for and also be publicly pullable.

**Comment by fortinj66** [comment]
I'll give it a try tomorrow...  

It would be nice if we were all using the same image though :)

**Comment by JaimeMagiera** [comment]
Just to clarify: Is that base URL applicable to all the relevant packages? (registry.ci.openshift.org/origin/builder:xxxx  => registry.ci.openshift.org/openshift/release:xxx)

**Comment by 87utierrez** [comment]
I'm trying to run a make build/olm-container
But I'm getting an error 
ERROR: failed to solve: registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14: pulling from host registry.ci.openshift.org failed with status code [manifests rhel-8-golang-1.20-openshift-4.14]: 401 

I tried to run a docker login to this registry using my Redhat authentication I don't have access but I have access to the other registry.redhat.io
Any help would be greatly appreciated
