### ISSUE TITLE
[MCO][vsphere]  vsphere hosts fail to get assigned hostnames from vsphere 

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#516]
MCO Pull https://github.com/openshift/machine-config-operator/pull/2405 breaks hostname retrieval from vsphere as vsphere-hostname.service now runs during first boot.  However, open-vm-tools, which provides the executables needed to get this isn't available during firstboot.  Since it only runs during firstboot, it never retrieves the proper hostname in subsequent boots:

```
 $ journalctl -u vsphere-hostname.service
-- Logs begin at Thu 2021-02-11 16:10:11 UTC, end at Thu 2021-02-11 16:35:11 UTC. --
Feb 11 16:16:34 localhost systemd[1]: Started vSphere hostname.
Feb 11 16:16:34 localhost vsphere-hostname.sh[1006]: /usr/local/bin/vsphere-hostname.sh: line 7: /bin/vmtoolsd: No such file or directory
Feb 11 16:16:34 localhost systemd[1]: vsphere-hostname.service: Succeeded.
-- Reboot --
Feb 11 16:27:32 localhost systemd[1]: Condition check resulted in vSphere hostname being skipped.
```
the condition to run this should probably be:
```ConditionPathExists=!/etc/ignition-machine-config-encapsulated.json```

**Version**
4.7 vSphere IPI

The equivalent pull is also targeted for 4.6: https://github.com/openshift/machine-config-operator/pull/2404

**Comment by vrutkovs** [comment]
This was reverted in OKD 4.7 fork, we'll reconcile on this again when forks get merged
