### ISSUE TITLE
FATAL Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition

### ISSUE THREAD

**Issue by bobby0724** [openshift/okd#517]
**Describe the bug**
Trying to install a fresh 4.6 cluster and have tried 2 times no luck

**Version**

4.6.0-0.okd-2021-02-14-205305
**How reproducible**

IPI Vsphere [installation]
**Log bundle**

https://www.dropbox.com/s/lvuc6g04klsu99q/log-bundle-20210218073109.tar.gz?dl=0

**Comment by bobby0724** [comment]
Installation completed after 45 min 3 masters and 3 workers up
bootstrap server was not deleted

**Comment by fortinj66** [comment]
The installer has an issue with internal DNS. 

https://github.com/openshift/installer/pull/4654

**Comment by bobby0724** [comment]
thanks John we can close this one then

**Comment by bobby0724** [comment]
already a issue open for this openshift/installer#4654
