### ISSUE TITLE
[OKD4] Documentation indicates to not use more or less than exactly 3 Master Nodes in OKD 4

### ISSUE THREAD

**Issue by devzeronull** [openshift/okd#519]
Hi,
is it really intended to not use more or less than 3 Master Nodes in a OKD 4 production environment, like the documentation states in "https://docs.okd.io/latest/architecture/control-plane.html"?

We would like to run more than 3 Master Nodes for redundancy and availability reasons, it would be kind if someone could explain why we shall not use more than exactly 3.

BR

**Comment by vrutkovs** [comment]
Yes. See https://github.com/openshift/enhancements/pull/292 for an enhancement to expand the control plane
