### ISSUE TITLE
openshift-authentication-operator is constantly logging a lot informational (?) events

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#520]
**Describe the bug**
The authentication-operator pod in the openshift-authentication-operator namespace is constantly logging (multiple times per second) such events:

`I0219 10:01:43.047914       1 event.go:282] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-authentication-operator", Name:"authentication-operator", UID:"6523525e-69c1-4520-9da2-deb351e53338", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'SecretUpdated' Updated Secret/v4-0-config-system-router-certs -n openshift-authentication because it changed
I0219 10:01:43.476509       1 event.go:282] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-authentication-operator", Name:"authentication-operator", UID:"6523525e-69c1-4520-9da2-deb351e53338", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'SecretUpdated' Updated Secret/v4-0-config-system-router-certs -n openshift-authentication because it changed
`

It's strange because the mentioned secret should not be changing so often?
In fact, it is not changing at all ... so why does the operator does this?

**Version**
OKD 4.6.0-0.okd-2021-02-14-205305

**How reproducible**
Always.

**Log bundle**
http://domino.ars.de/file/must-gather.local.7223640052665220174.tar.gz

**Comment by kai-uwe-rommel** [comment]
No comment from anyone?

**Comment by vrutkovs** [comment]
Is this an OKD specific problem? Is it reproducible in OCP?

**Comment by kai-uwe-rommel** [comment]
I just checked this also on an OCP cluster and it happens there as well.
So I should open a support case at Red Hat against this?

**Comment by vrutkovs** [comment]
I don't think a support case is necessary - lets create a new bugzilla (use Help icon -> Report bug to Red Hat in cluster console)

**Comment by kai-uwe-rommel** [comment]
Under Help there is only "Open Support Case with red Hat" ... which does exactly that and not Bugzilla.
So I need to use Bugzilla directly. Which component do you suggest?

**Comment by kai-uwe-rommel** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1935654
