### ISSUE TITLE
OVNKubernetes: network connectivity issue when k8s network interface is not default gateway.

### ISSUE THREAD

**Issue by m-yosefpor** [openshift/okd#522]
**Describe the bug**
We have two network interfaces on our nodes, one of which is default GW, with internet access, and one internal interface, as our internal network. We need to have both interfaces on all nodes, and also need to set up the OVNKubernetes on our internal network interface (which is not default GW), as not all of our nodes can see each other on default GW interface and must use internal network interface. OVNKuberenetes always sits on default GW, regardless of order of interfaces (or anything else we tried), so some of our nodes can't see each other.

I can't find any option to specify the interface which OVNKubernetes should sit on.

My assumptions:
OVNKubernetes always sits on default GW if gateway-interface is not provided [link](https://github.com/openshift/ovn-kubernetes/blob/b6d0e7398325742c17c64e90eba69970698fbd37/go-controller/pkg/config/config.go#L781).
As cluster-network-operator does not provide gateway-interface [link](https://github.com/openshift/cluster-network-operator/blob/dfea1dc53ed82f5e4a4e85b7e8e863af3e4bd54a/bindata/network/ovn-kubernetes/004-config.yaml#L26), it always uses default GW

**Version**
`4.6.0-0.okd-2021-02-14-205305`
UPI, Openstack

**Comment by vrutkovs** [comment]
Please open a bugzilla for OCP, as its most likely not specific to OKD
