### ISSUE TITLE
{4.7][console] Hide Insights section in Home/Overview section

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#524]
**Describe the bug**

Insights would seem to be only for OCP and should be hidden/removed for OCP

![image](https://user-images.githubusercontent.com/8594283/108899399-5d1c5d80-75e6-11eb-9c3b-1076420f8225.png)

**Version**
OKD 4.7 

**How reproducible**
OKD 4.7 Installs

**Comment by vrutkovs** [comment]
Strictly speaking Insights would work just fine when pull secret has redhat.io section.

**Comment by vrutkovs** [comment]
With fake pull secret it shows as `Disabled or waiting for results.`, with Red Hat's pull secret its available
