### ISSUE TITLE
Older cri-tools package got picked up and throws `unsupported output format ""` on `crictl ps -a`

### ISSUE THREAD

**Issue by CC-Kuoying** [openshift/okd#527]
Hello,
A problem with a fresh install of OKD 4.6 and FedoraCoreOS 33.20210201 in my vSphere Environnement :

ESXi-6.7.0 & Virtual Machine version to 13
FedoraCoreOS 33.20210201
Client Version: 4.6.0-0.okd-2021-02-14-205305
Server Version: 4.6.0-0.okd-2021-02-14-205305
<img width="650" alt="截圖 2021-02-24 下午4 41 09" src="https://user-images.githubusercontent.com/71488933/108974645-9e813b80-76c0-11eb-8139-35fdd1be82d2.png">

**Comment by vrutkovs** [comment]
An older `cri-tools` from 1.11 era got picked up. We'd need to revive https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-tools ideally to have it fixed (cc @haircommander).

Workaround: `crictl ps -a -o table`

**Comment by CC-Kuoying** [comment]
@vrutkovs thanks.

**Comment by vrutkovs** [comment]
Let keep it open until correct cri-tool package lands

**Comment by vrutkovs** [comment]
Resolved in 4.7 builds
