### ISSUE TITLE
What is this problem?

### ISSUE THREAD

**Issue by CC-Kuoying** [openshift/okd#528]
<img width="1040" alt="截圖 2021-02-24 下午7 43 47" src="https://user-images.githubusercontent.com/71488933/108995976-ce3c3d80-76d8-11eb-9c76-409f81614dd6.png">

<img width="1101" alt="截圖 2021-02-24 下午7 47 03" src="https://user-images.githubusercontent.com/71488933/108996235-18252380-76d9-11eb-939d-f1be63e9dab1.png">

**Comment by vrutkovs** [comment]
Dupe of #523
