### ISSUE TITLE
OKD 4.7: openshift-ingress-operator is degraded if you redirect http to https in external LB

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#529]
Hi,

we use an external Load Balancer that redirects all http traffic to https routes.

In OKD 4.7 a new concept was introduced to test the ingress during upgrades with the help of an "openshift-ingress-canary" route. 

The operator tests if it gets a HTTP response from the canary route ("hello-openshift"). Because we redirect http traffic to https externally, this route does timeout and the ingress-operator degrades.

If you manually add edge termination to the canary route, everything works again.

https://github.com/openshift/cluster-ingress-operator/pull/555

Greetz,

Josef

**Comment by vrutkovs** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1932649

PR for release-4.7 - https://github.com/openshift/cluster-ingress-operator/pull/558
