### ISSUE TITLE
OperatorHub UI broken in 4.4.0-0.okd-2020-01-28-022517 in console app

### ISSUE THREAD

**Issue by gtema** [openshift/okd#53]
Switching between categories in the OperatorHub in the web console leads to entities being appended to the list of previous entities, instead of their replacement (in 4.3 it was working correctly).

So if I i.e. go to https://console-openshift-console.apps.mycluster/operatorhub/all-namespaces?category=Storage I see 8 items (including counter of 8 top right). Actually each item is doubled, so there are only 4 unique items. Switching to "Streaming and messaging" category append some items, so that overall UI shows 12 items.
Only checking on some filter checkbox resets the view after switching between categories.

Additionally comparing to the content of operatorhub.io not all items present there are shown in UI (i.e. rook is missing)

**Comment by vrutkovs** [comment]
Seems to be related to Community operators only restriction

**Comment by vrutkovs** [comment]
Is it still happening on latest builds?
