### ISSUE TITLE
Upgrade from 4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-02-23-121606 fail

### ISSUE THREAD

**Issue by bobby0724** [openshift/okd#530]
**Describe the bug**

Trying to upgrade from 4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-02-23-121606 fail

1 master and 1 worker reboot and i can see that they dont have ip from dhcp

**Version**

4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-02-23-121606
**How reproducible**

upgrade from 4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-02-23-121606
**Log bundle**

**Comment by dubbrian** [comment]
I have exactly this issue with one master and one worker not picking up dhcp IP addresses

**Comment by dubbrian** [comment]
unfortunately mst gather times out fairly promptly

$ oc adm must-gather
[must-gather      ] OUT Using must-gather plugin-in image: registry.ci.openshift.org/origin/4.7-2021-02-23-121606@sha256:c9df868c75ce5b8bea5b787f5a89dff23d4f081f078bf723cc7616a7c16fa278
[must-gather      ] OUT namespace/openshift-must-gather-h8xtv created
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-m9csq created
[must-gather      ] OUT pod for plug-in image registry.ci.openshift.org/origin/4.7-2021-02-23-121606@sha256:c9df868c75ce5b8bea5b787f5a89dff23d4f081f078bf723cc7616a7c16fa278 created
[must-gather-8zvkf] OUT gather did not start: timed out waiting for the condition
[must-gather      ] OUT clusterrolebinding.rbac.authorization.k8s.io/must-gather-m9csq deleted
[must-gather      ] OUT namespace/openshift-must-gather-h8xtv deleted
error: gather did not start for pod must-gather-8zvkf: timed out waiting for the condition

**Comment by fortinj66** [comment]
How many masters/workers are in your cluster?

**Comment by bobby0724** [comment]
3 Masters 3 Workers, the cluster is functional pero this 2 nodes are pending to upgrade
![image](https://user-images.githubusercontent.com/30838789/109516431-cd573300-7a6d-11eb-85d1-6ac6cc7b973c.png)

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by fortinj66** [comment]
Can you try getting the must-gather again?

Also, I've found that shutting down the bad servers for a minute or so and rebooting them help clear up the DHCP issues...

**Comment by bobby0724** [comment]
> Can you try getting the must-gather again?
> 
> Also, I've found that shutting down the bad servers for a minute or so and rebooting them help clear up the DHCP issues...

Yes we have try restarting both machines and same result

**Comment by fortinj66** [comment]
> Yes we have try restarting both machines and same result

Did you leave them powered off for a minute or two and then restart?

> error: You must be logged in to the server (Unauthorized)

This seems to indicate that you aren't using the correct credentials...  Can you list the nodes? `oc get nodes`

**Comment by bobby0724** [comment]
> > Yes we have try restarting both machines and same result
> 
> Did you leave them powered off for a minute or two and then restart?
> 
> > error: You must be logged in to the server (Unauthorized)
> 
> This seems to indicate that you aren't using the correct credentials... Can you list the nodes? `oc get nodes`

No let me try that now

**Comment by bobby0724** [comment]
> > Yes we have try restarting both machines and same result
> 
> Did you leave them powered off for a minute or two and then restart?
> 
> > error: You must be logged in to the server (Unauthorized)
> 
> This seems to indicate that you aren't using the correct credentials... Can you list the nodes? `oc get nodes`

Shutting down the nodes for 2 + minutes do the trick i can see both servers now have let see if they advance

**Comment by fortinj66** [comment]
if they come up, please try to capture a new must-gather...  Make sure you are using a user with cluster-admin permissions...

**Comment by dubbrian** [comment]
nodes came up but not ready, restarted master-0 and now doesnt get dhcp addres again even after leaving powered off for 5 mins
Ran a must gather in that state, and generated 191Mb output
will try to attach that

**Comment by bobby0724** [comment]
> if they come up, please try to capture a new must-gather... Make sure you are using a user with cluster-admin permissions...

Yes we are not using normal users everything is done with [kubeadmin](https://www.dropbox.com/s/sykircqs5ksjhtr/must-gather.tar.gz?dl=0)

**Comment by fortinj66** [comment]
I was hoping to see a `journalctl` output from one of the bad masters.  If you get the "bad" master running, please post the output of `journalctl`

Unfortunately, I am no longer able to reproduce this issue in my environment

**Comment by bobby0724** [comment]
The bad master is sending this error when we try to login from bastion server
"System is booting up. Unprivileged users are not permitted to log in yet.

    On Monday, March 1, 2021, 4:16:48 PM CST, John Fortin <notifications@github.com> wrote:  
 
 


I was hoping to see a journalctl output from one of the bad masters. If you get the "bad" master running, please post the output of journalctl

Unfortunately, I am no longer able to reproduce this issue in my environment

**Comment by fortinj66** [comment]
> The bad master is sending this error when we try to login from bastion server "System is booting up. Unprivileged users are not permitted to log in yet.

I'd restart it.  I was getting that also on occasion...

**Comment by bobby0724** [comment]
Ok i check journalctl and see some certificate errors so i check pending csr's i find many of them pending so i approve them and master-0 finish, now i am not able to make master-1 to get the ip from dhcp :(
[okd4admin@sacla107 ~]$ oc get nodes
NAME                         STATUS                        ROLES    AGE     VERSION
okd4lab-kq2kj-master-0               Ready                                 master   5d1h    v1.20.0+5fbfd19-1046
okd4lab-kq2kj-master-1               NotReady,SchedulingDisabled   master   5d1h    v1.19.2+f173eb4-1049
okd4lab-kq2kj-master-2               Ready                                 master   5d1h    v1.19.2+f173eb4-1049
okd4lab-kq2kj-worker-c9msm       Ready                                 worker   5d      v1.20.0+5fbfd19-1046
okd4lab-kq2kj-worker-ckv4q       Ready,SchedulingDisabled          worker   5d      v1.20.0+5fbfd19-1046
okd4lab-kq2kj-worker-fg8q9       Ready                                  worker   4d23h   v1.19.2+f173eb4-1049
    


    On Monday, March 1, 2021, 4:24:37 PM CST, John Fortin <notifications@github.com> wrote:  
 
 



The bad master is sending this error when we try to login from bastion server "System is booting up. Unprivileged users are not permitted to log in yet.


I'd restart it. I was getting that also on occasion...

**Comment by bobby0724** [comment]
> > The bad master is sending this error when we try to login from bastion server "System is booting up. Unprivileged users are not permitted to log in yet.
> 
> I'd restart it. I was getting that also on occasion...

It takes a while but finally I was able to complete the upgrade, the DHCP issues is really bad, sometimes I reboot reset power off restart up to 10 times, also 1 of the workers was corrupted and that was preventing the operators to complete the upgrade, so i deleted and the upgrade finally completes.

Now I want to provision a new worker node to get back to 4 but is not happening the server is created in the vcenter but is not completing the bootstrap is stuck any suggestion ?

**Comment by bobby0724** [comment]
No more comments
