### ISSUE TITLE
[AWS UPI] Documentation refers to RHCOS AMI instead of FCOS

### ISSUE THREAD

**Issue by rheathcote-deloitte** [openshift/okd#532]
Running `4.7.0-0.okd-2021-02-25-144700` on user provisioned infrastructure with AMI ID `ami-0d5f9982f029fbc14`. My bootstrap instance fails to complete the release-image process. Error is that `podman image mount` is unrecognized (see below for error message in full context). Podman version on the instance is 2.0.5. The `image mount` command was [added to podman in `2.1.0`](https://github.com/containers/podman/commit/6979d140f1c531fd32e885542be27407105ebf90). So the AMI specified in the [OKD Installation Documentation](https://docs.okd.io/latest/installing/installing_aws/installing-aws-user-infra.html#installation-aws-user-infra-rhcos-ami_installing-aws-user-infra) (which is the latest 4.7.0 AMI I can find in AWS) is running a version of podman that is behind what the latest release of OKD's installer is expecting.

**Version**

4.7.0-0.okd-2021-02-25-144700

**How reproducible**
I expect 100% - haven't tried it a second time.

**Log bundle**

Openshift version on installer instance:
```
[ec2-user@ip-172-31-17-183 ~]$ openshift-install version
openshift-install 4.7.0-0.okd-2021-02-25-144700
built from commit a005bb9eddcbc97e4cac2cdf4436fe2d524cc75e
release image quay.io/openshift/okd@sha256:d0141818eca0f2d49fdea7f3ae5789f3bc747a669f2459f8ef189d1702405b08
```
Podman version on bootstrap node:
```
[core@ip-10-0-25-46 ~]$ podman -v
podman version 2.0.5
```
release-image logs on bootstrap node:
```
[core@ip-10-0-25-46 ~]$ journalctl -b -f -u release-image.service
-- Logs begin at Fri 2021-02-26 22:03:07 UTC. --
Feb 26 22:18:56 ip-10-0-25-46 systemd[1]: Starting Download the OpenShift Release Image...
Feb 26 22:18:56 ip-10-0-25-46 release-image-download.sh[1137]: Pulling quay.io/openshift/okd@sha256:d0141818eca0f2d49fdea7f3ae5789f3bc747a669f2459f8ef189d1702405b08...
Feb 26 22:18:57 ip-10-0-25-46 release-image-download.sh[1137]: 527e7307a15add8f82970d0b62cf156e6ea9304b6cc8ffdf3a64f98fadc48758
Feb 26 22:18:59 ip-10-0-25-46 release-image-download.sh[1137]: d51bd10e5e5c48fec6a70aa02b9b8746a71f0f1e02b871c6460ff29f353750a2
Feb 26 22:18:59 ip-10-0-25-46 release-image-download.sh[1137]: Error: unrecognized command `podman image mount`
Feb 26 22:18:59 ip-10-0-25-46 release-image-download.sh[1137]: Try 'podman image --help' for more information.
Feb 26 22:18:59 ip-10-0-25-46 systemd[1]: release-image.service: Main process exited, code=exited, status=125/n/a
Feb 26 22:18:59 ip-10-0-25-46 systemd[1]: release-image.service: Failed with result 'exit-code'.
Feb 26 22:18:59 ip-10-0-25-46 systemd[1]: Failed to start Download the OpenShift Release Image.
```

**Comment by vrutkovs** [comment]
Why are you starting with RHCOS AMI?

**Comment by rheathcote-deloitte** [comment]
Good question - I guess I’m a little confused about that. The answer is that I went with the AMI ID indicated by the OKD install guide linked above. Feel free to double check me, but the AMI ID that I’m having trouble with was listed as the appropriate FCOS AMI for the us-east-1 region. It’s definitely labeled as RHCOS in the AWS AMI listing, and when logged into the running machine it claims to be RHCOS.

I tried searching for an FCOS AMI, but wasn’t able to find anything with a name containing “fcos” in the same place I found multiple containing “rhcos” (including the one specified in the docs).

If the AMI given by the OKD install documentation is RHCOS, then I’ll need help understanding how to find the appropriate FCOS AMI, and we will need to update the documentation of which AMIs are prebaked for each region. If there are no prebaked AMIs for FCOS, that will need to be clarified in the documentation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rheathcote-deloitte** [comment]
> Why are you starting with RHCOS AMI?
> 
> Does it work correctly if you use AMIs from https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable?

Silly me - I didn't see the link in your first response - thank you for the link - I'll try that out and respond if it works.

**Comment by rheathcote-deloitte** [comment]
The AMI Id referenced in the link worked great - thank you! I'm not closing the issue as the documentation still needs to be updated, but just wanted to confirm that the link provided does work and should be referenced in the documentation. I'm not sure how the docs get built, otherwise I'd be glad to create the MR myself.

**Comment by vrutkovs** [comment]
Agreed, we should remove AMIs / ISO links from UPI installs and link to [FCOS download](https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable) instead

**Comment by mburke5678** [comment]
What is the docs change suggested here? Remove the text and table in [FCOS AMIs for the AWS infrastructure](https://docs.okd.io/latest/installing/installing_aws/installing-aws-user-infra.html#installation-aws-user-infra-rhcos-ami_installing-aws-user-infra) and replace it with  https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable?

**Comment by vrutkovs** [comment]
Lets remove it for now

With https://github.com/openshift/enhancements/blob/master/enhancements/coreos-bootimages.md landing in 4.8 there'd be an installer subcommand to print AMIs

**Comment by mburke5678** [comment]
@vrutkovs @rheathcote-deloitte I removed the AMI table from the OKD docs. Please see: https://github.com/openshift/openshift-docs/pull/32270

**Comment by mburke5678** [comment]
PR is merged
