### ISSUE TITLE
Nameserver limits were exceeded with vsphere IPI

### ISSUE THREAD

**Issue by webrod** [openshift/okd#534]
**Describe the bug**
/etc/resolv.conf has more than 3 namespaces, this lead to thousand of messages in OKD console:
nameserver limits were exceeded, some nameservers have been omitted

If I manually update resolv.conf on each master and worker nodes to only keep the 3 first, the issue is solved, but it's not the proper way in case I need to scale nodes.
It seems /etc/NetworkManager/dispatcher.d/30-resolv-prepender theoretically limits to 3 by commenting the others, but it does not. Probably it runs before another process that set /resolv.conf from scratch.
No idea how to solve this, I could use a machine config if the nameservers would be fixed IP, but I understand resolv.conf needs to have the first namespace set to its own IP, so I don't think I can use machine config with such dynamic config.

**Version**
v4.5, v4.6, and even 4.7.0-0.okd-2021-02-25-144700.
IPI

**How reproducible**
./openshift-install create cluster --dir=../install/  --log-level=debug
go to OKD console to see tons of errors saying "nameserver limits were exceeded, some nameservers have been omitted"

**Log bundle**
N/A

**Comment by fortinj66** [comment]
Could you post the contents of your /etc/resolv.conf?  Also, is it a symbolic link or a static file?

**Comment by vrutkovs** [comment]
>It seems /etc/NetworkManager/dispatcher.d/30-resolv-prepender theoretically limits to 3 by commenting the others

It does that only when NM manages resolv.conf, which is disabled since a switch to F33. 

Glibc has been fixed for a long time to support >3 nameservers afaik, I suppose this alert should be disabled - please file an bug for OCP

**Comment by fortinj66** [comment]
> It does that only when NM manages resolv.conf, which is disabled since a switch to F33.

It seems strange to me that this should happen in 4.6/4.7...

**Comment by webrod** [comment]
> Could you post the contents of your /etc/resolv.conf? Also, is it a symbolic link or a static file?

# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 172.30.88.106
nameserver 172.30.188.11
nameserver 172.30.190.11
# Too many DNS servers configured, the following entries may be ignored.
nameserver 156.24.14.137
nameserver 156.24.14.11
nameserver 156.24.2.11
nameserver 10.246.64.165
nameserver 10.246.64.167
search my-obfuscated-domain my-other-obfuscated-domain

**Comment by fortinj66** [comment]
That is a large number of DNS servers :)

I don't know if it is specifically documented anywhere, but I believe the suggested number of DNS servers is two external and one internal.  I did validate that you get a warning in /etc/resolv.conf in Fedora 33 if there are more than 3 DNS servers.  So if you can reduce the number of nameservers from DHCP that would eliminate the issue...

Or you can file a bug in OCP as @vrutkovs suggested

**Comment by webrod** [comment]
unfortunately updating my DHCP server is not an option.
do you have a workaround till this is fixed?
/etc/NetworkManager/dispatcher.d/30-resolv-prepender has this interesting command: 
```
 # Only leave the first 3 nameservers in /etc/resolv.conf
 sed -i ':a $!{N; ba}; s/\(^\|\n\)nameserver/\n# nameserver/4g' /etc/resolv.conf
```

can I inject this with a machineconfig?
I have no idea yet if there is a means to run a command at startup from machineconfig.

BTW I'm a bit confused with OKD/OCP.
I thought OCP was the commercial edition of OKD, and I read from OKD page 
"To report issues, use the OKD Github Repo: https://github.com/openshift/okd"

thus those questions:

1. why should I submit a bug to OCP ? I don't even know where to submit
2. My OKD web console actually shows the "RedHat Openshift Container platform" logo on the upper left! The OKD home page (https://www.okd.io/) has a screen shot of the web console, and it shows the OKD logo (not OCP)  on the upper left so I'm very confused about this. I have installed OKD not OCP, it says: 
OpenShift version
4.7.0-0.okd-2021-02-25-144700

hopefully you will clarify for me :-)

thanks!

**Comment by vrutkovs** [comment]
>unfortunately updating my DHCP server is not an option.

Well, then you can just silence the alert. I don't see a reason for OKD to trim nameservers list - what if first three are unavailable?

>why should I submit a bug to OCP ? I don't even know where to submit

Help icon -> Report bug to Red Hat. Component would be Monitoring

> My OKD web console actually shows the "RedHat Openshift Container platform" logo

Resolved in latest nightlies

**Comment by webrod** [comment]
> > unfortunately updating my DHCP server is not an option.
> 
> Well, then you can just silence the alert. I don't see a reason for OKD to trim nameservers list - what if first three are unavailable?
>

It is an event not an alert, it shows on the overview page (Activity web part), I don't think I can silent them

**Comment by vrutkovs** [comment]
Wait, if it not the alert what functionality is impaired and what's the expected result here? OKD can't decide which three DNS nameservers to pick

**Comment by webrod** [comment]
overall it works, the cluster is available. my issue is being flooded by those events, it makes a bit useless the "activity" web part:
![image](https://user-images.githubusercontent.com/1897537/109857115-9c882100-7c5a-11eb-8871-88efcc3830e3.png)

It is very annoying to have that part of the screen refreshing every sec, not being able to make any action on this event, nor disabling them (I can only pause and they miss important events, and pause is removed when you refresh the screen).
OKD can't know which one to pick, but I do.
THat's why I was looking at a way to set myself resolv.conf by setting 2 nameservers + the local one, so I don't get anymore those messages. Setting that file with the 2 is easy with machine config, but I don't know how to add the local one.
I don't know how to  run the sed command neither. I know the 3 first one are the good one so it would work (in my case).
or running any other command to dynamically inject the local IP.
I will keep looking in the documentation how to do this. hopefully this is possible.

thanks

**Comment by vrutkovs** [comment]
The easiest way is to configure systemd-resolved (via machineconfigs) to limit a number of DNS. Alternatively, an MC can also rewrite the NM script to inject only the required nameservers.

Closing this as no fix in OKD is required
