### ISSUE TITLE
openshift-install - now external dependency on libvirt?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#535]
**Describe the bug**
Unlike in OKD up until 4.6, in OKD 4.7 there now is a new external dependency for the openshift-install program on libvirt:

./openshift-install: error while loading shared libraries: libvirt-lxc.so.0: cannot open shared object file: No such file or directory

Is this intentional? The openshift-install program is not smaller than the previous ones.

I can of course install libvirt in the OS where I run openshift-install, but it may not be desirable ...
For example, for the cluster installations that I do on vSphere, I always run the openshift-install on an extra helper VM that is also installed with FCOS like the cluster nodes. I now have to layer libvirt onto this FCOS machine, this works. But it could be a libvirt version that differs from the version that the OKD developers use ...

**Version**
4.7.0-0.okd-2021-02-25

**How reproducible**
always

**Log bundle**
n/a

**Comment by kai-uwe-rommel** [comment]
BTW, this new external dependency is not there in the openshift-install for OCP 4.7 ...

**Comment by vrutkovs** [comment]
>Is this intentional?

Yes. OCP doeesn't support libvirt as a platform, but OKD does

**Comment by Reamer** [comment]
This new dependency breaks installations on hosts that do not have this library installed. In my case, I am using Ubuntu.
Is it possible to include this dependency statically?

Please reopen this issue.

**Comment by vrutkovs** [comment]
>Is it possible to include this dependency statically?

no, that'd require including the whole libvirt.

>hosts that do not have this library installed

We ship the whole `installer` container image, could you use that?

**Comment by Reamer** [comment]
Thanks @vrutkovs 

Steps in my case
```
# Get the installer image for your release
oc adm release info quay.io/openshift/okd:4.7.0-0.okd-2021-04-11-124433 --image-for=installer
# Output
quay.io/openshift/okd-content@sha256:11afc2efb95a1ec369be643e562f26b38c64335d14da718692a191cef8b2362b
```
Run this image to complete your tasks
```
docker run -v $(pwd):/output -ti --user 0 quay.io/openshift/okd-content@sha256:11afc2efb95a1ec369be643e562f26b38c64335d14da718692a191cef8b2362b create ignition-configs
```
