### ISSUE TITLE
[OKD4.7] New installation of OKD 4.7.0-0.okd-2021-02-25-144700 results in OpenShift Branding

### ISSUE THREAD

**Issue by devzeronull** [openshift/okd#538]
Hi,

we've got some experiences right now with OKD 4.x and we recognized that after installing a new UPI 4.7 Cluster  that the branding of the Web-Console has changed.

![grafik](https://user-images.githubusercontent.com/77630137/109969450-34861900-7cf4-11eb-96a4-cca15ed05a9d.png)

![grafik](https://user-images.githubusercontent.com/77630137/109969595-61d2c700-7cf4-11eb-97e8-3ed2c2862aef.png)

In all Versions before 4.7 Logos etc. were branded with "okd" and now it comes with "RedHat OpenShift Container Platform" as long as an activated "Insights" Operator which should be exclusively related to OpenShift if I am right?

Looking at the OpenShift Version, it says: "OpenShift version: 4.7.0-0.okd-2021-02-25-144700", so generally we should be on the right track...

So is this intended or another kind of downstream bug?

Best regards

**Comment by vrutkovs** [comment]
Right, that was resolved in https://amd64.origin.releases.ci.openshift.org/releasetag/4.7.0-0.okd-2021-03-02-232606.

>"Insights" Operator which should be exclusively related to OpenShift if I am right?

Insights operator works in OKD too, as long as user has pull secret with redhat.io entry

**Comment by devzeronull** [comment]
Alright, thank you for the quick response and clarification!

Can we expect any other impact when it will be rebranded with the next stable release?

**Comment by vrutkovs** [comment]
I'll file a tracking issue for that

**Comment by devzeronull** [comment]
With the current Version (4.7.0-0.okd-2021-03-07-090821) this issue has been resolved - thanks to the Team!

![grafik](https://user-images.githubusercontent.com/77630137/110470720-7ee40d00-80db-11eb-91a7-28ab92c59989.png)
