### ISSUE TITLE
[Baremetal IPI] Docs reference "Fedora 8" in baremetal IPI prereqs

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/okd#542]
Minor docs bug that will nonetheless probably confuse people: The baremetal IPI docs make reference to "Fedora 8.x" and "Fedora 8" throughout. This is probably because the docs are swapping out references to "RHEL" with "Fedora" too naively.

https://docs.okd.io/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html

**Comment by mburke5678** [comment]
@SriRamanujam @vrutkovs I have changed the `Fedora 8.x` and `Fedora 8` references to ` Fedora CoreOS (FCOS)` or `FCOS` as appropriate. See https://github.com/openshift/openshift-docs/pull/32263

**Comment by mburke5678** [comment]
PR is merged.
