### ISSUE TITLE
[OKD4.7] [mac] Creating cluster on AWS failing at connecting to API step 

### ISSUE THREAD

**Issue by mahmoudajawad** [openshift/okd#543]
**Describe the bug**
Using release `4.7.0-0.okd-2021-02-25-144700`, I tried to create a cluster on AWS three times and it is always failing at connecting to API step:
```
? SSH Public Key  [Use arrows to move, enter to select, type to filter, ? for mo? SSH Public Key  [Use arrows to move, enter to select, type to filter, ? for mo? SSH Public Key /path/to/key
? Platform  [Use arrows to move, enter to select, type to filter, ? for more hel? Platform aws
INFO Credentials loaded from the "default" profile in file "/path/to/credentials" 
? Region REGION-CODE
? Base Domain  [Use arrows to move, enter to select, type to filter, ? for more ? Base Domain  [Use arrows to move, enter to select, type to filter, ? for more ? Base Domain DOMAIN
? Cluster Name CLUSTER
? Pull Secret [? for help] **********************************
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s for the Kubernetes API at https://api.CLUSTER.DOMAIN:6443... 
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.CLUSTER.DOMAIN:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp IP:6443: connect: connection refused 
INFO Pulling debug logs from the bootstrap machine 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client: failed to use pre-existing agent, make sure the appropriate keys exist in the agent for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://api.CLUSTER.DOMAIN:6443/version?timeout=32s": dial tcp IP:6443: connect: connection refused 
```

**Version**
I used the release: https://github.com/openshift/okd/releases/tag/4.7.0-0.okd-2021-02-25-144700

**How reproducible**
I hit this issue running `openshift-installer create cluster` three times. After using release https://github.com/openshift/okd/releases/tag/4.6.0-0.okd-2021-02-14-205305 I didn't get the issue.

**Log bundle**
Can't provide `adm must-gather` output as no cluster is being created.

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

**Comment by mahmoudajawad** [comment]
@vrutkovs, so, I deleted 4.7 release and I'm using 4.6 release now. How can I make sure I'm providing the correct logs?

**Comment by vrutkovs** [comment]
In order to fix the issue we need to make sure its happening in 4.7. 4.6-specific issues won't get a lot of attention as OKD is a rolling distro

**Comment by mahmoudajawad** [comment]
Closing as not using v4.7 anymore.
