### ISSUE TITLE
[OKD45][vSphere][UPI] Pod is not able to attach Persistent Volume.

### ISSUE THREAD

**Issue by gunjangarge** [openshift/okd#546]
**Describe the bug**

Pod is not able to attach Persistent Volume. PVC is bound to PV as expected.

**Version**

4.5.0-0.okd-2020-10-15-235428

UPI - vSphere - Restricted environment.

**How reproducible**

100%

**Log bundle**

Pod 'describe' output:
```
  Warning  FailedAttachVolume  4m17s (x25 over 4m22s)  attachdetach-controller  AttachVolume.Attach failed for volume "pv-40gb-1" : ServerFaultCode: Permission to perform this operation was denied.
  Warning  FailedMount         107s                    kubelet                  Unable to attach or mount volumes: unmounted volumes=[sample], unattached volumes=[sample default-token-vs2t5]: timed out waiting for the condition
```

Kube manager logs:
```
I0303 09:19:01.473446       1 reconciler.go:275] attacherDetacher.AttachVolume started for volume "pv-40gb-1" (UniqueName: "kubernetes.io/vsphere-volume/[DISK_01] persistentvolumes/pv-40gb/pv-40gb-1") from node "worker03"
E0303 09:19:01.491969       1 datacenter.go:74] Failed to find VM by UUID. VM UUID: 422d8cdb-1c8f-a664-cf85-046d2460ca73, err: ServerFaultCode: Permission to perform this operation was denied.
E0303 09:19:01.492014       1 nodemanager.go:297] Error "ServerFaultCode: Permission to perform this operation was denied." node info for node "worker03" not found
E0303 09:19:01.492029       1 vsphere.go:609] Cannot find node "worker03" in cache. Node not found!!!
E0303 09:19:01.492050       1 attacher.go:93] Error attaching volume "[DISK_01] persistentvolumes/pv-40gb/pv-40gb-1" to node "worker03": ServerFaultCode: Permission to perform this operation was denied.

```

Error log mentions permission denied but okdadmin@vpshere.local user has all required permissions as per https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html#static-provisioning and user is member of Read-Only group.

Are there any additional permissions required?

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive.

Is it reproducible in OKD 4.7?

**Comment by gunjangarge** [comment]
@vrutkovs, Is there any specific file/folder I should attach.
Unfortunately, I may have to go through it and redact customer-specific information before upload.

**Comment by vrutkovs** [comment]
>Is there any specific file/folder I should attach.

we need all of it.

> I may have to go through it and redact customer-specific information 

Sorry, I won't be looking at that then - I can't be sure all names have been changed and the log bundle won't make sense to me

**Comment by gunjangarge** [comment]
We can close this issue, as the customer will not allow sharing the entire file as-is.
