### ISSUE TITLE
Ability to create small non-reselient cluster

### ISSUE THREAD

**Issue by jimmyjones2** [openshift/okd#55]
It'd be useful to be able to create a small non-reselient cluster (eg. 1x master, 1x infra, 2x workers) that could fit in VMs on a laptop (<16GB). Appreciate I could use CRC, but that's not entirely representative of a real cluster. Without this I'd need a fair amount of kit, or a fairly large (for personal or research use) AWS bill - could this feature bring OKD to more people?

I think in the old days of 3.11 you could do something like this, from memory you even put master and infra on the same VM. Anyone else interested, or maybe this is just something I'd like :)

**Comment by vrutkovs** [comment]
Out of scope for OKD project. OKD has to have all OCP features - one of the most important ones would be upgrades. With OTA nature of upgrades it cannot be archieved with one master.

However a number of masters and workers can edited in install-config - so if you voluntarily give up on updates (and probably by tweaking operators to use less resources) pods can fit on one master + 1 or 2 workers.

**Comment by LorbusChris** [comment]
What @vrutkovs said. My apologies if this is not a satisfactory answer, but this is out of scope for OKD and needs architectural directives. Note that a 1x master setup (i.e. just 1x etcd) can and will never achieve a real representation of a real cluster. Nonetheless, I'd advise to keep an eye open for OpenShift (and CRC) Roadmap updates.

**Comment by jimmyjones2** [comment]
Thanks @vrutkovs @LorbusChris 

I'll see if I can hack install-config and post a little guide if it works.
