### ISSUE TITLE
Kubernetes API: Service Unavailable

### ISSUE THREAD

**Issue by vladuhul** [openshift/okd#553]
Please help me.
If you need further information, let me know.

**Describe the bug**
Kubernetes Api is never coming up.

```
#openshift-install --dir=installdir/ wait-for bootstrap-complete --log-level=debug

DEBUG OpenShift Installer 4.6.0-0.okd-2021-01-23-132511
DEBUG Built from commit 6f79a4c4279ce2b56a522d98ae1ea6fef2e02e9b
INFO Waiting up to 20m0s for the Kubernetes API at https://api.ocp.okd.local:6443...
DEBUG Still waiting for the Kubernetes API: Get "https://api.ocp.okd.local:6443/version?timeout=32s": Service Unavailable
DEBUG Still waiting for the Kubernetes API: Get "https://api.ocp.okd.local:6443/version?timeout=32s": Service Unavailable
DEBUG Still waiting for the Kubernetes API: Get "https://api.ocp.okd.local:6443/version?timeout=32s": Service Unavailable

```

**Version**

UPI install on vSphere Client version 6.7.0.45000

OKD version release:
openshift-install-linux-4.6.0-0.okd-2021-01-23-132511
fedora-coreos-33.20210104.20.0

**How reproducible**

Every time I try to install OKD. I tried different versions of Fedora coreos and openshift-install. Same thing.

**Log bundle**

Updated with 4.7 logs.

**Comment by vrutkovs** [comment]
Is it reproducible on OKD 4.7?

**Comment by vladuhul** [comment]
Yes it is reproducible. That s why I've tried an older version, to see if it works. Should I try again with 4.7 and collect logs?

**Comment by vrutkovs** [comment]
Yup. In order to fix it we need to land a fix in 4.8, then 4.7 and then 4.6 in the worst case

**Comment by vladuhul** [comment]
I've tried to collect logs but it doesn't do that. It just hangs indefinitely without giving a result. As far as I see, the problem is replicated. Any idea on how to collect logs?
```
#openshift-install gather bootstrap --dir=dirinstall/ --bootstrap bootstrap --master master-1
INFO Pulling debug logs from the bootstrap machine

```

**Comment by kai-uwe-rommel** [comment]
> 
> 
> I've tried to collect logs but it doesn't do that. It just hangs indefinitely without giving a result. As far as I've seen from the output of `journalctl -b -f -u release-image.service -u bootkube.service`, the problem is replicated. Any idea on how to collect logs? Thank you.
> 
> ```
> #openshift-install gather bootstrap --dir=dirinstall/ --bootstrap bootstrap --master master-1
> INFO Pulling debug logs from the bootstrap machine
> ```

I recently made the same experience for another issue. The "openshift-install gather bootstrap" currently seems to be broken. Someone should open an issue for this ...

**Comment by vrutkovs** [comment]
See #552

**Comment by vladuhul** [comment]
@kai-uwe-rommel  I confirm that using #552 indicated by @vrutkovs works. Thank you.

Here are the logs.
[log-bundle-20210312152408.tar.gz](https://github.com/openshift/okd/files/6130282/log-bundle-20210312152408.tar.gz)

**Comment by vladuhul** [comment]
Any information regarding this issue please? What's causing it? so I can debug on my own if I can.

**Comment by vrutkovs** [comment]
>bootkube.sh[50483]: bootkube.service complete

Your bootstrap is complete, seems the machine you're running installer can't contact bootstrap node?

**Comment by vladuhul** [comment]
Ping works, ssh to bootstrap node works. As far as I know the machine should connect to the haproxy than it will be redirected to bootstrap. I'm confused about your question. Can you please tell me what are you are referring to?

haproxy.cfg
```

# Global settings
#---------------------------------------------------------------------
global
    maxconn     20000
    log         /dev/log local0 info
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
#    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          300s
    timeout server          300s
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 20000

listen stats
    bind :9000
    mode http
    stats enable
    stats uri /

frontend okd_k8s_api_fe
    bind :6443
    default_backend okd_k8s_api_be
    mode tcp
    option tcplog

backend okd_k8s_api_be
    balance source
    mode tcp
    server      bootstrap 192.168.164.50:6443 check
    server      master-1 192.168.164.51:6443 check
    server      master-2 192.168.164.52:6443 check
    server      master-3 192.168.164.53:6443 check

frontend okd_machine_config_server_fe
    bind :22623
    default_backend okd_machine_config_server_be
    mode tcp
    option tcplog

backend okd_machine_config_server_be
    balance source
    mode tcp
    server      bootstrap 192.168.164.50:22623 check
    server      master-1 192.168.164.51:22623 check
    server      master-2 192.168.164.52:22623 check
    server      master-3 192.168.164.53:22623 check

frontend okd_http_ingress_traffic_fe
    bind :80
    default_backend okd_http_ingress_traffic_be
    mode tcp
    option tcplog

backend okd_http_ingress_traffic_be
    balance source
    mode tcp
    server      worker-1 192.168.164.61:80 check
    server      worker-2 192.168.164.62:80 check
    server      worker-3 192.168.164.63:80 check

frontend okd_https_ingress_traffic_fe
    bind *:443
    default_backend okd_https_ingress_traffic_be
    mode tcp
    option tcplog

backend okd_https_ingress_traffic_be
    balance source
    mode tcp
    server      worker-1 192.168.164.61:443 check
    server      worker-2 192.168.164.62:443 check
    server      worker-3 192.168.164.63:443 check

frontend ocp_etcd
    bind :2379
    default_backend ocp_etcd
    mode tcp
    option tcplog

backend ocp_etcd
    balance source
    mode tcp
    server      bootstrap 192.168.164.50:2379 check
    server      master-1 192.168.164.51:2379 check
    server      master-2 192.168.164.52:2379 check
    server      master-3 192.168.164.53:2379 check
```

**Comment by vrutkovs** [comment]
`wait-for bootstrap-complete` connects to bootstrap's API server and waits for event to appear. Seems the API is running on the node, but the machine where installer runs can't connect to 6443 port there.

I see you're using a proxy, so it might have been misconfigured - does it work without a proxy setup?

**Comment by vladuhul** [comment]
I am using cntlm as a proxy; this is where I set a variable `NoProxy         localhost, 127.0.0.*, 10.*, 192.168.*`. Now, I set the 
 ` no_proxy=okd.local,192.168.164.0/24 ` as an environment variable on the machine where i'm running the installer, rather than puting it in the `cntlm.conf`. Will get back to you to see if it works. Thank you.

**Comment by vladuhul** [comment]
@vrutkovs Thank you, everything is up and running.

**Comment by vladuhul** [comment]
First of all, sorry i accidentally pressed the "Close with comment" button.
Second of all, regarding the OKD4.7 installation, please give me your take on the process. Here is the log bundle.


[log-bundle-20210316231321.tar.gz](https://github.com/openshift/okd/files/6155041/log-bundle-20210316231321.tar.gz)

**Comment by vrutkovs** [comment]
That still uses a proxy. Does it work without it? My best guess is that `noProxy` is wrong

**Comment by vrutkovs** [comment]
FWIW [proxy test](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1372114364814856192) passed for this release.

Here's what we have in proxy settings:
```
status:
  httpProxy: http://ewolinet:5f6ccbbbafc66013d012839921ada773@35.196.128.173:3128/
  httpsProxy: http://ewolinet:5f6ccbbbafc66013d012839921ada773@35.196.128.173:3128/
  noProxy: .cluster.local,.svc,10.0.0.0/16,10.128.0.0/14,127.0.0.1,169.254.169.254,172.30.0.0/16,api-int.ci-ln-4xwylzt-f76d1.origin-ci-int-gce.dev.openshift.com,localhost,metadata,metadata.google.internal,metadata.google.internal.
```

**Comment by vladuhul** [comment]
> 
> 
> 
> Here's what we have in proxy settings:
> 
> ```
> status:
>   httpProxy: http://ewolinet:5f6ccbbbafc66013d012839921ada773@35.196.128.173:3128/
>   httpsProxy: http://ewolinet:5f6ccbbbafc66013d012839921ada773@35.196.128.173:3128/
>   noProxy: .cluster.local,.svc,10.0.0.0/16,10.128.0.0/14,127.0.0.1,169.254.169.254,172.30.0.0/16,api-int.ci-ln-4xwylzt-f76d1.origin-ci-int-gce.dev.openshift.com,localhost,metadata,metadata.google.internal,metadata.google.internal.
> ```

I added ` *.local ` to the variable  ` NoProxy `  in  ` cntlm.conf  `. The installation seems to be successful. Please take a look at the log-bundle. There were so many error messages. 

The answer for the initial problem (API: service unavailable) was to set an environment variable ` no_proxy=okd.local, 192.168.164.0/24 `, in the machine's OS where I was performing the installation.  After this, the variable in `cntlm.conf` was also set to the aforementioned value.

Please take a look at the log-bundle. There were so many error messages. Thank you for your support.


[log-bundle-20210318111645.tar.gz](https://github.com/openshift/okd/files/6164737/log-bundle-20210318111645.tar.gz)

**Comment by vladuhul** [comment]
I edited correctly the proxy and no proxy variables in the install-config.yaml file. It works. Thank you.
