### ISSUE TITLE
Upgrade to 4.7.0-0.okd-2021-03-07-090821 not available from 4.6.0-0.okd-2021-01-23-132511

### ISSUE THREAD

**Issue by bdurrow** [openshift/okd#558]
https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.7.0-0.okd-2021-03-07-090821 indicates that it upgrades from 4.6.0-0.okd-2021-01-23-132511 but it is not available as an upgrade from the console.

**Comment by vrutkovs** [comment]
![Screenshot-20210315100933-604x310](https://user-images.githubusercontent.com/114501/111129610-935e5480-8576-11eb-89e9-bce67713f010.png)
Make sure you have `stable-4` channel selected

**Comment by bdurrow** [comment]
I am not sure what is different about your test and my two clusters.  My ClusterVersion spec.upstream: 'https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/graph'

<img width="693" alt="Screen Shot 2021-03-16 at 5 17 42 PM" src="https://user-images.githubusercontent.com/437291/111392364-07365500-867c-11eb-8cfd-faea4ce1cd6d.png">
<img width="514" alt="Screen Shot 2021-03-16 at 5 17 11 PM" src="https://user-images.githubusercontent.com/437291/111392371-0ac9dc00-867c-11eb-96f7-1529e69e175d.png">

As far as I can tell from the UI okd does not have a `stable-4` channel, I have `stable-4.6` selected:
<img width="509" alt="Screen Shot 2021-03-16 at 5 22 24 PM" src="https://user-images.githubusercontent.com/437291/111392506-567c8580-867c-11eb-9ae4-9d2fb455cf57.png">

**Comment by vrutkovs** [comment]
Wrong channel - in OKD we have `stable-4` only. Unfortunately, channels are hardcoded in console now, so please avoid using UI to select it.

You can switch back by `oc edit clusterversion`, change `spec.channel` to `stable-4`

**Comment by bdurrow** [comment]
Thanks, that did it.  Is there a ticket about the hard coded channels?  I don't even see mention of it in the documentation as a caveat to look out for.

**Comment by bdurrow** [comment]
@vrutkovs, https://github.com/openshift/enhancements/pull/531 has been closed without merge but selecting the channel from the UI is still handled poorly (see attached screenshot).  There is no longer a drop down with choices that cause a problem but now there is a text input with text suggesting incorrect (at least as you have previously indicated) values.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/437291/154993082-92ca3436-86c6-43be-a2d3-274e23c01983.png">

**Comment by vrutkovs** [comment]
Right, lets reopen this and we'll contact folks from console for instructions
