### ISSUE TITLE
Configuring GitHub Idp from UI does not work

### ISSUE THREAD

**Issue by gtema** [openshift/okd#56]
When trying to add github Idp from UI (4.4.0-0.okd-2020-01-28-022517) and entering clientId, clientSecret and org name or teams I get following error:
```
Error "Invalid value: v1.ConfigMapNameReference{Name:"ca-name"}: cannot be specified when hostname is empty" for field "spec.identityProviders[0].github.ca".
```

Using cli and steps described in https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-github-identity-provider.html - works

**Comment by vrutkovs** [comment]
Docs state that `ca` needs to be set when Github Enterprise is used only:
```
Only for use in GitHub Enterprise with a non-publicly trusted root certificate.
```
So I assume you were using console to set it up and it failed, correct?

**Comment by gtema** [comment]
Right, the URL was not set an ca was even disabled, but got the warning

**Comment by vrutkovs** [comment]
Right, thanks. I think its safe to me moved to https://github.com/openshift/console then
