### ISSUE TITLE
Upgrading from 4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-03-07-090821 failed

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#560]
**Describe the bug**
After upgrading from version 4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-03-07-090821 some cluster operators stuck in degraded state:
```
oc get co
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.7.0-0.okd-2021-03-07-090821   False       True          True       49m
console                                    4.7.0-0.okd-2021-03-07-090821   True        False         True       54m
ingress                                    4.7.0-0.okd-2021-03-07-090821   True        False         True       53d

oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.0-0.okd-2021-02-14-205305   True        True          158m    Working towards 4.7.0-0.okd-2021-03-07-090821: 507 of 669 done (75% complete)

```

**Version**
from 4.6.0-0.okd-2021-02-14-205305 to 4.7.0-0.okd-2021-03-07-090821

**Log bundle**
https://drive.google.com/file/d/16vQyN-4-HZAV4G93tVfemWDrWnDC2YDE/view?usp=sharing

**Comment by alexanderniebuhr** [comment]
are they stuck with same as #559, we might found another one than

**Comment by myg0v** [comment]
I think the reason is different, maybe there is some issue with the proxy configuration?

oc get co authentication -o json | jq -r '.status.conditions[] | select(.type == "Degraded")'
{
  "lastTransitionTime": "2021-03-15T09:03:20Z",
  "message": "OAuthRouteCheckEndpointAccessibleControllerDegraded: Get \"https://oauth-openshift.apps.okd.basedomain.com/healthz\": read tcp 10.200.8.14:50772->10.1.232.248:443: read: connection reset by peer\nProxyConfigControllerDegraded: endpoint(\"https://oauth-openshift.apps.okd.basedomain.com/healthz\") found in NO_PROXY(\".cluster.local,.svc,10.0.0.0/16,10.1.232.0/24,10.200.0.0/16,127.0.0.0/8,127.0.0.1,172.30.0.0/16,::1/128,admin.***.de,api-int.okd.basedomain.com,***.de,***.net,itp.***.net,localhost,okd.basedomain.com\") is unreachable with proxy(Get \"https://oauth-openshift.apps.okd.basedomain.com/healthz\": EOF) and without proxy(Get \"https://oauth-openshift.apps.okd.basedomain.com/healthz\": read tcp 10.200.8.14:50548->10.1.232.248:443: read: connection reset by peer)",
  "reason": "OAuthRouteCheckEndpointAccessibleController_SyncError::ProxyConfigController_SyncError",
  "status": "True",
  "type": "Degraded"
}

**Comment by myg0v** [comment]
After restarting the router-default* pods (oc -n openshift-ingress delete pod router-default-74b7577d56-5pqpc router-default-74b7577d56-dgj9k) and restarting some nodes the issue seems to be resolved for now. The upgrade is now complete

`
oc get clusterversion                              
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.0-0.okd-2021-03-07-090821   True        False         2m23s   Cluster version is 4.7.0-0.okd-2021-03-07-090821

NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.7.0-0.okd-2021-03-07-090821   True        False         False      6m28s
baremetal                                  4.7.0-0.okd-2021-03-07-090821   True        False         False      3h33m
cloud-credential                           4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
cluster-autoscaler                         4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
config-operator                            4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
console                                    4.7.0-0.okd-2021-03-07-090821   True        False         False      6m26s
csi-snapshot-controller                    4.7.0-0.okd-2021-03-07-090821   True        False         False      164m
dns                                        4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
etcd                                       4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
image-registry                             4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
ingress                                    4.7.0-0.okd-2021-03-07-090821   True        False         False      6m43s
insights                                   4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
kube-apiserver                             4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
kube-controller-manager                    4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
kube-scheduler                             4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
kube-storage-version-migrator              4.7.0-0.okd-2021-03-07-090821   True        False         False      66m
machine-api                                4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
machine-approver                           4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
machine-config                             4.7.0-0.okd-2021-03-07-090821   True        False         False      152m
marketplace                                4.7.0-0.okd-2021-03-07-090821   True        False         False      17m
monitoring                                 4.7.0-0.okd-2021-03-07-090821   True        False         False      17m
network                                    4.7.0-0.okd-2021-03-07-090821   True        False         False      3h11m
node-tuning                                4.7.0-0.okd-2021-03-07-090821   True        False         False      3h31m
openshift-apiserver                        4.7.0-0.okd-2021-03-07-090821   True        False         False      9m40s
openshift-controller-manager               4.7.0-0.okd-2021-03-07-090821   True        False         False      3h30m
openshift-samples                          4.7.0-0.okd-2021-03-07-090821   True        False         False      3h31m
operator-lifecycle-manager                 4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
operator-lifecycle-manager-catalog         4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
operator-lifecycle-manager-packageserver   4.7.0-0.okd-2021-03-07-090821   True        False         False      10m
service-ca                                 4.7.0-0.okd-2021-03-07-090821   True        False         False      53d
storage                                    4.7.0-0.okd-2021-03-07-090821   True        False         False      53d

`
