### ISSUE TITLE
machine-api-termination-handler terminates aws spot-instances

### ISSUE THREAD

**Issue by alexanderniebuhr** [openshift/okd#561]
**Describe the bug**

new health check for aws spot-instances loops through generation of machine generation. machine will not be ready in 10m, so they get killed.. 

**Version**

4.7

**How reproducible**

**Log bundle**

https://drive.google.com/file/d/1lS2Eq9LlKuCBieNk1PVR6fVNDT7xoLhL/view?usp=sharing

**Comment by alexanderniebuhr** [comment]
reference https://bugzilla.redhat.com/show_bug.cgi?id=1939054
it happens on first boot of nodes

**Comment by alexanderniebuhr** [comment]
changed aws base ami image from coreos 32 to 33.. seems to resolve it.. still waiting for our disaster tests

**Comment by vrutkovs** [comment]
Tracked in bugzilla now
