### ISSUE TITLE
 Topology page loads white screen in webConsole 4.7.0-0.okd-2021-03-07-090821

### ISSUE THREAD

**Issue by klzsysy** [openshift/okd#568]
**Describe the bug**
In webConsole view of the developers ，topology page load white screen，all the namespace is the same problem，but Other page is normal

![image](https://user-images.githubusercontent.com/3226923/111721927-cfa5f380-889b-11eb-9bff-5a3610830cf9.png)

![image](https://user-images.githubusercontent.com/3226923/111721627-48588000-889b-11eb-9a9a-ea4f3d81bf31.png)

**Version**

4.7.0-0.okd-2021-03-07-090821
Vsphere UPI

**How reproducible**

100%

**Comment by vrutkovs** [comment]
Not OKD specific, please file a bugzilla for OCP, Component - console
