### ISSUE TITLE
[OKD4.7] Web-UI broken on "Create PersistentVolumeClaim"

### ISSUE THREAD

**Issue by devzeronull** [openshift/okd#573]
Hi,

we experenced an error on the Web-UI in 4.7.0-0.okd-2021-03-21-094146 Release (bare-metal UPI).
When we click in Administrator View on "PersistentVolumeClaims" -> "Create PersistentVolumeClaim" (URL: https://console-openshift-console.apps.clustername.basedomain/k8s/ns/default/persistentvolumeclaims/~new/form") 
![grafik](https://user-images.githubusercontent.com/77630137/112304265-93a8cf00-8c9d-11eb-9a39-5649c8183751.png)

the page gets loaded and after a  short flickering showing the Forms content for a millisecond it stays completely empty - like beimg overlayed with a white page or the page content blended out:
![grafik](https://user-images.githubusercontent.com/77630137/112304481-d23e8980-8c9d-11eb-88e7-48dc5b2b8b4f.png)

In 4.6 it would look like this:
![grafik](https://user-images.githubusercontent.com/77630137/112304666-0ade6300-8c9e-11eb-85c9-b0f1e9ffe446.png)

When looking at the pages source code it seems to be loaded having the following JavaScript-error:
![grafik](https://user-images.githubusercontent.com/77630137/112304828-3e20f200-8c9e-11eb-964d-180bef43192a.png)

> **TypeError: can't convert undefined to object**
>     d create-pvc-chunk-e6298432dd020e2cd449.min.js:1
>     k create-pvc-chunk-e6298432dd020e2cd449.min.js:1
>     Ia vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Ws vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     unstable_runWithPriority vendors~main-chunk-3652a4e54bce917198bc.min.js:166497
>     li vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Ws vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Fs vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Ps vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     hi vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     unstable_runWithPriority vendors~main-chunk-3652a4e54bce917198bc.min.js:166497
>     li vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     hi vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     di vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Is vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     notify vendors~main-chunk-3652a4e54bce917198bc.min.js:39200
>     notifyNestedSubs vendors~main-chunk-3652a4e54bce917198bc.min.js:39200
>     notifySubscribers vendors~main-chunk-3652a4e54bce917198bc.min.js:109462
>     handleChangeWrapper vendors~main-chunk-3652a4e54bce917198bc.min.js:39200
>     v vendors~main-chunk-3652a4e54bce917198bc.min.js:24762
>     b main-chunk-0e0280b47986f6ccc022.min.js:1
>     dispatch vendors~main-chunk-3652a4e54bce917198bc.min.js:24762
>     s main-chunk-0e0280b47986f6ccc022.min.js:1
>     s main-chunk-0e0280b47986f6ccc022.min.js:1
>     i main-chunk-0e0280b47986f6ccc022.min.js:1
> vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
> **stopped watching storage.k8s.io~v1~StorageClass before finishing incremental loading with error TypeError: can't convert undefined to object! main-chunk-0e0280b47986f6ccc022.min.js:1**

It is reproduceable in 4.7, but not in 4.6 and seems like it could be related to the templating/branding issue on the first 4.7 Release...

Can you confirm that?

Best regards

**Comment by vrutkovs** [comment]
Console bugs should go directly to OCP bugzilla, as OKD doesn't modify the console

**Comment by nate-duke** [comment]
Is there a github project tracking the console where folks that can't use the Redhat Bugzilla can report issues?

**Comment by devzeronull** [comment]
Thanks for the hint, but as nate-duke said, how can Origin people report it?

**Comment by devzeronull** [comment]
Btw. this might be related to:

#568 
#538

**Comment by vrutkovs** [comment]
>Is there a github project tracking the console where folks that can't use the Redhat Bugzilla can report issues?

Yes, https://github.com/openshift/console (although I don't understand why bugzilla can't be used)

**Comment by devzeronull** [comment]
Thanks, reported it there:
https://github.com/openshift/console/issues/8452
