### ISSUE TITLE
[4.7][installer] Reapply 30-local-dns-prepender fix for 4.7

### ISSUE THREAD

**Issue by fortinj66** [openshift/okd#579]
It looks like https://github.com/openshift/installer/pull/4654 was reverted for 4.7 releases after **4.7.0-0.okd-2021-03-21-094146**

It (or the equivalent) needs to be reapplied so that bootstrap finished successfully.

**Comment by vrutkovs** [comment]
Fixed in https://github.com/vrutkovs/installer/commit/c959bf7d9e292e959bfd6d0c66d0184887ba02dd, landed in https://amd64.origin.releases.ci.openshift.org/releasestream/4.7.0-0.okd/release/4.7.0-0.okd-2021-04-06-125404

Could you give that one a try (vsphere CI seems happy with it)

**Comment by fortinj66** [comment]
New install looks good with the updated installer in https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.7.0-0.okd/release/4.7.0-0.okd-2021-04-06-164431
