### ISSUE TITLE
OKD4.6 bootkube,kubelet,crio doesn't start on bootstrap - /usr/bin/hyperkube missing

### ISSUE THREAD

**Issue by 94DanielBrown** [openshift/okd#580]
**Describe the bug**
Services on bootstrap node are not coming up seems like it is not pulling whatever it needs.

**Version**
vSphere UPI
I am using latest 4.6 release 4.6.0-0.okd-2021-02-14-205305
I have also tried and got the same issue with:
4.6.0-0.okd-2021-01-23-132511
4.6.0-0.okd-2020-11-27-200126
Weirdly I have deployed the last version before successfully with the same code many times..
I have also tried different versions of fedora coreos

**How reproducible**
100%

**Log bundle**
Can't get log bundle as control nodes can't get there config due to bootstrap node not working and therefore have no SSH key-to be accessed with. I have got the bootkube, kubelet and crio logs off of the bootstrap node. 
[bootkube.log](https://github.com/openshift/okd/files/6242625/bootkube.log)
[kubelet.log](https://github.com/openshift/okd/files/6242626/kubelet.log)
[crio.log](https://github.com/openshift/okd/files/6242627/crio.log)

**Comment by vrutkovs** [comment]
>I have also tried different versions of fedora coreos

Have you tried 20210217 to work around #566?

**Comment by 94DanielBrown** [comment]
I hadn't seen that bug and hadn't tried that specific coreos version, it has fixed the problem with the bootstrap node. 
However the API on the control nodes isn't coming up...
I can see that there are no pods running on the control nodes but the crio service is running

```core@ldokc001 ~]$ crictl ps
FATA[0000] listing containers failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable   
[core@ldokc001 ~]$ sudo su  
[root@ldokc001 core]# crictl ps  
FATA[0000] listing containers failed: unsupported output format ""   
[root@ldokc001 core]# crictl ps --output=table  
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT```

I have attached log bundle
[log-bundle-20210401122419.tar.gz](https://github.com/openshift/okd/files/6243225/log-bundle-20210401122419.tar.gz)

**Comment by vrutkovs** [comment]
>Weirdly I have deployed the last version before successfully with the same code many times..

Which "last" version do you mean - 4.7?

**Comment by 94DanielBrown** [comment]
Nope I meant the last 4.6 version I mentioned - 4.6.0-0.okd-2020-11-27-200126
I have only tried the latest 4.6 - 4.6.0-0.okd-2021-02-14-205305 with the 20210217 coreos

**Comment by vrutkovs** [comment]
Okay, is it reproducible with 4.7 payload?

**Comment by 94DanielBrown** [comment]
I get 'innapropriate ioctl for device error' with 4.7, I have tried all versions.
I think is must be because I am including static networking configuration in the ignition files to and I guess the 4.7 installer uses a later version of ignition or something which is causing problems for whatever reason, I will have to resolve this first before I can test with 4.7..

**Comment by 94DanielBrown** [comment]
I sorted out the ignition problem..
Pleased to report I have cluster up and running with 4.7.0-0.okd-2021-03-28-152009 and the 20210217 fcos, no problems.
