### ISSUE TITLE
Unable to install latest okdv4 on AWS

### ISSUE THREAD

**Issue by GaborVarga** [openshift/okd#581]
**Describe the bug**
Unable to install okdv4 on AWS with 1 master and 2 worker nodes

**Version**
openshift-install-mac-4.7.0-0.okd-2021-03-28-152009.tar.gz

**How reproducible**
Tried 3 times. 
I created a new domain in Route 53, the process created the required public hosted zone for me. Then I created the install file, changed the number of masters and workers and started the installation according to the docs.

**Log bundle**
INFO Waiting up to 20m0s for the Kubernetes API at https://api.mydomain-openshift-cluster.mydomain.net:6443... 
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.mydomain-openshift-cluster.mydomain.net:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 46.137.149.119:6443: connect: connection refused 
INFO Pulling debug logs from the bootstrap machine 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client: failed to use pre-existing agent, make sure the appropriate keys exist in the agent for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://api.mydomain-openshift-cluster.mydomain.net:6443/version?timeout=32s": dial tcp 46.137.149.119:6443: connect: connection refused 

I created the SSH keys as well, but for some reason the ssh connection failed as well. I wonder what 46.137.149.119 could be as the bootstrap machine had a different public IP.

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

**Comment by GaborVarga** [comment]
Here it is.
[log-bundle-20210407133314.tar.gz](https://github.com/openshift/okd/files/6271245/log-bundle-20210407133314.tar.gz)

**Comment by vrutkovs** [comment]
Mismatching installer used:
```
$ oc adm release info quay.io/openshift/okd:4.7.0-0.okd-2021-03-28-152009 --commits | grep installer
  baremetal-installer                            https://github.com/vrutkovs/installer                                       cf35dc04aedf7a80bea5470358025cbe91d232c9
  installer                                      https://github.com/vrutkovs/installer                                       cf35dc04aedf7a80bea5470358025cbe91d232c9
  installer-artifacts                            https://github.com/vrutkovs/installer                                       cf35dc04aedf7a80bea5470358025cbe91d232c9
```
is the commit we want, but it was generated by `unreleased-master-3671-g2ef2b7e490e63e5a8afff6c98fe12505540c2114-dirty` - https://github.com/vrutkovs/installer/commits/2ef2b7e490e63e5a8afff6c98fe12505540c2114 - something from 4.6 era?

**Comment by GaborVarga** [comment]
Which installer shall I use?

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd/releases/tag/4.7.0-0.okd-2021-03-28-152009

or extract it from the payload:
```
$ oc adm release extract --command='openshift-installer'  quay.io/openshift/okd:4.7.0-0.okd-2021-03-28-152009
```

**Comment by GaborVarga** [comment]
[log-bundle-20210408154357.tar.gz](https://github.com/openshift/okd/files/6279340/log-bundle-20210408154357.tar.gz)

Tried again with the latest installer, failed again.
