### ISSUE TITLE
Disaster recovery on OVN stuck at 'failed to get annotations'

### ISSUE THREAD

**Issue by maartenq** [openshift/okd#586]
**Describe the bug**

- Default installation on AWS https://docs.okd.io/latest/installing/installing_aws/installing-aws-default.html
- Created a project and within it 2 sample applications (python django/ nginx)
- Created a backup following https://docs.openshift.com/container-platform/4.7/backup_and_restore/backing-up-etcd.html
- Delete the 2 sample apps
- followed https://docs.openshift.com/container-platform/4.7/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html
-  At step 11 I don't seem to get  "all nodes at the latest revision"
```console
 $ oc get etcd -o=jsonpath='{range .items[0].status.conditions[?(@.type=="NodeInstallerProgressing")]}{.reason}{"\n"}{.message}{"\n"}'

 3 nodes are at revision 3; 0 nodes have achieved new revision 4
```

**Version**
4.7.0-0.okd-2021-03-28-152009 on AWS

**How reproducible**
100% (tried twice on clean installation)

**Log bundle**
https://nfdvmaoeikfjtviehegjfcb.s3-eu-west-1.amazonaws.com/must-gather.local.1084280979694287889.tar.gz

**Comment by vrutkovs** [comment]
etcd operator logs:
```
"ip-10-0-173-39.eu-west-1.compute.internal" is in transition to 4, but has not made progress because
```

but `installer-4-ip-10-0-173-39.eu-west-1.compute.internal` is in ContainerCreating:
```
containers with unready status: [installer]
```

kubelet logs:
```
Apr 07 18:27:06.081721 ip-10-0-173-39 hyperkube[379114]: E0407 18:27:06.081226  379114 kuberuntime_manager.go:767] createPodSandbox for pod "installer-4-ip-10-0-173-39.eu-west-1.compute.internal_openshift-etcd(44f9ba1c-1a01-41cf-9990-52912f090149)" failed: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_installer-4-ip-10-0-173-39.eu-west-1.compute.internal_openshift-etcd_44f9ba1c-1a01-41cf-9990-52912f090149_0(452bff968561e5c1997654c20e3a7fdff3d1325ee4f290b03c5366321a6d427c): [openshift-etcd/installer-4-ip-10-0-173-39.eu-west-1.compute.internal:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[openshift-etcd/installer-4-ip-10-0-173-39.eu-west-1.compute.internal 452bff968561e5c1997654c20e3a7fdff3d1325ee4f290b03c5366321a6d427c] [openshift-etcd/installer-4-ip-10-0-173-39.eu-west-1.compute.internal 452bff968561e5c1997654c20e3a7fdff3d1325ee4f290b03c5366321a6d427c] failed to get annotations: pod "installer-4-ip-10-0-173-39.eu-west-1.compute.internal" not found
```

Please file a bugzilla report, seems etcd restore from backup is broken with OVN

**Comment by hexfusion** [comment]
Hmm great catch @vrutkovs thanks! @marun as OVN touches hostNetwork seems very possible we are breaking some assumptions here on restore. High-level networking needs to own DR for its component, seem like that team should be able to implement an OVN specific version of your DR test in their repo to block regressions. This should be high/urgent bug for 4.8.

**Comment by marun** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1947705

**Comment by vrutkovs** [comment]
Not an OKD-specific issue, closing in favor of bugzilla
