### ISSUE TITLE
oc login error:EOF

### ISSUE THREAD

**Issue by rupang790** [openshift/okd#587]
**Describe the bug**

```error:EOF``` is occurred when I try to login to my cluster.
On each nodes ( 3 masters and bastion ) are also not able to login and show same error as ```error:EOF```.

**Version**

4.5.0-0.okd-2020-10-15-235428

**How reproducible**

100%

**Log bundle**

```
[root@mec-bastion1:/root] $ oc login -u admin -p .dlfndhs https://api.mec.tb.nia:6443 --certificate-authority=ingress-ca.crt --loglevel=10
I0408 01:28:30.035935  225273 loader.go:375] Config loaded from file:  /root/install_dir/auth/kubeconfig
I0408 01:28:30.036546  225273 round_trippers.go:423] curl -k -v -XHEAD  'https://api.mec.tb.nia:6443/'
I0408 01:28:30.038215  225273 round_trippers.go:443] HEAD https://api.mec.tb.nia:6443/  in 1 milliseconds
I0408 01:28:30.038239  225273 round_trippers.go:449] Response Headers:
F0408 01:28:30.038269  225273 helpers.go:115] error: EOF
```

To verify the cluster and update to OKD 4.6 version, I tried to login to my cluster by OKD Dashboard(console-openshift-console.) and could not see anything.
![image](https://user-images.githubusercontent.com/40801176/113955277-5e33e200-9856-11eb-9475-3521cae2bf65.png)

So I used CLI to login on terminal, I got EOF error. system:admin also not work for me.
```
[root@mec-bastion1:/root] $ oc login -u system:admin https://api.mec.tb.nia:6443
error: EOF
```

How can I recover my cluster as before? What am I missing to solve it?
I checked all environments such as haproxy and named, and also check network between all cluster nodes.

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive.

Use `export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig` on one of the master nodes to bypass the load balancer

**Comment by rupang790** [comment]
@vrutkovs, The system which login as occurred was on-service, so I re-install OKD cluster already.
However, if the same issue is occurred later, I will attach must-gather archive as you mentioned. Thank you for answer.
