### ISSUE TITLE
local-storage-operator is unavailable in OKD 4

### ISSUE THREAD

**Issue by OleksandrShtepa** [openshift/okd#588]
**Describe the bug**
Regarding OKD 4 docs [Persistent storage using local volumes](https://docs.okd.io/latest/storage/persistent_storage/persistent-storage-local.html):
> The Local Storage Operator is not installed in OKD by default. Use the following procedure to install and configure this Operator to enable local volumes in your cluster.

I tried to install local-storage-operator, but any my actions was not successfully.
> From the UI
> 2. Navigate to Operators → OperatorHub.
> 3. Type Local Storage into the filter box to locate the Local Storage Operator.

No Results Match the Filter Criteria

> From the CLI
> 2. Create the Local Storage Operator object by entering the following command:
> $ oc apply -f openshift-local-storage.yaml

got:
```console
$ oc describe subscriptions local-storage-operator -n openshift-local-storage
Status:
  Conditions:
    Last Transition Time:  2021-04-08T07:35:13Z
    Message:               targeted catalogsource openshift-marketplace/redhat-operators missing
    Reason:                UnhealthyCatalogSourceFound
```
On fresh installed OKD 4.7 I have:
```console
$ oc describe operatorhubs cluster
Spec:
  Disable All Default Sources:  true
  Sources:
    Disabled:  false
    Name:      community-operators
$ oc get packagemanifests -n openshift-marketplace|fgrep -i local
$
```

**Version**
4.7.0-0.okd-2021-03-28-152009

**How reproducible**
100%

**Comment by vrutkovs** [comment]
See #456

**Comment by gardart** [comment]
after upgrading my OKD cluster to 4.14 I needed to disable and then re-enable all the sources in Cluster Settings->Configuration->OperatorHub details, click edit on Default sources, disable them and then enable them again. Now I can see both local storage and data foundation operators
