### ISSUE TITLE
Unable to install latest okdv4 on AWS

### ISSUE THREAD

**Issue by GaborVarga** [openshift/okd#589]
Unable to install latest okdv4 on AWS

**Version**
4.7.0-0.okd-2021-03-28-152009

**How reproducible**
openshift-install deploy cluster --dir=mydir

**Log bundle**
[log-bundle-20210408154357.tar.gz](https://github.com/openshift/okd/files/6283940/log-bundle-20210408154357.tar.gz)

**Comment by vrutkovs** [comment]
Same issue as in #581:
```
version: unreleased-master-3671-g2ef2b7e490e63e5a8afff6c98fe12505540c2114-dirty
```
