### ISSUE TITLE
Cannot ignite worker nodes on OKD 4.7.0-0.okd-2021-03-28-152009 and fedora-coreos-33.20210314.3.0

### ISSUE THREAD

**Issue by WillNilges** [openshift/okd#590]
**Describe the bug**

After an upgrade to 4.7.0-0.okd-2021-03-28-152009, two of our fifteen worker nodes did not come back after the reboot. It appeared as though their hard drives had disappeared. No entries in the boot menu, nothing.

So I tried re-igniting the nodes with the latest fcos, but the ignition seemingly did not work. While it appears to unpack the image, modify the disk, and generally do installer-y things, upon reboot after a successful install, it goes right back to the ISO boot screen, and the disk is still not visible in the boot menu.

![image](https://user-images.githubusercontent.com/42927786/114294475-e7246680-9a6c-11eb-81f1-fe7554673399.png)

I checked with a live disk, and the disk does infact get partitioned and is visible and everything, it's just corrupted or something.

![image](https://user-images.githubusercontent.com/42927786/114294460-d2e06980-9a6c-11eb-901c-4fe4579bd9e6.png)

I have tried igniting (and re-creating ignition configs) with the following versions of Fedora CoreOS
fedora-coreos-33.20210217.3.0
fedora-coreos-33.20210314.3.0
fedora-coreos-33.20210328.2.1

A very similar issue happened last time we updated, and I was able to solve it by re-igniting
with fedora-coreos-33.20210217.3.0. [This](https://github.com/openshift/okd/issues/570#issuecomment-804269906) issue thread tipped me off to that solution. Apparently it had something to do with fcos 33.20210301.3.1.

Possibly related issues:
https://github.com/openshift/okd/issues/566
https://github.com/openshift/okd/issues/580

**Version**

    4.7.0-0.okd-2021-03-28-152009
    Proxmox 6.3

**How reproducible**

100%

**Log bundle**

N/A
Seriously, if you know how to extract logs from a FCOS installation, I'll buy you a beer.

**Comment by vrutkovs** [comment]
That looks like a hardware failure. I suggest opening an issue at https://github.com/coreos/fedora-coreos-tracker

**Comment by WillNilges** [comment]
We host our OKD cluster on Proxmox, so it's unlikely to be a hardware issue. I will definitely open an issue on the coreos tracker, though.

**Comment by WillNilges** [comment]
So, it turns out it was a Proxmox issue. I ignited as normal, but upon reboot, I removed all boot sources (ISO disk, pxe) except for the hard disk image, and it worked. I used my original ignition configs that I made when I initially created the cluster, and  fedora-coreos-33.20210217.3.0.
