### ISSUE TITLE
[OKD 4.7] unable to access Project "Topology View" 

### ISSUE THREAD

**Issue by k-nuhdim** [openshift/okd#591]
**Describe the bug**

Developers unable to see the topology view of openshift project, Insted of that it is showing white blank page. 

**Version**

4.7.0-0.okd-2021-03-07-090821

**How reproducible**

Switch to Developer console ---> click on topology 
**Expected** - Topology view of the project 
**Results** - White Blank Page 
 
**URL Path looks like** - https://console-url/topology/ns/project-name?view=graph

**Comment by vrutkovs** [comment]
OKD's developer console is coming unmodified from OCP, so its best to file a OCP bugzilla to track this
