### ISSUE TITLE
Machine Config Controller does not retry draining nodes: stuck in degraded

### ISSUE THREAD

**Issue by m-yosefpor** [openshift/okd#593]
**Describe the bug**

I upgraded the cluster to `4.7.0-0.okd-2021-04-11-124433`, and in the part when worker nodes should reboot with new machine config, the node has stuck in degraded state. The reason for that was node timed out while draining (due to a pdb) and the machine-controller didn't retry anymore even after I drained the node manually and fixed the drain issue. I rebooted the node and restarted the machine-config-controller, but it didn't help and node was still stuck in degraded state.
`oc describe mcp worker`
```
    Message:               Node okd4-worker-worker-1 is reporting: "failed to drain node (5 tries): timed out waiting for the condition: [error when evicting pods/\"elasticsearch-sample-es-default-1\" -n
\"jaeger-pro-es\": global timeout reached: 1m30s, error when evicting pods/\"elasticsearch-sample-es-default-1\" -n \"jaeger-system-pro-es\": global timeout reached: 1m30s]"
```

I also change node annotations to match a node which wasn't updated yet:
```
    machineconfiguration.openshift.io/currentConfig: rendered-worker-ebe004d73753a16b988adbf1dcc3a57d
    machineconfiguration.openshift.io/desiredConfig: rendered-worker-ebe004d73753a16b988adbf1dcc3a57d
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/state: Done
```

Machine-config-controller continued updating nodes, but the same node still got degraded this time with:
```
    machineconfiguration.openshift.io/reason: 'unexpected on-disk state validating against rendered-worker-8f1e87f0faa38cf72b460505d6e1de20: expected target osImageURL "quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb", have "quay.io/openshift/okd-content@sha256:21a90d62459c272718c77ce5e28cd38026b877cb3461c193f687c37a696db57e"'
```
   

**Version**
`4.7.0-0.okd-2021-04-11-124433`

**Comment by m-yosefpor** [comment]
@vrutkovs Should I fill an issue in machine-config-controller repo too?

**Comment by vrutkovs** [comment]
> The reason for that was node timed out while draining (due to a pdb)

There is nothing MCO can do about this. 

>I rebooted the node and restarted the machine-config-controller

What was the output of machine-config-daemon on that node?

**Comment by m-yosefpor** [comment]
@vrutkovs 
> What was the output of machine-config-daemon on that node?

The same thing as annotation reason:
```
unexpected on-disk state validating against rendered-worker-8f1e87f0faa38cf72b460505d6e1de20: expected target osImageURL "quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb", have "quay.io/openshift/okd-content@sha256:21a90d62459c272718c77ce5e28cd38026b877cb3461c193f687c37a696db57e
```

I tried annotating node's `machineconfiguration.openshift.io/currentConfig` equal to not updated nodes, and also updated nodes, but in either case I received the similar issue.

**Comment by m-yosefpor** [comment]
As I found in the code [here](https://sourcegraph.com/github.com/openshift/machine-config-operator/-/blob/pkg/daemon/daemon.go#L1377:28), if the function returns `false`, then we need to perform an update. However, [here](https://sourcegraph.com/github.com/openshift/machine-config-operator/-/blob/pkg/daemon/daemon.go#L1329) if OS does not match, it returns an error to [here](https://sourcegraph.com/github.com/openshift/machine-config-operator/-/blob/pkg/daemon/daemon.go#L1092) which cause to mark node as degraded and then mc-controller stops updating the nodes!

**Comment by vrutkovs** [comment]
One line from the logs doesn't help me figure out all details of this issue. Please provide a must-gather

**Comment by m-yosefpor** [comment]
I destroyed the old worker node and upgrad completed. I'll try reproducing the issue, and if I could, I'll reopen this issue with bundle logs attached. Thanks.
