### ISSUE TITLE
Issue in upgrading worker node during okd4.7  cluster upgrade

### ISSUE THREAD

**Issue by rvijayanand** [openshift/okd#596]
**Describe the bug**

worker nodes are struck with below error message as when they are being upgraded by Machine Config Operator ( as 
 part of cluster upgrade)Briefly 

Node <HOSTNAME> is reporting: "unexpected on-disk state validating against rendered-worker-465487939d115353a4b7f9344cea8974: expected target osImageURL \"quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb\", have \"quay.io/openshift/okd-content@sha256:bfb5305e3e6117b1e81632a5bedb3230b36cbf96f755b7b34c22be25976209fe\""

**Version**
OKD version release: e.g. 4.7.0-0.okd-2021-04-11-124433 .
It is UPI install 

**How reproducible**
Mostly few nodes were having this issue as part of every cluster upgrade cycle

**Log bundle**

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by rvijayanand** [comment]
Please find the link https://drive.google.com/file/d/1uDQwmNovp1d81HEySgK-pWHpfpmaQDhb/view?usp=sharing

**Comment by vrutkovs** [comment]
>pool degraded: true total: 145, ready 35, updated: 35, unavailable: 1

`worker-335-5.live.okdb.las1.mz-inc.com` is oddly stuck, it said it has been rebaed to new content:
```
2021-04-15T18:12:43.516048660Z I0415 18:12:43.516007  270705 rpm-ostree.go:261] Running captured: rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-784346739/srv/repo:eeac001390627c178b7fba1ab347f5f23dc89447bc2b3900d963d2b0e8143d3c --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb --custom-origin-description Managed by machine-config-operator
```
but boot list is old:
```
2021-04-15T18:16:02.188193010Z Deployments:
2021-04-15T18:16:02.188193010Z * pivot://quay.io/openshift/okd-content@sha256:bfb5305e3e6117b1e81632a5bedb3230b36cbf96f755b7b34c22be25976209fe
2021-04-15T18:16:02.188193010Z               CustomOrigin: Managed by machine-config-operator
2021-04-15T18:16:02.188193010Z                  Timestamp: 2021-03-04T22:47:33Z
2021-04-15T18:16:02.188193010Z            LayeredPackages: NetworkManager-ovs glusterfs glusterfs-fuse qemu-guest-agent
```

Could you check `rpm-ostreed` from previous boot to check why a new deployment was not created?

**Comment by rvijayanand** [comment]
[core@worker-335-5 ~]$ journalctl -u rpm-ostreed.service
-- Logs begin at Mon 2021-03-01 14:05:32 UTC, end at Thu 2021-04-22 00:48:33 UTC. --
Mar 03 11:27:57 worker-335-5.live.okdb.las1.mz-inc.com systemd[1]: Starting rpm-ostree System Management Daemon...
Mar 03 11:27:57 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: Reading config file '/etc/rpm-ostreed.conf'
Mar 03 11:27:57 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: In idle state; will auto-exit in 62 seconds
Mar 03 11:27:57 worker-335-5.live.okdb.las1.mz-inc.com systemd[1]: Started rpm-ostree System Management Daemon.
Mar 03 11:27:57 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: client(id:machine-config-operator dbus:1.13086 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) added; new total=1
Mar 03 11:27:58 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: client(id:machine-config-operator dbus:1.13086 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) vanished; remaining=0
Mar 03 11:27:58 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: In idle state; will auto-exit in 61 seconds
Mar 03 11:27:58 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: client(id:machine-config-operator dbus:1.13088 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) added; new total=1
Mar 03 11:27:58 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: client(id:machine-config-operator dbus:1.13088 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) vanished; remaining=0
Mar 03 11:27:58 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: In idle state; will auto-exit in 60 seconds
Mar 03 11:28:59 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[415837]: In idle state; will auto-exit in 63 seconds
Mar 03 11:28:59 worker-335-5.live.okdb.las1.mz-inc.com systemd[1]: rpm-ostreed.service: Succeeded.
Mar 03 11:28:59 worker-335-5.live.okdb.las1.mz-inc.com systemd[1]: rpm-ostreed.service: Consumed 1.599s CPU time.
Mar 04 07:14:30 worker-335-5.live.okdb.las1.mz-inc.com systemd[1]: Starting rpm-ostree System Management Daemon...
Mar 04 07:14:30 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Reading config file '/etc/rpm-ostreed.conf'
Mar 04 07:14:31 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: In idle state; will auto-exit in 63 seconds
Mar 04 07:14:31 worker-335-5.live.okdb.las1.mz-inc.com systemd[1]: Started rpm-ostree System Management Daemon.
Mar 04 07:14:31 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: client(id:machine-config-operator dbus:1.14033 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) added; new total=1
Mar 04 07:14:31 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: client(id:machine-config-operator dbus:1.14033 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) vanished; remaining=0
Mar 04 07:14:31 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: In idle state; will auto-exit in 60 seconds
Mar 04 07:14:33 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: client(id:machine-config-operator dbus:1.14035 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0) added; new total=1
Mar 04 07:14:34 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Locked sysroot
Mar 04 07:14:34 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Initiated txn UpdateDeployment for client(id:machine-config-operator dbus:1.14035 unit:crio-82ea272a4b0a93c98b2cc12835cd06b5d96ee94f333ad4e845314872b3331708.scope uid:0): /org/projectatomic/rpmostree1/fedora_coreos
Mar 04 07:14:39 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
Mar 04 07:14:39 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Librepo version: 1.12.1 with CURL_GLOBAL_ACK_EINTR support (libcurl/7.71.1 OpenSSL/1.1.1h-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.41.0)
Mar 04 07:14:39 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
Mar 04 07:14:39 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
Mar 04 07:14:39 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Preparing pkg txn; enabled repos: ['coreos-extensions'] solvables: 51
Mar 04 07:14:39 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
Mar 04 07:14:41 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Imported 6 pkgs
Mar 04 07:14:41 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Relabeled 0/22 pkgs
Mar 04 07:14:41 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278097]: (2021-03-04  7:14:42:397428): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278097]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278094]: groupadd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278094]: groupadd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278103]: (2021-03-04  7:14:42:437159): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278103]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278094]: groupadd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278094]: groupadd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278119]: (2021-03-04  7:14:42:521377): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278119]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278116]: useradd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278116]: useradd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278135]: (2021-03-04  7:14:42:557987): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278135]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278116]: useradd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(glusterfs.prein)[1278116]: useradd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Executed %prein for glusterfs in 437ms
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278176]: (2021-03-04  7:14:42:753925): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278176]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278171]: groupadd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278171]: groupadd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278188]: (2021-03-04  7:14:42:796148): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278188]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278171]: groupadd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278171]: groupadd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278196]: (2021-03-04  7:14:42:896860): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278196]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278193]: useradd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278193]: useradd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278201]: (2021-03-04  7:14:42:936594): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278201]: Could not open available domains
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278193]: useradd: sss_cache exited with status 5
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(unbound-libs.prein)[1278193]: useradd: Failed to flush the sssd cache.
Mar 04 07:14:42 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree[1277347]: Executed %prein for unbound-libs in 367ms
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278234]: (2021-03-04  7:14:43:128196): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278234]: Could not open available domains
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278229]: groupadd: sss_cache exited with status 5
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278229]: groupadd: Failed to flush the sssd cache.
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278243]: (2021-03-04  7:14:43:178453): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278243]: Could not open available domains
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278229]: groupadd: sss_cache exited with status 5
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278229]: groupadd: Failed to flush the sssd cache.
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278254]: (2021-03-04  7:14:43:290323): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278254]: Could not open available domains
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278251]: useradd: sss_cache exited with status 5
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278251]: useradd: Failed to flush the sssd cache.
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278259]: (2021-03-04  7:14:43:339528): [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278259]: Could not open available domains
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm-ostree(openvswitch.prein)[1278251]: useradd: sss_cache exited with status 5
Mar 04 07:14:43 worker-335-5.live.okdb.las1.mz-inc.com rpm...

**Comment by vrutkovs** [comment]
Is it reproducible on latest stable OKD 4.7?
