### ISSUE TITLE
worker node struck with error message "failed to update OS to quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb : with stdout output: : error running rpm-ostree" during cluster Upgrade process

### ISSUE THREAD

**Issue by rvijayanand** [openshift/okd#598]
Describe the bug

worker nodes are struck with below error message as when they are being upgraded by Machine Config Operator ( as
part of cluster upgrade)Briefly

Node is reporting: "failed to update OS to quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb : with stdout output: : error running rpm-ostree rebase --experimental /run/mco-machine-os-content/os-content-400463164/srv/repo:eeac001390627c178b7fba1ab347f5f23dc89447bc2b3900d963d2b0e8143d3c --custom-origin-url pivot://quay.io/openshift/okd-content@sha256:16da407404e6cedf64b0b6680ddac2bc2e2a3cc6b761fb8ff92d23ef55c7cfdb --custom-origin-description Managed by machine-config-operator: 1437 metadata, 4609 content objects imported; 1.2?GB content"

Version
OKD version release: e.g. 4.7.0-0.okd-2021-04-11-124433 .
It is UPI install

How reproducible
Mostly few nodes were having this issue as part of every cluster upgrade cycle

Log bundle
--

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by rvijayanand** [comment]
uploaded must-gather
https://drive.google.com/file/d/1zUDK5bKEc2mc8tVeHLw4xddjJBT41wva/view
