### ISSUE TITLE
Registry unavailable: registry.svc.ci.openshift.org 

### ISSUE THREAD

**Issue by samuelneagu** [openshift/okd#608]
**Describe the bug**
Registry registry.svc.ci.openshift.org seems to be unavailable:

oc adm release extract registry.svc.ci.openshift.org/origin/release:4.5.0-0.okd-2020-07-29-070316
error: unable to connect to image repository registry.svc.ci.openshift.org/origin/release:4.5.0-0.okd-2020-07-29-070316: endpoint "https://registry.svc.ci.openshift.org" does not support v2 API

**Version**
Not version related 

**How reproducible**
oc adm release extract registry.svc.ci.openshift.org/origin/release:4.5.0-0.okd-2020-07-29-070316
(or with any other version)

**Log bundle**
This is a fresh install; encountering issue in the cluster deployment process

**Comment by vrutkovs** [comment]
This registry moved to `registry.ci.openshift.org` (no `.svc.`).

We can't update existing images as it would change their pullspecs and signatures

**Comment by samuelneagu** [comment]
Thanks for the quick response!
