### ISSUE TITLE
Still waiting for the Kubernetes API: the server could not find the requested resource

### ISSUE THREAD

**Issue by thummanareshreddy** [openshift/okd#614]
I'm was trying to Install OKD 4.5.0-0.okd-2020-10-15-235428 cluster on AWS in a restricted network with user-provisioned infrastructure  in [AWS restricted](https://docs.okd.io/latest/installing/installing_aws/installing-restricted-networks-aws.html). During initializing bootstrap node I see debug Still waiting for the Kubernetes API: the server could not find the requested resource. I have attached log bundle here. can someone help me here.

I'm able to ssh into bootstrap node but not master and worker nodes. I see error as connection refused while ssh into master and worker nodes.

[log-bundle-20210429135148.tar.gz](https://github.com/openshift/okd/files/6399376/log-bundle-20210429135148.tar.gz)

**Comment by vrutkovs** [comment]
Is it reproducible in latest OKD stable?

**Comment by thummanareshreddy** [comment]
As per client requirement I'm trying with OKD 4.5.  Please let me know if it is known issue, I'll inform my client and try with OKD stable.

**Comment by vrutkovs** [comment]
If its an OKD bug we'd need to make sure it has not been resolved already in newer versions. If it has been, we might cherry-pick it back to 4.5 (but chances are very slim to be honest).

Closing this until evidence that it happens in OKD 4.7 appears
