### ISSUE TITLE
OKD 4.7 UPI vSphre installation fail

### ISSUE THREAD

**Issue by riccardopulcini** [openshift/okd#620]
**Describe the bug**
we have two problems:
1.  On bootstrap the ignition fails due to an error in the boot process. We found a workaround by executing the following cmd in the bootstrap machine:  `chmod 0644 /etc/zincati/config.d/90-disable-feature.toml`
2. On the master node at the bootstrapping of the node we have the following strange message, maybe it is normal but I had never noticed before:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1457347/117260668-99becd80-ae4f-11eb-9f78-2c2a8a08c9fb.png)

**Version**
4.7.0-0.okd-2021-04-24-103438 on vSphere UPI

**How reproducible**
100%

**Log bundle**
[openshift_install.log](https://github.com/openshift/okd/files/6433005/openshift_install.log)
[bootstraper.log](https://github.com/openshift/okd/files/6434964/bootstraper.log)

**Comment by vrutkovs** [comment]
>If needed I can attach it

please do

**Comment by riccardopulcini** [comment]
Hello 
log attached

Regards

**Comment by vrutkovs** [comment]
That's openshift install log, not [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html)

**Comment by spatel95** [comment]
Same issue as the author but for Installer Provisioned Infrastructure. 

![bootstrap-failure-zincati](https://user-images.githubusercontent.com/18754101/117355196-c7ccfd80-aea1-11eb-90f6-8494b0da248f.PNG)

In IPI the IP address and hostname is not provisioned. So I don't believe I am able to get log bundle
![bootstrap-failure-gather-log-bundle](https://user-images.githubusercontent.com/18754101/117355312-f1862480-aea1-11eb-8ecd-996531af73b1.PNG)

**Comment by riccardopulcini** [comment]
Hi 

log attached :)

Regards

**Comment by riccardopulcini** [comment]
Hello 

need anything else?

Regards

**Comment by vrutkovs** [comment]
I don't know what bootstraper.log is, but its certainly not a log bundle

**Comment by riccardopulcini** [comment]
Hi all

sorry for the delay,
We repeated the test to create clean logs.
By repeating the test, we have updated the version of fedora coreos.

[_.openshift_install.log](https://github.com/openshift/okd/files/6532946/_.openshift_install.log)
[194.log](https://github.com/openshift/okd/files/6532947/194.log)
[kube-api.log](https://github.com/openshift/okd/files/6532948/kube-api.log)

**Comment by vrutkovs** [comment]
>time="2021-05-19T18:04:43+02:00" level=debug msg="Unable to connect to the server: read tcp 10.98.202.111:54502->10.98.202.108:6443: read: connection reset by peer"

Seems the network is unstable so log bundle cannot be received? Is this happening if you try several times?

**Comment by riccardopulcini** [comment]
Hello
after updating the installer and fedoraos the problem was solved

Thanks
