### ISSUE TITLE
OKD 4.7 storage operator degraded - VSphereProblemDetectorController_SyncError

### ISSUE THREAD

**Issue by schadom** [openshift/okd#621]
**Describe the bug**
Cluster operator storage has been degraded for 10 minutes. Operator is degraded because VSphereProblemDetectorController_SyncError and cluster upgrades will be unstable.

VSphereProblemDetectorControllerDegraded: failed to connect to vcenter.corp.com: Post "https://vcenter.corp.com/sdk": dial tcp 192.168.144.100:443: i/o timeout

Cause:  Openshift Cluster in DMZ-segment with no access to vCenter API in Management-network.

**Version**
4.7.0-0.okd-2021-04-24-103438 (UPI on vSphere, without NSX(-T))

Is there any possiblity to disable VSphereProblemDetector checks or switch the cluster/provider from vSphere to bare-metal without having to reinstall the whole cluster?

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by schadom** [comment]
Thanks @vrutkovs, will provide logs asap. This is more of a question than a bug. Is there any possiblity to disable VSphereProblemDetector checks or switch the cluster/provider from vSphere to bare-metal without having to reinstall the whole cluster?
