### ISSUE TITLE
Prometheus-adapter can't query custom metrics  in OKD 4.7.

### ISSUE THREAD

**Issue by wayne-cec** [openshift/okd#634]
**Describe the bug**

Prometheus-adapter can't query custom metrics for HPA  in OKD 4.7, and it works in OKD 4.6.

**Version**

 # oc version
Client Version: 4.6.0-0.okd-2021-02-14-205305
Server Version: 4.7.0-0.okd-2021-03-21-094146
Kubernetes Version: v1.20.0-1054+bafe72fb05eddc-dirty 

**How reproducible**

follow  the blog from openshift web: 
https://www.openshift.com/blog/enabling-monitoring-and-scaling-of-your-own-services-application
 

**Log bundle**

Resource list is empty when run below command:
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ 
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}

**Comment by vrutkovs** [comment]
OKD doesn't change Prometheus configuration, so its not an OKD specific bug.

Please submit a bugzilla ticket for OCP with must-gather
