### ISSUE TITLE
Insights status report issue

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/okd#635]
Hey i install OKD   4.7.0-0.okd-2021-04-24-103438

After that i saw that i still have 1 usse on Insights status. After check it and click on View all in **OpenShift Cluster Manager** it's redirect me to https://cloud.redhat.com/openshift/
and get error:
Cluster with subscription ID undefined was not found, it might have been deleted or you don't have permission to see it.

Can anyone explain me this is a tech preview function or maybe i forget to configure something ?

**Comment by vrutkovs** [comment]
Does your cluster use pull secret from cloud.redhat.com?

**Comment by ZrytyADHD** [comment]
Yes and also I include it into install-config.yaml during install.
I check it now and it's correct. On Redhat I use my private acoount and it's pull secret maybe this is a problem ?
There is a option to update this after install ?

**Comment by vrutkovs** [comment]
>I check it now and it's correct

So, the issue can be closed? Looks like some intermittent issue, could be on Insight's side

>There is a option to update this after install ?

Yes - https://docs.okd.io/latest/support/remote_health_monitoring/opting-out-of-remote-health-reporting.html#images-update-global-pull-secret_opting-out-remote-health-reporting

**Comment by ZrytyADHD** [comment]
Yes i check link which you provide me and test it.
