### ISSUE TITLE
OKD 4.7 Upgrade stuck: Progressing: browser oauthclient does not exist

### ISSUE THREAD

**Issue by creativie** [openshift/okd#639]
**Describe the bug**
Upgrade cluster stuck on authentication-operator with message "Progressing: browser oauthclient does not exist".
![image](https://user-images.githubusercontent.com/12710067/118628486-4f393b80-b7d5-11eb-963f-c2a8b8ac48e1.png)

When change logging level to debug i can see 409 errors from api
```
POST https://100.99.0.1:443/apis/oauth.openshift.io/v1/oauthclients 409 Conflict in 38 milliseconds
```
 
**Version**
4.7.0-0.okd-2021-04-24-103438
vsphere 6.7 U3

**How reproducible**
Upgrade cluster from 4.5 with --allow-explicit-upgrade --force

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by vrutkovs** [comment]
>Upgrade cluster from 4.5 with --allow-explicit-upgrade --force

you can't upgrade across a version, this must be a 4.5 -> 4.6 -> 4.7 upgrade
