### ISSUE TITLE
different used repositories leads in inability to apply update

### ISSUE THREAD

**Issue by gtema** [openshift/okd#64]
Not sure, whether I did everything right, but with okd 4.4 (preview2) deployed I am now trying to force update to the newer image:

- neither channel offers update (so far so good)
- trying to apply desiredUpdate to the ClusterVersion operator:
- initial deployment claims to be installed from quay.io repo 
```
- completionTime: '2020-01-30T17:29:08Z'
      image: >-
        quay.io/openshift/okd@sha256:df6caca5d103f75909fd7cdbf294991023b9fc79c137dbb61754000196f97b8e
      startedTime: '2020-01-30T17:09:04Z'
      state: Completed
```

- creating spec.desiredUpdate, which will refer quay.io with newer sha image from https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-31-123546 leads to `image not found`
- using `registry.svc.ci.openshift.org/origin/release@sha256:12739a1e37e13b8557039c6eec1e4212e3c5532deb283419e3cac9a3783e5393` works and starts update
- update stucks on the last step for machine-operator, which degrades, since in crio.conf "quay.io/openshift/okd-content@sha256:2f68508143d397e98e2aa53967d28357263a10d0832d611bee1656b3a32ecbc2 != registry.svc.ci.openshift.org/origin/4.4-2020-02-03-013019@sha256:2f68508143d397e98e2aa53967d28357263a10d0832d611bee1656b3a32ecbc2"

Result: can not update to the newer release, cluster degraded

**Comment by vrutkovs** [comment]
>neither channel offers update (so far so good)

Upgrades via channels are out of scope for now, at least until Beta

>trying to apply desiredUpdate to the ClusterVersion operator:

Does it work with `oc adm upgrade --force --force --allow-explicit-upgrade --to-image=<release pull spec>`? Note that CI registry may be unreliable sometimes so its recommended to mirror the image to quay / your registry - [docs](https://docs.openshift.com/container-platform/4.2/installing/install_config/installing-restricted-networks-preparations.html)

**Comment by gtema** [comment]
not sure it will help, but I give it a try (actually this command also results in very similar spec of the ClusterConfig operator. I need now somehow to overcome downgraded machine-config operator.

I think the problem is that machine-config operator generates/uses some registry name, which does not match to what some other component, or even itself, expects/does (generated machine-config contains pause_image ref to registry.svc.co.openshift.org (what was initially given as target), while MCO further step's expectation is quay.io).

So, MCO applies update to the target state and immediately exists literally complaining about this particular inconsistency.

rendered config and applied file contain:
```
pause_image = "registry.svc.ci.openshift.org/origin/4.4-2020-02-03-013019@sha256:2f68508143d397e98e2aa53967d28357263a10d0832d611bee1656b3a32ecbc2"
```

error messages from MCD:
```
I0203 11:22:08.302318 2059171 daemon.go:732] Current config: rendered-worker-e0186732891c0943f9f1d3a266c90c34
I0203 11:22:08.302350 2059171 daemon.go:733] Desired config: rendered-worker-8e62143cdd82ff4cd2fd6a6293b6e669
I0203 11:22:08.308816 2059171 daemon.go:423] Detected a login session before the daemon took over on first boot
I0203 11:22:08.308840 2059171 daemon.go:424] Applying annotation: machineconfiguration.openshift.io/ssh
I0203 11:22:08.321357 2059171 daemon.go:959] Validating against current config rendered-worker-e0186732891c0943f9f1d3a266c90c34
E0203 11:22:08.322104 2059171 daemon.go:1351] content mismatch for file /etc/crio/crio.conf: # The CRI-O configuration file specifies all of the available configuration
```

And rolling back manually the crio.conf content on the target system brings me to https://github.com/openshift/machine-config-operator/issues/1378, which most likely is the real cause here

**Comment by gtema** [comment]
well yes, after reading more precisely - https://github.com/openshift/machine-config-operator/issues/1378 is exactly the cause

**Comment by vrutkovs** [comment]
Lets keep this bug so it would be used as an OKD tracking bug

**Comment by vrutkovs** [comment]
Tried a few updates recently and didn't hit it - is it still occurring?
