### ISSUE TITLE
4.7 install with installer-provisioned infrastructure on AWS

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/okd#643]
I've now tried this three times using the latest linux installer (4.7.9). I'm following the same steps with which I've previously been able to install successfully. I've attached the log-bundle and a file containing a grep for errors. 

I am finding it difficult to locate a root cause as it is tricky to see what goes wrong first. In bootstrap/containers/bootstrap-control-plane/kube-apiserver.log has this error fairly early on:

```
E0519 15:41:06.741389       1 customresource_handler.go:669] error building openapi models for subscriptions.operators.coreos.com: ERROR $root.definitions.com.coreos.operators.v1alpha1.Subscription.properties.spec.properties.config.properties.env.items.<array>.properties.valueFrom.properties.resourceFieldRef.properties.divisor has invalid property: anyOf
ERROR $root.definitions.com.coreos.operators.v1alpha1.Subscription.properties.spec.properties.config.properties.resources.properties.limits.additionalProperties.schema has invalid property: anyOf
ERROR $root.definitions.com.coreos.operators.v1alpha1.Subscription.properties.spec.properties.config.properties.resources.properties.requests.additionalProperties.schema has invalid property: anyOf
```

Not sure if that's a cause or a symptom of something else.

[log-bundle-20210519171340.tar.gz](https://github.com/openshift/okd/files/6510348/log-bundle-20210519171340.tar.gz)

[errors.txt](https://github.com/openshift/okd/files/6510347/errors.txt)

**Comment by vrutkovs** [comment]
2 masters requested, these won't form a quorum.

Also OCP bugs should go to https://bugzilla.redhat.com

**Comment by ryandawsonuk** [comment]
Thanks, this helped a lot as I can create now!
