### ISSUE TITLE
kube-controller-manager degraded after replacing ingress certificate (4.7.0-0.okd-2021-04-24-103438)

### ISSUE THREAD

**Issue by mvrk69** [openshift/okd#644]
Hi,

Today i did a fresh deployment of 4.7.0-0.okd-2021-04-24-103438 on Fedora CoreOS 33.20210328.3.0.

Everything was working fine until i replaced the ingress certificate, i followed the doc:
https://docs.okd.io/latest/security/certificates/replacing-default-ingress-certificate.html

and after the replacement the kube-controller-manager became degraded, i noticed al the 3 masters where rebooted one by one after the replacement, but the kube-controller-manager never recovered.

oc get clusteroperators
NAME                                                VERSION                                      AVAILABLE   PROGRESSING   DEGRADED   SINCE
...
kube-controller-manager                    4.7.0-0.okd-2021-04-24-103438   True               True                       True               5h32m

--------------

oc describe clusteroperator kube-controller-manager
...
...
 Status:
  Conditions:
    Last Transition Time:  2021-05-21T10:03:04Z
    Message:               NodeInstallerDegraded: 1 nodes are failing on revision 10:
NodeInstallerDegraded: no detailed termination message, see `oc get -n "openshift-kube-controller-manager" pods/"installer-10-ocp-master1" -oyaml`
    Reason:                NodeInstaller_InstallerPodFailed
    Status:                True
    Type:                  Degraded
    Last Transition Time:  2021-05-21T09:55:33Z
    Message:               NodeInstallerProgressing: 2 nodes are at revision 9; 1 nodes are at revision 10

----------------------------

Anyone has any idea what could be the problem?

-------------------------

oc adm must-gather
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information.
ClusterID: 959dbd46-b03b-4365-80dd-1bd53cd87f15
ClusterVersion: Stable at "4.7.0-0.okd-2021-04-24-103438"
ClusterOperators:
	clusteroperator/kube-controller-manager is degraded because NodeInstallerDegraded: 1 nodes are failing on revision 10:
NodeInstallerDegraded: no detailed termination message, see `oc get -n "openshift-kube-controller-manager" pods/"installer-10-ocp-master1" -oyaml`

[must-gather.local.7522213070732357412.tar.gz](https://github.com/openshift/okd/files/6523139/must-gather.local.7522213070732357412.tar.gz)

**Comment by mvrk69** [comment]
Well..., i was able to fix it now by forcing the redeploy of that operator:

oc patch kubecontrollermanager/cluster --type merge -p "{\"spec\":{\"forceRedeploymentReason\":\"Forcing new revision with random number $RANDOM to make message unique\"}}"

**Comment by vrutkovs** [comment]
Closing as non-OKD specific and a documented workaround
