### ISSUE TITLE
FATAL failed to wait for bootstrapping to complete: timed out waiting for the condition

### ISSUE THREAD

**Issue by getsueineko** [openshift/okd#669]
**Version**
Version: 4.7.0-0.okd-2021-05-22-050008
**How reproducible**
100%
**Log bundle**
[log-bundle-20210608101024.tar.gz](https://github.com/openshift/okd/files/6615874/log-bundle-20210608101024.tar.gz)

I use this https://github.com/ryanhay/ocp4-metal-install#deploy-openshift as a basic guide. 
But I have a Windows DNS server and I set static IP addresses through nmcli in livecd env coreos. 
My dig command checks are successful.
My start commands for nodes are as:
sudo coreos-installer install /dev/sda **--copy-network** --image-url https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/34.20210427.3.0/x86_64/fedora-coreos-34.20210427.3.0-metal.x86_64.raw.xz --ignition-url http://192.168.29.99:8080/okd4/bootstrap.ign --insecure-ignition

After starting the bootstrap node, three masters and two workers after the specified time, I always encounter an error:
[root@balancer ~]# openshift-install --dir=/opt/okd4 wait-for bootstrap-complete --log-level=debug
DEBUG OpenShift Installer 4.7.0-0.okd-2021-05-22-050008
DEBUG Built from commit ba1a5fc61dd3be134a24fa6d89ae24012a93385a
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd4.domain.com:6443...
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding
INFO API v1.20.0-1073+df9c8387b2dc23-dirty up
INFO Waiting up to 30m0s for bootstrapping to complete...
W0608 09:58:03.380065  143021 reflector.go:424] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ConfigMap ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
INFO Use the following commands to gather logs from the cluster
INFO openshift-install gather bootstrap --help
FATAL failed to wait for bootstrapping to complete: timed out waiting for the condition

At the same time, I see that my masters started (screenshot), but the workers did not.

![master](https://user-images.githubusercontent.com/14312837/121172960-eb001980-c860-11eb-8ef7-7378826c8798.png)

**Comment by vrutkovs** [comment]
3 control plane replicas specified, but a single master IP is in the log bundle (no data fetched for it).

Also the same IP is requesting masters and worker data:
```
E0608 09:35:49.035159       1 api.go:136] couldn't get config for req: {worker 0xc00058c080}, error: refusing to serve bootstrap configuration to pool "worker"
I0608 09:35:49.034841       1 api.go:117] Pool master requested by address:"192.168.29.99:45830" User-Agent:"Ignition/2.9.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.2.0, */*;q=0.1"
I0608 09:35:49.035226       1 bootstrap_server.go:66] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0608 09:35:49.034956       1 api.go:117] Pool master requested by address:"192.168.29.99:45836" User-Agent:"Ignition/2.9.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.2.0, */*;q=0.1"
I0608 09:35:49.035319       1 bootstrap_server.go:66] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0608 09:35:49.034965       1 api.go:117] Pool master requested by address:"192.168.29.99:45834" User-Agent:"Ignition/2.9.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.2.0, */*;q=0.1"
I0608 09:35:49.035371       1 bootstrap_server.go:66] reading file "/etc/mcs/bootstrap/machine-pools/master.yaml"
I0608 09:35:49.036951       1 api.go:117] Pool worker requested by address:"192.168.29.99:45824" User-Agent:"Ignition/2.9.0" Accept-Header: "application/vnd.coreos.ignition+json;version=3.2.0, */*;q=0.1"
E0608 09:35:49.036990       1 api.go:136] couldn't get config for req: {worker 0xc000574f00}, error: refusing to serve bootstrap configuration to pool "worker"

```

**Comment by getsueineko** [comment]
The whole bundle is nothing new
[log-bundle-20210608112502.tar.gz](https://github.com/openshift/okd/files/6616043/log-bundle-20210608112502.tar.gz)

It's weird, but I am getting the ping problem to hosts.
ping 192.168.29.92
PING 192.168.29.92 (192.168.29.92) 56 (84) bytes of data.
From 192.168.29.99 icmp_seq = 1 Destination Host Unreachable (balancer?)

I don't know how to log into coreos to see what the IP is.
I'm using login core and password core, but no luck.

Is  --copy-network won't transfer my network settings to the target system?

**Comment by getsueineko** [comment]
I suppose the problem was with the network. I setup dhcpd and got bootsrap complete!
