### ISSUE TITLE
Improve search in OKD console

### ISSUE THREAD

**Issue by startxfr** [openshift/okd#67]
Hi all,

In OKD 4.3 and previous versions, there is no equivalent of the `oc get all -l xx=yyy` search request within the web console. 
In the search menu, we can search only a defined resource, but not *all* resources. Is it possible to add an *all* option to the resource kind dropdown list ? 
If request is to huge to perform when no filter is apply, perhaps adding the *all* option could be suggested only when a filter is apply (like app=xx or version=x.x.x).

**Comment by vrutkovs** [comment]
Seems that would affect OCP too, could you file this issue at https://github.com/openshift/console as well?

**Comment by startxfr** [comment]
thanks vadim for your answer.

issue is opened in openshift console too: https://github.com/openshift/console/issues/4173

**Comment by LorbusChris** [comment]
Thanks for reporting this @startxfr :)
Let's track this over in the other repo
/close
