### ISSUE TITLE
Nodes randomly rebooting every few minutes

### ISSUE THREAD

**Issue by HaehnleinMar** [openshift/okd#671]
**Describe the bug**
Since upgrading to OKD 4.7.0-0.okd-2021-06-04-191031 my worker nodes are seemingly randomly rebooting every 5 minutes or so.

**Version**
OKD 4.7.0-0.okd-2021-06-04-191031 on vSphere IPI

**How reproducible**
The behaviour occurs on 100% of my 12 worker nodes.

**Log bundle**
https://docker.ntslabs.net/files/must-gather.local.8916468073005934167.tar.gz

**Comment by HaehnleinMar** [comment]
By making a screenshot at the right time (because there wasn't anything loggen in journald) I learned that there is a kernel NULL pointer dereference:

![kernel-null-pointer](https://user-images.githubusercontent.com/9468979/121304663-ed17b600-c8fc-11eb-916b-c8a357aecd41.png)

**Comment by vrutkovs** [comment]
Kernel bug, seems to be nfs4 related.

Please report it for Fedora in bugzilla.redhat.com
