### ISSUE TITLE
[OKD 4.7] No Upgrades possible on all "4.7.0-0.okd-2021-04-11-124433" Clusters - Image Resources not available?

### ISSUE THREAD

**Issue by devzeronull** [openshift/okd#674]
Hi,

after tinkering around with Update Problems on a Test and Pre-Upgrade Environment, we are now also recognizing available upgrade Error Messages on 3 Clusters running version "4.7.0-0.okd-2021-04-11-124433":

> message: 'Unable to retrieve available updates: Get "https://origin-release.svc.ci.openshift.org/graph?arch=amd64&channel=stable-4.7&id=xxxxxxxxxxx&version=4.7.0-0.okd-2021-04-11-124433": Bad Gateway'
      reason: RemoteFailed
      status: "False"
      type: RetrievedUpdates
    desired:
      image: quay.io/openshift/okd@sha256:4414db9e8945504d1d5423ec11d64df9fa8b4aa60d978f8b4bdb3d0720800741
      version: 4.7.0-0.okd-2021-04-11-124433

Is it possible, that the sources are not available anymore or that there are issues with the registry?

Best regards

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd/blob/master/KNOWN_ISSUES.md#cannotretrieveupdates-alert

**Comment by devzeronull** [comment]
Okay, thank you very much a short:
`oc patch clusterversion/version --patch '{"spec":{"upstream":"https://amd64.origin.releases.ci.openshift.org/graph"}}' --type=merge`

solved the Problem immediately!
