### ISSUE TITLE
Cluster version operator has not retrieved updates in 14h 41m 2s.

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#676]
Looks like the update site endpoint has a DNS issue, did you guy's change the UPDATE site DNS entry.
![image](https://user-images.githubusercontent.com/23619505/121415669-00934300-c936-11eb-8105-0d5ecce6a3f2.png)

**Comment by cgruver** [comment]
The DNS record for `origin-release.svc.ci.openshift.org` did get messed up.

Efforts are underway to fix it, but in the meantime I was able to work around the issue by modifying my DNS configuration.

I'm using Bind in my lab, so I added a CNAME record.

Create a zone file: `/etc/named/zones/db.okdfix`

```bash
@       IN      SOA     yourdnshost.your.domain.org. admin.your.domain.org. (
                              3         ; Serial
             604800     ; Refresh
              86400     ; Retry
            2419200     ; Expire
             604800 )   ; Negative Cache TTL
;
; name servers - NS records
    IN      NS     yourdnshost.your.domain.org.

origin-release.svc.ci.openshift.org IN CNAME amd64.origin.releases.ci.openshift.org.
```

Edit `/etc/named/named.conf.local` and add:

```bash
zone "okdfix" {
    type master;
    file "/etc/named/zones/db.okdfix"; allow-query {none;};
};
```

Edit `/etc/named.conf` and add `response-policy { zone "okdfix"; };` to the `options` section.

Restart named.

**Comment by cgruver** [comment]
Actually...  I just realized that this did not fix it.  It fixed the DNS resolution, but now has a CERT issue.

**Comment by cgruver** [comment]
Do this to work around the issue:

```bash
oc patch ClusterVersion version --type merge --patch '{"spec":{"upstream":"https://amd64.origin.releases.ci.openshift.org/graph"}}'
```

**Comment by johnlongo** [comment]
That did the trick thank you

![image](https://user-images.githubusercontent.com/23619505/121429406-e14fe200-c944-11eb-8184-69f8ac8a22b3.png)
