### ISSUE TITLE
OKD 4.7.0-0.okd-2021-06-04-191031: setlocale failed

### ISSUE THREAD

**Issue by Reamer** [openshift/okd#677]
**Describe the bug**
After updating to OKD 4.7.0-0.okd-2021-06-04-191031, I encountered the following errors during SSH login.
```
~ # ssh worker2-cl1-dc99.t-ocp.cloud.mycompany.com -l core
Warning: the ECDSA host key for 'worker2-cl1-dc99.t-ocp.cloud.mycompany.com' differs from the key for the IP address '10.20.17.42'
Offending key for IP in /root/.ssh/known_hosts:796
Matching host key in /root/.ssh/known_hosts:819
Are you sure you want to continue connecting (yes/no)? yes
Fedora CoreOS 34.20210518.3.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

Last login: Fri Jun  4 08:41:13 2021 from 10.4.4.2
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```
It's just a warning and I haven't noticed any restrictions.

**Version**
OKD 4.7.0-0.okd-2021-06-04-191031 - UPI installation

**How reproducible**
100% reproducible on all my hosts during the SSH login.

**Comment by Reamer** [comment]
Still happen on 4.7.0-0.okd-2021-08-22-163618.
I thing because of
```
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
```
in `/etc/ssh/sshd_config.d/50-redhat.conf`
On the SSH client side, I have the following configuration.
```
    SendEnv LANG LC_*
```

**Comment by vrutkovs** [comment]
That's a Fedora bug then, please report it to bugzilla instead

**Comment by sandrobonazzola** [comment]
@Reamer did you open a bugzilla to Fedora?
```bash
$ rpm -qf /etc/ssh/sshd_config.d/50-redhat.conf
openssh-server-8.6p1-3.fc34.x86_64
```

**Comment by sandrobonazzola** [comment]
@vrutkovs I think this one can be closed as not an OKD issue.

**Comment by Reamer** [comment]
> @Reamer did you open a bugzilla to Fedora?
> 
> ```shell
> $ rpm -qf /etc/ssh/sshd_config.d/50-redhat.conf
> openssh-server-8.6p1-3.fc34.x86_64
> ```

Unfortunately not at the moment. Maybe you can open an issue for this topic and link it to this thread. I am closing this issue because it is a FCOS error.
