### ISSUE TITLE
Error deploying sample builds

### ISSUE THREAD

**Issue by gratchie** [openshift/okd#7]
I have a new OKD install, version: 4.3.0-0.okd-2019-11-15-182656,  but I'm getting the error below when trying to do a generic deployment to test builds (S2i and docker-built). 

> error instantiating Build from BuildConfig project-py/docker-build (0): Error resolving ImageStreamTag ruby:latest in namespace openshift: unable to find latest tagged image

> Generated from buildconfig-controller
12 times in the last few seconds
error instantiating Build from BuildConfig project-py/s2i-build (0): Error resolving ImageStreamTag ruby:2.4 in namespace openshift: unable to find latest tagged image

**Comment by DanyC97** [comment]
@gratchie i suspect you've deployed on AWS provider ? would be good to add this info moving forward, thanks

**Comment by gratchie** [comment]
Yes, it’s on AWS. Thanks

**Comment by vrutkovs** [comment]
What's the output of `oc describe is ruby -n openshift`?

**Comment by vrutkovs** [comment]
lets close it as dupe of #34, might require PRs to https://github.com/openshift/cluster-samples-operator/
