### ISSUE TITLE
systemd-hostnamed may not set hostname due to SELinux permissions

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#709]
### Discussed in https://github.com/openshift/okd/discussions/698

<div type='discussions-op-text'>

<sup>Originally posted by **Bengrunt** June 17, 2021</sup>
Hello there,

**Describe the bug**
We've been running an OKD 4.7 cluster for a few months, carrying out a few updates (stable releases) successfully.
However, when upgrading from 4.7.0-0.okd-2021-05-22-050008 to 4.7.0-0.okd-2021-06-04-191031 a few days ago, the process failed.

The Operator upgrades went well, with all of them succeeding, but the nodes upgrades failed, and we ended up stuck in the middle of the process with one master and one worker node unavailable:

![image](https://user-images.githubusercontent.com/5541437/122401825-3e6b1980-cf7d-11eb-8a74-2c9dc57e89b9.png)

We tried to ssh on the affected nodes to see what happened but the SSH server was not available. Using the hardware console we saw that the machines went through a FCOS upgrade to FCOS 34.20210518.3.0 and after it boots it immediately looses networking connectivity and the hostname of the host gets set to `localhost` (that can be seen on the prompt).

![Clipboard - June 8, 2021 4_58 PM](https://user-images.githubusercontent.com/5541437/122403870-006ef500-cf7f-11eb-81f1-911302dc810e.png)

It seems the issue occurs as soon as we're done with the FCOS 34 boot process.
From then on, we don't really know what we could do and any help would be greatly appreciated.

 * Is it possible to rollback the upgrade process?
 * Can we force the nodes to stay on a specific FCOS version?
 * Can we skip this upgrade to go to the more recent 4.7.0-0.okd-2021-06-13-090745 release? 

**Version**
UPI Baremetal clusters with 3 master and 3 worker nodes running 4.7.0-0.okd-2021-05-22-050008.

**How reproducible**
The issue occurs every time. We tried reinstalling the nodes (PXE installs) from the FCOS 34 image directly but the node ends but downgraded to FCOS 33.20210426.3.0 then back to 34.20210518.3.0 and we loose the connectivity.

**Log bundle**
We cannot complete the `oc adm must-gather` process since it can't reach some of the nodes.
I'll try to gather a console boot log from our remote console.

Thanks a lot ! :)</div>

**Comment by Bengrunt** [comment]
Hello,

How could I check if the nightly build with the fix works ? We'd love to be able to finish this cluster update :)
Thanks a lot for your help @vrutkovs

**Comment by vrutkovs** [comment]
See instructions at https://amd64.origin.releases.ci.openshift.org/releasestream/4.7.0-0.okd/release/4.7.0-0.okd-2021-06-29-103107
