### ISSUE TITLE
Documentation missing for service mesh

### ISSUE THREAD

**Issue by webrod** [openshift/okd#717]
**Describe the bug**

This pages:
https://docs.okd.io/latest/post_installation_configuration/network-configuration.html
says :
"Next steps
Install Red Hat OpenShift Service Mesh in your OKD environment."

The link redirects to:
https://docs.okd.io/latest/service_mesh/v2x/installing-ossm.html#installing-ossm
but this page does not exist. 
So basically there is NO OKD documentation about how to install service mesh.
Only "openshift" has: https://docs.openshift.com/container-platform/4.7/service_mesh/v1x/installing-ossm.html#installing-ossm-v1x

**Version**

OKD latest documentation (4.7 as of now)

**How reproducible**

100%
**Log bundle**

**Comment by vrutkovs** [comment]
Service Mesh has no community counterpart yet, so documentation is hidden.

See #456

**Comment by webrod** [comment]
I'm confused the OKD doc says:
_The following configurations are supported for the current release of Red Hat OpenShift Service Mesh:
Red Hat OKD version 4.x._

so I understand we can use "Red Hat OpenShift Service Mesh" with OKD, can't we? 

also you just provided a link to #456 saying
_Available in Community Catalog
Maistra-Istio Servicemesh Operator (https://github.com/maistra/istio-operator)_

isn't (community) "maistra-istio service mesh" the counterpart of "service mesh"?
