### ISSUE TITLE
Azure: etcd cluster operator: StaticPodsDegraded

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#76]
Hi folks,

I installed

registry.svc.ci.openshift.org/origin/release:4.4.0-0.okd-2020-02-08-183312

on Azure.

After restarting all masters and workers the installation I was able to login to the Console. 

The etcd operator seems to have problems. I got this events in the Cluster Overview:

```
StaticPodsDegraded: pods "etcd-c1-okd4-454td-master-1" not found
StaticPodsDegraded: pods "etcd-c1-okd4-454td-master-0" not found
StaticPodsDegraded: pods "etcd-c1-okd4-454td-master-2" not found
InstallerControllerDegraded: missing required resources: configmaps: config-1,etcd-pod-1
RevisionControllerDegraded: configmaps "etcd-pod" not found
TargetConfigControllerDegraded: "configmap/kube-apiserver-pod": node/c1-okd4-454td-master-1 missing InternalDNS
```

oc adm must-gather results are here:
https://drive.google.com/open?id=1TYfWYnWzo--RqXrfJI16uhORx5YRyviH

Greetz,

Josef

**Comment by jomeier** [comment]
Dupe of https://bugzilla.redhat.com/show_bug.cgi?id=1800313 or https://github.com/openshift/cluster-etcd-operator/pull/103

**Comment by LorbusChris** [comment]
possibly, let's re-test here once that has landed and leave this open for tracking
xref: https://github.com/openshift/okd/issues/13

**Comment by jomeier** [comment]
@LorbusChris  @vrutkovs 
Currently I installed the latest version 

4.4.0-0.okd-2020-02-12-020746

Problem still exists.

```
StaticPodsDegraded: pods "etcd-c3-okd4-x924z-master-0" not found
StaticPodsDegraded: pods "etcd-c3-okd4-x924z-master-1" not found
StaticPodsDegraded: pods "etcd-c3-okd4-x924z-master-2" not found
InstallerControllerDegraded: missing required resources: [configmaps: config-1,etcd-metrics-proxy-client-ca-1,etcd-metrics-proxy-serving-ca-1,etcd-peer-client-ca-1,etcd-pod-1,etcd-serving-ca-1, secrets: etcd-all-peer-1,etcd-all-serving-1,etcd-all-serving-metrics-1]
TargetConfigControllerDegraded: "configmap/kube-apiserver-pod": node/c3-okd4-x924z-master-0 missing InternalDNS
RevisionControllerDegraded: configmaps "etcd-pod" not found
```

**Comment by vrutkovs** [comment]
Pretty sure that's https://bugzilla.redhat.com/show_bug.cgi?id=1801898

**Comment by jomeier** [comment]
Yes. That's it. Seems to be introduced recently.

**Comment by jomeier** [comment]
I tried out 4.4.0-0.okd-2020-02-18-143245 on vSphere. It seems to be fixed. I had the problem on vSphere as well on Azure.
