### ISSUE TITLE
KubeVirt support

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#77]
Looking to add `semanage` binary to fcos so as to allow Kubevirt and other similar solutions to manage selinux labels. 

Currently kubevirt has this PR: https://github.com/kubevirt/kubevirt/pull/2694

However, it would be useful to have `semanage` in general.

**Comment by vrutkovs** [comment]
`semanage` requires python dependencies, which means we'd have to pull in a lot of RPMs one by one and carefully track dependencies. I'm afraid that would be too complicated to manage

**Comment by jdhirst1** [comment]
This problem must have been solved in RHCOS in order to enable openshift-cnv, as it has the same problem. (tested openshift-cnv 2.2 on okd4.4/fcos)
```
{"component":"virt-handler","hostname":"master-2.okd.example.net","level":"info","pos":"virt-handler.go:187","timestamp":"2020-02-10T16:56:45.794105Z"}
panic: failed to list labels: out: "", error: could not find binary semanage

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000246000)
	cmd/virt-handler/virt-handler.go:205 +0x1ea7
main.main()
	cmd/virt-handler/virt-handler.go:468 +0x6e
```

**Comment by vrutkovs** [comment]
Right, RHCOS does include Python and semanage RPMs. However in FCOS-on-OKD4 we'd like to avoid that (services should not rely on specifics of host utils - and we mix in RPMs one by one at the moment, so tracking dependencies would be complex).

`rpm-ostree install <rpm name>` however would work, so that's probably the right way to go about this

**Comment by LorbusChris** [comment]
I believe something like https://github.com/kubevirt/kubevirt/pull/2694 would be a proper solution for this

**Comment by LorbusChris** [comment]
I've renamed this issue - we're not going to include `semanage` in Fedora or OKD's machine-os-content by default.

**Comment by rmohr** [comment]
Note that apart from relabeling we also need to install our own policy, which obviously also does not work in rhcos and fcos. I will redbase https://github.com/kubevirt/kubevirt/pull/2694 but users will right now also have to force kubevirt to use `spc_t` for our workloads (https://github.com/kubevirt/kubevirt/pull/3056). That is of course not an optimal solution, but the best we have right now and you can then at least still leave selinux enabled.

**Comment by vladikr** [comment]
@rmohr installation of new policy does work on rhcos, as demonstrated in [1] - however,
 `semodule` is required 

[1] https://github.com/JAORMX/selinux-operator/blob/master/pkg/controller/configmap/configmap_controller.go#L133

**Comment by rmohr** [comment]
> @rmohr installation of new policy does work on rhcos, as demonstrated in [1] - however,
> `semodule` is required

hm, but we assume semodule and I thought that we fail to install also on rhcos. Would `we` have to ship it or is it on the node?

**Comment by vladikr** [comment]
> hm, but we assume semodule and I thought that we fail to install also on rhcos. Would `we` have to ship it or is it on the node?

All I'm saying is that it's opossible to install on rhcos. This project ships `semodule`, hopefully it will be able in rhcos at some point (so I heard) , but until then, if we want to make it work ourselves `we` will need to ship it...

**Comment by vrutkovs** [comment]
`semodule` requires Python, right? We won't ship python on FCOS

**Comment by vladikr** [comment]
> `semodule` requires Python, right? We won't ship python on FCOS

@vrutkovs `semodule` is written in C, afaik[1]

[1] https://github.com/SELinuxProject/selinux/tree/master/policycoreutils/semodule

**Comment by vrutkovs** [comment]
So which RPM should we include in OKD-on-FCOS to make things work? 

Note that at this point we have to specify every dependency manually from Fedora 31 repos ([list of RPMs already included there](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifest-lock.x86_64.json)) - and we need to add a few more to enable KubeVirt, then it can be done

**Comment by LorbusChris** [comment]
```
$ rpm -qf /usr/sbin/semodule
policycoreutils-2.9-5.fc31.x86_64
```
`semodule` is included in the policycoreutils rpm, which already ships in FCOS (and I would assume in RHCOS as well)

**Comment by LorbusChris** [comment]
So depending on `semodule` would be fine

**Comment by jasonbrooks** [comment]
I was wondering why kubevirt didn't show up in the OperatorHub in my OKD cluster -- I thought something might be misconfigured, but maybe this is the reason?

**Comment by vrutkovs** [comment]
>I was wondering why kubevirt didn't show up in the OperatorHub in my OKD cluster

Its unlikely to be related - probably it was removed from OperatorHub? In any case operatorhub can't hide operators based on packages installed in the OS

**Comment by rajinator** [comment]
@jasonbrooks go to Administration->Global Configuration->OperatorHub->Sources and make sure all sources shown in the image are enabled

![image](https://user-images.githubusercontent.com/26853703/83300280-bb3a2280-a1c5-11ea-8ba8-c53c3b408bd3.png)

**Comment by LorbusChris** [comment]
@vrutkovs this still needs https://github.com/kubevirt/kubevirt/pull/2694 to merge - it won't work as-is afaict.
/reopen

**Comment by vrutkovs** [comment]
Moving this out of Beta6 milestone as OKD did its part and we're waiting for updated KubeVirt operator

**Comment by jasonbrooks** [comment]
I can confirm that Kubevirt is working for me in OKD now.

**Comment by jdhirst1** [comment]
Closing as this issue was previously noted as fixed.
