### ISSUE TITLE
Created new cluster based on  4.7.0-0.okd-2021-07-03-190901 using fedora-coreos-34.20210626.3.1 core os image

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#773]
Created new cluster based on  4.7.0-0.okd-2021-07-03-190901 with latest fedora-coreos-34.20210626.3.1 core OS image.
Still getting errors when I try to deploy an image (see attached). checked all cluster nodes files "/run/systemd/resolve/resolv.conf" & "/etc/resolv.conf" and found they all contain the line "search .". Please advise what I can do to resolve this issue.
![image](https://user-images.githubusercontent.com/23619505/126188515-793ba224-9d13-4d72-8939-d966b2c2e4bd.png)
![image](https://user-images.githubusercontent.com/23619505/126189052-0704c8a8-a839-46d1-986c-b9dbdab17c87.png)

**Comment by vrutkovs** [comment]
Check if you have `fix-resolv-conf-search.service` running on the nodes?

**Comment by johnlongo** [comment]
![image](https://user-images.githubusercontent.com/23619505/126211097-0940708a-6079-43ac-9226-c8cdaa267531.png)

**Comment by johnlongo** [comment]
This is what I see in the files
![image](https://user-images.githubusercontent.com/23619505/126211468-5d9f34cd-bc3d-4093-be27-2db23068d394.png)

**Comment by vrutkovs** [comment]
Interesting, on my nodes resolv.conf starts with `# Generated by NetworkManager`

Does it come back if you remove it manually? Did you restart any services since `fix-resolv-conf-search.service` started?

**Comment by johnlongo** [comment]
I removed the /etc/resolve.conf file from a worker  and rebooted this is how it came back:
![image](https://user-images.githubusercontent.com/23619505/126231959-12cce474-09da-4636-b215-8407a478f0c7.png)

I will do that to all of them and let you know what happens

**Comment by johnlongo** [comment]
Removed  /etc/resolve.conf for all the nodes one by one and rebooted then after each remove. Everything worked I had files where the "search ." line was removed like above. Then I shutdown the cluster and brought it back up and the "search ." line reappeared (see attached)
<img width="1005" alt="Snag_1d2274fd" src="https://user-images.githubusercontent.com/23619505/126358054-f198ddac-49d0-443a-9a10-67d366654197.png">
<img width="1005" alt="Snag_1d22c3c9" src="https://user-images.githubusercontent.com/23619505/126358096-d96ba3ad-ad6e-4626-bcef-fa84f4029daa.png">

**Comment by johnlongo** [comment]
The nodes were created using vSphere ova fedora-coreos-34.20210626.3.1-vmware.x86_64.ova, not sure if that will make a difference but wanted to post it in case it does.

**Comment by johnlongo** [comment]
Updated the cluster to 4.7.0-0.okd-2021-08-07-063045 and checked all 9 nodes for the search line in resolve.conf and found it was not present in all nodes. The I shut down the cluster and took a backup and started it back up. After it came back up I checked all nine nodes (3 master and 6 worker) and did not see the search line in any of the resolve.conf files. see attached. From what I see it looks like the issue is now been fixed so I'm closing it and want to thank you for the help.

![image](https://user-images.githubusercontent.com/23619505/128718883-a134f737-24b8-47fe-821f-2167444353f6.png)

![image](https://user-images.githubusercontent.com/23619505/128718898-c2deabd3-7f00-42e9-8634-0968341ad45c.png)

![image](https://user-images.githubusercontent.com/23619505/128718914-7b08055a-0e90-46a1-a369-7ab3886a0a92.png)

![image](https://user-images.githubusercontent.com/23619505/128718932-1a0ce659-ea53-4c43-9818-fde9903ee42d.png)

![image](https://user-images.githubusercontent.com/23619505/128718952-9fdcd5c0-031b-4b6e-9bea-ea05b04f5b48.png)

![image](https://user-images.githubusercontent.com/23619505/128718989-f0c16d8b-2129-433f-873e-84871552c7c7.png)

![image](https://user-images.githubusercontent.com/23619505/128719023-ab44329e-de87-4182-9602-801811a251b9.png)

![image](https://user-images.githubusercontent.com/23619505/128719045-a834e879-08f8-401a-b917-9fb5d25fa0d8.png)
