### ISSUE TITLE
etcd Cluster Operator wait-for-kube

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#78]
Can we track https://github.com/openshift/cluster-etcd-operator/pull/73 and pull it into the beta?

This currently blocks the ability to restart a cluster an all-master-down scenario as etcd operator waits for kube to come up.

**Comment by vrutkovs** [comment]
Anything except machine-os-content/installer/MCO (and Ironic bits for baremetal IPI) gets into OKD builds once it passes tests in OCP (right after `.ci` is passing tests). So once this PR merges, passes OCP tests OKD release would be updated.

Should we rename this into more generic "when does a particular commit lands in OKD"?

**Comment by jdhirst1** [comment]
Sure; however my question was more like 'should this particular PR be something we consider beta-blocking?'.

**Comment by vrutkovs** [comment]
Oh, I see. Okay, lets use this ticket for tracking then

**Comment by jdhirst1** [comment]
This has been merged and can be closed.
