### ISSUE TITLE
[okd] Fresh install of OKD 4.7 - community operator pod failing with `standard_init_linux.go:228: exec user process caused: exec format error`

### ISSUE THREAD

**Issue by leenooks** [openshift/okd#785]
**Describe the bug**
So I'm new to OKD - and tried an install this week. I'm using PXE installation and got 3 nodes up and running. Noticing a problem with the community operators, I added a worker node (so I only have 1) in case the problem was due to my masters also being workers.

Here is the problem:
![image](https://user-images.githubusercontent.com/131527/126592896-67a200eb-261c-42be-acfb-20ccac3c5565.png)

I got here, because I wanted to go through the "quick start" to deploy the Container Storage Operators and couldnt get past the first instruction which is navigating to Operators -> Operator Hub (which the nothing here - install it page shows). 

When I look at the pod's log, it shows `standard_init_linux.go:228: exec user process caused: exec format error` (which to me is normally an indicator of the wrong architecture being run - so not sure why that would be the case). 

**Version**
4.7.0-0.okd-2021-07-03-190901

This is all VMs on ESXi running CoreOS downloaded this week.

So a) I thought it might be useful in case some body else has this challenge, and b) how do I reload the image that the pod uses? I know docker, but I dont know Openshift. :)

Thanks...

**Comment by myg0v** [comment]
This issue seems to be since yesterday. We see this also on 5 different OKD cluster with latest 4.7.0-0.okd-2021-07-03-190901.
I tried already to delete this CrashLooping pod, without success.

```
oc -n openshift-marketplace get events --sort-by='.metadata.managedFields[0].time'
m55s       Normal    Scheduled        pod/community-operators-gbjjl   Successfully assigned openshift-marketplace/community-operators-gbjjl to k8s-worker-8-01.okd.***.***.***
5m53s       Normal    AddedInterface   pod/community-operators-gbjjl   Add eth0 [10.234.1.136/23]
4m50s       Normal    Pulling          pod/community-operators-gbjjl   Pulling image "registry.access.redhat.com/redhat/community-operator-index:v4.7"
5m50s       Normal    Pulled           pod/community-operators-gbjjl   Successfully pulled image "registry.access.redhat.com/redhat/community-operator-index:v4.7" in 3.615410937s
4m47s       Normal    Started          pod/community-operators-gbjjl   Started container registry-server
4m47s       Normal    Created          pod/community-operators-gbjjl   Created container registry-server
5m46s       Normal    Pulled           pod/community-operators-gbjjl   Successfully pulled image "registry.access.redhat.com/redhat/community-operator-index:v4.7" in 3.067923536s
52s         Warning   BackOff          pod/community-operators-gbjjl   Back-off restarting failed container
5m23s       Normal    Pulled           pod/community-operators-gbjjl   Successfully pulled image "registry.access.redhat.com/redhat/community-operator-index:v4.7" in 2.7133503s
4m48s       Normal    Pulled           pod/community-operators-gbjjl   Successfully pulled image "registry.access.redhat.com/redhat/community-operator-index:v4.7" in 2.788870806s
2m41s       Normal    Scheduled        pod/redhat-operators-8pqgc      Successfully assigned openshift-marketplace/redhat-operators-8pqgc to k8s-worker-4-01.okd.***.***.***

```

**Comment by ssams** [comment]
Experiencing this issue on two clusters - versions _4.7.0-0.okd-2021-06-19-191547_ and _4.7.0-0.okd-2021-07-03-190901_. Failing container _registry_server_ in the Pod is using the image _registry.access.redhat.com/redhat/community-operator-index:v4.7_. As indicated in the initial description it seems related to an architecture issue with the image, running it locally via Docker gives me the following error message:
```
❯ docker run --rm -it     registry.access.redhat.com/redhat/community-operator-index:v4.7
WARNING: The requested image's platform (linux/s390x) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```
Did the default platform get messed up, or maybe it did not get built/published for amd64 correctly?

**Comment by vrutkovs** [comment]
By mistake `ppc64le` version was pushed, sorting this out

**Comment by vrutkovs** [comment]
`registry.access.redhat.com/redhat/community-operator-index:v4.7` was reverted to x86_64 arch.
I'll keep the ticket open in case this regresses in the next few days

**Comment by ssams** [comment]
> `registry.access.redhat.com/redhat/community-operator-index:v4.7` was reverted to x86_64 arch.

Seems to have worked on our clusters, Pods already recovered.

**Comment by leenooks** [comment]
Thank you - this seems to fix that issue I was having.

What prompted me to open this ticket was I was following the quickstart `Install the OpenShift® Container Storage Operator` - now that tile for OCS seems to have disappeared. Could it have been something I did? (I tried a few things to get that community operator running.)

**Comment by vrutkovs** [comment]
No issues so far, closing
