### ISSUE TITLE
 Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.

### ISSUE THREAD

**Issue by ssbano** [openshift/okd#80]
./openshift-install create cluster
? Platform aws
? Region us-east-1
?
INFO Creating infrastructure resources...
ERROR
ERROR Error: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
ERROR   status code: 400, request id: 03c4f08f-f29b-49f9-bc1f-7de38c82516e
ERROR
ERROR   on ../tmp/openshift-install-986803207/vpc/vpc-public.tf line 68, in resource "aws_eip" "nat_eip":
ERROR   68: resource "aws_eip" "nat_eip" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform

**Comment by vrutkovs** [comment]
See https://docs.openshift.com/container-platform/4.2/installing/installing_aws/installing-aws-account.html#installation-aws-limits_installing-aws-account

**Comment by ssbano** [comment]
> See https://docs.openshift.com/container-platform/4.2/installing/installing_aws/installing-aws-account.html#installation-aws-limits_installing-aws-account

The installer using openshift 4.3 works perfectly but the okd preview happens this error

Best Regards,
Fábio Sbano
