### ISSUE TITLE
Upgrade to 4.7.0-0.okd-2021-08-07-063045 failling

### ISSUE THREAD

**Issue by globaldyne** [openshift/okd#810]
**Describe the bug**
Upgrade from 4.7.0-0.okd-2021-07-03-190901 to 4.7.0-0.okd-2021-08-07-063045 failing with service-ca error
  
    Error: container has runAsNonRoot and image will run as root

**Version**
 4.7.0-0.okd-2021-08-07-063045

**Comment by vrutkovs** [comment]
Please attach (or upload to the public file sharing service) [must-gather](https://docs.okd.io/latest/support/gathering-cluster-data.html#support_gathering_data_gathering-cluster-data) archive

**Comment by globaldyne** [comment]
File link
https://drive.google.com/file/d/16NRwpPX9xOp7AJy2YtPa6xA9kHgViHWT/view?usp=sharing

**Comment by vrutkovs** [comment]
>openshift.io/scc: anyuid

was selected for `service-ca-df5c9b4f-9jv8d` pod instead of

> openshift.io/scc: restricted

passing it to @stlaz

**Comment by globaldyne** [comment]
Any workaround for this?

**Comment by globaldyne** [comment]
Resolved by referring to this https://access.redhat.com/solutions/5875621

**Comment by drod0258** [comment]
It also looks like this might be a related issue to BZ#1914446 that was resolved and released with v4.8: https://bugzilla.redhat.com/show_bug.cgi?id=1914446.

**Comment by LorbusChris** [comment]
> Resolved by referring to this https://access.redhat.com/solutions/5875621

/close
