### ISSUE TITLE
OKD4.7 offline installation(openstack)

### ISSUE THREAD

**Issue by Mohammed-Idrees** [openshift/okd#861]
Hi Team,
I'm trying to install OKD 4.7 (4.7.0-0.okd-2021-05-22-050008) using mirror registry for offline installation(no internet), I'm able to see bootstrap node is able to pull the images from the mirror registry and when I execute "openshift-install --dir=install_dir/ wait-for bootstrap-complete --log-level=debug" command I'm able to see API is up but the master nodes are not able to pull the images from the mirror registry and I'm not able to ssh to any of the master nodes. is it possible to install OKD4.7 on a cluster without internet?

![image](https://user-images.githubusercontent.com/36164488/132165213-820b6105-d736-4252-98c7-053533d15c86.png)

**Comment by vrutkovs** [comment]
Please attach [log bundle](https://docs.okd.io/latest/installing/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting)

>the master nodes are not able to pull the images from the mirror registry

On this screen master is unable to provision at all

**Comment by Mohammed-Idrees** [comment]
Hi @vrutkovs 

Please find the attached log bundle.
[log-bundle-20210906113141.tar.gz](https://github.com/openshift/okd/files/7115737/log-bundle-20210906113141.tar.gz)

**Comment by Mohammed-Idrees** [comment]
Hi @vrutkovs 

Is this a bug/ known issue? is there any workaround for this?
can you please let me know any solution on this.

**Comment by vrutkovs** [comment]
No data collected from masters and apparently these never requested their Ignition.

Check LB configuration and network settings for masters
