### ISSUE TITLE
The pipelines page turn to blank when there is pipeline defined

### ISSUE THREAD

**Issue by vincent-pli** [openshift/okd#863]
**Describe the bug**

I'm not sure if it's right place to report the issue, but it really suffer me.
that's the page when there is no `pipeline` defined, looks normal
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/8669744/132507916-3a64f391-4f07-42d5-b18a-92a6cb490bfb.png">

but if any `pipeline` defined, no matter on UI or by CLI, the page will turn to blank
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/8669744/132508142-ad06620f-c818-4c18-942d-e22e16403a73.png">

I'm not expert for GUI, so any suggestion or what's the right place to raise the issue? thanks

**Version**

OpenShift Version
4.6.42
Kubernetes Version
v1.19.0+4c3480d

**How reproducible**

**Log bundle**

**Comment by vrutkovs** [comment]
Please file a new [https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform](bug) for "Dev Console" component
