### ISSUE TITLE
Kernel freeze when running BuildConfig Pods on version 4.7.0-0.okd-2021-08-22-163618

### ISSUE THREAD

**Issue by spasche** [openshift/okd#864]
**Describe the bug**

We have a cluster with user provisioned infrastructure using libvirt KVM virtual machines.

After updating to version 4.7.0-0.okd-2021-08-22-163618, some of the Nodes were becoming NotReady.
When that happens, the node is consuming 100% and doesn't respond to ping or from input in the console.
This is a regression, we didn't have such issue with the previous version 4.7.0-0.okd-2021-08-07-063045.

I noticed that the issue is triggered when running BuildConfig Pods on the node (testcase below).

Just before the node is unresponsive, there are still plenty of resources available (CPU, memory, disk).

According to the console output, it looks like a kernel panic is happening. Unfortunately, the panic message is not printed to the console, the last available line is the `cut here` message. For instance:
```
[  729.229244] audit: type=1138 audit(1631135817.973:413): pid=11270 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:spc_t:s0 msg='sw="libblkid-2.23.2-65.el7_9.1.x86_64" sw_type=rpm key_enforce=0 gpg_res=1 root_dir="/" comm="yum" exe="/usr/bin/python2.7" hostname=? addr=? terminal=? res=success'
[  731.433044] audit: type=1138 audit(1631135820.177:414): pid=11067 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:spc_t:s0 msg='sw="libblkid-2.23.2-65.el7_9.1.x86_64" sw_type=rpm key_enforce=0 gpg_res=1 root_dir="/" comm="yum" exe="/usr/bin/python2.7" hostname=? addr=? terminal=? res=success'
[  735.719951] audit: type=1138 audit(1631135824.464:415): pid=11270 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:spc_t:s0 msg='sw="pam-1.1.8-23.el7.x86_64" sw_type=rpm key_enforce=0 gpg_res=1 root_dir="/" comm="yum" exe="/usr/bin/python2.7" hostname=? addr=? terminal=? res=success'
[  738.137203] audit: type=1138 audit(1631135826.881:416): pid=11067 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:spc_t:s0 msg='sw="pam-1.1.8-23.el7.x86_64" sw_type=rpm key_enforce=0 gpg_res=1 root_dir="/" comm="yum" exe="/usr/bin/python2.7" hostname=? addr=? terminal=? res=success'
[  741.316403] ------------[ cut here ]------------
```

**Version**

4.7.0-0.okd-2021-08-22-163618, UPI, libvirt.

**How reproducible**

Happens most of the time when running the testcase below.

```
oc apply -f - <<"EOF"
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: testcase
spec:
  output:
    to:
      kind: DockerImage
      name: your-registry.example.com/testcase:test
  source:
    type: Dockerfile
    dockerfile: |
      FROM centos:7

      RUN yum update -y && \
        yum -y groups install "GNOME Desktop"
  strategy:
    type: Docker
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
EOF
oc start-build bc/testcase
```

**Log bundle**

Must-gather logs: https://1drv.ms/u/s!AloPbwYP-ZZVhYQZSIr6GyZYnxCQow

**Comment by vrutkovs** [comment]
We consume Fedora kernel, so it needs to be reported there.

Lets leave this bug as a tracker

**Comment by depouill** [comment]
Hi,

We have excatly same problem here when updating to 4.7.0-0.okd-2021-08-22-163618.
Bare-metal nodes suddenly freeze on starting pods with message like (appear  not every time):
```
[Mon Sep 13 23:16:13 2021] ------------[ cut here ]------------
[Mon Sep 13 23:16:13 2021] rq->tmp_alone_branch != &rq->leaf_cfs_rq_list
[Mon Sep 13 23:16:13 2021] WARNING: CPU: 112 PID: 0 at kernel/sched/fair.c:401 enqueue_task_fair+0x26f/0x6a0
```

**Comment by spasche** [comment]
Issue is fixed with kernel 5.14.14-200.fc34.x86_64, available since OKD 4.8.0-0.okd-2021-11-14-052418.

**Comment by bo0ts** [comment]
@spasche @vrutkovs Any chance this going to be backported to OKD 4.7?

**Comment by vrutkovs** [comment]
Latest OKD 4.7 should include kernel-5.14.14-200.fc34.x86_64
