### ISSUE TITLE
vSphere: machine-config-operator degraded

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#87]
Hi,

4.4.0-0.okd-2020-02-25-003044

shows a degraded machine-config-operator:
```
Failed to resync 4.4.0-0.okd-2020-02-25-003044 because: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: configuration status for pool master is empty: pool is degraded because nodes fail with "3 nodes are reporting degraded status on sync": "Node chmuokd4c2master1 is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-8bd6f27c8029fb358c8835dabc9b4b54\\\" not found\", Node chmuokd4c2master2 is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-8bd6f27c8029fb358c8835dabc9b4b54\\\" not found\", Node chmuokd4c2master0 is reporting: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-8bd6f27c8029fb358c8835dabc9b4b54\\\" not found\"", retrying
```

I saw this on two clusters: with and without corporate proxy.

must-gather for openshift-machine-config-operator:
https://drive.google.com/open?id=1LUqusoSMx8-U_wfCZc_-aC2R-HmMpZRb

Discussion:
https://kubernetes.slack.com/archives/C6BRQSH2S/p1582643088050500

Thanks and greetings,

Josef

**Comment by LorbusChris** [comment]
This _should_ be fixed by the upcoming fcos rebase. Let's keep this open until confirmed

**Comment by jomeier** [comment]
This seems to be related:  https://bugzilla.redhat.com/show_bug.cgi?id=1806403

**Comment by jomeier** [comment]
I just saw that I had pending CSRs for one of my workers. One pod of the machine-config-daemon daemon showed TLS errors.

After I approved the CSRs all pods of the daemon set seem to have come up.

Now I'm trying to get the machine-config cluster operator trying again to update.

**Comment by vrutkovs** [comment]
Is this still an issue? Worker CSR need to be confirmed manually in UPI mode

**Comment by jomeier** [comment]
Yes it degrades sometimes. Not on every update.

**Comment by jomeier** [comment]
I will reevaluate it if MCO rebase has occured. Maybe that fixes the issues.

**Comment by adarshaj** [comment]
I am adding more information which was relevant while upgrading from `4.4.0-0.okd-2020-03-14-003840` to version `4.4.0-0.okd-2020-03-23-055059` (and `4.4.0-0.okd-2020-03-21-112849`). 

MCD on the worker nodes were able to reboot into the new config, however, in the master pool, all master nodes reported : `unexpected on-disk state validating against rendered-master-b73ccd6d224db08e405f4bc42c4a7c4e`. On further inspection by ssh'ing into one of master node, I found that the MCD pod was reporting:
```
E0323 00:57:53.718885  125177 writer.go:130] Marking Degraded due to: unexpected on-disk state validating against rendered-master-b73ccd6d224db08e405f4bc42c4a7c4e
I0323 00:58:53.759489  125177 daemon.go:725] Current+desired config: rendered-master-b73ccd6d224db08e405f4bc42c4a7c4e
I0323 00:58:53.775541  125177 daemon.go:959] Validating against current config rendered-master-b73ccd6d224db08e405f4bc42c4a7c4e
E0323 00:58:53.778455  125177 daemon.go:1351] content mismatch for file /usr/local/bin/etcd-snapshot-restore.sh
```
On manually checking the content of file at `/usr/local/bin/etcd-snapshot-restore.sh`, I could see that the version on disk was exactly like the file at https://github.com/openshift/cluster-etcd-operator/blob/e36a02f044f191b9959ab72c9769c0a042c03bf3/bindata/etcd/etcd-snapshot-restore.sh . However, the expected file in the files section of rendered-master machineconfigs was supposed to be the file at: https://github.com/openshift/machine-config-operator/blob/2d7ff58a4bb52241931dfa614c34342b5b70191c/templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml (fcos branch of MCO)

I could not understand why the difference existed. I could not gather the `must-gather` as I had forced upgrade to another version in the meantime.

**Comment by jomeier** [comment]
I just found out that some of my update problems that occured rather often have to do with hostnames that have a double entry in our DNS server.

I will double check that in the future and see if my update problems disappear. I'll update this issue if I have news.

**Comment by vrutkovs** [comment]
Lets file a new issue if that still happens
