### ISSUE TITLE
Documentation says MachineConfig/system-reserved will show in ps -ef but it's in kubelet.conf

### ISSUE THREAD

**Issue by smuda** [openshift/okd#872]
**Describe the bug**
[Documentation](https://docs.okd.io/latest/nodes/nodes/nodes-nodes-resources-configuring.html) specifies that configured system-reserved values can be observed by running `ps -ef | grep kubelet` and observing the startup parameter `--system-reserved`.

However, on a configured system those parameters does not go into the startup parameters:
```
$ oc debug node/master0.ocp4.example.com -- ps -ef | grep ' kubelet '
Starting pod/master0ocp4examplecom-debug ...
To use host binaries, run `chroot /host`
root        1680       1  9 03:43 ?        00:03:41 kubelet --config=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --runtime-cgroups=/system.slice/crio.service --node-labels=node-role.kubernetes.io/master,node.openshift.io/os_id=fedora --node-ip=192.168.60.180 --minimum-container-ttl-duration=6m0s --cloud-provider= --volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec --register-with-taints=node-role.kubernetes.io/master=:NoSchedule --pod-infra-container-image=quay.io/openshift/okd-content@sha256:289da7c88de628a2cf9b45143053908581a3a7c05a36d8160beaa04b6f30743e --v=2

Removing debug pod ...
```

Instead, the values goes into /etc/kubernetes/kubelet.conf:
```
$ oc debug node/master0.ocp4.example.com -- cat /host/etc/kubernetes/kubelet.conf 
Starting pod/master0ocp4examplecom-debug ...
To use host binaries, run `chroot /host`
{
  "kind": "KubeletConfiguration",
  "apiVersion": "kubelet.config.k8s.io/v1beta1",
  "staticPodPath": "/etc/kubernetes/manifests",
  ...
  "systemReserved": {
    "cpu": "1000m",
    "ephemeral-storage": "1Gi",
    "memory": "3Gi"
  },
  ...
}

Removing debug pod ...
```

One piece of information also missing in the documentation is from what version of OKD the autoSizingReserved keyword is supposed to work. By comparing [OCP4.7](https://docs.openshift.com/container-platform/4.7/nodes/nodes/nodes-nodes-resources-configuring.html) and [OCP4.8](https://docs.openshift.com/container-platform/4.8/nodes/nodes/nodes-nodes-resources-configuring.html) I assume it requires OKD 4.8 but the documentation does not mention system requirements.

**Version**
4.7.0-0.okd-2021-08-22-163618 on bare-metal, installed according with [my ansible script](https://github.com/AyoyAB/okd-with-ansible)

**How reproducible**
100% both times I reinstalled. 

**Log bundle**
If you really want a log bundle, let me know and I'll publish one.

**Comment by vrutkovs** [comment]
Documentation for okd.io is alway pointing to latest available, which is OKD 4.8
