### ISSUE TITLE
ingress ignores timeout settings with more than 60 seconds

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openshift/okd#874]
**Describe the bug**
We run OKD clusters (currently 4.7-2021-07-03) on vSphere UPI.
Our developers run one service which when called very often needs more than a minute to respond with a result, due to very complicated calculations and database queries.
When the service is called from within the cluster from another workload, the call takes as long as it needs and all is fine.
But when the service is called from outside the cluster through an ingress, with the default ingress timeout setting, it would usually fail with a timeout.
So our developers set a (higher) custom timeout value like this on the ingress object:

```
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 300s
```

The developers now reported to us that "since a while", which according to them means "probably since two or three months", the timeout value is capped at 60s. That means when they set a value of up to 60s, a timeout happens after the specified value. But if they set any higher value than 60s, the timeout always happens after 60s. The developers say that "this was working fine before" - see above for time frame.

To let us reproduce, the developers gave us a simple Spring Boot "timeout" sample application that we could deploy on other clusters. We did so and can reproduce the problem on all OKD clusters.
We even threw this at a current OCP 4.7.23 cluster and see the same problem there but there the timeout is capped at already 30s.

**Version**
OKD 4.7-2021-07-03
but happens already since (probably 2021-03-28 but this is an estimate)

**How reproducible**
100%

**Log bundle**
Would a must-gather help here at all?
Just let me know and I will provide what ever logs you ask for.

**Comment by kai-uwe-rommel** [comment]
Is there a trick about configuring a higher ingress timeout through some other value?
Or is this really a bug that needs to be fixed in order to use higher timeouts?

**Comment by vrutkovs** [comment]
Is this OKD-specific? I think it best be filed in bugzilla

**Comment by kai-uwe-rommel** [comment]
A similar problem happens on OCP, but the actual timeout is different (even only 30s).
So there may be differences in the implementation.

**Comment by kai-uwe-rommel** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2004955

**Comment by kai-uwe-rommel** [comment]
We finally found out, that it was a problem of the load balancer which runs in front of the cluster.
