### ISSUE TITLE
No releases is available of latest available version

### ISSUE THREAD

**Issue by smuda** [openshift/okd#882]
According to #872 the latest available version of OKD is 4.8 but there is no releases for 4.8 under [releases](https://github.com/openshift/okd/releases).

Suggestion would be to always publish releases of the latest available version, at least once.

**Comment by JaimeMagiera** [comment]
He was referring to nightly builds. Though we don't have a 4.8 release yet, there are[ 4.8 nightly builds](https://amd64.origin.releases.ci.openshift.org/#4.8.0-0.okd). Note that each nightly build is pruned after 72 hours.

**Comment by smuda** [comment]
I see, my bad of course. 

IMHO the documentation should state what version it applies to, especially when beta-versions are overwriting released versions. The kubernetes documentations has a ["Feature state"](https://kubernetes.io/docs/concepts/security/pod-security-admission/) headline on many pages where it says från what version it's for example alpha. That would of course be sufficient. But one project that really shine in this area is OpenShift where they (you?) have a different documentation set depending on version. I really like that.

I propose that I close this issue, re-open #872 and change that to a generic request for version information in the documentation. What do you think?

**Comment by JaimeMagiera** [comment]
Tomorrow is the OKD Documentation Subgroup meeting. I'll bring this up and get a sense of what folks think is a good path forward. I'll report back here.
