### ISSUE TITLE
SELinux denials for iptables on Fedora CoreOS 34

### ISSUE THREAD

**Issue by sandrobonazzola** [openshift/okd#895]
**Describe the bug**
SELinux denials for iptables on Fedora CoreOS 34 - Reported to Fedora:

[Bug 2008097](https://bugzilla.redhat.com/show_bug.cgi?id=2008097) - **AVC Denial on iptables / ip6tables on Fedora CoreOS 34**

**Version**
4.8.0-0.okd-2021-09-26-121959 / Fedora CoreOS 34 OSTREE_VERSION='49.34.202109261048-0'

**How reproducible**
bare metal UPI deploymnet, bootstrap machine.

**Comment by gjsmo** [comment]
Can confirm this is an install blocker on oVirt with IPI as well.

**Comment by a2902793** [comment]
Workaround borrowed from [here](https://bugzilla.redhat.com/show_bug.cgi?id=1927639) 
1. Manually create policy file
    ```
    echo '(allow iptables_t cgroup_t (dir (ioctl)))' > local_iptables.cil
    ```
2. SCP the policy file to the problematic nodes
3. Install the policy module on all the problematic nodes
    ```
    sudo semodule -i ~/local_iptables.cil
    ```
