### ISSUE TITLE
Support for vSphere

### ISSUE THREAD

**Issue by Reamer** [openshift/okd#9]
Hi okd working group,
After some initial problems `pull-secret={"auths":{"fake":{"auth": "bar"}}}`, I was able to install okd 4.3 on vsphere. I followed this (OpenShift 4.2 vSphere Install Quickstart)[https://blog.openshift.com/openshift-4-2-vsphere-install-quickstart/]
I encountered the following issues. The image registry was not able to start, because of a missing (ReadWriteMany) persistent storage (PV). After changing the storage to empty dir 
`oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'`
and
`oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState": "Managed"}}'`
 (Value before `Removed`) the image registry was able to launch.

Now I'll deep dive into okd4. Thanks to @LorbusChris for fast help via chat.

Best Regards
Reamer

**Comment by DanyC97** [comment]
thanks @Reamer for taking the time to test and also provide feedback. I guess there is no followup needed here in which case @LorbusChris  we need to think on a process to maybe add a label like `note` or s'thing which should provide folks the message that there is nothing to follow up/ action on it

**Comment by DanyC97** [comment]
Related to https://github.com/openshift/okd/issues/14 provider

**Comment by LorbusChris** [comment]
Closing in favor of #14
