### ISSUE TITLE
Upgrade from 4.7.0-0..... to 4.8.0-0... updates k8s to v1.22.1 (and not v1.21) ?

### ISSUE THREAD

**Issue by titou10titou10** [openshift/okd#908]
I'm confused after having updated OKD from **4.7.0-0.okd-2021-09-19-013247 to 4.8.0-0.okd-2021-10-01-221835**
We were expecting k8s to be upgraded from **v1.20 to v1.21** but k8s is now **v1.22.1** !

    oc get clusterversion
    NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
    version   4.8.0-0.okd-2021-10-01-221835   True        False         19h     Cluster version is 4.8.0-0.okd-2021-10-01-221835

    oc get nodes
    NAME              STATUS   ROLES          AGE    VERSION
    oc4-master1.<x>   Ready    master         257d   v1.22.1+8719299-1678
    oc4-master2.<x>   Ready    master         257d   v1.22.1+8719299-1678
    oc4-master3.<x>   Ready    master         257d   v1.22.1+8719299-1678
    oc4-worker1.<x>   Ready    infra,worker   257d   v1.22.1+8719299-1678
    oc4-worker2.<x>   Ready    infra,worker   257d   v1.22.1+8719299-1678
    oc4-worker3.<x>   Ready    worker         257d   v1.22.1+8719299-1678

    oc describe node oc4-worker3.<x>
    System Info:
      Kernel Version:                         5.13.14-200.fc34.x86_64
      OS Image:                               Fedora CoreOS 34
      Operating System:                       linux
      Architecture:                           amd64
      Container Runtime Version:              cri-o://1.22.0
      Kubelet Version:                        v1.22.1+8719299-1678
      Kube-Proxy Version:                     v1.22.1+8719299-1678

    oc version
    Client Version: 4.8.0-0.okd-2021-10-01-221835
    Server Version: 4.8.0-0.okd-2021-10-01-221835
    Kubernetes Version: v1.21.2-1503+a620f506e95653-dirty <------ different from OKD!

It seems the upgrade is a mix of v4.8 and v4.9...

Amongst many other signs of the mix, the CatalogSource`openshift-marketplace/redhat-operators`has been updated to point to 

     registry.redhat.io/redhat/redhat-operator-index:v4.9

Also the OKD documentation (https://docs.okd.io/latest) is also a mix of v4.8 and v4.9. Just enter "4.9" into the search box to find many pages referencing v4.9

As for the update channel, in the v4.7 console there was a drop-down list to choose the channels (stable-4.7..) now it is a free text. 
Q:
- is k8s v1.22.1 for OKD v4.8...the correct version for k8s?
- what about the mix of versions in the documentation?
- where to find the list of available update channels for v4.8?  

OKD is installed on "baremetal" (Proxmox VMs) in UPI mode. The cluster has been installed with v4.6, upgraded to 4.7 and now v4.8

**Comment by vrutkovs** [comment]
Yup, we messed up `machine-os-content` and 4.9 version got promoted.
It should be safe to revert back to 1.21

**Comment by vrutkovs** [comment]
It can't be done manually at this point.
We'll need to [remove automated promotion jobs](https://github.com/openshift/release/pull/20134) (which caused the issue) - and update okd-machine-os, stay tuned.

**Comment by vrutkovs** [comment]
Resolved in 4.8 nightlies.

>Also related to this issue is that the community-operators CatalogSource is using the 4.9 endpoint

https://github.com/openshift/release/pull/22390 would fix that

**Comment by titou10titou10** [comment]
Upgrading to`4.8.0-0.okd-2021-10-10-030117` seems to have solved all the problems
k8s version is fine now and the index for the CatalogSource for redhat operators is ok now. 

    oc get clusterversion
    NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
    version   4.8.0-0.okd-2021-10-10-030117   True        False         6m28s   Cluster version is 4.8.0-0.okd-2021-10-10-030117

    oc describe node oc4-worker3.<x>
    
    System Info:
      Kernel Version:                         5.13.13-200.fc34.x86_64
      OS Image:                               Fedora CoreOS 34
      Operating System:                       linux
      Architecture:                           amd64
      Container Runtime Version:              cri-o://1.21.3
      Kubelet Version:                        v1.21.2+a620f50-1503
      Kube-Proxy Version:                     v1.21.2+a620f50-1503

**Comment by vrutkovs** [comment]
That's great to hear, closing the bug
