### ISSUE TITLE
Etcd operator in 4.8 no longer supports --boostrap-ip option

### ISSUE THREAD

**Issue by stujb** [openshift/okd#910]
**Describe the bug**
In this documentation here https://github.com/openshift/okd/blob/35281e54d16dd6f8217c2067d677fa4db01a794d/Guides/UPI/baremetal/nodes-custom-ip.md#configure-etcd-bootstrap there is a process described to set the etcd bootstrap ip to one other than the first in a list of the network interfaces. We were successfully using this on OKD 4.7.

We have attempted to use the same method in OKD 4.8 and are getting an error in bootkube.sh output stating `bootkube.sh[4050]: unknown flag: --bootstrap-ip`

It appears that this flag has been removed from the etcd operator - https://github.com/openshift/cluster-etcd-operator/commit/79a173702a820064738b802f263763695f1601d1

Assumption is that OKD 4.7 does not consume this commit but OKD 4.8 does. 

How to set the bootstrap ip for etcd to the desired IP that is not the first in the list of network interfaces ?

**Version**
4.8.0-0.okd-2021-10-01-221835
UPI install using bare-metal method on Digitial Ocean

**How reproducible**
100% works on OKD4.7
100% fails on OKD4.8

Have raised bug with same description in cluster-etcd-operator repository at https://github.com/openshift/cluster-etcd-operator/issues/685

**Comment by stujb** [comment]
I have been able to get the build working on okd4.8 by simply removing the patch from the bootkube.sh that added the --boostrap-ip option. I am fairly sure this wasn't working without this on okd4.7 so may be further updates in etcd operator have ensured the private ip is used as per the machineNetwork CIDR defined in the install-config

Will leave this open as a bug as the linked documentation page in this repo should be updated to reflect the fact the --bootstrap-ip is not available in okd4.8

**Comment by vrutkovs** [comment]
@GingerGeek would you have time to update the referenced guide for 4.8 any time soon?

If not I think we'll just leave a note that the guide was created at 4.6 and some parts of it may no longer be valid
