### ISSUE TITLE
Problems with Disconnected/Restricted Network Mirroring Steps

### ISSUE THREAD

**Issue by DizzyThermal** [openshift/okd#913]
The disconnected/restricted mirroring steps appear to be a mix of OCP and OKD documentation:

https://docs.okd.io/latest/installing/installing-mirroring-installation-images.html#installation-mirror-repository_installing-mirroring-installation-images

For example, it tells the reader to view both:
https://access.redhat.com/downloads/content/290/
and
https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags

to determine an **OCP_RELEASE** tag (i.e., 4.5.4).
From experience, I know that **OCP_RELEASE** is looking for the full tag (i.e.,: 4.7.0-0.okd-2021-09-19-013247).

I use an online VM to [1] mirror the images for a release to a directory, I transfer it to a VM in a restricted network with both docker and a registry:2 running and [2] upload the images to the local docker registry running:

[1]
`oc adm release mirror -a ${LOCAL_SECRET_JSON} --to-dir=${REMOVABLE_MEDIA_PATH}/mirror quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}`

[2]
`oc image mirror -a ${LOCAL_SECRET_JSON} --from-dir=${REMOVABLE_MEDIA_PATH}/mirror "file://openshift/release:${OCP_RELEASE}*" ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}`

After this, I see the docker registry contents in the persistent volume mount to the registry:2 docker registry container.

My install-config.yaml also has the imageContentSources block so it can use my mirror instead of quay.io.

Bootstrap node is complaining about manifests being unknown:
`ERRO[1831] response completed with error auth.user.name=admin err.code="manifest unknown" err.detail="unknown manifest name=okd4 revision=sha256:dbf65<snip>34209" err.message="manifest unknown" ... response.status=404`

I've done this process with the past 3 Release Tags - I'm also aware that the first release of 4.8.0 will not work because of v2/s2 Digest errors: https://github.com/openshift/okd/discussions/904#discussioncomment-1420766

I'm not sure the proper procedure to mirror without running into manifest issues. Is there something I'm doing wrong in the mirroring process?

Thank you

**Comment by DizzyThermal** [comment]
Definitely hitting some sort of cached/expected tag/manifest..

Using both commands above with **OCP_RELEASE** of: **4.7.0-0.okd-2021-08-22-163618**

After bringing the REMOVABLE_MEDIA directory to our restricted network, the bootstrap node is complaining about manifest unknown for: **sha256:dbf6525b1580c9cf0d03b8841b6f9b0a9c05dc306a825bc66d37ab0c9d342094**

That sha256 sum is for the _next_ release of OKD ([4.7.0-0.okd-2021-09-19-013247](https://github.com/openshift/okd/releases/tag/4.7.0-0.okd-2021-09-19-013247))

I am removing my **okd-install** directory (where the manifests/ignition configs are created) between each deployment attempt..

FCOS: 33.20210217.3.0 (IIRC there was an issue preventing me from using a newer version, but has since been resolved).

Maybe something else is dirty/stale and needs to be cleaned up?

Any help would be appreciated, thanks

**Comment by DizzyThermal** [comment]
That version was coming from my oc/kubectl/openshift-install binaries.. I've made sure that the binary tarball matches the tag I'm attempting to deploy. Will update with my results (pass/fail) after my next attempt.

Sorry for the noise, hope this helps others with debugging their restricted/disconnected deployments.

**Comment by mschauf** [comment]
also hitting this
