### ISSUE TITLE
Feature request: Show banners defined by ConsoleNotification CR also in CLI

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#93]
Hi,

I love the ConsoleNotification feature where custom banners are presented to the users (can do a 'We'll do maintenance on this cluster in two weeks' stuff).

Would it be possible to also show a banner after logging in to a console on the terminal with the CLI oc or kubectl ? It would be useful to notify our console hackers about maintanance tasks :-)

```
> oc login ... 

Message: The cluster okd4.c1.dev will get planned maintenance in two weeks.

> 
```

Greetings,

Josef

**Comment by LorbusChris** [comment]
Hi Josef,
could I ask you to open an issue against www.github.com/openshift/oc for this? 

Thank you !

**Comment by jomeier** [comment]
Hi Christian,

thanks for your feedback. Is done.

Greetings,

Josef

**Comment by LorbusChris** [comment]
Thank you @jomeier!
xref: https://github.com/openshift/oc/issues/344
