### ISSUE TITLE
Newly bootstrapped cluster not approving worker CSRs

### ISSUE THREAD

**Issue by SriRamanujam** [openshift/okd#94]
As the title says, I attempted to bootstrap a cluster using `openshift-install-4.4.0-0.okd-2020-03-08-163730` retrieved from https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-03-08-163730. The masters came up, but the cluster is not approving the workers' CSRs.

[must-gather.tar.gz](https://github.com/openshift/okd/files/4303990/must-gather.tar.gz)

**Comment by vrutkovs** [comment]
https://docs.openshift.com/container-platform/4.3/installing/installing_bare_metal/installing-bare-metal.html#installation-approve-csrs_installing-bare-metal

In UPI installs admins should approve CSRs (to ensure a malicious node doesn't join the cluster)

**Comment by LorbusChris** [comment]
Seems to me like this is expected behaviour for UPI installs.
Should this be closed?

**Comment by SriRamanujam** [comment]
In the preview builds, the behavior is that workers that were up during initial bootstrapping would auto-join the cluster because the bootstrap VM was set up to auto-approve all CSRs.

Now that behavior has been removed, which is a fairly large change between the released preview builds and master. If that is the intended behavior, that's fine. I just wanted to ensure that this behavior is intended going forward. 

It should probably be called out in the next release notes, too, so that anybody else used to the preview's behavior isn't surprised.

**Comment by vrutkovs** [comment]
>In the preview builds, the behavior is that workers that were up during initial bootstrapping would auto-join the cluster because the bootstrap VM was set up to auto-approve all CSRs.

I don't think this has ever happened for any UPI build. If it ever did its a serious security issue

>It should probably be called out in the next release notes, too, so that anybody else used to the preview's behavior isn't surprised.

Approval is mentioned in the official docs

**Comment by SriRamanujam** [comment]
> 
> 
> > In the preview builds, the behavior is that workers that were up during initial bootstrapping would auto-join the cluster because the bootstrap VM was set up to auto-approve all CSRs.
> 
> I don't think this has ever happened for any UPI build. If it ever did its a serious security issue

It always did that for me. I would bring up 3 masters, 8 workers, leave them spinning waiting for the machine api to come up, and then bring up the bootstrap VM. They would all fetch at the same time and do their thing, and all 11 nodes would auto-join. I figured that was a convenience measure to make the bring-up more hands-off, so with both preview installers I have never needed to approve CSRs during initial deployment.

Nodes that were set up after the bootstrap VM finished needed to be approved manually, as you describe. I think the behavior changed as a consequence of https://github.com/openshift/machine-config-operator/pull/1423, which made it so that the workers now _always_ receive their initial config after the bootstrap VM finishes.

**Comment by vrutkovs** [comment]
> leave them spinning waiting for the machine api to come up

Wait, which install type are we talking about? If workers are created / managed by machine API then its safe to approve their CSRs since these are known to the cluster

>I figured that was a convenience measure to make the bring-up more hands-off, so with both preview installers I have never needed to approve CSRs during initial deployment.

That must have been a bug

**Comment by SriRamanujam** [comment]
Baremetal UPI. Sorry, I got confused between the MCO serving Ignition configs and machine api.

Which I guess means the current behavior must have been a bug.

**Comment by cgruver** [comment]
@SriRamanujam 

In my recent deployments with Bare-metal UPI I have had to execute the following to approve the CSRs for Masters and Workers

```
oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs oc adm certificate approve
```

This is after the MachineConfig operator is finally up and the Masters/Workers have booted and are trying to join the cluster.
