### ISSUE TITLE
Unable to upgrade from 4.5.0-0.okd-2020-09-18-202631 to 4.5.0-0.okd-2020-10-15-235428

### ISSUE THREAD

**Issue by tijnwe** [openshift/okd#976]
**Describe the bug**

When doing the upgrade at the stage of the dns and network cluster operators the daemonsets don't want to schedule pods on the master nodes. Complaining about affinity rules, the nodeSelector on the daemonset matches that of the masters. 

**Version**

UPI on vSphere.

**How reproducible**
Not completely sure. 

**Log bundle**
https://herbosch.be/must-gather.tar.gz

**Comment by vrutkovs** [comment]
network operator is progressing: `DaemonSet "openshift-ovn-kubernetes/ovnkube-master" is not available (awaiting 1 nodes)`
One of OVN-master pods is crashlooping: `back-off 5m0s restarting failed container=nbdb pod=ovnkube-master-sqvzz_openshift-ovn-kubernetes(fd5f8ef2-b6f4-4a20-8287-01bcf5bc3908)`

This needs to be filed for OCP in bugzilla.redhat.com, component Networking, subcomponent ovn-kubernetes
