### ISSUE TITLE
eventrouter-rhel8:latest no longer available

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#983]
**Describe the bug**
In the latest documentation at https://docs.openshift.com/container-platform/4.9/logging/cluster-logging-eventrouter.html or https://docs.okd.io/latest/logging/cluster-logging-eventrouter.html you provide the "latest" tag of the event router image. But it seems this is no longer available at https://catalog.redhat.com/software/containers/openshift-logging/eventrouter-rhel8/6017a6d9ef2940f01428eb81?tag=all

The eventrouter pods will restart with the following ImagePullBackOff error:
Failed to pull image "registry.redhat.io/openshift-logging/eventrouter-rhel8:latest": rpc error: code = Unknown desc = Error reading manifest latest in registry.redhat.io/openshift-logging/eventrouter-rhel8: unsupported: This repository does not use the "latest" tag to track the most recent image and must be pulled with an explicit version or image reference. For more information, see: https://access.redhat.com/articles/4301321
 
**Version**
4.8.0-0.okd-2021-11-14-052418

**Comment by vrutkovs** [comment]
Not an OKD issue, see https://issues.redhat.com/projects/LOG/issues for Openshift Logging issues
