### ISSUE TITLE
updated v4.8 to v4.9 and a day later starting to see errors trying to pull the community-operators

### ISSUE THREAD

**Issue by johnlongo** [openshift/okd#997]
updated v4.8 to v4.9 and a day later starting to see errors trying to pull the community-operators

Failed to pull image "registry.access.redhat.com/redhat/community-operator-index:v4.9": rpc error: code = Unknown desc = reading manifest v4.9 in registry.access.redhat.com/redhat/community-operator-index: name unknown: Repo not found

![image](https://user-images.githubusercontent.com/23619505/144151579-e2c49808-f037-4bed-8f42-baf351224856.png)

**Comment by GeoEducator** [comment]
what do I need to learn here

**Comment by johnlongo** [comment]
that the "registry.access.redhat.com/redhat/community-operator-index:v4.9" is no longer working.

**Comment by GeoEducator** [comment]
ok, where do I need to be to start learning so v.4.10

**Comment by johnlongo** [comment]
Market place is back online closing ticket

![image](https://user-images.githubusercontent.com/23619505/144159282-b892d6b9-e0a6-48d8-979a-0ee2c58d9102.png)

**Comment by vrutkovs** [comment]
https://status.redhat.com/incidents/36hmgm2b1g3s
